### ISSUE TITLE
CPU: cpu info is not correct

### ISSUE THREAD

**Issue by ailun258** [projectacrn/acrn-hypervisor#1003]
following up Getting started guide to setup SOS and UOS with ACRN.
log into UOS, run "cat /proc/cpuinfo", it shows 1 cpu info only, 
it should has 3 cores allocated to UOS by default on APL NUC.

**Comment by ailun258** [comment]
the fixed path:
https://github.com/projectacrn/acrn-hypervisor/pull/1002

**Comment by gvancuts** [comment]
Hi @ailun258 , can you close this issue now that #1001 has been merged?

(next time I would recommend you use of one of the automatic mechanism for closing an issue when sending a Pull Request: https://help.github.com/articles/closing-issues-using-keywords/)
