### ISSUE TITLE
Graphic:  video screen is not refreshed sometime in UOS

### ISSUE THREAD

**Issue by ailun258** [projectacrn/acrn-hypervisor#1005]
1, setup SOS and UOS following getting started guide
2, installed desktop bundle in UOS
3, sharing USB keyboard and mouse for UOS
4, playing video with totem player

result: sometime, video screen blocked without refresh , if user moving mouse,  playing video continue. and there is clear "frame skip"

**Comment by xiaoxiax** [comment]
Cannot reproduced this issue with gst-launch-1.0 tool.
Please help to close it, thanks!
