### ISSUE TITLE
Debug: Post-morem debug analysis

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#1024]
Hypervisor shall provide support for post mortem debug analysis by providing the following:
1. The platform shall provide support to save crashlogs of each Guest OS's, firmware and Hypervisor to files, to enable analysis of the firmware and hypervisor logs by host tool.
2. The platform shall provide support to dump RAM after Guest OS's or Hypervisor crash, to enable this RAM dump file should be able to be analyzed offline by host tool.

**Comment by hwang37** [comment]
[External_System_ID] 211427

**Comment by NanlinXie** [comment]
Feature done, closed.
