### ISSUE TITLE
Security: Enable compiler and linker setting-flags to harden software

### ISSUE THREAD

**Issue by wws666** [projectacrn/acrn-hypervisor#1122]
Below settings/flags should be enabled for ACRN: 
  1) Stack execution protection;
  2) Data relocation and protection (RELRO);        
  3) Stack-based Buffer Overrun Detection;          
  4) Position Independent Execution (PIE);           
  5) Fortify source;                                
  6) Format string vulnerabilities;

**Comment by hwang37** [comment]
[External_System_ID] 253110
