### ISSUE TITLE
Clear Linux image not longer available on the download website

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#1135]
The Clear Linux image that we use as a [reference](https://download.clearlinux.org/releases/23690/clear/clear-23690-installer.img.xz) in our [Getting Started Guide](https://projectacrn.github.io/latest/getting-started/apl-nuc.html#set-up-a-clear-linux-operating-system) is no longer available from the download website. This is a new policy from the Clear Linux team. We need to update the instructions to use a newer (ideally the latest as of today) image as a reference.

**Comment by gvancuts** [comment]
@ttzeng @kiendinh @ailun258 is this something that one of you could do?

@dbkinder , FYI

**Comment by dbkinder** [comment]
We could use instructions that don't go obsolete within a day as new releases of CL are made :(

**Comment by gvancuts** [comment]
> We could use instructions that don't go obsolete within a day as new releases of CL are made :(

Couldn't agree more.. the path to that in my opinion is a bundle that *really* installs all components where they ought to be (and configure the system accordingly). That would also solve the "upgrade" issue where one cannot upgrade the Service OS at all without breaking the installation.

**Comment by dbkinder** [comment]
So what's stopping such a bundle from being implemented?  Is this a CL or ACRN issue (or both)?

**Comment by gvancuts** [comment]
So what's stopping such a bundle from being implemented? Is this a CL or ACRN issue (or both)?

Proper packaging for ACRN isn’t straightforward, nothing that cannot be solved I’m sure but it would take a bit of time that nobody has really invested in yet. I’m not sure whose job it is to solve this.

One aspect is the ESP manipulation (and its equivalent when using SBL) and the other one is the platform detection (apl-mrb vs. NUC, EFI vs. SBL, etc). That’s for the SOS part of it. Then there is a similar challenge when dealing with Clear as a UOS.

**Comment by Mingyuan18** [comment]
@gvancuts , What is the current situation of this bug, do we still need to track?

**Comment by gvancuts** [comment]
This one will come and go, depending on how long images will be posted on Clear Linux download website and how often we release new versions. The instructions are a lot more generic than they used to be, I think we can close this ticket.
