### ISSUE TITLE
Debug: NPK

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1138]
The platform shall provide support for North Peak (NPK) logging and trace information, collected to memory from hypervisor, Guest OS's, FW, and HW.  Support for DbC/PTI output shall be provided subsequent to memory output functionality.

**Comment by mwang106** [comment]
[External_System_ID]  247329

**Comment by yakuizhao** [comment]
Now the code is already submitted to GitHub.com/intel/Linux-intel-lts.git
So the issue is closed.
