### ISSUE TITLE
acrm-dm stucks during destroying gvt instance

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1141]
There is a deadlock at below case
- acrn-dm create gvt instance successfully
- acrn-dm open uos image failed(wrong image path), the acrn-dm does some cleanup,
  like destroy gvt instance
then acrn-dm stucks.

when destroying gvt instance, it waits client->kthread_exit to be true
while client->kthread_exit is set to be 0 at initializing and the thread
is not created/started actually.

**Comment by ftangx** [comment]
it is verified with
AaaG build :
https://buildbot.sh.intel.com/absp/builders/master-latest/builds/2268
Image info:
SOS version:           20180926-25180
acrn-hypervisor:   2018w39.2.140000p  
linux-pk414:             4.14.69        102
IFWI Version: ABL_1820HF1
IOC Version ：4. 0. 8
