### ISSUE TITLE
GPU Mediator shall provide assignment of individual display planes to individual domains

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#1149]
GPU Mediator shall provide assignment of individual display planes to individual domains The GPU mediator will support assignment of any one of the multiple planes on a given pipe to a specific guest domain. The assignment of planes to guests provides one way to use HW composition within the display engine to combine output of multiple domains on a single display pipe/device. Multiple planes from a given pipe may be assigned to one or more different guest domains (and or remain in the control of the service OS). Guest domains may continue to configure planes through the emulated MMIO interface, in which case the GPU mediator must ensure that the overall configuration of the display HW is still sustainable (i.e. memory BW, scalars etc.). Guest domains may also be para'-virtualized to make higher'-level, explicit, requests of the GPU mediator for a desired plane configuration (the GPU mediator must still regulate these for compatibility with the overall global configuration). Generally, production systems are expected to be configured in such a way as to make the requested configurations of all pipes/planes achievable. Attempts by a guest OS to write to the MMIO registers of a plane that was not assigned to it will be discarded

**Comment by hwang37** [comment]
[External_System_ID]212333

**Comment by Mingyuan18** [comment]
No regression issue found in test.
