### ISSUE TITLE
GPU Mediator shall be implemented with a permissive license (not copyleft like GPL/LGPL), allowing arbitrary 3rd party re-use.

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#1150]
GPU Mediator shall be implemented with a permissive license (not copyleft like GPL/LGPL), allowing arbitrary 3rd party re'-use.

**Comment by hwang37** [comment]
[External_System_ID]212332

**Comment by Mingyuan18** [comment]
No regression issue found in test. So close this issue.
