### ISSUE TITLE
memory under 1M leak during system S3 enter/exit

### ISSUE THREAD

**Issue by fyin1** [projectacrn/acrn-hypervisor#1156]
During S3 enter/exit, we need to online/offline APs in HV. Now, we prepare the trampoline code in start_cpus function which is called when doing S3 enter/exit. So we need to make sure it doesn't have memory leak.

**Comment by lijinxia** [comment]
[External_System_ID] 252189

**Comment by fyin1** [comment]
The fixing patch was merged and we could mark this issue closed.
