### ISSUE TITLE
Add support for partition mode

### ISSUE THREAD

**Issue by zds100** [projectacrn/acrn-hypervisor#1160]
Add support for partition mode on ACRN hypervisor.  With the partition mode enabled, Hypevisor assigns the PCI passthru devices to UOS directly, achieving a near-native performance.  To support partition mode,  we need to add/port the following to Hypervisor:
1.  VPCI: needs to capture the PCI config space access and emulate a virtual PCI bus to UOS.
The per-vm PCI passhtru device list needs to be defined to specify a list of the PCI passthru devices assigned to UOS. 
2. VRTC: needs to emulate a virtual RTC to UOS
3. MP table:  pass MP table to UOS, ACPI will not be used
4. LAPIC passthru/interrupt remapping:  pass LAPIC directly to UOS to achieve exit-less interrupt handling, no interrupt remapping on Hypervisor side
5. Eliminate DM: do not use DM to launch UOS, launch UOS directly in hypervisor instead.

**Comment by KaigeFu** [comment]
[External_System_ID] 255255

**Comment by Mingyuan18** [comment]
The patch was merged.
