### ISSUE TITLE
Cursor not work when enable_initial_modeset is 0

### ISSUE THREAD

**Issue by zhipenggong** [projectacrn/acrn-hypervisor#1171]
ddb allocation for the PLANE_CURSOR is removed to save some ddb for support 4K monitors. as a result, cursor not work when enable_initial_modeset is 0.

**Comment by mwang106** [comment]
[External_System_ID] 255419

**Comment by dandanyx** [comment]
Cannot reproduce this issue on WW42 AaaG build, and cursor can move normally.
Suggest to close this issue, thanks!
