### ISSUE TITLE
Should enable interrupt-window if any pending external interrupts

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1189]
The external interrupt events only can be inject if RFLAGS.IF = 1 and no blocking by both STI and MOV SS. If met this scenario, we need to enable "interrupt-window exiting" for injection in next VMEXIT.

**Comment by mwang106** [comment]
[External_System_ID] 253873

**Comment by ywan170** [comment]
Need QA to confirm no regression

**Comment by mwang106** [comment]
no regression bug
