### ISSUE TITLE
Fix launch two UOS using the same tap interface issuse

### ISSUE THREAD

**Issue by JiangboWuWJB** [projectacrn/acrn-hypervisor#1194]
Launch two clearlinux as a guest will using the same 'LaaG' tap interface, it will cause launch failed. We need      using the different tap interface when launch more than one UOS. Add tap interface as launch function parameter to fix this issue.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1433

**Comment by mwang106** [comment]
verified
