### ISSUE TITLE
System S3 is broken when switch bootloader to ABL

### ISSUE THREAD

**Issue by jsun26intel** [projectacrn/acrn-hypervisor#1196]
The system S3 is broken when the boot loader of GP MRB switched to ABL. The root cause is wake vector address in ACPI table is changed, need a patch to change ACPI info accordingly.

**Comment by mwang106** [comment]
[External_System_ID] 254072

**Comment by mwang106** [comment]
The bug cannot be reproduced with w37.5 aaag build:
AaaG build:
Image info:
SOS version:   20180912-24970
acrn-hypervisor   2018w37.2.140000p
linux-pk414          4.14.68             95
IFWI Version: ABL_1820HF1
IOC Version ：4. 0. 8
