### ISSUE TITLE
Instruction emulation code reshuffle

### ISSUE THREAD

**Issue by fyin1** [projectacrn/acrn-hypervisor#1207]
Improve the current acrn hypervisor instruction emulation. Make it to follow SDM to handle failure case like injecting correct fault during instruction emulation.

**Comment by mwang106** [comment]
[External_System_ID] 254196

**Comment by fyin1** [comment]
https://github.com/projectacrn/acrn-hypervisor/pull/1219 was merged and all instruction emulation reshuffle was done.
