### ISSUE TITLE
init_iommu rework to enable IOMMU for partition mode ACRN

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#1246]
IOMMU is enabled only if the VM is SOS. This will break partition mode functionality as there is no SOS.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1462

**Comment by Mingyuan18** [comment]
Can't reproduce now.
Commit: 8c9e0d17dbc31141cc3cf2af13c2c7294dfc7973
