### ISSUE TITLE
Reduce function calls to dynamic-memory allocation in efi boot code of hypervisor

### ISSUE THREAD

**Issue by guoch2** [projectacrn/acrn-hypervisor#1260]
Dynamic-memory might cause un-expected results in IoT and embedded system. We should reduce the calls to dynamic-memory allocation as many as possible.   Hypervisor EFI stub code has several places which call into UEFI memory allocation, some of them could be removed and some can be merged. Besides,  some dead code should be removed to reduce footprint.

**Comment by mwang106** [comment]
[External_System_ID] 255276

**Comment by mwang106** [comment]
Verified this issue, and it introduced PXE boot fails issue.
