### ISSUE TITLE
acrnctl tool hangs on ClearLinux build 25050

### ISSUE THREAD

**Issue by LibertadCruz** [projectacrn/acrn-hypervisor#1263]
The acrnctl tool has hanged on ClearLinux release 25050. The launch_uos.sh has added the VM2 and has launched it but when trying to list the VMs with acrnctl list the tool hangs.

**Comment by Mingyuan18** [comment]
@LibertadCruz , Does this issue still exist?

**Comment by LibertadCruz** [comment]
No, you can close this now
