### ISSUE TITLE
add ACPI fixup feature

### ISSUE THREAD

**Issue by jsun26intel** [projectacrn/acrn-hypervisor#1264]
The platform ACPI table might be changed before production, this brings
issue to us as current host_acpi_info data is hard-coded.

The patch set enable the feature that could parse the needed ACPI data
after boot and then override the host_acpi_info structure for system
usage.

**Comment by mwang106** [comment]
[External_System_ID] 255412

**Comment by mwang106** [comment]
This feature has been verified on MRB
