### ISSUE TITLE
vioapic: change the method for assert/deassert

### ISSUE THREAD

**Issue by JasonChenCJ** [projectacrn/acrn-hypervisor#1269]
a guest may use per-cpu vector allocation mechanism which may lead to
    same vector on different vcpu for different vioapic pins.
    when we broadcast EOI from vlapic to vioapic, it could trigger
    ptdev_intx_ack for incorrect vioapic pin which will lead to incorrect
    vioapic_irq_deassert.

    old implementation is recording assert & deassert by acnt, like:
    - assert -> acnt++
    - deassert -> acnt--
    which means an incorrect deassert may descrease acnt from 0 to -1, it leads
    to error.

**Comment by mwang106** [comment]
[External_System_ID] 255851

**Comment by ftangx** [comment]
Defect 255851 has verified.

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in SOS:260120
