### ISSUE TITLE
[APL][Aaag][HV]system crash after enable acrnd service to auto boot uos

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1278]
1.Environment
MRB image:
AaaG build:
https://buildbot.sh.intel.com/absp/builders/master-latest/builds/2233
Image info:
SOS version:   20180912-24970
acrn-hypervisor   2018w37.2.140000p
linux-pk414          4.14.68  95
IFWI Version: ABL_1820HF1
IOC Version ：4. 0. 8

2.  Steps
1). boot up sos.
2). In SOS, copy launch_uos.sh from /usr/share/acrn/samples/apl-mrb/ to ~/;
3). Edit launch_uos.sh, remove the line include “virtio-hyper_dmabuf” to disable hyperdma; (2 lines total, one for AaaG and one for LaaG)
4). Open another ssh section to SOS, input: “acrnctl add ./launch_uos.sh –V 2” (note: -V 1 for LaaG, 2 for AaaG),
    you will get output as below:
    “vm1-xx:yy:zz added”
    Note: this only need run once, next time you might get “vm1 … already exist …”,
6). Input “acrnctl list” to confirm VM name(i.e. vm1-xx:yy:zz);
7). Run “systemctl enable acrnd " command in the SOS
8). "rn1#" to reboot

3.  Observations
system crash after enable acrnd services.

4. repetition rate
1/3

5. Expected result:
system will nornally after enable acrnd services.

**Comment by mwang106** [comment]
[External_System_ID] 255030

**Comment by Mingyuan18** [comment]
The bug cannot be reproduced with ww39.5 build.
