### ISSUE TITLE
[graphics] conformance check  clean up

### ISSUE THREAD

**Issue by xinyunliu** [projectacrn/acrn-hypervisor#1289]
During code  review and debug, there are two issues  there.

1. SOS kernel complains there is non-conformance register access.   there is the log  via `dmesg`:

```
[drm:intel_gvt_vgpu_conformance_check] *ERROR* gvt: vgpu1 unconformance mmio 0x20d4:0x40004,0x4
[drm:workload_thread] *ERROR* gvt: vgpu1 unconformance guest detected
```

2. wrong address computation logic in the mmio_host_cache

`host_cache[cmd_reg(s, i) >> 2]` should be `host_cache[cmd_reg(s, i)]`

**Comment by mwang106** [comment]
[External_System_ID] 255507
