### ISSUE TITLE
ACRN ramdump have regression after switched to ABL

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1295]
After switched to ABL, we are using SPI crashmode.
crashmode can work successfully, and dump is also ok

SOS also can be decoded successfully.
However, ACRN have issues, below is the error:

file '/home/btian1/work/data/ramdump/hv/ram.sparse.bin' (SPARSE) loaded.
loading ELF/DWARF
file '/home/btian1/work/data/ramdump/hv/acrn.out' (ELF/DWARF2) loaded.
cpu_regs variable not found..

Attachments

**Comment by Mingyuan18** [comment]
commit id: 2908f09f88e47f297fa4bbfc6e9cce946671c2e5
Can't reproduce this issue
