### ISSUE TITLE
hyper_dmabuf compile warnings once -Werror enabled

### ISSUE THREAD

**Issue by liuwei987** [projectacrn/acrn-hypervisor#1300]
hyper_dmabuf compile warnings once -Werror enabled:
drivers/dma-buf/hyper_dmabuf/virtio/hyper_dmabuf_virtio_be_drv.c: In function ‘vbs_k_reset’:
drivers/dma-buf/hyper_dmabuf/virtio/hyper_dmabuf_virtio_be_drv.c:368:1: error: no return statement in function returning non-void [-Werror=return-type]
 }
 ^
  CC      drivers/input/input.o
drivers/dma-buf/hyper_dmabuf/virtio/hyper_dmabuf_virtio_be_drv.c: In function ‘vbs_k_ioctl’:
drivers/dma-buf/hyper_dmabuf/virtio/hyper_dmabuf_virtio_be_drv.c:406:9: error: ‘r’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  return r;
         ^

**Comment by mwang106** [comment]
[External_System_ID] 255625

**Comment by liuwei987** [comment]
bug fixed. close it.
