### ISSUE TITLE
ioeventfd and irqfd implementation to support vhost on ACRN

### ISSUE THREAD

**Issue by shuox** [projectacrn/acrn-hypervisor#1329]
To support vhost, we need implement call eventfd and notify eventfd in
kernel for it. For ACRN vhm, we implement ioeventfd and irqfd for that.

ioeventfd which is based on eventfd, intends to glue vhm module and
other modules who are interested in guest IOs.
Each ioeventfd registered by userspace can map a PIO/MMIO range of
the guest to eventfd, and response to signal the eventfd when get the
in-range IO write from guest. Then the other side of eventfd can be
notified to process the IO request.

irqfd is based on eventfd too, provides a pipe for injecting guest
interrupt through a file description writing operation.
Each irqfd registered by userspace can map a interrupt of the guest
to eventfd, and a writing operation on one side of the eventfd will
trigger the interrupt injection on vhm side.

**Comment by mwang106** [comment]
[External_System_ID] 255848
