### ISSUE TITLE
combine VM creating and ioreq shared page setup

### ISSUE THREAD

**Issue by shuox** [projectacrn/acrn-hypervisor#1330]
We intend to combine VM creating and ioreq shared page setup into one step.
We need be careful with the compatibility. To achieve it safely, we will do,
      1) Do shared page setup in IC_CREATE_VM, what this patch do exactly
      2) Move the shared page setup action into vm creating in DM.
      3) Remove the ioctl IC_SET_IOREQ_BUFFER in kernel.

**Comment by mwang106** [comment]
[External_System_ID] 255915

**Comment by Mingyuan18** [comment]
No regression issue found in test, So close this issue.
