### ISSUE TITLE
[APL][IO Mediator][LaaG]The screen does not light up after startup UOS

### ISSUE THREAD

**Issue by lidongwangx** [projectacrn/acrn-hypervisor#1384]
Environment: version release:
SOS Kernel version:4.14
UOS OS Type: LaaG
UOS Kernel version: 4.14
Reproduce rate: always
LaaG E2E build:
SOS version:          25170
acrn-hypervisor    2018w38.4.140000p
linux-pk414             4.14.68 99
IFWI Version: ABL_1820HF1
IOC Version ：4. 0. 8
UOS kernel:     c795424a331f [upstream] drm/i915/gvt: Fix stack-out-of-bounds bug in cmd parser

step:
1:boot sos
2.boot UOS by default script
Expected result:
uos screen can be light up
Actual result:
uos screen does not light up

**Comment by lidongwangx** [comment]
[External_System_ID] 256694

**Comment by Mingyuan18** [comment]
Can't reproduce this issue now.
