### ISSUE TITLE
Improve crashlog tool

### ISSUE THREAD

**Issue by miguelinux** [projectacrn/acrn-hypervisor#1386]
We need to improve crashtool to comply with the Clear Linux requirements.

- Do not alter system behavior without notify to the user
- Rewrite the code of the usercrash-wrapper
- Introduce a new tool which can control the usercrash behavior
- Deprecate the old crashtool tools

**Comment by dbkinder** [comment]
... and update the documentation?

**Comment by chengangc** [comment]
@dbkinder Sure, we'll update the documents soon.

**Comment by mwang106** [comment]
patch merged and document updated
