### ISSUE TITLE
[APL][Hypervisor] guest can not recovery successfully after kernel panic. [Assertion `irq_counts[irq] == 0 || irq_counts[irq] == IRQ_DISABLED' failed.]

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1402]
1. Environment
--------------------------------------------------------------
ACRN-Hypervisor 2018w39.2.140000p_92
SOS Build Link20180926-25180
SOS VersionInstalled version: 25180
SOS Kernel Version4.14.69-102.pk414-sos #1 SMP PREEMPT Tue Sep 25

2.  Steps
--------------------------------------------------------------
Reproduce step:
1. Launch SOS
2. Use acrn-dm to launch android with -vsbl <valiad vsbl image path >
(./launch_UOS.sh -V 2)
3. Trigger kernel panic
      echo 1 > /proc/sys/kernel/sysrq
      echo c > /proc/sysrq-trigger
4. repeat step3 5 times
5. Observe AaaG guest can recovery successfully every time after kernel panic. 

3. Current result:
--------------------------------------------------------------
step5: AaaG can not recovery successfully at the second times, and it shows “acrn-dm: hw/pci/irq.c:110: pci_irq_reserve: Assertion `irq_counts[irq] == 0 || irq_counts[irq] == IRQ_DISABLED' failed.”

**Comment by mwang106** [comment]
[External_System_ID] 256887

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below environment: ACRN-Hypervisor 2018w43.5.140000p_106; SOS Version:25920
