### ISSUE TITLE
dm: inline functions defined in header must be static

### ISSUE THREAD

**Issue by tomasbw** [projectacrn/acrn-hypervisor#1406]
An inline function defined in headers must be static otherwise compilation may fail, depending on gcc optimization level, particularly if dropping -O2 from the Makefile dm doesn't compile reporting unresolved symbols.

**Comment by hwang37** [comment]
@mwang106 to add bi-direction for this bug's traceability

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1547

**Comment by Mingyuan18** [comment]
This is an old issue and has been fixed for a long time.
