### ISSUE TITLE
Add support for profiling [sep/socwatch tools]

### ISSUE THREAD

**Issue by mchinth** [projectacrn/acrn-hypervisor#1409]
Provide necessary infrastructure for  profiling. Tools use this infrastructure to program the performance and power hardware registers to collect the performance analysis data.

**Comment by junjunshan1** [comment]
External System ID: 261914

**Comment by junjunshan1** [comment]
[External System ID]: 261914

**Comment by junjunshan1** [comment]
[External System ID]:  261914

**Comment by junjunshan1** [comment]
[External_System_ID]: 261914

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2175

**Comment by Mingyuan18** [comment]
The patch of this issue has been merged for a long time, so close it.
