### ISSUE TITLE
dm:  mevent.h has a global variable define in header vmname

### ISSUE THREAD

**Issue by tomasbw** [projectacrn/acrn-hypervisor#1415]
The vmname variable is missing 'export', so it's probably only shadowing the already exported variable from devicemodel/include/dm.h

**Comment by hwang37** [comment]
@mwang106 to add bi-direction for this bug's traceability

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1548

**Comment by Mingyuan18** [comment]
This is an old issue and has been fixed for a long time.
