### ISSUE TITLE
dm: mevent missing mevent_disable/enable implementation

### ISSUE THREAD

**Issue by tomasbw** [projectacrn/acrn-hypervisor#1416]
Current mevent mevent_del/add() implementations are incomplete and buggy  It's easier to implement  mevent_enable/disable() required for mei virtualization. Other user of these functions, which were previously empty stubs is the uart mediator, so far it looks working well.
.

**Comment by hwang37** [comment]
@mwang106 to add bi-direction for this bug's traceability

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1546

**Comment by Mingyuan18** [comment]
This is an old issue and has been fixed for a long time.
