### ISSUE TITLE
dm: mevent : need to provide edge driven triggers

### ISSUE THREAD

**Issue by tomasbw** [projectacrn/acrn-hypervisor#1417]
For mei mediator we need to detect changes in sysfs files, it's not possible to do it via level based triggers as the files are always readable.

**Comment by hwang37** [comment]
@mwang106 to add bi-direction for this bug's traceability

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1549

**Comment by Mingyuan18** [comment]
Can't reproduce this issue.
