### ISSUE TITLE
dm: clean up virtio-block and block_if

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#1422]
1. Remove some dead code from Bhyve
2. Add debugging info
3. Add I/O range checks

**Comment by hwang37** [comment]
@conghuic23  to co-review these code changes.
@peterfang  Is this a new feature? I change the type to feature if yes and you can use it for "Tracked-On". @junjiemao1 to add bi-direction link for new feature

**Comment by peterfang** [comment]
> @conghuic23 to co-review these code changes.
> @peterfang Is this a new feature? I change the type to feature if yes and you can use it for "Tracked-On". @junjiemao1 to add bi-direction link for new feature

The changes are cleanups and minor improvements. I think you can put this down as a bug.

**Comment by junjunshan1** [comment]
[External_System_ID] 258897

**Comment by Mingyuan18** [comment]
No regression issue found.
