### ISSUE TITLE
SOS failed boot

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1432]
Root Cause:
    COM1_IRQ's polarity setting is from ACPI table, as we do not want to parse
    ACPI table here, we just get the configuration from vioapic RTE setting.

    TODO:
    Here should assert vuart irq according to COM1_IRQ polarity.  The best way
    is to get the polarity info from ACIP table. But we just get the info from
    vioapic configuration. Based on this, we can still have irq storm during
    guest modify the vioapic setting.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1538

**Comment by Mingyuan18** [comment]
Can't reproduce this issue now.
