### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by shrmrf** [projectacrn/acrn-hypervisor#144]
We should update the README file with a **Quickstart**, **license**  and **Contribution Guideline** section. 

[I have added](https://github.com/projectacrn/acrn-hypervisor/pull/143#issue-186149893) easy setup files in [this issue](https://github.com/projectacrn/acrn-hypervisor/pull/143#issue-186149893). If that issue is somewhat acceptable, I can expand and contribute to the README.

### Goals
- Use standard tools (no handwritten `bash` scripts)
- Use idioms provided by `docker` e.g. `.env` file to pass some environment variables
  - This will assist in passing proxy environment variables in corporate settings

**Comment by gvancuts** [comment]
Hi @shrmrf , all documentation should be put in the https://github.com/projectacrn/acrn-documentation repo so we can easily publish it on the [documentation website](https://projectacrn.github.io/latest/index.html). I would love to have you contribute to what we have there so feel free to create pull requests wherever you see an opportunity to bring more clarity to the docs we have!!

**Comment by shrmrf** [comment]
@dbkinder exactly... I was going to push for those next.

**Comment by gvancuts** [comment]
> I just realized that the license header is some proprietary license 

Not sure why you're saying that. This is the standard [BSD-3-Clause license](https://opensource.org/licenses/BSD-3-Clause) text. Am I missing something?

**Comment by gvancuts** [comment]
👍 on all other suggestions made here :) (and thanks for clarifying your suggestion @shrmrf , it makes complete sense to me now)

**Comment by shrmrf** [comment]
>Not sure why you're saying that. This is the standard BSD-3-Clause license text. Am I missing something?

Woops, my bad. I hadn't read the BSD licenses before. But still it looks more like C source code than a proper LICENSE file that Github likes :)

**Comment by dbkinder** [comment]
GitHub is clever when you try to create a new file called LICENSE (and you have the right permissions) -- it will prompt you to pick one of the standard licenses and grab that for you, no typing needed.  That's how the MIT License on NVIDIA's dfc project, noted above, looks nice and pretty.
