### ISSUE TITLE
A makefile dependency issue was observed

### ISSUE THREAD

**Issue by liuming50** [projectacrn/acrn-hypervisor#1441]
I observed a build error as follows:
| In file included from include/hv_debug.h:10,
|                  from include/hypervisor.h:37,
|                  from arch/x86/cpu.c:7:
| arch/x86/cpu.c: In function 'bsp_boot_post':
| arch/x86/cpu.c:453:4: error: 'HV_FULL_VERSION' undeclared (first use in this function); did you mean 'LAPIC_VERSION'?
|     HV_FULL_VERSION,
|     ^~~~~~~~~~~~~~~
| include/debug/logmsg.h:111:33: note: in definition of macro 'pr_acrnlog'
|    do_logmsg(LOG_ACRN, pr_prefix __VA_ARGS__); \
|                                  ^~~~~~~~~~~
| arch/x86/cpu.c:453:4: note: each undeclared identifier is reported only once for each function it appears in
|     HV_FULL_VERSION,
|     ^~~~~~~~~~~~~~~
| include/debug/logmsg.h:111:33: note: in definition of macro 'pr_acrnlog'
|    do_logmsg(LOG_ACRN, pr_prefix __VA_ARGS__); \
|                                  ^~~~~~~~~~~
| arch/x86/cpu.c:454:4: error: 'HV_BUILD_TIME' undeclared (first use in this function)
|     HV_BUILD_TIME, HV_BUILD_VERSION, HV_BUILD_TYPE,
|     ^~~~~~~~~~~~~
| include/debug/logmsg.h:111:33: note: in definition of macro 'pr_acrnlog'
|    do_logmsg(LOG_ACRN, pr_prefix __VA_ARGS__); \
|                                  ^~~~~~~~~~~
| arch/x86/cpu.c:454:19: error: 'HV_BUILD_VERSION' undeclared (first use in this function); did you mean 'LAPIC_VERSION'?
|     HV_BUILD_TIME, HV_BUILD_VERSION, HV_BUILD_TYPE,
|                    ^~~~~~~~~~~~~~~~
| include/debug/logmsg.h:111:33: note: in definition of macro 'pr_acrnlog'
|    do_logmsg(LOG_ACRN, pr_prefix __VA_ARGS__); \
|                                  ^~~~~~~~~~~
| arch/x86/cpu.c:454:37: error: 'HV_BUILD_TYPE' undeclared (first use in this function)
|     HV_BUILD_TIME, HV_BUILD_VERSION, HV_BUILD_TYPE,
|                                      ^~~~~~~~~~~~~
| include/debug/logmsg.h:111:33: note: in definition of macro 'pr_acrnlog'
|    do_logmsg(LOG_ACRN, pr_prefix __VA_ARGS__); \

when I run the following command:
$ cd hypervisor
$ make defconfig PLATFORM=uefi
$ make -j 16

**Comment by gvancuts** [comment]
I'm not seeing this error, I tried with the latest commit on both Clear Linux and Fedora. What is the commit and your environment?

**Comment by liuming50** [comment]
I was building acrn-hypervisor on a Ubuntu host (16 cpus) when I saw this issue, the command is: make -j 16

**Comment by binbinwu1** [comment]
I can reproduce the issue on a Ubuntu 16.04 host.

**Comment by wenlingz** [comment]
@liuming50 please add externel_ID,thanks

**Comment by liuming50** [comment]
Hi, Wenling:

What did you mean "external_id"? Could you please give more explanation?
Thanks.

//Ming Liu

wenlingz <notifications@github.com> 於 2018年10月16日 週二 上午6:53寫道：

**Comment by liuming50** [comment]
OK, thanks.

//Ming Liu

Wang, Minxia <notifications@github.com> 於 2018年10月16日 週二 上午8:25寫道：

**Comment by Mingyuan18** [comment]
@liuming50 ，  Please confirm whether this issue is still exists, thanks!

**Comment by liuming50** [comment]
It's fixed per test, close it.
