### ISSUE TITLE
update apicv irr/rvi before handle vmcs event injection

### ISSUE THREAD

**Issue by ywan170** [projectacrn/acrn-hypervisor#1443]
From SDM Vol3 26.3.2.5:
Once the virtual interrupt is recognized, it will be delivered in VMX
non-root operation immediately after VM entry(including any specified
event injection) completes.

So the hardware can handle vmcs event injection and evaluation/delivery
of apicv virtual interrupts in one time vm-entry.

This patch move the apicv irr/rvi sync before handle vmcs events
injection. The old code cause the apicv virtual interrupt evaluation and
delivery be handled until next vm-exit if met pending exceptions.

**Comment by mwang106** [comment]
[External_System_ID] 259243

**Comment by Mingyuan18** [comment]
Can't reproduce this issue.
