### ISSUE TITLE
[APL][AaaG][HV]AaaG kernel crash when audio driver probe

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1461]
[Board]: 
D0 MRB
Kernel Version/Android Version 4.19.quilt-2e5dc0ac-gea32cb468fb1

Steps
--------------------------------------------------------------
boot AaaG with audio passed-through

Current result:
--------------------------------------------------------------
AaaG kernel panic.

Expected result:
--------------------------------------------------------------
AaaG kernel can boot successfully.

Repetition rate
10%

**Comment by mwang106** [comment]
[External_System_ID] 259736

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in this environment:  ACRN-Hypervisor : 2018w42.5.140000p_103 ; SOS: 25730
