### ISSUE TITLE
Option to disable the serial console via Kconfiglib

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#1481]
It's possible to instruct the hypervisor to disable the uart (by passing the `uart=disabled` option to it at boot time). I could not find such option in the `kconfiglib` infrastructure however. It would be good to be able to disable it from there too.

**Comment by gvancuts** [comment]
Update: this is still WIP, current idea is to do [this](https://github.com/gvancuts/acrn-hypervisor/commit/a591f99b33eb1df036825df0d866006b43b84d9e)... but I still need to test it to make sure it has the desired effect :-)

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-1969

**Comment by Mingyuan18** [comment]
@gvancuts , Please confirm whether this problem has been solved. If so, please close it. Thanks!
