### ISSUE TITLE
provide a string convert api and remove banned function for virtio-blk

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#1496]
1. As function sscanf is banned, to get value from parameter buffer, strto* is recommended. To reduce the inspection code when using strto*, it's better to use a string convert API.
2. replace the banned function for virtio-blk.

**Comment by mwang106** [comment]
[External_System_ID] 260208

**Comment by Mingyuan18** [comment]
No regression issue found in test.
