### ISSUE TITLE
add watchdog MSI and INTR support in DM

### ISSUE THREAD

**Issue by jsun26intel** [projectacrn/acrn-hypervisor#1498]
The i6300esb watchdog has a feature that it could generate a interrupt on stage1 timeout, the reset occurs on stage2 timeout. This feature could be used for debug that user could dump system info in the interrupt.
We need to enable the feature in DM.

**Comment by jsun26intel** [comment]
[External_System_ID] 260218

**Comment by Mingyuan18** [comment]
No regression issue found in test
