### ISSUE TITLE
DM: customized changes for RPMB mux kernel module

### ISSUE THREAD

**Issue by yang8621** [projectacrn/acrn-hypervisor#1508]
As RPMB mux kernel module is going to be created, there are two 
corresponding changes required for DM:
1. The name has been changed to /dev/rpmbmux.
2. DM does NOT check MAC of RPMB result returned by kernel
    module because DM doesn't own the real key.

**Comment by mwang106** [comment]
[External_System_ID] 260411

**Comment by Mingyuan18** [comment]
Can't reprouce this issue in below build:
ACRN : 2019w08.3.150000p_158
SOS : 27930
