### ISSUE TITLE
acrn-kernel change has broken API doc generation

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#1511]
See https://github.com/projectacrn/acrn-kernel/issues/119

**Comment by hwang37** [comment]
@xinyunliu our developer to look at the issue.

**Comment by dbkinder** [comment]
PR to add API comments has not been posted to the acrn-kernel repo (and merged), so the doc build failure is still here.

**Comment by mwang106** [comment]
Resolved
