### ISSUE TITLE
Aaag UOS resume failed by "acrnctl resume" if it was suspended by "acrnctl suspend"

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#1550]
UOS requires an wakeup reason when resumed from S3 suspend. If user use "acrnctl resume [VMNAME]" without an reason, 0x0 will be used as default reason, and this is not work. We can use CBC_WK_RSN_BTN instead.

[External_System_ID] 259324

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in this build: ACRN-Hypervisor : 2018w43.5.140000p_106; SOS Version: 25920
