### ISSUE TITLE
Samples: Kernel bootchart generation using cmdline.

### ISSUE THREAD

**Issue by santoshkumarlaxminarayanrai** [projectacrn/acrn-hypervisor#1551]
Need to add kernel command line parameters to generate kernel boot-chart for GP APL.
Which can help to measure kernel boot time. Using this data developer can optimize kernel booting.

Parameters to add in file : **devicemodel/samples/apl-mrb/sos_bootargs_debug.txt**
Parameters:  **initcall_debug printk.time=y init=/usr/lib/systemd/systemd-bootchar**t

**Comment by mwang106** [comment]
@santoshkumarlaxminarayanrai Will you cook a patch for this?

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2468

**Comment by Mingyuan18** [comment]
@santoshkumarlaxminarayanrai , Would you like to submit a new patch again?
