### ISSUE TITLE
[sos]Could not find /sys/module/i915/parameters/gvt_workload_priority in SoS

### ISSUE THREAD

**Issue by xinyunliu** [projectacrn/acrn-hypervisor#1552]
Issue Summary:
 -------------------------
 As testing "GPU Preemption QoS Stress Test", we need to configure the UoS priority via 
 setting /sys/module/i915/parameters/gvt_workload_priority. But we couldn't find this variable on ww42_b release.

**Comment by xinyunliu** [comment]
[External_System_ID] ACRN-70320

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in this build:  SOS version is 26150
