### ISSUE TITLE
doc: Update ACRN-specific coding style exceptions with regard to Linux style

### ISSUE THREAD

**Issue by junjiemao1** [projectacrn/acrn-hypervisor#1557]
ACRN mostly follows Linux coding style, but with a few exceptions for, e.g. MISRA-C compliance. The checkpatch.pl script shall be customized before applying to the ACRN code so that warnings on such exceptions are suppressed.

**Comment by dbkinder** [comment]
@junjiemao1 @NanlinXie @lijinxia @hwang37 Can we close this issue as fixed now?

**Comment by eternalNight** [comment]
@dbkinder I think so. The customized configuration to checkpatch has been merged months ago.

@NanlinXie Would you please verify and close this issue? Thanks.

**Comment by junjiemao1** [comment]
@dbkinder I think so. The customized configuration to checkpatch has been merged months ago.

@NanlinXie Would you please verify and close this issue? Thanks.

**Comment by dbkinder** [comment]
We're also maintaining a [coding style doc](https://projectacrn.github.io/latest/developer-guides/coding_guidelines.html) now, so the issue is resolved.
