### ISSUE TITLE
Implement PCI emulation functionality in HV for UOS passthrough devices and SOS MSI/MSI-X remapping

### ISSUE THREAD

**Issue by ZideChen0** [projectacrn/acrn-hypervisor#1568]
In sharing mode, implement these functionalities in hypervisor:
1) MSI/MSI-X remapping for SOS PCI devices, so we can remove the related code from SOS Linux kernel;
2) UOS passthrough devices: BAR emulation and MSI/MSI-X remapping. And remove the related code from DM.

After this, HV won't inject PIO access to PCI configuration to DM for passthrough devices.

**Comment by junjunshan1** [comment]
External System ID: 261923

**Comment by junjunshan1** [comment]
[External System ID]: 261923

**Comment by junjunshan1** [comment]
External System ID: 261914

**Comment by junjunshan1** [comment]
[External_System_ID]: 261923

**Comment by junjunshan1** [comment]
[External_System_ID]: 261923

**Comment by junjunshan1** [comment]
External_System_ID: 261923

**Comment by Mingyuan18** [comment]
No regression issue found in test.
