### ISSUE TITLE
HV: build: configuration is inefficient and does not support flexible defconfig

### ISSUE THREAD

**Issue by eternalNight** [projectacrn/acrn-hypervisor#1588]
The current kconfig-based configuration system in the hypervisor has the following issues:

1. It takes several seconds for dependency checking, which is hardly acceptable.
1. config.h/config.mk may not remade right after changing .config by oldconfig.
1. The help messages in Kconfig is not yet sufficient.

In addition, the current implementation of defconfig is not flexible enough to support the following scenarios.

1. By 'make' a config with all default values is used, instead of one based on a defconfig.
1. It is difficult to maintain multiple defconfigs for different boards running the same firmware.

**Comment by eternalNight** [comment]
[External_System_ID] 262780

**Comment by junjiemao1** [comment]
[External_System_ID] 262780

**Comment by Mingyuan18** [comment]
A symbol for specifying defconfig file is added in Kconfig. And the oldconfig tool now reads the specified defconfig as the base config when a new .config is to be created.
the bug can be closed.
