### ISSUE TITLE
Clean up/refactor devicemodel Makefile and .gitignore

### ISSUE THREAD

**Issue by liuming50** [projectacrn/acrn-hypervisor#1599]
I found there are quite some redundant and deprecated entries in .gitignore, they should be removed, like:
.gitignore
...
hypervisor/build/
hypervisor/bsp/uefi/include/bsp/version.h
hypervisor/bsp/sbl/include/bsp/version.h
devicemodel/build/
..

And the Makefile of devicemodel should be refactored a lit bit as well, like:
- version.h could be generated in build instead of in the source.
- include/version.h vmcfg_header targets should be depended by OBJS.
- Some redundant lines should be removed.

and so on.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2466
