### ISSUE TITLE
dm: mei: error path check

### ISSUE THREAD

**Issue by tomasbw** [projectacrn/acrn-hypervisor#1630]
MEI mediator is missing few checks for NULL on returned values  and doesn't clean up on error path.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1622

**Comment by Mingyuan18** [comment]
This is an old issue and has been fixed for a long time.

**Comment by Mingyuan18** [comment]
This is an old issue and has been fixed for a long time.
