### ISSUE TITLE
dm: mei: fix firmware reset race.

### ISSUE THREAD

**Issue by tomasbw** [projectacrn/acrn-hypervisor#1632]
The FW reset is currently detected from two points upon
    a read failure from native read and from the reset
    handler.
    The fix removes the detection from the mevent rx callback,
    leaving a single detection point.
    To prevent reset hiccup, hw_ready is not set if a full rescan is
    performed, it will be set only when virtio FW will request the FW reset.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1623

**Comment by Mingyuan18** [comment]
This is an old issue and has been fixed for a long time.
