### ISSUE TITLE
sos_bootargs to add missing parameters

### ISSUE THREAD

**Issue by chivakker** [projectacrn/acrn-hypervisor#1638]
SOS on mainline-tracking kernel can use a patch to load late firmware, in particular GuC and HuC.  With that being possible sos_bootargs should include i915.enable_guc=0x02 (or its equivalent in decimal)

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1617

**Comment by chivakker** [comment]
Patch was merged, @mwang106 why is status still open?

**Comment by mwang106** [comment]
@chivakker , sorry for confusing status, we will change the status after regression test.

**Comment by Mingyuan18** [comment]
No regression issue . so close it.
