### ISSUE TITLE
Build a single hypervisor binary that works between different platforms

### ISSUE THREAD

**Issue by bryteise** [projectacrn/acrn-hypervisor#165]
Rather than have a unique binary per PLATFORM configuration, enable the hypervisor to run regardless of which platform it is used on via run time detection and handling.

**Comment by gvancuts** [comment]
Hi @bryteise , the idea is interesting but is that even doable? We're talking about two different executable formats, an EFI executable or one that can be launched by SBL. Isn't this akin to asking for a single executable that can be run on Windows or Linux?

**Comment by bryteise** [comment]
My understanding that today SBL can launch a linux kernel itself so if that is true I am not sure why this isn't doable.

**Comment by gvancuts** [comment]
I'll leave it to the expert but this would indeed be cool if we could have a single binary that supports both.

**Comment by zhujun74** [comment]
i think it should be understood that ACRN very concerned about CPU arch and SOC memory remapping.so platform is good idea.

**Comment by bryteise** [comment]
@zhujun74 Does that mean you think building multiple versions of ACRN for each platform is the best approach?

**Comment by mattcurf** [comment]
As a contrary point of view, I desire a hypervisor that boots as fast as possible on a single platform by removing run time detection and handling, and hard coding as much as possible.

**Comment by zhujun74** [comment]
Actually.As a SOC hyperviser it must be some configueable IO depend on system requirements.So does that meaning if it is possible keeping some freedom on configrable API for different requirements?

**Comment by mattcurf** [comment]
@zhujun74 I agree for need for configuration to support a wide range of devices; I'm just suggesting that this configuration be done at compile time and not at run time.  In other words, source level configuration and support for a broad swarth of devices is good, but it is preferred that a single compiled binary boot as fast as possible on a single configured device.  In summary, my feedback is please don't provide flexibility at the expense of additional boot time or performance.  Thanks :)

**Comment by mattcurf** [comment]
or ... provide the option for one configuration to boot dynamically for development purposes, but also provide the option for locking down configuration statically at compile time when it comes time to deploy a device broadly.

**Comment by bryteise** [comment]
If there needs to be otherwise not required calls to probe hardware in order to handle a single run-time for all platforms, I'm very sympathetic to compile time configuration. It would be good to have data on a single-run time's performance impact.

**Comment by zhujun74** [comment]
Option during the compiling time at source level is better.and given minmized time－boot setting by default board
