### ISSUE TITLE
Fix the $PATH and missing 'make' tool in the documentation

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#1650]
If one follows the instructions provided in the [Getting Started Guide](https://projectacrn.github.io/latest/getting-started/apl-nuc.html) and [ACRN Documentation Generation](https://projectacrn.github.io/latest/tutorials/docbuild.html#installing-the-documentation-tools) tutorial, a couple of steps are missing, as highlighted by @dbkinder in https://github.com/projectacrn/acrn-hypervisor/issues/1389#issuecomment-432422746

Specifically:
* We need to add a bundle that provides `make` (and all related development files)
* We need to add `~/.local/bin` to the `PATH` so that `sphinx-build` is found.

**Comment by mwang106** [comment]
Patch merged.
