### ISSUE TITLE
Missing the console value in release version,

### ISSUE THREAD

**Issue by santoshkumarlaxminarayanrai** [projectacrn/acrn-hypervisor#1655]
File: devicemodel/samples/apl-mrb/sos_bootargs_release.txt

For GP-MRB ACRN using ttyS0 as console, since this is release bootargs file so ttyS0 will be skipped in booting and but needed kernel console ttyS2 in bootargs to get the Kernel console. From there user can run guest OS by its choice.

ttyS2 is missing in this bootargs file. Will add in that and raise a pull request as well.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1634

**Comment by Mingyuan18** [comment]
This issue was fixed
