### ISSUE TITLE
acrn-kernel API change breaking doc build

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#1669]
Recent change to vbs.h has incorrect kerneldoc comment for one of the parameters:
```
acrn-kernel/include/linux/vbs/vbs.h:189: warning: No description found for parameter 'name'
```
vbs.h documents a parameter as ``@name[]`` but should be ``@name`` (without the brackets)

**Comment by mwang106** [comment]
Resolved
