### ISSUE TITLE
change SOS console from ttyS0 to ttyS2 to make debug & release matched.

### ISSUE THREAD

**Issue by mcao6** [projectacrn/acrn-hypervisor#1690]
change SOS console from ttyS0 to ttyS2 to make debug & release matched.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1641

**Comment by yujian4x** [comment]
SOS version: 26540

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build: 
ACRN-Hypervisor : 2018w48.1.173000p_123
SOS Build Link : 26540
