### ISSUE TITLE
Fix wrong condition check in debug/profiling.c 

### ISSUE THREAD

**Issue by mchinth** [projectacrn/acrn-hypervisor#1693]
due to wrong check , cannot collect MSR samples information .

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1647

**Comment by Mingyuan18** [comment]
@mchinth , Please confirm whether this issue has been solved. If so, please close this bug. Thank you！

**Comment by Mingyuan18** [comment]
@mchinth , Please confirm whether this issue has been solved. If so, please close this bug. Thank you！

**Comment by mchinth** [comment]
This issue is resolved !
