### ISSUE TITLE
RFC: kernel bootargs adding parameters

### ISSUE THREAD

**Issue by chivakker** [projectacrn/acrn-hypervisor#1697]
I'd like to understand the usage of these parameters in https://github.com/projectacrn/acrn-hypervisor/blob/master/devicemodel/samples/apl-mrb/sos_bootargs_release.txt

i915.enable_preemption=1
i915.context_priority_mode=2
i915.tsd_delay=2000

These are non-existent in kernel-4.19

Please explain.

**Comment by xinyunliu** [comment]
They are obsoleted  and need clean up since v4.14, thanks!

**Comment by lijinxia** [comment]
[External_System_ID] ACRN-1652

**Comment by Mingyuan18** [comment]
No regression issue found in test.
