### ISSUE TITLE
msix.c: use MMIO read/write APIs to access MMIO registers

### ISSUE THREAD

**Issue by shiqingg** [projectacrn/acrn-hypervisor#1711]
MMIO registers might be changed at any time.
The changes might not be catched due to compiler optimization if there is no 'volatile' keyword.

We have defined MMIO read/write APIs to address the above issue.
'volatile' keyword is being used in these defined MMIO read/write APIs.

This patch updates the MMIO registers access implementation in 'msix.c' to use these defined MMIO read/write APIs.

**Comment by mwang106** [comment]
[External_System_ID] 263882

**Comment by shiqingg** [comment]
patch has been merged
https://github.com/projectacrn/acrn-hypervisor/pull/1713
