### ISSUE TITLE
guest x2APIC support for SOS

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#1717]
This patch adds support to use x2APIC in SOS when ACRN exposes x2APIC and supports x2APIC MSR emulation for guests.

**Comment by lijinxia** [comment]
[External_System_ID] 263045

**Comment by Mingyuan18** [comment]
Duplicate with #1626(https://github.com/projectacrn/acrn-hypervisor/issues/1626)
