### ISSUE TITLE
[APL][Aaag][HV]system will crash after manual triggle kernel panic.

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1745]
1. Image Version

2. Steps
1. Launch SOS
2. Use acrn-dm to launch android with -vsbl <valiad vsbl image path >
(./launch_UOS.sh -V 2)
3. Trigger kernel panic
echo 1 > /proc/sys/kernel/sysrq
echo c > /proc/sysrq-trigger

3. Current result:
System will crash after manual triggle kernel panic.

4. Expected result:
SOS and UOS recovery successfully after triggle kernel panic.
5. repetition rate
100%

Notes: SOS is crash.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1653

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in this build: 
ACRN-Hypervisor : 2018w48.1.173000p_123;  SOS : 26550
