### ISSUE TITLE
Any UOS/VM can destroy other VM?

### ISSUE THREAD

**Issue by bzhu5** [projectacrn/acrn-hypervisor#175]
https://github.com/projectacrn/acrn-hypervisor/blob/bbac18cf190f532ea3e7b56380219678b022f4c9/hypervisor/common/hypercall.c#L196

It seems like there are no restrictions for this hypercall (may have others), for example, can we check/test these?

- Can this hypercall be called from other guest VM?
- What if a ring-3 hypercall from a malicious application in guest VM is called to destroy other guest VM or itself?

**Comment by bzhu5** [comment]
anyone knows how to "label" an issue? for example, I'd like to label this w/ "security"

**Comment by gvancuts** [comment]
> anyone knows how to "label" an issue? for example, I'd like to label this w/ "security"

@Rraghuveer should be able to help.

**Comment by bzhu5** [comment]
thank you @gvancuts !

@Rraghuveer is this because that i don't have permission to do that? it seems that I didn't find UI interface to allow me to either create a new label or label an issue with an existing label.  thank you.

**Comment by dbkinder** [comment]
I went and created some labels you can choose from.

**Comment by bzhu5** [comment]
looks like bug fixed. close it
