### ISSUE TITLE
UOS cannot stop by command: acrnctl stop [vm name] in SOS

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1774]
1.Environment
[Board]: APL NUC
Installed version: 26120
Version URL: https://cdn.download.clearlinux.org/update/
Content URL: https://cdn.download.clearlinux.org/update/

2. Steps
1). Boot to SOS
2). SSH to SOS
3). Add a aaag UOS into list over SOS SSH by
 acrnctl add [uos_bash_script]
   ex: acrnctl add launch_UOS.sh -V 2
4). Start that VM by below command
acrnctl start [vm name]
  Notes: use "acrnctl list" to check the vm name, if you don't know it. 
    ex: acrnctl start vm1-13:ce:dd
5). Over console stop vm by below command
    acrnctl stop [vm name]
  Notes: use "acrnctl list" to check the vm name, if you don't know it. 

3. Current result:
Uos cannot stop by command:acrnctl stop [vm name].

4. Expected result:
Uos will stop by command:acrnctl stop [vm name].

5. repetition rate
100%

**Comment by Mingyuan18** [comment]
This issue can not be reproduced on APL NUC&KBL NUC on build version: 28070
