### ISSUE TITLE
gfxbench cannot run in SOS&UOS

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1779]
Environment:
------------
E2E NUC image: 
https://download.clearlinux.org/latest (26120) Which tag is 2018w45.1.140000p

Bug detailed description:
-------------
gfxbench cannot run in SOS&UOS

Reproduce steps:
-------------
1. Boot up SOS& UOS
2. Start Weston by command "Weston --tty=1 -I 0 &"
3. Run gfxbench in SOS or UOS

Current result:
--------------
gfxbench cannot run in SOS&UOS

Expected result:
--------------
gfxbench can run normally

Rate: 5/5

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1667

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in SOS:26260
