### ISSUE TITLE
export kdf_sha256 interface from crypto lib

### ISSUE THREAD

**Issue by GangSecurity** [projectacrn/acrn-hypervisor#1812]
export the function and use it to derive key for attestation keybox decryption

**Comment by hwang37** [comment]
@GangSecurity  Is this a new feature? If yes, @mwang106 can help to add link ID for tracking.

**Comment by GangSecurity** [comment]
yes, please help add link

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1743
