### ISSUE TITLE
SOS : network on MRB not stable

### ISSUE THREAD

**Issue by Johnliuxin** [projectacrn/acrn-hypervisor#1813]
# Environment
- Hardware : GP-MRB-B2.C (Fab D)
- Software : acrn-2018w46.2-140000p

# Description
Boot to SOS rootfs, then plugin ethernet cable, then we need to wait long time to obtain the IP address.  

If you type cmd 'dmesg', you can see the following log:  

> [  331.452926] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
> [  333.531492] igb 0000:02:00.0: exceed max 2 second
> [  333.531768] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Down
> [  335.265925] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
> [  337.347479] igb 0000:02:00.0: exceed max 2 second
> [  337.347795] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Down
> [  351.189879] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
> [  353.267461] igb 0000:02:00.0: exceed max 2 second
> [  353.267740] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Down
> [  354.894884] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
> [  356.979475] igb 0000:02:00.0: exceed max 2 second
> [  356.979750] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Down
> [  362.508908] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
> [  364.587527] igb 0000:02:00.0: exceed max 2 second
> [  364.587822] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Down
> [  366.192886] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
> [  368.315462] igb 0000:02:00.0: exceed max 2 second
> [  368.315764] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Down
> [  393.562880] igb 0000:02:00.0 ens4: igb: ens4 NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX

Sometimes, the interface may UP/Down for a long time (maybe 10 minute or 1 hour or more long), then yuo can see it work normal.
> [  393.562953] igb 0000:02:00.0 ens4: Link Speed was downgraded by SmartSpeed
> [  393.563104] acrn-br0: port 1(ens4) entered blocking state
> [  393.563108] acrn-br0: port 1(ens4) entered forwarding state
> [  393.563308] IPv6: ADDRCONF(NETDEV_CHANGE): acrn-br0: link becomes ready

# More test result
## 2018.11.15

- If MRB connect to our company's router
    - On 1000M port : MRB could obtain IP normally
    - On 100M port : MRB could NOT obtain IP normally, and the above problem occurs. But if use my PC connect to the same port, PC could obtain IP normally.
- If MRB connect to my own home router
    - On 100M port : MRB could obtain IP normally.
    - ON 1000M port : not test.

Conclusion : maybe the problem is related to our company's network enviroment, we will check internal first.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1720
