### ISSUE TITLE
improve emulation of I/O port CF9

### ISSUE THREAD

**Issue by ZideChen0** [projectacrn/acrn-hypervisor#1815]
Currently, from guests' perspective, the behavior of I/O port CF9 is correct, but the implementation in hypervisor may not be ideal:
- SOS, it calls allow_guest_pio_access() to clear the IO bitmap for CF9.
- partition mode, port CF9 is handled by vpci. It works but conceptually
 this is not good.
- Not yet, but if vpci is enabled in UOS, similarly, CF9 will be handled
 in vpci code.

**Comment by Mingyuan18** [comment]
[System_External_ID] ACRN-2231

**Comment by Mingyuan18** [comment]
No regression issue found in test.
