### ISSUE TITLE
Add SOS vuart port base address/IRQ Kconfig options

### ISSUE THREAD

**Issue by zds100** [projectacrn/acrn-hypervisor#1817]
Adding Kconfig option to define SOS vuart port base address/IRQ.
By fault, use 0x3F8/IRQ4. For MRB, use 0x3E8/IRQ6.

We are experiencing problems on NUC after changing from 0x3F8/IRQ4 
to 0x3E8/IRQ6.

**Comment by donsheng** [comment]
[External_System_ID] ACRN-1703

**Comment by Mingyuan18** [comment]
Can't reproduce this issue.
