### ISSUE TITLE
Add OVMF booting support

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#1832]
Add OVMF support for booting as an alternative to vSBL.
Add support for loading OVMF into the High BIOS area and booting it from acrn-dm.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1733

**Comment by mattcurfman** [comment]
What is fast boot performance of OVMF compared with vSBL?

**Comment by hwang37** [comment]
@peterfang to follow up

**Comment by NanlinXie** [comment]
Basic function test to launch UOS with OVMF has done on KBL NUC/APL NUC/APL UP2
One critical issue found, tracked by https://github.com/projectacrn/acrn-hypervisor/issues/2276
