### ISSUE TITLE
Multiple display rotation test is not displayed on the android screen.

### ISSUE THREAD

**Issue by dandanyx** [projectacrn/acrn-hypervisor#1841]
Environment:
------------
Hypervisor: acrn-2018w41.4-140000p
Kernel branch: acrn_mainline_v419-rc6_ww413 
Clearlinux: 20180926-25180

Bug detailed description:
-------------
Multiple display rotation test is not displayed on the android screen and no rotating

Reproduce steps:
-------------
1. Boot up SOS
2. Boot up Android guest 
3. Edit "/vendor/etc/hwc_display.ini" to rotate Android guest:
fail:
(1).ROTATION="true"
PHYSICAL_DISPLAY_ROTATION="1:1"
(2).ROTATION="true"
PHYSICAL_DISPLAY_ROTATION="1:2"
(3).ROTATION="true"
PHYSICAL_DISPLAY_ROTATION="1:3"
5.adb push hwc_display.ini /vendor/etc
6.adb shell "cat /vendor/etc/hwc_display.ini"
7.Execute the command "adb reboot" to reboot Android guest.

Current result:
--------------
Multiple display rotation test is not displayed on the android screen and no rotating

Expected result:
--------------
Can be rotated according to edited parameters

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in this build: 
ACRN-Hypervisor: 2018w48.1.173000p_123; SOS Build :  20181128-26540
