### ISSUE TITLE
ACRN modulization

### ISSUE THREAD

**Issue by JasonChenCJ** [projectacrn/acrn-hypervisor#1842]
According to ACRN HLD https://projectacrn.github.io/latest/developer-guides/hld/hld-overview.html#acrn-architecture, we organize ACRN arch as different components like lib, hwinit, hwmgmt, vcpu, passthru, dm, io, vmmgmt and debug.
This story is used to trace the modulization progress for these different components.

**Comment by JasonChenCJ** [comment]
[External_System_ID] ACRN-1750

**Comment by NanlinXie** [comment]
Closed with no regression issue.
