### ISSUE TITLE
Put partition mode board specific files under partition/$(CONFIG_BOARD)/ and added partition mode support for cb2_dnv

### ISSUE THREAD

**Issue by donsheng** [projectacrn/acrn-hypervisor#1853]
Put partition mode board specific files under partition/$(CONFIG_BOARD)/ and added partition mode support for cb2_dnv.

**Comment by donsheng** [comment]
[External_System_ID] ACRN-1899

**Comment by Mingyuan18** [comment]
No regression found, closed this issue.
