### ISSUE TITLE
Fail to enumerate USB device after many times of suspending and resuming

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1894]
Fail to enumerate USB device after many times of suspending and resuming;

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2013

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
ACRN-Hypervisor : 2018w51.2.140000p_134
SOS : 26830
