### ISSUE TITLE
Fix acrnctl mistake displaying suspended to paused

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#1910]
After running "acrnctl suspend vm1", the VM1 state shows "pause" instead of "suspend".
[internal systemID] 1721

**Comment by lijinxia** [comment]
[External_System_ID] ACRN-1721

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
ACRN : 2018w50.3.140000p_131
SOS : 26800
