### ISSUE TITLE
Documentation: What does ',b' flag do with virtio-blk?

### ISSUE THREAD

**Issue by mattcurfman** [projectacrn/acrn-hypervisor#1917]
In the launch script @ https://github.com/projectacrn/acrn-hypervisor/blob/master/devicemodel/samples/apl-mrb/launch_uos.sh#L118, there is a ‘,b’ flag added to the virtio-blk parameters for acrn-dm, but this flag is missing in the NUC launch script @ https://github.com/projectacrn/acrn-hypervisor/blob/master/devicemodel/samples/nuc/launch_uos.sh

Further, there is no documentation for this flag at https://projectacrn.github.io/latest/developer-guides/hld/virtio-blk.html

What does the ‘,b’ flag do?

**Comment by yifanddd** [comment]
[External_System_ID] ACRN-3378

**Comment by Mingyuan18** [comment]
@mattcurfman , Could you please confirm whether this problem still exists? If it does not exist, can you close it?

**Comment by gvancuts** [comment]
This issue is still valid as far as I can see, the script uses the `,b` flag as part of the `virtio-blk` options but it is not described anywhere (that I could easily find) in our documentation.

**Comment by Mingyuan18** [comment]
Patch merged. So close this issue.
