### ISSUE TITLE
HV: move PCI ignored device from SOS bootargs to hypervisor

### ISSUE THREAD

**Issue by mcao6** [projectacrn/acrn-hypervisor#1923]
now vPCI supported in HV, we can move PCI ignored device (PCI uart device) from SOS bootargs to hypervisor; so we can revert the patch in SOS kernel, which is hard to upstream.

**Comment by mcao6** [comment]
extern ticket: ACRN-1698

**Comment by Mingyuan18** [comment]
No regression issue found in test.
