### ISSUE TITLE
SOS failed to boot on KBL NUC while using NVME strorage

### ISSUE THREAD

**Issue by binbinwu1** [projectacrn/acrn-hypervisor#1946]
SOS failed to boot on KBL NUC while using NVME strorage.
The root cause is there is a bug when handling guest MSI-X table access.

**Comment by binbinwu1** [comment]
[External_System_ID] ACRN-1967

**Comment by mattcurfman** [comment]
Which exact KBL NUC model exhibits this bug?  Not reproduced with NUC7i7DNHE with BIOS 58

**Comment by binbinwu1** [comment]
@mattcurfman My KBL NUC model is NUC7i7DNH, product code is BLKNUC7i7DNH1E.
The bug can be triggered if the msix-table offset is not 0 in the msix table BAR.
