### ISSUE TITLE
Minor refinement and enhancement about acrntrace/log

### ISSUE THREAD

**Issue by KaigeFu** [projectacrn/acrn-hypervisor#1975]
1. In current implementation, those tools will run without an error thrown out when no devices found. It is a little bit confusing.
2. We use get_cpu_num to get devices count. It is more suitable to rename it to get_dev_cnt.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2018

**Comment by Mingyuan18** [comment]
It's fixed by using below build: 
ACRN-Hypervisor :  2018w51.2.140000p_134
SOS : 26830
