### ISSUE TITLE
add 'no-omit-frame-pointer' in debug version

### ISSUE THREAD

**Issue by mingqiangchi** [projectacrn/acrn-hypervisor#1979]
Hypervisor uses '-O2' compiler option,
it will omit frame pointer by default for '-O2',
need to add 'no-omit-frame-pointer' in debug version.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2026

**Comment by Mingyuan18** [comment]
No regression issue found in test. So close it.
