### ISSUE TITLE
Input is useless in UART Console for corner case

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#1991]
1.Environment
--------------------------------------------------------------
Installed version: 26550
Version URL: http://linux-ftp.sh.intel.com/pub/mirrors/clearlinux/update
Content URL: http://linux-ftp.sh.intel.com/pub/mirrors/clearlinux/update

2.Reproduce step:
--------------------------------------------------------------
1). Boot to SOS
2). SSH to SOS.
3). ./launch_UOS.sh to boot uos.
4). minicom -s dev/ttyUSB0 in host.
5). sos_console 0 to launch sos.

3. Current result:
--------------------------------------------------------------
in step 5: It could't input(only output) in console

4. Expected result:
--------------------------------------------------------------
in step 5: It is normally in console.

5. repetition rate
--------------------------------------------------------------
100%

6.Logs:

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2011

**Comment by Mingyuan18** [comment]
This issue of third party, so close it.
