### ISSUE TITLE
[launch_uos.sh]need to change the path of UOS image

### ISSUE THREAD

**Issue by ailun258** [projectacrn/acrn-hypervisor#2003]
in latest( v0.4 ) update of getting started guide, for using Clear Linux as the SOS, we switched to "clear" user as the default User name to void using "root" directly, and created a uos folder for placing UOS image, 
so need to change path of the uos image in launch_uos.sh.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-1910

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
ACRN: 2018w50.3.140000p_131; SOS : 26800
