### ISSUE TITLE
[MRB][HV][AaaG]acrnctl reset fail.

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#2016]
1.Environment
 --------------------------------------------------------------
 Installed version: 26400

2.Reproduce step:
 --------------------------------------------------------------
 1). Boot to SOS
 2). SSH to SOS
 3). Add a Laag UOS into list over SOS SSH by
 acrnctl add [uos_bash_script]
    ex: acrnctl add launch_UOS.sh -V 1
 4). Start that VM by below command
     acrnctl start [vm name]
   Notes: use "acrnctl list" to check the vm name, if you don't know it. 
     ex: acrnctl start vm1-13:ce:dd
 5). Over console reset vm by below command
     acrnctl reset [vm name]
     Notes: use "acrnctl list" to check the vm name, if you don't know it. 

3. Current result:
 --------------------------------------------------------------
 Uos cannot boot up successfully.

4. Expected result:
 --------------------------------------------------------------
 Uos could boot up successfully.

5. repetition rate
 --------------------------------------------------------------
 100%

6.Logs:
 --------------------------------------------------------------
 root@clr-d62d549093f94ce9ac1a4b639ab448e3 ~ # acrnctl reset vm1-14:5b:5a
 Failed to stop vm1-14:5b:5a in 10 sec

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1922

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build: 
ACRN: 2018w51.2.140000p_134; SOS: 26830
