### ISSUE TITLE
UP2 fails to boot with uart=disabled for hypervisor

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2030]
1.Environment
[Board]: APL UP2
daily build：https://download.clearlinux.org/releases/26740/ 
Image info：26740

2.Steps
Replace acrn.efi After modifying acrn.conf, execute efibootmgr -c -l "\EFI\acrn\acrn.efi" -d /dev/mmcblk0 -p 1 -L "ACRN Hypervisor" -u "bootloader=\EFI\org .clearlinux\bootloaderx64.efi uart=disabled" SOS startup failed

3. Current result: SOS startup failed
4. Expected result: The SOS starts successfully

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2239

**Comment by Mingyuan18** [comment]
Cannot be reproduced in this build:
Installed version: 27050
