### ISSUE TITLE
tpm_emulator code reshuffle

### ISSUE THREAD

**Issue by yingbinx** [projectacrn/acrn-hypervisor#2052]
There are several issues which uninitialized variables
are used. This patch will fix those issues.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2245

**Comment by Mingyuan18** [comment]
@yingbinx , the patch was merged, please verify this issue, if the result is pass, please close this issue.

**Comment by Mingyuan18** [comment]
@yingbinx Do you have any update?

**Comment by Mingyuan18** [comment]
Close this issue, because Patch has been merged for a long time。
