### ISSUE TITLE
[MRB][HV]NO acrnlog_last log recorded after hypervisor crash.

### ISSUE THREAD

**Issue by KaigeFu** [projectacrn/acrn-hypervisor#2108]
NO acrnlog_last log recorded after hypervisor crash.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1650

**Comment by Mingyuan18** [comment]
Can not repro this bug by using below build
ACRN-Hypervisor : 2019w01.4.150000p_138
SOS : 27040

**Comment by Mingyuan18** [comment]
Reopen this issue due to can reproduce it now: 
ACRN-Hypervisor | 2019w03.5.150000p_148
SOS : 27215

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in this build:
ACRN: 2019w05.3.150000p_156
SOS : 27700
