### ISSUE TITLE
Profiling: fix the profiling tool crash by page faults

### ISSUE THREAD

**Issue by mlim19** [projectacrn/acrn-hypervisor#2157]
Profiling tools are broken, which cause page faults during collection.
The issue happens by enabling SMAP recently. Therefore, 
we use stac() and clac() to allow access to buffers allocated by guest vm.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2344

**Comment by Mingyuan18** [comment]
@mlim19  please verify this issue, thanks!

**Comment by mlim19** [comment]
Successfully verified.
