### ISSUE TITLE
The Jenkins CI does not catch all compilation errors

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#216]
It was observed during the review process of PR #197 that it was not possible to compile the code with the patch proposed. The error was visible in the Jenkins CI console [output](http://darcy-optiplex.sh.intel.com:8080/job/acrn-hypervisor-premerge-build-nuc/105/console) but the end result of the test was still set to `SUCCESS`.

We need to investigate why it did not set this to `FAILED` and correct this to make sure similar problems are caught by the Jenkins CI system automatically.

**Comment by NanlinXie** [comment]
@gvancuts The previous failure not captured by CI is because that acrn.efi and DM is built out and deployment is successfully although tools failed. We have updated our CI script to check tool build failure and plan to add some tool test in deployment.

**Comment by gvancuts** [comment]
hi @NanlinXie , can we close this issue?

**Comment by NanlinXie** [comment]
@gvancuts , Yes, we have already fixed the compile check issue.

**Comment by gvancuts** [comment]
Closing as per the previous comment
