### ISSUE TITLE
For UEFI based hardware platforms, one ClearLinux E2E build binary can be used for all platform's installation

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2170]
The E2E build binary should include ACRN component, vSBL, SOS, LaaG image.
The E2E build binary should support IVI usage by sharing mode, Real-time usage by partition mode.
The open source platforms to be supported: Apollo Lake NUC, Kabylake NUC, Apollo Lake UP2, with UEFI firmware as boot loader.
 ACRN hypervisor only need one UEFI kconfig file for all. In the long run, should remove different configure file for different hardware platform
ClinuxLinux E2E GSG may have addition steps to guide community developer on how to boot E2E build on different platforms, by changing efibootmgr params for different hardware platforms.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2274

**Comment by Mingyuan18** [comment]
Not found any Regression issue in test. So clost it
