### ISSUE TITLE
Fix RTC issues in ACPI

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#2176]
Clear Linux complains about RTC in ACPI:

platform rtc_cmos: registered platform RTC device (no PNP device found)
ACPI Error: Could not enable RealTimeClock event (20180531/evxfevnt-184)
ACPI Warning: Could not enable fixed event - RealTimeClock (4) (20180531/evxface-620)

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2322

**Comment by Mingyuan18** [comment]
Verify pass on this build:
E2E 27840
