### ISSUE TITLE
Add doc build to CI acceptance test

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#218]
A recent PR (https://github.com/projectacrn/acrn-hypervisor/commit/ab0ba5f520d699c25521ac454f8c2670ba70eec3) broke the documentation build because of reST/Sphinx errors.  Adding a doc build to the CI acceptance test would have caught this before it was merged.

**Comment by NanlinXie** [comment]
Current CI will do "make doc" check for document PR (PR for /doc folder)

**Comment by gvancuts** [comment]
This is good, however not sufficient. We also need to catch documentation problems for the tools folder and also where Doxygen is involved. I don’t know if we can easily filter out the PRs that need this check vs. those that don’t.
