### ISSUE TITLE
cpuid leaf function 07h has subleaf

### ISSUE THREAD

**Issue by binbinwu1** [projectacrn/acrn-hypervisor#2198]
1. cpuid leaf 07h has subleaf:
According to SDM 3-194 Vol.2A, Table 3-8, cpuid leaf 07h has sub-leaves.
cpuid.07.eax reports the maximum input for sub-leaves.
Since there is no definition for subleaf > 0 in SDM, hv only supports subleaf 0.

2. In currently hv code, cpuid leaf function 14h is disabled,
CPUID.07H:EBX.INTEL_PROCESSOR_TRACE should be disabled as well.

**Comment by binbinwu1** [comment]
[External_System_ID] ACRN-2335

**Comment by Mingyuan18** [comment]
uos is one subleaf and CPUI.0x07. [ebx.bit25] =0 
Installed version: 27050
Linux sos-dom0 4.19.8-1901020539.iot-lts2018-sos #1 SMP PREEMPT Thu Jan 3 08:50:25 PST 2019 x86_64 GNU/Linux
DM version is: 0.5-unstable-”2019w01.5.170000p_140” (daily tag:”2019w01.5.170000p”), build by mockbuild@2019-01-04 09:37:48
