### ISSUE TITLE
Security: Service OS Support for Platform Security Discovery (apl_sdc_stable)

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2241]
The platform shall mediate access to the Platform Security Discovery (PSD) data structure between all guest operating systems, including the Service OS.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2415

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
ACRN-Hypervisor: 2019w02.2.150000p-141
SOS : 27151
