### ISSUE TITLE
need to wait for loading snd-soc-skl before starting UOS 

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#2247]
Currently whether audio works in virtio mediator or pass-through mode can be determined by checking the device file of vbs_k_audio

But before the completion of loading audio virtio-BE module, the device file of /dev/vbs_k_audio doesn't exist. In such case in course of loading UOS, the incorrect work mode is selected for audio device (passthru instead of mediator). This is incorrect.

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
ACRN-Hypervisor: 2019w03.1.150000p_143
SOS : 27213
