### ISSUE TITLE
[APLUP2][LaaG]LaaG can't detect 4k monitor

### ISSUE THREAD

**Issue by xiaoxiax** [projectacrn/acrn-hypervisor#2267]
Environment:
------------
HSW: APLUP2

Bug detailed description:
-------------
LaaG can't detect 4k monitor,4k monitor does not display.

Reproduce steps:
-------------

1.Connnet 4k monitor.
2. Boot up hypervisor and SOS and UOS

Current result:
--------------
LaaG can't detect 4k monitor,4k monitor does not display.

Expected result:
--------------
LaaG can detect 4k monitor,4k monitor can display.

**Comment by xiaoxiax** [comment]
[External_System_ID] ACRN-2423

**Comment by mwang106** [comment]
Mark this issue as a known limitation on APL platform.

**Comment by gvancuts** [comment]
> Mark this issue as a known limitation on APL platform.

Can you explain in a few words where the limitation comes from?
