### ISSUE TITLE
Launch UOS with 5G memory will hang 2 minutes

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#2277]
1.Environment:
HW/Board: APLNUC
Clearlinux: 27050(APLNUC)
acrn tag:”2019w01.5.170000p”
2. steps:
1. Launch SOS
2. Modify launch script, change memory to 5G
3. launch uos
3.Expected result:
UOS boot successfully
4.Actual result:
launch uos successfully, but will hang about 2 minutes in the launch process
5.Reproduce rate:
5/5

**Comment by mwang106** [comment]
the bug cannot reproduced with 
Build Image:
Installed version: 27600
Version URL: http://linux-ftp.sh.intel.com/pub/mirrors/clearlinux/update
Content URL: http://linux-ftp.sh.intel.com/pub/mirrors/clearlinux/update
