### ISSUE TITLE
[IO Mediator][AaaG]IOC mediator sometimes loses packets sent to UOS, including wakeup reason and signal data.[FR: 5%](apl_sdc_stable)

### ISSUE THREAD

**Issue by lidongwangx** [projectacrn/acrn-hypervisor#2282]
IOC mediator sometimes loses packets sent to UOS, including wakeup reason and signal data.[FR: 5%]

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2427

**Comment by Mingyuan18** [comment]
No regression issue found in test.
