### ISSUE TITLE
Acrnd timer expire when test S39(apl_sdc_stable).

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#2306]
When testing ignition button triggered S3 , UOS setup a timer in Acrnd, wich should not have chance to be expire and run. Because UOS & SOS should enter S3 soon, and this timer will be removed from Acrnd memory. But it seems the UOS have a chance to run into  timer expired case, and Acrnd try to launch the UOS, do not answer the request from acrn-dm & lifecycle-service

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-2262

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
ACRN-Hypervisor | 2019w03.5.150000p_148
SOS : 27215
