### ISSUE TITLE
apl-mrb: add panic_print parameter to sos boot cmdline(apl_sdc_stable)

### ISSUE THREAD

**Issue by ftang1** [projectacrn/acrn-hypervisor#2309]
Add "panic_print=0x1f" will enable the kernel to print out more system info when panic is hit, which will help much on system debugging

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2463

**Comment by Mingyuan18** [comment]
@ftang1 , Please confirm whether this problem has been solved. If so, please close it
