### ISSUE TITLE
Tools don't respect CFLAGS/LDFLAGS from environment

### ISSUE THREAD

**Issue by rossburton** [projectacrn/acrn-hypervisor#2316]
The build environment might want to pass extra CFLAGS or LDFLAGS to the build of the acrn tools.  With conventional build systems like automake, Meson, etc this is possible by just setting CFLAGS and LDFLAGS in the environment.

However as the tools are built using bare Makefiles, these environment variables are overwritten.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2474

**Comment by Mingyuan18** [comment]
@rossburton Please verify this issues, close it if the result is pass. Thanks!
