### ISSUE TITLE
DMAR_PARSE_ENABLED fails on few platforms

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#2320]
when DMAR_PARSE_ENABLED is set to true, hypervisor crashes on certain platforms. For example, apl-MRB.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2462

**Comment by Mingyuan18** [comment]
@sainath14 , 
Please confirm if this bug still exists. If can't be reproduced. Please close it.

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build, so close it.
SOS: 28720
ACRN TAG: acrn-2019w15.3-140000f
