### ISSUE TITLE
[UP2]Lost 2G memory in SOS when using SBL as bootloader on UP2

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2338]
After using SBL as bootloader to boot UP2 with 4G physical memory bank, SOS only has 2G memory.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2475

**Comment by mwang106** [comment]
This is an SBL issue. Will fix in the future release. For work-around, user can change SBL configuration and rebuild to detect the correct memory capacity. See the following:

1. https://slimbootloader.github.io/how-tos/configure-memory-down.html
2. https://lists.01.org/pipermail/sbl-devel/2018-December/000033.html

**Comment by Mingyuan18** [comment]
Cannot reproduced in up2 with SOS 28100.
