### ISSUE TITLE
[tools] Don't hardcode install paths

### ISSUE THREAD

**Issue by rossburton** [projectacrn/acrn-hypervisor#2347]
The tools hardcode install locations, which is bad practise as not every distro is the same.

Would it be better to just replace the Makefiles with Meson or similar?

**Comment by gvancuts** [comment]
> Would it be better to just replace the Makefiles with Meson or similar?

I'm all in favour of that, +1!

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2539

**Comment by lyan3** [comment]
It's a 

> The tools hardcode install locations, which is bad practise as not every distro is the same.
> 
> Would it be better to just replace the Makefiles with Meson or similar?

Thanks for the good suggestion. I will have it as one future work for now, and of course, it needs to be resolved before more distro other than ClearLinux and Ubuntu is supported as SOS.

**Comment by fuzhongl** [comment]
@rossburton 
Thanks for reporting this issue; we are working on this issue and will keep you update in future.

**Comment by rossburton** [comment]
How are you working on it?  If you're making the paths variables in the makefiles then I have a patch you can start with.  If you're moving to Meson then I'll help where I can.
