### ISSUE TITLE
Doesn't use parallel make in subbuilds

### ISSUE THREAD

**Issue by rossburton** [projectacrn/acrn-hypervisor#2370]
If I pass -j to the top level make, because it recurses using `make` instead of `$(MAKE)` you get a warning:

> ‘warning: jobserver unavailable: using -j1. Add `+' to parent make rule.’

Changing all instances of `make` to `$(MAKE)` solves this.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2535

**Comment by Mingyuan18** [comment]
@rossburton Please verify this issue and close it if the result is pass. Thanks!
