### ISSUE TITLE
Use the kthread API to manage the kernel thread related with ioreq_client

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#2383]
Currently some backend driver will create one specific kernel thread to handle the emulated ioreq.
It will be better that they are unified to the same style. 

At the same time it will be better that the kthread API is used to manage the lifecycle of ioreq_client_thread, which helps to remove the complex state setting in ioreq_client.

**Comment by yakuizhao** [comment]
[External_System_ID] ACRN-2545

**Comment by Mingyuan18** [comment]
The patch was merged and no new issue found.
