### ISSUE TITLE
Coding style changes for IOAPIC and MSI representation

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#2407]
Bits in IOAPIC RTE and MSI addr and data registers mean different when Interrupt Remapping is enabled.
Adding bit representation for structures that represent IOAPIC and MSI interrupt registers. This will improve flexibility and clarity in ACRN as it needs to use both IR format and legacy (compatibility) format. This is a staging patch for implementing IR in ACRN.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2587

**Comment by Mingyuan18** [comment]
No regression issue found in test.
