### ISSUE TITLE
[PATCH] profiling: fix the system freeze issue when running profiling  tool

### ISSUE THREAD

**Issue by mlim19** [projectacrn/acrn-hypervisor#2422]
The msr load/restore during vmexit/vmenty in HV by default. The profiling has assumption that it's only user for this feature, which could overwrite of HV default setting.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2605

**Comment by Mingyuan18** [comment]
@mlim19 , Please help to check this issue is resolved or not.  If verify pass, please close it. Thanks!
