### ISSUE TITLE
Fix the acrn-hypervisor panic of invalid pte caused by the incorrect resource release in gvt 

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#2440]
The gvt refinement of using the unified ioreq_client kthread API introduces one bug of vgpu resource release. Then this bug will trigger the pance in hypervisor:
   >panic("invalid op, pte present");

**Comment by yakuizhao** [comment]
[External_System_ID] ACRN-2583

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
Installed version: 27530
sos info:
Linux sos-dom0 4.19.19-quilt-2e5dc0ac-04443-gf4dbe17e3b91 #1 SMP PREEMPT Fri Feb 15 04:33:47 UTC 2019 x86_64 GNU/Linux
