### ISSUE TITLE
Adding support for socket as a backend for Virtio-Console

### ISSUE THREAD

**Issue by vijaydhanraj** [projectacrn/acrn-hypervisor#2448]
socket is not currently supported as backend for virtio-console. Kata containers require socket backend for virtio-console in order to communicate between the agent running in the VM and the proxy running in the host. In order to support Kata with ACRN, this feature is required.

**Comment by vijaydhanraj** [comment]
Sure, can do it. But any reason why? Am I missing something?

FYI: I had created a pull request by accident before getting the patch reviewed. So closed the previous PR.

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in this build: SOS: 28010; ACRN tag: 2019w08.5.140000p_165
