### ISSUE TITLE
Enable cache QOS with CAT

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#2462]
The Hypervisor and ServiceOS shall enable cache QOS with CAT (Cache Allocation Tech), CDP (Cache Data Prioritization) and pseudo-locking across GuestVMs. This feature availability shall be a build time or boot time configuration. The cache configuration shall be accessible via runtime interfaces accessible to both GuestVMs and ServiceOS processes, through some trusted mechanism.

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-2408

**Comment by Mingyuan18** [comment]
this issue is ok on build:
UP2 build:
Clear Linux 28260,
acrn hypervisor tag: 2019w11.1.140000p
