### ISSUE TITLE
Need to capture dropped sample info while profiling

### ISSUE THREAD

**Issue by mlim19** [projectacrn/acrn-hypervisor#2474]
Since the profiling may experience dropped samples due to the limited size of buffer, capturing the information is required to understand the reliability of the data collected by the profiling tool.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2636

**Comment by Mingyuan18** [comment]
@mlim19 , Could you please verify this issue? If it cannot be reproduced, please close this issue, thank you!

**Comment by mlim19** [comment]
Verified.
