### ISSUE TITLE
Mismatch the max vcpus between hypervisor and SOS profiling module

### ISSUE THREAD

**Issue by mlim19** [projectacrn/acrn-hypervisor#2476]
The number of max VCPUs defined in hypervisor can be different, compare to SOS profiling module, in which case the profiling tool can't obtain vcpu-pcpu mapping information properly.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2637

**Comment by mlim19** [comment]
Based on Eddie's suggestion, I am going to submit new patchset.

**Comment by Mingyuan18** [comment]
@mlim19 , Will you update the patch?

**Comment by fuzhongl** [comment]
@mlim19 Any plan for new patch?
Thanks!

**Comment by mlim19** [comment]
No plans at this time. I close it for now and will create a new issue later when ready to submit.
