### ISSUE TITLE
Don't hard-code TAP names

### ISSUE THREAD

**Issue by rossburton** [projectacrn/acrn-hypervisor#2509]
`acrn-dm` takes the TAP device name and appends `acrn_` to it, which is unobvious.  The name of the tap device passed to `acrn-dm` should be the name that is used.

**Comment by rossburton** [comment]
https://github.com/projectacrn/acrn-hypervisor/blob/master/devicemodel/hw/pci/virtio/virtio_net.c#L667

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2677

**Comment by rossburton** [comment]
Fixed in 00dd26b0815548c5669c3fd52a65286cc0503a1c.

**Comment by rossburton** [comment]
Thanks!
