### ISSUE TITLE
GPIO virtualization

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2512]
GPIO virtualization

GPIO virtualization is para-virtualization, which based on virtio.

The BE controls whole native gpio resource via linux gpio userspace interface, and FE supports a virtual GPIO controller that FE driver is able to access GPIO via virtio virtqueue.

The major functions include set/get GPIO value/direction, set GPIO config, switch a GPIO to interrupt mode.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-1946

**Comment by Mingyuan18** [comment]
No regression issue found in QA test.
