### ISSUE TITLE
[UP2][SBL] System hang with DP monitor connected

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2516]
SOS version: 27530
Bug detailed description:
1. Enter SOS console and run cmd as following:
ebug/dri/0/i915_display_info
Current result:
SOS hang and then meet  task hang kernel panic after 2 mins.
Expected result:
Able to show display info without crash.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2646

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in 28010.
