### ISSUE TITLE
System Hangs when invoking sos_console X (Where X >= CONFIG_MAX_VM_NUM) in CONFIG_PARTITION_MODE

### ISSUE THREAD

**Issue by kpanchag** [projectacrn/acrn-hypervisor#2520]
System hangs, only way to recover is a reset of the SOC

ACRN:\>sos_console 5
----- Entering Guest 5 Shell -----

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2675

**Comment by Mingyuan18** [comment]
@kpanchag , Please confirm whether this issue has been solved. Thanks!

**Comment by kpanchag** [comment]
> @kpanchag , Please confirm whether this issue has been solved. Thanks!
Yes this i
