### ISSUE TITLE
[APLUP2] SBL (built by SBL latest code) failed to boot ACRN hypervisor

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2528]
SBL built by latest slimbootloader code (HEAD->ad42a2bd6e4a6364358b9c712cb54e821ee7ee42) failed to boot acrn hypervisor.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2623

**Comment by mwang106** [comment]
SBL built by earlier slimbootloader code (commit id:edc112328cf3e414523162dd75dc3614e42579fe) can boot acrn hypervisor normally.

**Comment by Mingyuan18** [comment]
usehttps://github.com/slimbootloader/slimbootloader/tree/d397299797ecc402767f9caa5433e61c9d3e886d as release SBL
