### ISSUE TITLE
VPCI code cleanup: unify the vpci sharing and partition mode

### ISSUE THREAD

**Issue by donsheng** [projectacrn/acrn-hypervisor#2534]
Changes include:
Bug fix, code cleanup, misra c violations fix
Unify the vpci sharing and partition mode
Remove CONFIG_PARTITION_MODE in vpci code to support hybrid mode
Code cleanup

Note: will take several PRs to complete this issue.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2682

**Comment by Mingyuan18** [comment]
No regression issue in below build:
Clear Linux 28800
Kenrel Version: linux-iot-lts2018-4.19.34-45
acrn hypervisor tag: acrn-2019w15.4.140000p
