### ISSUE TITLE
GVT-g not fully functional on SKL

### ISSUE THREAD

**Issue by rossburton** [projectacrn/acrn-hypervisor#2542]
Sky Lake is Gen9, Kaby Lake is Gen9.5.

So in theory, it shouldn't be *that* difficult to enable GVT-g on SKL.  However a lot of the kernel code is guarded with `IS_KABYLAKE()` so doesn't even attempt to work on SKL.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3083

**Comment by fuzhongl** [comment]
@rossburton Sky Lake isn't the supported HW.
Any more concern, please update the comments. If no more feedback within two weeks, this ticket will be closed by default. 
Appreciate for your understanding.

**Comment by rossburton** [comment]
For what it's worth the only piece of SKL enabling unmerged is the top two commits on this branch:

https://github.com/projectacrn/acrn-kernel/compare/acrn_skl_test

I'd love to see them merged, even if SKL isn't a supported platform these patches make it work.

**Comment by fuzhongl** [comment]
@rossburton  Let me check it internally and back to you.
Thanks!

**Comment by fuzhongl** [comment]
@rossburton  Please try with release_2.0
Thanks!

**Comment by rossburton** [comment]
Pinging @moto-timo as I don't work for Intel anymore.
