### ISSUE TITLE
vLAPIC: DCR not properly initialized

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#2543]
DCR is initialized to 0 which means divisor shift is 1. Currently, both are initialized to 0 which result in incorrect APIC timer counts if the vLAPIC's DCR is never programmed.

**Comment by peterfang** [comment]
[External_System_ID] ACRN-2688

**Comment by Mingyuan18** [comment]
No regression with 
swupd info
Installed version: 28010
