### ISSUE TITLE
Support DISCARD common for virtio-block.(apl_sdc_stable)

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#2547]
Porting discard related patches to stable branch, with these patches:
1.  'adb erase' time can be decreased.
2.  After run for a long time, android storage write performance will not decreased.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2697

**Comment by Mingyuan18** [comment]
No regression issue in GP2.0 PV test.
