### ISSUE TITLE
adb lost during S3 stress test

### ISSUE THREAD

**Issue by ywan170** [projectacrn/acrn-hypervisor#2557]
The adb get lost during S3 stress test.

**Comment by wenlingz** [comment]
@ywan170 please add external_ID, thanks

**Comment by shenfang2019** [comment]
[External_System_ID] ACRN-2684

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
ACRN-Hypervisor : 2019w09.4.153000p_162
SOS : 28102
