### ISSUE TITLE
Bugs related to PDPT address calculation for PAE mode

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2561]
1. Current code doesn't ignore the "Ignored" fileds when load pdpt registers.
Mask the "Ignored" fileds according to SDM Figure 4-7 Vol3.
2. Current code only ignores 4bits instead of 5bits in low "Ignored" filed when
calculate PDPT address in PAE mode for guest memory address translation.

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2707

**Comment by Mingyuan18** [comment]
change code,fixed bug
