### ISSUE TITLE
UOS boot failed for IASL updated to support ACPI 6.3 (apl_sdc_stable)

### ISSUE THREAD

**Issue by mcao6** [projectacrn/acrn-hypervisor#2565]
UOS boot failed for IASL updated to support ACPI 6.3

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2714

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
ACRN-Hypervisor : 2019w09.4.153000p_162
SOS: 28102
