### ISSUE TITLE
UOS boot failed for IASL updated to support ACPI 6.3. 

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#2568]
UOS boot failed for IASL updated to support ACPI 6.3

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2715

**Comment by xyliu** [comment]
should work with new `/usr/sbin/iasl` tool. seems like with : https://github.com/acpica/acpica/commit/9cef114ce61ede77110cd93c42d50e5e82552ad3

**Comment by Mingyuan18** [comment]
Can’t reproduce this issue in below build:
ACRN Tag: 2019w09.4.153000p_162
SOS : 28102
