### ISSUE TITLE
Remove debug feature for tools (apl_sdc_stable)

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2574]
Environment

HW/Board

ACRN MRB

Build link

https://mcg-depot.intel.com/artifactory/cactus-absp-jf/build/eng-builds/master/PSI/weekly/2019_WW05/daily/weekly build link
Image info.

Steps

check ./tools/Makefile

Expected result

remove debug feature for ACRN Tools

Actual result

#acrnlog &acrntrace is built-in.

Reproduce rate

100%

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2717

**Comment by Mingyuan18** [comment]
Have verified, fixed it.
