### ISSUE TITLE
Remove debug feature for tools

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2575]
Steps

check ./tools/Makefile

Expected result

remove debug feature for ACRN Tools

Actual result

#acrnlog &acrntrace is built-in.

Reproduce rate

100%

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2720

**Comment by Mingyuan18** [comment]
https://jira.devtools.intel.com/browse/ACRN-2720
