### ISSUE TITLE
allocate 64bit MMIO above 4G strictly to pass OVMF check

### ISSUE THREAD

**Issue by chejianj** [projectacrn/acrn-hypervisor#2577]
allocate 64bit MMIO above 4G strictly to pass OVMF check

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2723

**Comment by Mingyuan18** [comment]
Let's close this bug first. For the new issue, let's file another one to track.
No regression issue found in below build:
SOS version: 28600
acrn tag: acrn-2019w14.1-140000p
kernel: 2018 4.19.31-39
