### ISSUE TITLE
acrn-dm segfaults if virtio-gvt enabled but not enabled in kernel

### ISSUE THREAD

**Issue by rossburton** [projectacrn/acrn-hypervisor#2584]
If acrn-dm is configured with VGT but `i915.enable_gvt=1` was not passed to the SOS kernel then acrn-dm segfaults instead of reporting a nice error.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2744

**Comment by fuzhongl** [comment]
@rossburton Patch was merged. Could you please close this ticket?
Thanks!

**Comment by Mingyuan18** [comment]
Closed this issue because there was no feedback for two weeks.
