### ISSUE TITLE
ACRN HV: allow pre-launched VMs have different memory size and use > 2GB memory

### ISSUE THREAD

**Issue by ZideChen0** [projectacrn/acrn-hypervisor#2587]
Need to:

1) allow different pre-launched VMs use different memory size.
2) allow pre-launched VMs use more than 2GB guest memory.
3) for multiboot, ramdisk should bet available for per-launched VMs.

**Comment by ZideChen0** [comment]
[External_System_ID] ACRN-2690

**Comment by Mingyuan18** [comment]
No regression issue in below build:
SOS : 29070
ACRN TAG: acrn-2019w17.4-160000p 
Kernel: linux-iot-lts2018 4.19.34
