### ISSUE TITLE
Update vsbl to v1.2(apl_sdc_stable)

### ISSUE THREAD

**Issue by binbinwu1** [projectacrn/acrn-hypervisor#2595]
Update vFastboot to v1.2
Newly changed:
        Optimize fastboot erase for virtual IO block medium.
        Update openssl to version 1.0.2q.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2745

**Comment by Mingyuan18** [comment]
Cannot reproduced this issue in below build:
SOS version: 28100
