### ISSUE TITLE
Return PIPEDSL from HW register instead of cached memory for Guest VGPU

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#2597]
Currently when guest VGPU tries to read the PipeDSL register, it is returned from the cached content.
To get the accurate value from pipeDSL, it should be read from the HW register.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3097

**Comment by yakuizhao** [comment]
[External_System_ID] ACRN-3097

**Comment by yakuizhao** [comment]
Now the patch is already merged.
So this issue will be closed.
