### ISSUE TITLE
hv: search additional argument when parsing seed from ABL(apl_sdc_stable)

### ISSUE THREAD

**Issue by YadongQi** [projectacrn/acrn-hypervisor#2605]
Due to ABL design change, it will reword the "dev_sec_info.param_addr="
to "ABL.svnseed" in command line.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2802

**Comment by Mingyuan18** [comment]
No regression issue found in below build, so close this issue.
ACRN TAG:  2019w11.3.153000p
Kernel: 4.19.23-24
SOS: 28100
