### ISSUE TITLE
Remove redundant get_dmar_info API calls

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#2657]
get_dmar_info API is called from multiple functions in vtd.c. This patch
    calls get_dmar_info once during init and uses the cached info during
    runtime.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2861

**Comment by Mingyuan18** [comment]
Patch merged and no regression in daily build: 
CL:30400
ACRN TAG: acrn-2019w29.3-140000p
