### ISSUE TITLE
Script: Fix snd_soc_skl typo in launch script (apl_sdc_stable)

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#2666]
Fix snd-soc-skl to snd_soc_skl in launch script.

**Comment by wenlingz** [comment]
[External_System_ID]ACRN-2889

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build, so close it.
ACRN-Hypervisor : 2019w10.4.150000p_164
SOS: 28104
