### ISSUE TITLE
The "ACRN Shell Commands" documentation is out-of-date

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#2684]
The [ACRN Shell Commands](https://projectacrn.github.io/latest/user-guides/acrn-shell.html) document is out of date and could do with some extra details.

Examples of outdated info: `vmexit`, `logdump` are no longer available

A couple of commands are also missing:
```
rdmsr           [-p<pcpu_id>] <msr_index> - rdmsr -p<pcpu_id> <msr_index>, msr_index in hexadecimal
wrmsr           [-p<pcpu_id>] <msr_index> <value> - wrmsr -p<pcpu_id> <msr_index> <value>, msr_index and value in hexadecimal

```

**Comment by dbkinder** [comment]
Resolved.
