### ISSUE TITLE
HV: correct COM_IRQ default config type

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#2689]
Change the config type of COM_IRQ from "hex" to "int" , make it consistent with its default value.

**Comment by wenlingz** [comment]
@mcao6 please add external_ID,thanks

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2915

**Comment by Mingyuan18** [comment]
The patch was merged and no regression in daily test.
CL:30400
ACRN TAG: acrn-2019w29.3-140000p
