### ISSUE TITLE
Modularize hypervisor/boot and hypervisor/bsp folders

### ISSUE THREAD

**Issue by rarindam** [projectacrn/acrn-hypervisor#2694]
Re-organize the code to remove usage of hypervisor.h from boot and bsp folders, without changing any functionality.

Acceptance criteria: Both SOS and UOS should be able to boot up.

**Comment by acrnsi** [comment]
@rarindam please add your External_System_ID

**Comment by rarindam** [comment]
[External_System_ID] ACRN-2892
