### ISSUE TITLE
doc: fix typos in coding guidelines

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#2711]
Because the coding_guidelines.rst file is generated by a script, we can't make changes directly to the .rst file here in GitHub, for example, to fix typos, as noted here:

- replace "whitespaces" with "whitespace" (line 2815)
- replace "identifyer" with "identifier" (line 2903)
- replace "separete" with "separate" (line 2965)

**Comment by dbkinder** [comment]
@hwang37 Can we reevaluate how this document is generated so can be maintained directly in GitHub and be edited here?

**Comment by hwang37** [comment]
Will work with @shiqiangyu  to understand the doc process.

**Comment by dbkinder** [comment]
Typos are fixed.
