### ISSUE TITLE
Enable ACRN to boot Zephyr

### ISSUE THREAD

**Issue by KaigeFu** [projectacrn/acrn-hypervisor#2713]
Enable ACRN to boot Zephyr as a normal VM OS.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-2870

**Comment by Mingyuan18** [comment]
Verify pass on below build:
SOS version: 28600
acrn tag: acrn-2019w14.1-140000p
kernel: 2018 4.19.31-39
