### ISSUE TITLE
set realtime sched policy for vcpu thread (apl_sdc_stable)

### ISSUE THREAD

**Issue by mwang106** [projectacrn/acrn-hypervisor#2717]
To reduce the io emulation impact to audio FE which could trigger audio glitch

**Comment by mwang106** [comment]
[External_System_ID] ACRN-2941

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build, So close it.
ACRN TAG:  2019w11.3.153000p
Kernel: 4.19.23-24
SOS: 28100
