### ISSUE TITLE
Use domain/device specific invalidation for DMAR translation caches

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#2738]
ACRN uses global invalidation for all DMAR translation caches. Whenever
    a UOS is shutdown or rebooted, it ends up clearing entries in translation
    caches belonging to other VMs/domains. This patch adds support for
    domain/device level invalidation for DMA translation caches and index
    based invalidation for Interrupt Remapping Cache

**Comment by sainath14** [comment]
[External_System_ID] ACRN-2974

**Comment by Mingyuan18** [comment]
No regression issue found in below build:
SOS version: 28600 
 acrn tag: acrn-2019w14.1-140000p 
kernel: 2018 4.19.31-39 |
