### ISSUE TITLE
Fix the memory leak in pci_gvt_init/passthru_init of acrn-dm(apl_sdc_stable)

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#2752]
The pci_gvt_init/passthru_init tries to allocate some memory. But they are not released.
This will cause the memory leak.

**Comment by yakuizhao** [comment]
[External_System_ID] ACRN-3000

**Comment by Mingyuan18** [comment]
No regression issue in QA test.
