### ISSUE TITLE
Fix pthread_cond_wait usage

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#2763]
pthread_cond_wait() should take care of spurious wakeups and is usually used in conjunction with a predicate. Fix the uses of pthread_cond_wait() that can result in unintended behavior (e.g. segmentation fault).

**Comment by peterfang** [comment]
[External_System_ID] ACRN-3010

**Comment by Mingyuan18** [comment]
No regression issue found in below build,so close this issue.
ACRN TAG: acrn-2019w15.4.140000p
SOS: 28800
