### ISSUE TITLE
Enable PCI-E realtek MMC card for UOS

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#2772]
On APL-NUC when the realtek MMC card is assigned to UOS, no driver is loaded.

**Comment by yakuizhao** [comment]
[External_System_ID] ACRN-1480

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
Installed version: 28460
ACRN tag: acrn-2019w12.5-140000f
