### ISSUE TITLE
hv: trusty: refine control registers switching method

### ISSUE THREAD

**Issue by YadongQi** [projectacrn/acrn-hypervisor#2773]
Remove vmx_cr0/vmx_cr4 from ext_context structure, they are duplicated
with cr0/cr4 fields in run_context.
Switch cr0/cr4 of run_context structure on demand when do world switch.

Remove vmx_cr0_read_shadow/vmx_cr4_read_shadow from ext_context structure.
These fields should be same for both normal world and secure world.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3022

**Comment by Mingyuan18** [comment]
No regression issue found in below build,so close this issue.

ACRN TAG: acrn-2019w15.4.140000p

SOS: 28800
