### ISSUE TITLE
hv: seed: refine header file

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#2777]
1.move seed_info structure from trusty.h to seed.h
2.replace "#include <hypervisor.h>" with necessary including headers
    in seed.c/seed_abl.c/seed_sbl.c

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3028

**Comment by YadongQi** [comment]
please assign to me , thanks

**Comment by Mingyuan18** [comment]
No regression issue found in test.
SOS:28340
ACRN TAG: 2019w11.5.140000p
