### ISSUE TITLE
Pass ACRN E820 map to OVMF

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#2792]
ACRN currently uses [4GB, 5GB) as its 64-bit PCI host aperture. This is inconsistent with OVMF's assumption of its platform's memory layout, because it fetches the size of high memory from RTC CMOS.

Pass ACRN's E820 map to OVMF so it can correctly pass ACRN's memory configuration to UOS.

**Comment by peterfang** [comment]
[External_System_ID] ACRN-2931

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
Installed version: 28600
Kernel: 4.19.31-39
daily tag:”2019w14.1.140000p”
