### ISSUE TITLE
hv: minor issue in sbl_init_vm_boot_info()

### ISSUE THREAD

**Issue by ZideChen0** [projectacrn/acrn-hypervisor#2806]
In parsing multiboot info, in case of MULTIBOOT_INFO_HAS_CMDLINE if set, it wants to copy seed_arg, mbi->mi_cmdline and mods[0].mm_string to the 2KB kernel_cmdline[]buffer, but theoretically, the dest buffer could overflow.

**Comment by ZideChen0** [comment]
[External_System_ID] ACRN-3045

**Comment by Mingyuan18** [comment]
No regression issue in below build:
SOS version: 29070 
ACRN TAG: acrn-2019w17.4-160000p 
Kernel: linux-iot-lts2018 4.19.34    45 |
