### ISSUE TITLE
The ACRN hypervisor shell interactive help is rather terse

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#2829]
The ACRN hypervisor shell interactive help (typing `help` in the ACRN shell) is rather terse and some explanations are hard to understand and a bit confusing. We should add some verbiage and improve the readability and clarity of the help messages

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3070

**Comment by gvancuts** [comment]
#2816 has been merged, closing this issue.
