### ISSUE TITLE
Leave a gap for 32-bit PCI hole in E820 map

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#2843]
Guest OS (e.g. Linux) may rely on a gap in E820 map in the 32-bit memory space to determine the MMIO space for its PCI devices. Leave this gap when building E820 map to keep the guest's PCI subsystem working.

After commit 7752d5cfe3d11ca0bb9c673ec38bd78ba6578f8e, Linux kernel no longer requires the MMCONFIG region to be reserved in the E820 map. Nonetheless, keep it in the reserved region to be on the safe side.

**Comment by peterfang** [comment]
[External_System_ID] ACRN-3081

**Comment by Mingyuan18** [comment]
This issue can't duplicate in below build:
SOS: 28100
ACRN tag: acrn-2019w13.1-140000f
