### ISSUE TITLE
exception dump is not clear in certain scenario

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#2858]
In the cases when more than one CPU has something to print, exception
    dump from one CPU is overlapped with other CPU's messages and the final
    text that is printed on console is all mixed up and does not make any sense.
    Changing printf to pr_err so that the messages are printed one after
    the other.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3180

**Comment by Mingyuan18** [comment]
@sainath14 , the PR's ACRN tag is acrn-2019w13.4-140000p.  Can verify that the bug is fixed or not

**Comment by sainath14** [comment]
@Mingyuan18 this is fixed
