### ISSUE TITLE
support S5 of Normal VM with lapic_pt

### ISSUE THREAD

**Issue by KaigeFu** [projectacrn/acrn-hypervisor#2865]
The hypervisor and VM's shall power down the sytem to S5 state, when initiated by the Service OS.

**Comment by KaigeFu** [comment]
[External_System_ID] ACRN-2409

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build: 
Build info: ww15 E2E image:
Clear Linux 28720
Kenrel Version: linux-iot-lts2018 4.19.32-44
acrn hypervisor tag: acrn-2019w15.1.140000p
