### ISSUE TITLE
Completely remove enable_bar()/disable_bar() functions

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#2902]
Following up on d648df766c263512c93356a55ff97cb3e23fe3e4, surgically remove all the functions related to enable_bar()/disable_bar() that got introduced in 8787b65fdee622639925ad75fe920913e0e7f102.

**Comment by peterfang** [comment]
[External_System_ID] ACRN-3309

**Comment by Mingyuan18** [comment]
No regression issue in below build:
ACRN daily tag:acrn-2019w19.1-140000p
Installed version: 29250
