### ISSUE TITLE
Remove CONFIG_PARTITION_MODE used to compile out irq enable/disable

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#2903]
ACRN uses CONFIG_PARTITION_MODE  macro to compile out CPU_IRQ_ENABLE/DISABLE
    APIs. With vector remapping enabled for pre-launched VMs, this is of no use.
    And for VMs with LAPIC pass-thru, interrupts stay disabled in vmexit loop
    with the help of is_lapic_pt() API

**Comment by sainath14** [comment]
ACRN-3315

**Comment by Mingyuan18** [comment]
@sainath14 , This Patch has been merged, could you please close this issue. Thanks!

**Comment by Mingyuan18** [comment]
No regression was found, therefore closed it
