### ISSUE TITLE
Use virtual APIC IDs for Pre-launched VMs

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#2934]
In current code, ACRN uses physical APIC IDs as vLAPIC IDs for Pre-Launched VMs. Except for SOS, which is a special case, because host ACPI tables are pass-thru to SOS, ACRN can use vcpu id as vLAPIC ID for other types of VMs. (Note: For NORMAL_VM (Post-Launched) ACRN is already using vCPU ids as vLAPIC IDs.)

**Comment by sainath14** [comment]
ACRN-3353

**Comment by Mingyuan18** [comment]
No regression issue found in below build:
SOS:29070
HV: acrn-2019w17.4-160000p
