### ISSUE TITLE
Build mptable based on VM type

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#2941]
ACRN builds mptable for pre-launched VMs. It uses CONFIG_PARTITION_MODE
    to compile mptable source code and related support. This patch removes
    the macro and checks if the type of VM is pre-launched to build mptable.

**Comment by sainath14** [comment]
ACRN-3382

**Comment by Mingyuan18** [comment]
@sainath14 , This Patch has been merged, could you please close this issue. Thanks!

**Comment by Mingyuan18** [comment]
No regression was found, therefore closed it
