### ISSUE TITLE
Enable logic partition mode scenario on KBL NUC i7

### ISSUE THREAD

**Issue by wuxyintel** [projectacrn/acrn-hypervisor#2944]
Enable simple logical partition mode on KBL NUC i7, there are two pre-launched VM with virtual LAPIC and using ubuntu GRUB bootloader;

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3404

**Comment by Mingyuan18** [comment]
Pre-Interpretation test pass.
