### ISSUE TITLE
Warning removal from hypervisor codebase

### ISSUE THREAD

**Issue by kbillore** [projectacrn/acrn-hypervisor#2955]
(warning) %x in format string (no. 3) requires 'unsigned int' but the argument type is 'void *'.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3399

**Comment by kbillore** [comment]
Duplicate of #2957

**Comment by Mingyuan18** [comment]
@kbillore , No duplicate , 2957 is a PR.

**Comment by fuzhongl** [comment]
@kbillore Any plan to update PR?
Thanks!

**Comment by fuzhongl** [comment]
@kbillore this git issue will be closed  if no feedback within two weeks.
Appreciated for your understanding.
