### ISSUE TITLE
file location for RPMB 

### ISSUE THREAD

**Issue by bzhu5** [projectacrn/acrn-hypervisor#296]
where is the right place for these two files?

https://github.com/projectacrn/acrn-hypervisor/blob/master/devicemodel/hw/pci/virtio/rpmb_backend.c 
https://github.com/projectacrn/acrn-hypervisor/blob/master/devicemodel/hw/pci/virtio/rpmb_sim.c 

create a "rpmb" folder under this?
acrn-hypervisor/devicemodel/hw/platform/

**Comment by bzhu5** [comment]
@yang8621 if this issue is solved, please let me know, i will close it.

**Comment by yang8621** [comment]
@bzhu5  just merged.
