### ISSUE TITLE
Remove need for init_fallback_iommu_domain and fallback_iommu_domain

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#2965]
In the presence of SOS, ACRN uses fallback_iommu_domain which is the same
    used by SOS, to assign domain to devices during ACRN init. Also it uses
    fallback_iommu_domain when DM requests ACRN to remove device from UOS domain.
    This patch changes the design of assign/remove_iommu_device to avoid the
    concept of fallback_iommu_domain and its setup. This way ACRN can commonly
    treat pre-launched VMs bringup w.r.t. IOMMU domain creation.

**Comment by sainath14** [comment]
[External_System_ID] ACRN-3386

**Comment by Mingyuan18** [comment]
The patch was merged and no regression found in daily test.
