### ISSUE TITLE
PCIE ECFG support for AcrnGT

### ISSUE THREAD

**Issue by xyliu** [projectacrn/acrn-hypervisor#2971]
Linux access the first 256 Bytes of PCI configuration space through PIO
and the left content in 4KB space through mmio. Some other OS access the
whole PCI ECFG space through mmio. AcrnGT kernel driver need to trap the
access and intercept it, especially the first 256B.

**Comment by xinyunliu** [comment]
[External_System_ID] ACRN-3401

**Comment by Mingyuan18** [comment]
The patch was merged and no regression issue.
