### ISSUE TITLE
[GVT]don't register memory for gvt in acrn-dm

### ISSUE THREAD

**Issue by xinyunliu** [projectacrn/acrn-hypervisor#2976]
For AcrnGT, the memory access is trapped in sos kernel and acrngt driver intercepts it. So no need to register the memory block in acrn-dm when allocate the virtual bar.

**Comment by xinyunliu** [comment]
[External_System_ID] ACRN-3057

**Comment by Mingyuan18** [comment]
No regression issue in daily test. So close this issue.
SOS:29520
ACRN TAG: acrn-2019w21.2-140000p
