### ISSUE TITLE
HV: vuart refine

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#2987]
As there are requirements for switching VM's console at hypervisor side and providing a mechanism to connect vuart between different VMs, so refine the vuart code.

In current implementation, two vuart are added to pre-launched VM's configuration, one is for console, the other is for communication. And these can only be used in debug mode. Will move the vuart code from hypervisor/debug/ to hypervisor/dm/, so that the release version can also use it.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3461
