### ISSUE TITLE
Failed to boot normal vm on the pcpu which ever run lapic_pt vm

### ISSUE THREAD

**Issue by KaigeFu** [projectacrn/acrn-hypervisor#2991]
Environment

ClearLinux Version: 28720 or newer

HW/Board

KBLNUC

Build link

N/A

Image info
 N/A

Steps

Boot acrn SOS
./launch_hard_rt_vm.sh
poweroff hard rt vm
./launch_uos.sh
Expected result

normal vm bootup successfully.

Actual result

Normal vm fails to boot

Reproduce rate

100%

Debugging info

N/A

**Comment by KaigeFu** [comment]
[External_System_ID] ACRN-3456

**Comment by Mingyuan18** [comment]
The patch merged and test pass.
