### ISSUE TITLE
Pre-allocate the vbar (gpa) for pre-launched VMs

### ISSUE THREAD

**Issue by donsheng** [projectacrn/acrn-hypervisor#3022]
Currently we set all vbars to 0s initially in our bar emulation code, 
guest OS will  reprogram the bars when it sees the bars are uninited (0s). 
After discussion, we consider this is not the right solution, need to 
populate the vbars (to non zero valid pci hole address) based on the 
assigned ve820 table.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3452

**Comment by Mingyuan18** [comment]
The patch was merged and CI test pass.
