### ISSUE TITLE
virtio gpio line fd not release

### ISSUE THREAD

**Issue by fuyongjie** [projectacrn/acrn-hypervisor#3028]
When vm reset,the gpio line state is busy if we don't close the fd.
We should release the gpio line fd when BE deinit.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3586

**Comment by Mingyuan18** [comment]
@fuyongjie , The patch is merged, please confirm the result, if pass, please close the issue. Thanks!
