### ISSUE TITLE
FYI: Kconfiglib major version bumped to 11

### ISSUE THREAD

**Issue by ulfalizer** [projectacrn/acrn-hypervisor#3050]
Due to this change, which probably won't affect you: https://github.com/ulfalizer/Kconfiglib/commit/4fed39d9271ceb68be4157ab3f96a45b94f77dc0

Should modify `requirements.txt`, etc., if you want to keep getting the latest version.

Cheers,
Ulf

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3622

**Comment by fuzhongl** [comment]
It should be fine for "kconfiglib>=10.2" in requirements.txt (under acrn-hypervisor\doc\scripts)

Thanks for reminder.

**Comment by fuzhongl** [comment]
@ulfalizer 
Thanks for reminder! Could you please help to close this ticket?
Any more concern, please update the comments. If no more feedback within two weeks, this ticket will be closed by default. 
Appreciated for your understanding.

**Comment by Mingyuan18** [comment]
Close this issue due to no any feedback.
