### ISSUE TITLE
Storage: Support rescan feature for virtio-blk

### ISSUE THREAD

**Issue by vijaydhanraj** [projectacrn/acrn-hypervisor#3051]
This feature stems from the kata container requirement, which hot-plugs container rootfs to the guest VM. Since the current plan is not to support hot-plug, adding block rescan feature to virtio-blk. Using virtio-blk rescan feature, guest can add virtio-blk devices with dummy backend during VM launch and later replace the dummy backend with the actual file (in case of kata, the container rootfs).

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3623

**Comment by Mingyuan18** [comment]
DOC related PR.
Patch merged into CL 29310
acrn tag: acrn-2019w19.2-140000p
