### ISSUE TITLE
Emulated USB controller Vendor ID and Device ID are swapped

### ISSUE THREAD

**Issue by kriskep** [projectacrn/acrn-hypervisor#3053]
lspci in the UOS lists:
`00:07.0 USB controller: Device 1e31:8086`

this should be` 8086:1e31`

Relevant code here:

https://github.com/projectacrn/acrn-hypervisor/blob/122685b7b99731b939968fb3bc23a1d9c21b4157/devicemodel/hw/pci/xhci.c#L4039-L4040

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3624

**Comment by Mingyuan18** [comment]
@kriskep , the patch was merged, please verify this issue and close it. We will close it if two weeks no any feedback. Thanks!

**Comment by kriskep** [comment]
vendorid:deviceid is now 1234:1234 (PCI_ACRN_XHCI_VID:PCI_ACRN_XHCI_PID).
