### ISSUE TITLE
USB webcam not working in UOS

### ISSUE THREAD

**Issue by kriskep** [projectacrn/acrn-hypervisor#3054]
USB webcam is passed to the UOS using DM option `-s 7,xhci,1-2,1-3`
The webcam is properly detected by the UOS, but when launching an application (cheese), the syslog is flooded with the following messages:

`xhci_hcd 0000:00:07.0: WARN Successful completion on short TX for slot 2 ep 2: needs XHCI_TRUST_TX_LENGTH quirk?`

no image is captured.

UOS kernel: org.clearlinux.iot-lts2018.4.19.34-45
SOS kernel: 4.19.34-45.iot-lts2018-sos
ACRN: acrn-2019w16.5-140000p

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3625

**Comment by Mingyuan18** [comment]
This issue test passed on QA test:
【SOS Version】30000
daily tag:acrn-2019w23.4-140000p
