### ISSUE TITLE
Remove sharing_mode/partition_mode from vpci code

### ISSUE THREAD

**Issue by donsheng** [projectacrn/acrn-hypervisor#3056]
There is no more “partition_mode” or “sharing_mode” concept. so any names or strings of these should be removed.

We only has pre-launched VM, SOS, post-launched_vm. And at some point, it could no more SOS.

Change name partition_mode to prelaunched_vm, change sharing_mode to sos_vm

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3609

**Comment by Mingyuan18** [comment]
he patch was merged and CI test pass.
