### ISSUE TITLE
Virtualization will support VxWorks7 64-bit as a GuestVM

### ISSUE THREAD

**Issue by KaigeFu** [projectacrn/acrn-hypervisor#3069]
When configured according to provided documentation, the hypervisor will successfully boot and execute a 64-bit VxWorks7 VM image as a GuestOS.

See Informative section for expected 3rd party engagement to realize this requirement.

**Comment by KaigeFu** [comment]
[External_System_ID] ACRN-3532

**Comment by Mingyuan18** [comment]
Vxworks as a guest has been covered in daily test and result is pass, therefore close it
