### ISSUE TITLE
Can't set tsc frequency through option -f/--frequency of acrnalyze.py

### ISSUE THREAD

**Issue by KaigeFu** [projectacrn/acrn-hypervisor#3085]
It doesn't take effect when set tsc frequency through -f/--frequency of acrnalyze.py

**Comment by KaigeFu** [comment]
[External_System_ID] ACRN-3651

**Comment by Mingyuan18** [comment]
No regression issue fond in QA test:
SOS Installed version: 29360
ACRN tag: 2019w19.5.140000p
