### ISSUE TITLE
USB webcam does not work on UOS over xHCI

### ISSUE THREAD

**Issue by kiendinh** [projectacrn/acrn-hypervisor#3097]
I'm using HV (v0.7 and v1.0) on the NUC7i7DNHE connecting to the Logicool C922 USB webcam (uvc cam). The camera was confirmed to work on the SOS using the default Clear Linux desktop app. However, when trying to use the camera on the UOS using xHCI mediator:
`-s n,xhci,1:3`

the UOS showed errors in dmesg and camera device /dev/video* was not created. The UOS kernel was configured to support UVC cam already. Depending on the version of ACRN, there were different error messages.

With ACRN v0.7 (and acrn-dm), it was:
`usb 1-1: device descriptor read/64, error -110`

With ACRN v1.0, I got
`usb 1-1: device descriptor read/64, error -71`

Thanks

**Comment by Mingyuan18** [comment]
This issue is being solved, please reference to the duplicate with #https://github.com/projectacrn/acrn-hypervisor/issues/3054,  thanks!

**Comment by kiendinh** [comment]
@Mingyuan18 Thank you. It looks like the issues are not the same. Here the webcam is not even recognized by the UOS. I will check it again when #3054 is solved.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4642

**Comment by lirui34** [comment]
Hi @kiendinh, is this issue still reproducible on your NUC with the latest hypervisor ?

**Comment by Mingyuan18** [comment]
@kiendinh ,Patch merged on ww29.1 . Please help to double check the issue result. Thanks!

**Comment by fuzhongl** [comment]
@kiendinh  Please reopen this git issue if you still met same issue with latest code.
Thanks!
