### ISSUE TITLE
Expedited CI for documentation-only changes

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#310]
CI checks in Jenkins take over 40 minutes, so a simple typo change to a document requires a full build of the source code when no source code was changed.  Can we detect only .rst files are included in the PR (or allow adding a keyword to the PR commit message indicating this) that the CI system can notice and short-circuit the full CI testing?

This would also free up CI resources for more important code-change testing.

**Comment by NanlinXie** [comment]
Current CI will distinguish code PR and doc PR from repo, if it is PR for /doc repo, will only do "make doc" check. So this issue could be closed.
