### ISSUE TITLE
WaaG: Cursor is not visible with GVT-G on KBL NUC

### ISSUE THREAD

**Issue by xinyunliu** [projectacrn/acrn-hypervisor#3106]
After enable local display, H/W cursor is invisible.

**Comment by xinyunliu** [comment]
ACRN-3236

**Comment by acrnsi** [comment]
[External_System_ID] ACRN-3236

**Comment by Mingyuan18** [comment]
The patch was merged and no regression issue in below build:
ACRN tag: acrn-2019w20.4-140000p
CL: 29400
