### ISSUE TITLE
Documentation: "Using Partition mode on UP2" tutorial is outdated

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#3126]
The ["Using Partition mode on UP2" tutorial](https://projectacrn.github.io/latest/tutorials/using_partition_mode_on_up2.html) is outdated and needs to refreshed. There are references to files that are no longer in use such as `pt_dev.c` and `partition_config.h` (and probably more than that).

**Comment by gvancuts** [comment]
@NanlinXie , can you assign someone to this?

**Comment by lirui34** [comment]
Hi, @gvancuts  Can you please close this issue as the document is already published to ``v1.1`` ?

**Comment by gvancuts** [comment]
Hi @lirui34 , the PR referenced here (#3113) introduced a **new** tutorial for a different platform. The tutorial pertaining to the UP2 board is still part of our documentation (and still outdated).

**Comment by gvancuts** [comment]
Can someone take a look at this? I see some updates were made recently (in December) but we are still referencing v0.6 for ACRN... my recommendation is that we either update this tutorial to use the latest version of ACRN (1.5) or remove it altogether. My preference is that we do the former.

**Comment by fuzhongl** [comment]
@gvancuts Following Doc is updated to v1.6:
https://projectacrn.github.io/latest/tutorials/using_partition_mode_on_nuc.html
Can we close this git issue?
Thanks!

**Comment by gvancuts** [comment]
Yes, thanks!
