### ISSUE TITLE
Undefined CONFIG_REMAIN_1G_PAGES

### ISSUE THREAD

**Issue by KaigeFu** [projectacrn/acrn-hypervisor#3128]
The definition of CONFIG_REMAIN_1G_PAGES has been removed by patch (4627cd4d HV: build: drop useless files). CONFIG_REMAIN_1G_PAGES should be removed in acrn repo

**Comment by KaigeFu** [comment]
[External_System_ID] ACRN-3771

**Comment by Mingyuan18** [comment]
The patch was merged and no regression issue found.
