### ISSUE TITLE
distinguish between LAPIC_PASSTHROUGH configured vs enabled

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#3136]
ACRN supports LAPIC_PASSTHROUGH in guest_flags and enables LAPIC PT when guest kernel using x2APIC mode of LAPIC. When the guest kernel ends up using xAPIC mode of LAPIC, for whatever reasons, today hypervisor has no check to confirm LAPIC PT is enabled for the VM.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3824

**Comment by Mingyuan18** [comment]
No regression issue in daily test.
Patch merged into SOS: 29620
acrn tag: acrn-2019w21.4-140000p
