### ISSUE TITLE
Increase kernel boot args and VM Name length

### ISSUE THREAD

**Issue by vijaydhanraj** [projectacrn/acrn-hypervisor#3138]
Currently, we use STR_LEN for all checking the size of all the acrn-dm parameters. But some parameters like kernel boot args can grow based on different needs. For example, when kata launches guest VM using acrn, the kernel boot args increases by 256 characters (i.e 1024 +256). 
Just increasing STR_LEN will unnecessarily increase allocations for other acrn-dm parameters. So decoupling only boot_args length and increasing it to 2048.  

Similarly, VM Name length is restricted to 32 characters and kata creates a VM name with GUID added as a part of VM name making it around 80 characters. So increasing this size to 128.

PS: If other parameters like ramdisk path, kernel path, elf_path etc. don't need 1024 bytes, we can reduce this to 256 or 512 bytes.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3823

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
ACRN tag: acrn-2019w22.1-140000p
CL: 29660
