### ISSUE TITLE
Only certain guests should be granted the privilege to reset host

### ISSUE THREAD

**Issue by ZideChen0** [projectacrn/acrn-hypervisor#3145]
In a given scenario, only the guests that have the highest severity can reboot the host system, which the VM severity is defined as follows. 

safety VM > hard RTVM > soft RTVM > SOS > standard VM

This is to make sure that:
1) High severity VM reboot may reboot the low severity VM
2) Reboot of a low severity VM should not impact high severity VM

**Comment by ZideChen0** [comment]
[External_System_ID] ACRN-3759

**Comment by Mingyuan18** [comment]
#https://github.com/projectacrn/acrn-hypervisor/issues/3145

**Comment by Mingyuan18** [comment]
This issue on SBL UP2 with SDC configration  has been fixed 
Clear Linux: 29610
Daily tag:acrn-2019w21.5-140000p
