### ISSUE TITLE
[APLMRB][IO][AaaG] sos kernel conplains  vq is full

### ISSUE THREAD

**Issue by xinyunliu** [projectacrn/acrn-hypervisor#3151]
when test hyper dmabuf, kernel outputs this kind of log after runs for a while. 

[ 2102.944622] virtio_hyper_dmabuf: ndesc (129) out of range, driver confused?
[ 2102.944632] virtio_hyper_dmabuf: ndesc (129) out of range, driver confused?
[ 2102.947601] virtio_hyper_dmabuf: ndesc (130) out of range, driver confused?

**Comment by xinyunliu** [comment]
[External_System_ID] ACRN-3848

**Comment by Mingyuan18** [comment]
The test result is pass.
