### ISSUE TITLE
DM: handle SIGPIPE signal

### ISSUE THREAD

**Issue by vijaydhanraj** [projectacrn/acrn-hypervisor#3190]
Ignore SIGPIPE signal and handle the error directly when write() function fails. this will help us to catch the write failure rather than crashing the UOS.

PS: Observed that when acrnctl stop command was issued from kata-runtime, UOS was crashing with SIGPIPE signal.

**Comment by vijaydhanraj** [comment]
[External_System_ID] ACRN-3796

**Comment by Mingyuan18** [comment]
The patch was merge
