### ISSUE TITLE
Enabling acrn on qemu.

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#3198]
Enabling acrn on qemu.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3928

**Comment by fuzhongl** [comment]
@Mingyuan18  The patch was merged into (tag: acrn-2019w22.5-140000p) CL 29790.
Could you please close this ticket?
Thanks!

**Comment by gvancuts** [comment]
Can you also plan to add some documentation on how to run ACRN on QEMU?

**Comment by tw4452852** [comment]
@fuzhongl There's still one patch under review. So just hold on.

**Comment by tw4452852** [comment]
@gvancuts I will add a guild once all the code changes have been merged.

**Comment by LiangZhou9527** [comment]
just curious:  is there any guide about how to run acrn on qemu?

**Comment by gvancuts** [comment]
Hi @LiangZhou9527 , I haven't seen one yet. FYI, we may not get any better answer since most of the engineering team is in China and on holiday this week.

**Comment by yfliuu** [comment]
Hi @tw4452852  @gvancuts, is there any tutorial on running ACRN on QEMU/KVM? I've tried but ACRN complains about CPUID level being too small (13). Manually setting it to 22 (the value on physical machine) won't work as the hypervisor will crash.

**Comment by gvancuts** [comment]
I haven't seen one yet. @tw4452852 @NanlinXie @fuzhongl , do you know if we have instructions on how to run ACRN on QEMU? If so, it would be good to make a tutorial out of those!

**Comment by shlomopongartz** [comment]
Any updates on how to run ACRN on QEMU/KVM?

**Comment by NanlinXie** [comment]
Hi, Pongratz,

         We have plan to support it in ACRN v2.0 release(~2020.6), and will publish BKM once we done.  Please take care of our Release note for update. Thanks for your interest on ACRN.

Best wishes!
Nanlin

**Comment by gvancuts** [comment]
@shlomopongartz , you can now run ACRN on QEMU/KVM. The tutorial has been published here: https://projectacrn.github.io/latest/tutorials/acrn_on_qemu.html

Can you close this issue if this satisfies your needs?

**Comment by shlomopongartz** [comment]
Hi,
Thank you.
Why do you want me to close the issue? I didn't open it.
I just asked a question, I see that the one who open it is Mingyuan18  (see on top).
Best regards,
S.P.

**Comment by gvancuts** [comment]
> Why do you want me to close the issue? I didn't open it.

Indeed... no action needed your part... my bad! :-)

**Comment by fuzhongl** [comment]
Integrated into acrn v2.0
