### ISSUE TITLE
dm: virtio: bugfix for polling mode

### ISSUE THREAD

**Issue by gaojunhao0504** [projectacrn/acrn-hypervisor#3203]
In vxworks, virtio-console FE driver only initiate 2 virtqueues, but BE
creates 2+ virtqueues for it. So the rest of the virtqueues are not
initiated. vq->used->flags cannot be used directly without any
condition.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3947

**Comment by Mingyuan18** [comment]
The patch was merged and no regression in daily test:
ACRN TAG: acrn-2019w29.1-140000p
CL:30340
