### ISSUE TITLE
vbs: set memory barrier for virtio_vq

### ISSUE THREAD

**Issue by gaojunhao0504** [projectacrn/acrn-hypervisor#3207]
When virtio backend driver gets avail_idx or sets used_idx, memory
barrier can make sure of sequence of reading and writing. It can
guarantee the accuracy of avail_idx and used_idx.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3948

**Comment by Mingyuan18** [comment]
The patch was merged and no regression in daily test:
ACRN TAG: acrn-2019w29.1-140000p
CL:30340
