### ISSUE TITLE
remove reboot command from acrn shell

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#3210]
reboot in ACRN shell has no sense and bring confusion. It's only for debug purpose and we could remove it now.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3955

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3955

**Comment by NanlinXie** [comment]
Closed with no regression issues.
