### ISSUE TITLE
More vpci cleanup: code reorg, enable VPCI 64-bit bar emulation for sos and pre-launched VMs

### ISSUE THREAD

**Issue by donsheng** [projectacrn/acrn-hypervisor#3241]
The e820 may does not  cover the pci hole that exceeds the mem_top (see above), and if sos reprograms the bar, it may hang as there is no ept existing for that pci hole. If with bar emulation for sos, this can be avoided.

Currently, we only do pci bar emulation for partition mode (prelaunched vm), but we also need to do pci bar emulation for sos to unify the code

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3453

**Comment by Mingyuan18** [comment]
The patch was merged and no regression found in below build:
acrn tag: acrn-2019w30.2-140000p
CL: 30450
