### ISSUE TITLE
raise the priority of ioreq thread to reduce the trap time

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#3242]
Now the created kernel thread uses the default thread priority. When the SOS has some workload, the thread of handling emulated ioreq will be preempted. In such case maybe it will cause that the guest vcpu is in the trapped state.
In order to complete the emulated ioreq from guest, the priority needs to be changed.

**Comment by yakuizhao** [comment]
[External_System_ID] ACRN-4023

**Comment by Mingyuan18** [comment]
The patch was merged.
