### ISSUE TITLE
Introduce vLAPIC state for VMs

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#3253]
vLAPIC state is per vCPU. ACRN needs to know the vLAPIC of a VM before it programs interrupt vector information into devices for VMs with LAPIC Passthrough.

**Comment by Mingyuan18** [comment]
Please add [External_System_ID] ACRN-XXXX. Thanks!

**Comment by sainath14** [comment]
[External_System_ID]  ACRN-4010

**Comment by Mingyuan18** [comment]
The patch was merged and no regression in daily test:
ACRN TAG: acrn-2019w29.1-140000p
CL:30340
