### ISSUE TITLE
dm: add virtio-rnd device to command line

### ISSUE THREAD

**Issue by gaojunhao0504** [projectacrn/acrn-hypervisor#3268]
When FE virtio devices work in polling mode, sshd.service can't start
normally and blocks at generating random bytes. When reading from
the random source, getrandom() blocks caused by no random bytes.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4006

**Comment by Mingyuan18** [comment]
Verify this issue the result is pass
