### ISSUE TITLE
AcrnGT causes display flicker in some situations.

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#3279]
AcrnGT causes display flicker in some situations

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4088

**Comment by minhe1** [comment]
More detailed information about this issue:
In current scaler ownership assignment logic, there's an issue that when SOS disables a plane, it will disable corresponding plane scalers; however, there's no scaler ownership checking there. So the scalers owned by UOS may be disabled by SOS by accident.

**Comment by Mingyuan18** [comment]
Verify this issue in below build:
ClearLinux version: 30170
ACRN TAG: acrn-2019w27.4-140000p
Cannot reproduce this issue, so close it.
