### ISSUE TITLE
Remove all TravisCI-related files (including Dockerfiles)

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#3286]
The project does not use TravisCI and hence the related files should be removed from the tree (they are already bit-rotten). The following files should be removed:
* `.travis.xml`: main TravisCI configuration file
* `.travis-dockerfiles`: series of `Dockerfile` that can be used to simulate different build environments based on Docker containers.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4153

**Comment by fuzhongl** [comment]
@gvancuts Can we close this git issue since the PR is merged.

**Comment by gvancuts** [comment]
Yes, closing!
