### ISSUE TITLE
Update documentation and helper scripts to use newer `swupd` commands

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#3291]
A number of `swupd` commands are being deprecated in favour of new ones (all existing functionalities have been preserved). The specific changes are:
- `swupd diagnose` (that replaces `verify`): https://github.com/clearlinux/swupd-client/commit/2cb0dd80b4ba98b63c754cb5562c297f0cebdc1a
- `--version` flag (instead of `-m`): https://github.com/clearlinux/swupd-client/commit/a3131db0feb70f4a7616d29e38742d8d7a81c984
- `os-install` (that replaces `verify --install`): https://github.com/clearlinux/swupd-client/commit/a84c60a500ca6efe76368919542a11ee01de6184

A few documents and helper scripts need to be updated accordingly:
* doc/getting-started/acrn_quick_setup.sh
* doc/getting-started/apl-nuc.rst
* doc/tutorials/create-up2-images.sh
* doc/tutorials/skl-nuc.rst
* doc/tutorials/agl-vms.rst

Note that we need to pay attention to the fact the new instructions/scripts will need to be used with a version of Clear Linux that has a `swupd` client with these new commands.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4151

**Comment by Mingyuan18** [comment]
@gvancuts  Do you want to update another patch?

**Comment by fuzhongl** [comment]
@gvancuts 
acrn_quick_setup.sh was updated.
Can this git issue be closed now?
Thanks!

**Comment by gvancuts** [comment]
Yes, closing it.
