### ISSUE TITLE
Enhance the built-in and online help for `acrnd`

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#3329]
The online and built-in help in `acrnd` is somewhat inaccurate and has a couple of typos in it.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4263

**Comment by fuzhongl** [comment]
@gvancuts Can this issue be closed?
Thanks!

**Comment by gvancuts** [comment]
Yes, closing! Thanks
