### ISSUE TITLE
Add a check to `acrnd` and `acrnctl` to verify if running with root privileges

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#3330]
`acrnd` and `acrnctl` need root privileges to run correctly, both will fail in different manners if not but it will not be very obvious from the error. A simple check in the code when starting the program would be helpful to catch these (and return an error when not running with root privileges).

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4334

**Comment by Mingyuan18** [comment]
@gvancuts Can this issue be closed?
Thanks!

**Comment by gvancuts** [comment]
Yes, thanks!
