### ISSUE TITLE
hv: bugfix for sbuf reset

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#3335]
The sbuf is allocated for each pcpu by hypercall from SOS. Before launch
    Guest OS, the script will offline cpus, which will trigger vcpu reset and
    then reset sbuf pointer. But sbuf only initiate once by SOS, so these
    cpus for Guest OS has no sbuf to use. Thus, when run 'acrntrace' on SOS,
    there is no trace data for Guest OS.
    To fix the issue, only reset the sbuf for SOS.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4267

**Comment by Mingyuan18** [comment]
The patch was merged and no regression in daily test:
ACRN TAG: acrn-2019w26.5-140000p
CL:30110
