### ISSUE TITLE
virtio-console: cannot parse multi ports parameters.

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#3337]
In current code, the virtio-console cannot parse multi ports parameter,  only support one port. But it was designed to support multi ports:
virtio-console,[@]stdio|tty|pty|file:portname[=portpath]\
       [,[@]stdio|tty|pty|file:portname[=portpath]]
Need to fix this bug.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4268

**Comment by Mingyuan18** [comment]
The patch was merged and no regression issue in below build:
ACRN TAG: acrn-2019w26.5-140000p
CL: 30110
