### ISSUE TITLE
Documentation on how to run Windows as a Guest (WaaG)

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#3341]
It is possible to run Windows-as-a-Guest (aka WaaG) on ACRN, see #2962 for more information.

We now need to add documentation on how to do this :-)

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4340

**Comment by lirui34** [comment]
Doc is merged on tag: ``acrn-2019w30.1-140000p``

**Comment by lirui34** [comment]
Hi, @gvancuts @dbkinder 
Can we now close this issue ?

**Comment by dbkinder** [comment]
Yes.
