### ISSUE TITLE
Assert cleanup for gvt-g/hyperdma in device model

### ISSUE THREAD

**Issue by xinyunliu** [projectacrn/acrn-hypervisor#3349]
Assert cleanup for gvt-g/hyperdma in device model.

core/gc.c	2	
hw/pci/gvt.c	3	
hw/pci/virtio/virtio_hyper_dmabuf.c	1

**Comment by xinyunliu** [comment]
[External_System_ID] ACRN-4192

**Comment by Mingyuan18** [comment]
The patch was merged and no regression issue found:
ACRN TAG: acrn-2019w27.3-140000p
CL： 30140
