### ISSUE TITLE
HV: should check ecx instead of rcx when xsetbv

### ISSUE THREAD

**Issue by binbinwu1** [projectacrn/acrn-hypervisor#3360]
According to SDM, xsetbv writes the contents of registers EDX:EAX into the 64-bit extended control register (XCR) specified in the ECX register. (On processors  that support the Intel 64 architecture, the high-order 32 bits of RCX are ignored.)
In current code, RCX is checked, should ingore the high-order 32bits.

**Comment by binbinwu1** [comment]
[External_System_ID] ACRN-3210

**Comment by Mingyuan18** [comment]
Verify pass when use below build:
ACRN tag: acrn-2019w29.4-140000p
HV: 05acc8b7052ff2469613462f64e155dbc720bf95
kernel： 3843789e002f4184ea7c544a5335b1a7dc6f363e
SOS Installed version: 28100   4.19.40-quilt-2e5dc0ac
