### ISSUE TITLE
ioc-cbc-tools cannot compile

### ISSUE THREAD

**Issue by miguelinux** [projectacrn/acrn-hypervisor#3368]
The ioc-ccb-tools package depends on "acrn_mgr.h". This header was
updated with new includes since b2f2d952464e ("tools: acrnctl restrict
length of vmname to 32 bytes") and  in 517707dee4ca ("DM/HV: Increase VM
name len") was updated to include dm.h
    
The missing headers needs to be included in the install directory

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4566
