### ISSUE TITLE
vm_console 2 cannot switch to VM2’s console in hybrid and industry mode

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#3370]
vm_console 2 cannot switch to VM2’s console in hybrid mode, the error is:
ACRN:\>vm_console 2
vuart console is not active

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4271

**Comment by Mingyuan18** [comment]
The bug cannot reproduced in below build:
Installed version: 30880
daily tag:acrn-2019w35.1-140000p
