### ISSUE TITLE
Potential interrupt info overwrite in acrn_handle_pending_request 

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3374]
interrupt might be lost if we do acrn_handle_pending_request twice in one vmexit/vmentry of vcpu_thread. We need do it once per cycle of vmexit/vmentry

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4586

**Comment by Mingyuan18** [comment]
No regression issue found in daily test:
ACRN TAG: acrn-2019w28.3-140000p
CL: 30270
