### ISSUE TITLE
No check for Speculative Store Bypass Disable (SSBD) support

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3385]
Processor is susceptible to Speculative Store Bypass (SSB) if 

 IA32_ARCH_CAPABILITIES  [SSB_NO=4] is not enumerated. in this case, below CPUID.leaf should be checked:

CPUID.(EAX=7H,ECX=0):EDX[31] enumerates support for Speculative Store Bypass Disable (SSBD). Processors that set this bit support the IA32_SPEC_CTRL MSR. They allow software to set IA32_SPEC_CTRL[2] (SSBD).

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4561

**Comment by Mingyuan18** [comment]
The patch was merged and no regression in daily test:
ACRN TAG: acrn-2019w28.3-140000p
CL: 30270
