### ISSUE TITLE
Refine vcpu thread code to avoid two acrn_handle_pending_request call within one vmexit

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3387]
Calling acrn_handle_pending_request two times in one vmexit is error-prone. We need to update the vcpu_thread code to avoid this issue.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4602

**Comment by Mingyuan18** [comment]
No regression issue found in daily test:
ACRN TAG: acrn-2019w30.1-140000p
CL: 30450
