### ISSUE TITLE
Debug: Post-mortem debug analysis

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#3390]
If a GuestOS crashes, the Hypervisor and ServiceOS shall be able to save the faulting VMs kernel-crashlogs and in-RAM-crash-dumps to files.
NOTE: See Informative for rationale and analysis use of the dumps implication.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3568

**Comment by yaomichael** [comment]
This works only with AaaG. For LaaG, extra work need to be done inside Linux, which is out of this ticket's scope.

**Comment by Mingyuan18** [comment]
Verified SOS is able to capture the SOS panic log on APL NUC with ACRN tag: acrn-2019w29.2-140000p
