### ISSUE TITLE
Banned Functions Found in Source code

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3394]
sprintf() function unbounded, banned; use snprintf

vsnprintf() function banned except with approval from PSE. requires detailed inspection to avoid va_list pitfalls.

devicemodel/log/kmsg_logger.c:80:    len2 = vsnprintf(kmsg_buf + len1, MAX_ONE_LOG_SIZE, fmt, args);
devicemodel/log/disk_logger.c:159:    len1 = sprintf(buffer, "[%5lu.%06lu] ", times.tv_sec, times.tv_nsec / 1000);
devicemodel/log/disk_logger.c:160:    len2 = vsnprintf(buffer + len1, MAX_ONE_LOG_SIZE, fmt, args);

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4530

**Comment by Mingyuan18** [comment]
No regression issue found in daily test:
ACRN TAG: acrn-2019w29.1-140000p
CL: 30340
