### ISSUE TITLE
Possible memory leak in devicemodel blockif_open function

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3395]
acrn-hypervisor/devicemodel/hw/block_if.c | blockif_open():

``532     nopt = xopts = strdup(optstr);``

strdup memory not free before function return

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4529

**Comment by Mingyuan18** [comment]
No regression issue found in daily test:
ACRN TAG: acrn-2019w29.1-140000p
CL: 30340
