### ISSUE TITLE
Variable Argument List Read Without Ending with va_end

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3396]
va_end was not getting called under certain condition after the va_start function call taking the valist:

acrn-hypervisor\tools\acrn-crashlog\usercrash\crash_dump.c | loginfo()

devicemodel/hw/platform/acpi/acpi.c | dsdt_line()

tools/acrn-crashlog/common/log_sys.c | debug_log()

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4532

**Comment by Mingyuan18** [comment]
No regression issue found in daily test:
ACRN TAG: acrn-2019w29.1-140000p
CL: 30340
