### ISSUE TITLE
Prepare uuids for kata

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3402]
Kata need UUID to run VM, and hypervisor will check the UUID to create VM, so we need to prepare UUIDs for Kata container.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4045

**Comment by Mingyuan18** [comment]
The patch was merged and daily test no regression issue found:
ACRN TAG: acrn-2019w29.1-140000p
CL: 30340
