### ISSUE TITLE
Possible memory leak in devicemodel blockif_open function(apl_sdc_stable)

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3405]
acrn-hypervisor/devicemodel/hw/block_if.c | blockif_open():

``532     nopt = xopts = strdup(optstr);``
strdup memory not free before function return

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4635

**Comment by Mingyuan18** [comment]
The patch was merged and pre-integration test no regression issue found:
ACRN TAG: acrn-2019w29.4-150000p
CL: 30400
