### ISSUE TITLE
vuart communication may hang because of no THRE interrupt

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#3423]
When doing communication between VMs through vuart, the THRE interrupt are not correctly inject to VM, so the Tx process may hang. 
vuart driver should inject THRE interrupt to self VM after data was written to target vuart's rxfifo.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4760

**Comment by Mingyuan18** [comment]
No regression issue found in daily test :
ACRN TAG： acrn-2019w29.4-140000p
CL: 30400
