### ISSUE TITLE
Add SDC2 scenario to support three post-launched VM for some automotive SDC system

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3429]
Three post-launched VM might be needed for some automotive SDC system, so add SDC2 scenario to satisfy such requirement.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4775

**Comment by Mingyuan18** [comment]
No regression issue found  in daily test :
ACRN TAG： acrn-2019w29.5-140000p
CL: 30440
