### ISSUE TITLE
Symbols Not Stripped From Application Binaries(apl_sdc_stable) 

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3433]
While performing binary analysis on ACRN, it was observed that function names and other variables used in the source code were retained in the release build binaries. In a production environment, binary files must be stripped in order to remove debugging code sections and symbol information that aid attackers in the process of disassembly and reverse engineering.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-3994

**Comment by Mingyuan18** [comment]
No regression issue found in Pre-integration test:
ACRN TAG: acrn-2019w29.4-140000p
AaaG:107
CL:30340
