### ISSUE TITLE
The race condition pf monitor/mwait in wait_sync_change

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#3442]
monitor/mwait is used to wait for the specific write op from the other CPUS. It will firstly check whether the condition is expected before entering monitor/mwait.  
But under some scenario that the write happens between check and monitor, it will have the possible lockup.

At the same time the same input register is used for both monitor and mwait instruction. In fact monitor instruction uses the rax to arm the addr range while mwait uses the rax as the hint that the process should enter. They are different.

**Comment by yakuizhao** [comment]
[External_System_ID] ACRN-4801

**Comment by Mingyuan18** [comment]
No regression issue in V1.3 release test.
