### ISSUE TITLE
[PMU]Test RDPMC instruction execution cause #GP(should cause #UD) when PMU is hidden

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3453]
RDPMC instruction execution in guest mode should cause #UD when PMU is hidden.

**Comment by yonghuah** [comment]
[External_System_ID] ACRN-4666

**Comment by Mingyuan18** [comment]
Testing "rdpmc" instruction on the newest git branches: master and sliced_mainline, and it can generate UD exception on both branches, so the bug has been fixed.
