### ISSUE TITLE
Potential risk in virtioi_i2c.c & virtio_console.c

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#3467]
Array 'native_path' of size 20 may use index value(s) 20
/home/jenkins_worker/workspace/acrn-daily-kw-scan/acrn-hypervisor/devicemodel/hw/pci/virtio/virtio_i2c.c:446 | native_adapter_create()

Pointer 'portpath' checked for NULL at line 841 may be passed to function and may be dereferenced there by passing argument 1 to function 'virtio_console_open_backend' at line 862.
/home/jenkins_worker/workspace/acrn-daily-kw-scan/acrn-hypervisor/devicemodel/hw/pci/virtio/virtio_console.c:862 | virtio_console_add_backend()

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4820

**Comment by Mingyuan18** [comment]
The patch was merged and no regression issue found in daily test:
ACRN TAG: acrn-2019w30.5-140000p
CL: 30500
