### ISSUE TITLE
dm: bugfix for remote launch guest issue

### ISSUE THREAD

**Issue by gaojunhao0504** [projectacrn/acrn-hypervisor#3473]
when stdio is set as a virtio-console, guest run in backend, the open
file descriptor is not referring to a terminal.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4848

**Comment by Mingyuan18** [comment]
Can't reproduce this issue in below build:
acrn tag: daily-2019ww31.4-1
ClearLinux version: 30580
