### ISSUE TITLE
More vpci cleanup

### ISSUE THREAD

**Issue by donsheng** [projectacrn/acrn-hypervisor#3475]
Clean up vpci code introduced by vdev ops and enabling vhostbridge for sos:
Remove redundant function calling:
 The caller function has already done the checking to make sure the req is targeted
 for the called functions, so there is no need to do the same checking in called
 functions.

Make functions void because their return values are always 0 and not used.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4609

**Comment by Mingyuan18** [comment]
CI test pass in below tag: 
ACRN TAG: tag:acrn-2019w33.1-140000p
