### ISSUE TITLE
Add board specific cpu state table to support Px Cx

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3477]
Currently the Px Cx supported SoCs which listed in cpu_state_tbl.c is limited,
and it is not a wise option to build a huge state table data base to support
Px/Cx for other SoCs. This patch give a alternative solution that build a board
specific cpu state table in board.c which could be auto-generated by offline
tool, then the CPU Px/Cx of customer board could be enabled;
    
Hypervisor will search the cpu state table in cpu_state_tbl[] first, if not
found then go check board_cpu_state_tbl. If no matched cpu state table is found
then Px/Cx will not be supported;

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4885

**Comment by NanlinXie** [comment]
Closed with no regression issues.
