### ISSUE TITLE
Add script to ``acrn-config/target`` and ``acrn-config/host/board_confing``

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3480]
Scripts (tools) should be added to these folders:
* acrn-config/target/
* acrn-config/host/board_config/

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4889

**Comment by Mingyuan18** [comment]
The patch was merged and no regression issue found in daily test:
acrn tag： acrn-2019w31.5-140000p
CL: 30580
