### ISSUE TITLE
Acrn-hypervisor Root Directory Clean-up and Create misc/ folder for Acrn daemons, services and tools.

### ISSUE THREAD

**Issue by szhen11** [projectacrn/acrn-hypervisor#3482]
This patch is to clean-up acrn-hypervisor root directory, target only 5 folders under acrn-hypservisor:

1.       hypervisor    :  Hypervisor source code
2.       devicemodel : Device model source code
3.       misc               : Acrn daemons, services and tools
4.       doc                :  Acrn documents and config files
5.       build              :  Temporary building files

**Comment by szhen11** [comment]
ACRN-4890

**Comment by Mingyuan18** [comment]
The patch was merged into (tag: acrn-2019w31.2-140000p)  and no regression issue found in daily test:
CL: 30550
