### ISSUE TITLE
tools: support force stop VM

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#3484]
When run 'acrnctl stop VM_NAME', acrn-dm let guest OS to shutdown itself.
If something wrong with guest OS, it can't shutdown, we can run
'acrnctl stop VM_NAME --force', thus acrn-dm directly set suspend mode to
VM_SUSPEND_POWEROFF and quit main loop.

**Comment by taoyuhong** [comment]
[External_System_ID] ACRN-4891

**Comment by Mingyuan18** [comment]
The patch was merged and no regression issue found in daily test:
acrn tag： acrn-2019w31.5-140000p
CL: 30580
