### ISSUE TITLE
acrn.32.out for EFI firmware build is not available in acrn-hypervisor rpm in CL

### ISSUE THREAD

**Issue by ranenikhil19** [projectacrn/acrn-hypervisor#3487]
We use UEFI Firmware and our target is apl-nuc which is default board selection by generating acrn-hypervisor RPM in hybrid mode.
For hybrid mode bringup acrn.32.out is required which is currently not available in acrn-hypervisor RPM.
Need to add support to include this for UEFI firmware case.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4892
