### ISSUE TITLE
Cannot kill the acrn-dm if launch the Guest OS with 0 core

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3491]
Steps:

1.    Boot to Service OS
2.    Launch Guest OS with 0 core & memory=2048M

Results:
Fail to launch Guest OS with 0 core and also fail to kill the acrn-dm process.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4779

**Comment by Mingyuan18** [comment]
Verify pass:
ACRN tag: acrn-2019w37.2-140000p
CL: 30970
