### ISSUE TITLE
Inject exception for invalid vmcall

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3497]
For non-trusty hypercalls, HV should inject #GP(0) to vCPU if they are
from non-ring0 or inject #UD if they are from ring0 of non-SOS. Also
we should not modify RAX of vCPU for these invalid vmcalls.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4904

**Comment by Mingyuan18** [comment]
The patch was merged and no regression issue found in daily test:
acrn tag: acrn-2019w31.5-140000p
CL: 30580
