### ISSUE TITLE
Return extended info in vCPUID leaf 0x40000001

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3498]
In some case, guest need to get more information under virtual environment,
like guest capabilities. Basically this could be done by hypercalls, but
hypercalls are designed for trusted VM/SOS VM, We need a machenism to report
these information for normal VMs. In this patch, vCPUID leaf 0x40000001 will
be used to satisfy this needs that report some extended information for guest
by CPUID.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4905

**Comment by Mingyuan18** [comment]
The patch was merged and no regression issue found in daily test:
acrn tag: acrn-2019w31.5-140000p
CL: 30580
