### ISSUE TITLE
SOS_LTP_syscalls result is different with native

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3503]
**Environment:**
- Board:  KBL NUC
- Clear Linux version:  29880
- ACRN Tag:  acrn-2019w23.4-140000p
- Test Scenario:   Zephyr + SOS + Laag.

**Reproduce step:**
- Prepare the LTP tool

1. Boot to SOS
2. tar -zxf ltp0515installedoptltp.tar.gz -C /
3. cd /opt/ltp
4. ./runltp -p -l syscalls -g syscalls.html -f syscalls.

**result:**
SOS_LTP_syscalls result is different with native

**Repetition rate**
- 100%

**Comment by lirui34** [comment]
[External_System_ID] ACRN-4112

**Comment by Mingyuan18** [comment]
sendfile09 is caused by no memory, won't fixed this issue.
