### ISSUE TITLE
White listed SBL boards as most supported platforms are UEFI based

### ISSUE THREAD

**Issue by ttzeng** [projectacrn/acrn-hypervisor#3541]
The top-level Makefile white-lists BOARDs (i.e. ``apl-nuc`` and ``nuc6cayh``) to generate UEFI executable by default, but more UEFI BOARDs (e.g. ``nuc7i7dnb``, ``kbl-nuc-i7``) have been supported since then. As a result, the build instructions in existing documents may not be sufficient for those new BOARD targets, if the reader misses to supply the FIRMWARE variable while building the hypervisor.

**Comment by acrnsi** [comment]
@ttzeng  please add External_System_ID

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4949
