### ISSUE TITLE
UP2 SOS boot fail in ACRN hybrid mode for uefi firmware

### ISSUE THREAD

**Issue by ranenikhil19** [projectacrn/acrn-hypervisor#3545]
Kernel panic - no working init found error , while SOS booting in ACRN Hybrid mode for UP2.
 Rootfs path in sos kernel cmdline is not correct for uefi hybrid mode in Up2.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4960

**Comment by fuzhongl** [comment]
@ranenikhil19  since the patch was merged,Could you please close this issue?
Thanks!
