### ISSUE TITLE
Pre-launched VM is not started by default in Hybrid mode UP2

### ISSUE THREAD

**Issue by ranenikhil19** [projectacrn/acrn-hypervisor#3546]
Zephyr Pre-launched VM in case of UP2 hybrid mode is not STARTED . It is just created.

ACRN:\>vm_list

VM_UUID                          VM_ID VM_NAME                          VM_STATE
================================ ===== ================================ ========
fc83690186854bc08b716e31dc36fa47   0   ACRN PRE-LAUNCHED VM0            Created
dbbbd4347a574216a12c2201f1ab0240   1   ACRN SOS VM                      Started 

ve820 table for prelaunched VM is not defined for apl-up2

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4959

**Comment by fuzhongl** [comment]
@ranenikhil19 The patch was merged, could you please close this issue?
Thanks!
