### ISSUE TITLE
HV: shell: temp_str out of bounds buffer access

### ISSUE THREAD

**Issue by loyfan** [projectacrn/acrn-hypervisor#3549]
sanitize_vmid() in /hypervisor/debug/shell.c
String buffer temp_str is defined with size TEMP_STR_SIZE(60U) but accessed with MAX_STR_SIZE(256U). Better to limit the access bound to TEMP_STR_SIZE to prevent potential issue.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4957
