### ISSUE TITLE
Documentation: Instructions for Celadon as a UserOS incorrect

### ISSUE THREAD

**Issue by ngaloppo** [projectacrn/acrn-hypervisor#3606]
The instructions [to patch Celadon source code](https://projectacrn.github.io/latest/tutorials/using_celadon_as_uos.html#build-celadon-from-source) in preparation to enable Celadon as a User OS VM are incorrect. The patches do not apply cleanly.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5079

**Comment by fuzhongl** [comment]
@ngaloppo These patches maybe need to rebase for newer codebase, could you please check with Celadon open source project?
Thanks!
