### ISSUE TITLE
LaaG hang while run some workloads loop with zephyr idle.

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#3610]
Environment:
ClearLinux version: 30580
HW: KBLNUC DNHi7
Reproduce steps:
1. Enable no passwd ssh for SOS and UOS, and enable UOS auto boot.
2. Connect with $SOS_IP & $UOS_IP by ssh.
3. In UOS, continually and repeatedly run workloads loop
4. LaaG hang 
LaaG printed the log info "[drm:gen8_de_irq_handler] ERROR The master control interrupt lied (DE PIPE)!" continually.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4984

**Comment by fuzhongl** [comment]
Need revert following patch from acrn-kernel:
revert bbb891728d82834ec450f6a61792f715f4ec3013
