### ISSUE TITLE
OVMF launch UOS fail for Hybrid and industry scenario.

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#3611]
Environment
isd/vbs/kbl
HW/Board
kbl-nuc-i7
Image info
uos kvm version : 30800
Steps
boot launch_uos.sh with OVMF.fd
change uos_bzImge  and  uos_kernel
bash launch_uos.sh 
Expected result
uos boot successfully
Actual result
uos boot fail
Reproduce rate
100%

**Comment by fuzhongl** [comment]
Issue fixed with following commit:
80c252a28ff8c704719231403b875169692643e9  config: uos EFI boot support
