### ISSUE TITLE
 Potential Null pointer be dereferenced  in 'usb_dev_request()' 

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3612]
acrn-hypervisor/devicemodel/hw/platform/usb_pmapper.c, @usb_dev_request()
Null pointer 'data' that comes from line 964 may be passed to function and can be dereferenced there by passing argument 2 to function 'clear_uas_desc' at line 1028

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5084

**Comment by Mingyuan18** [comment]
The Patch was merged.
