### ISSUE TITLE
virtio-console not work for Debian

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#3615]
when add the virtio-console to acrn-dm cmdline to boot Debian, there will be a segment fault in acrn-dm.

vtcon: read from bad offset/size 1/1
vtcon: write to bad offset/size 1/1
vtcon: read from bad offset/size 1/1
vtcon: write to bad offset/size 1/1
vtcon: read from bad offset/size 1/1
vtcon: write to bad offset/size 1/1
vtcon: read from bad offset/size 9/1
vtcon: write to bad offset/size 9/1
vtcon: read from bad offset/size 9/1
vtcon: write to bad offset/size 9/1
vtcon: read from bad offset/size 9/1
vtcon: write to bad offset/size 9/1
vtcon: read from bad offset/size 17/1
vtcon: write to bad offset/size 17/1
vtcon: read from bad offset/size 17/1
vtcon: write to bad offset/size 17/1
vtcon: read from bad offset/size 17/1
vtcon: write to bad offset/size 17/1

Thread 13 "vcpu 0" received signal SIGSEGV, Segmentation fault.
                                                               [Switching to LWP 748]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000555555562536 in virtio_pci_legacy_write (ctx=<optimized out>, vcpu=<optimized out>, baridx=0, value=0, size=1, offset=25, dev=0x5555557e5750)
    at hw/pci/virtio/virtio.c:913
#2  virtio_pci_write (ctx=<optimized out>, vcpu=<optimized out>, dev=0x5555557e5750, baridx=0, offset=25, size=1, value=0) at hw/pci/virtio/virtio.c:1852
#3  0x00005555555802ed in pci_emul_io_handler (ctx=<optimized out>, vcpu=<optimized out>, in=<optimized out>, port=<optimized out>, bytes=1,
    eax=0x5555557dc058 <vhm_request_page+88>, arg=0x5555557e5750) at hw/pci/core.c:390
#4  0x00005555555a046c in emulate_inout (ctx=<optimized out>, pvcpu=<optimized out>, pio_request=<optimized out>) at core/inout.c:115
#5  0x00005555555a2475 in vmexit_inout (ctx=<optimized out>, vhm_req=0x5555557dc000 <vhm_request_page>, pvcpu=<optimized out>) at core/main.c:345
#6  0x00005555555a26bf in handle_vmexit (vcpu=<optimized out>, vhm_req=0x5555557dc000 <vhm_request_page>, ctx=0x5555557e1080) at core/main.c:435
#7  vm_loop (ctx=0x5555557e1080) at core/main.c:690
#8  start_thread (param=<optimized out>) at core/main.c:278
#9  0x00007ffff7f9f7bf in ?? () from /usr/lib64/libpthread.so.0
#10 0x00007ffff7c08043 in clone () from /usr/lib64/haswell/libc.so.6

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5080
