### ISSUE TITLE
cbm length calculation,Extended model judge, print info error

### ISSUE THREAD

**Issue by cdliuqiang** [projectacrn/acrn-hypervisor#3675]
1. CPUID(EAX = 10H, ECX = ResID=1 or 2).EAX Bits 04 - 00: Length of the capacity bit mask for the corresponding ResID using minus-one notation
2. The Extended Model ID needs to be examined only when the Family ID is 06H or 0FH
3. check_name function, print info error

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5175
