### ISSUE TITLE
The documentation build system creates artefacts in the `doc/` folder

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#3686]
Generating the documentation for the ACRN project (`make doc` from the top-level folder, or `make html` from the `doc/` folder) always creates artefacts under the `doc/` folder, such as:
- `doc.log`
- `doc.warnings`
- `doxygen`
- `misc`

We should modify the build infrastructure to only put build artefacts, even if temporary, inside a `$(BUILDDIR)`.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5177

**Comment by NanlinXie** [comment]
@gvancuts, Could this issue be closed since the patch is merged?

**Comment by gvancuts** [comment]
Yes, thanks for the reminder. Closing.
