### ISSUE TITLE
Properly reset pCPUs with LAPIC PT enabled during VM shutdown/reset

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#3708]
When a VM is configured with LAPIC PT mode and its vCPU is in x2APIC mode, the corresponding pCPU needs to be reset during VM shutdown/reset as its physical LAPIC was used by its guest

This commit fixes an issue where this reset never happens. is_lapic_pt_enabled() needs to be called before reset_vcpu() to be able to correctly reflect a vCPU's APIC mode.

A vCPU with LAPIC PT mode but in xAPIC mode does not require such reset, since its physical LAPIC was not touched by its guest directly.

**Comment by peterfang** [comment]
[External_System_ID] ACRN-5137

**Comment by Mingyuan18** [comment]
Verify pass. Close this issue.
