### ISSUE TITLE
Add support for multiple RDT resource allocation and fix L3 CAT config overwrite by L2

### ISSUE THREAD

**Issue by vijaydhanraj** [projectacrn/acrn-hypervisor#3715]
Current implementation doesn't support RDT allocation for multiple resources. For example, if both L2 and L3 CAT are supported, then L3 CAT configuration will be overwritten by L2 resulting in unexpected behavior. 

Goal: Create a general framework that can support RDT allocation for multiple resources (L2, L3, and Memory) and fix the overwriting of the configurations.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5328

**Comment by fuzhongl** [comment]
@vijaydhanraj Can this git issue be closed now?
Thanks!
