### ISSUE TITLE
CODEOWNERS folder names are incorrect

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#3723]
Folders in the CODEOWNERS file need to end with a slash

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5303

**Comment by fuzhongl** [comment]
@dbkinder  Can we close this ticket since patch was merged?
Thanks!

**Comment by fuzhongl** [comment]
@dbkinder Can we close this ticket since patch was merged?
Thanks!

**Comment by dbkinder** [comment]
Issue fixed and verified.
