### ISSUE TITLE
dm: refine the check of return value of snprintf

### ISSUE THREAD

**Issue by gaojunhao0504** [projectacrn/acrn-hypervisor#3789]
int snprintf(char *str, size_t size, const char *format, ...)
The functions snprintf() write at most size bytes (including the
terminating null byte('\0')) to str.
only when returned value of snprintf is non-negative and less than size,
the string has been completely written.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5299

**Comment by Mingyuan18** [comment]
Verify pass, so close this issue.
