### ISSUE TITLE
hv: error debug message in  hcall_set_callback_vector

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3801]
Error debug message in this function, there is no string variable for %s output in below statement:
pr_err("%s: Invalid passed vector\n");

int32_t hcall_set_callback_vector(const struct acrn_vm *vm, uint64_t param)
{
	int32_t ret;

	if (!is_sos_vm(vm)) {
		pr_err("%s: Targeting to service vm", __func__);
	        ret = -EPERM;
	} else if ((param > NR_MAX_VECTOR) || (param < VECTOR_DYNAMIC_START)) {
		pr_err("%s: Invalid passed vector\n");

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4886

**Comment by Mingyuan18** [comment]
The bug cannot reproduced with below build
Installed version: 31380
ACRN tag: acrn-2019w43.5-140000p
