### ISSUE TITLE
hv: Hypervisor will crash when invalid parameters is used for  hcall_setup_hv_npk_log()

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3802]
Input "npk_param" for below hypercall handler should be verified, else hypervisor will potentiallly crash in some cases.
static int32_t hcall_setup_hv_npk_log(struct acrn_vm *vm, uint64_t param)

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4888

**Comment by Mingyuan18** [comment]
Won't fix this issue.
