### ISSUE TITLE
DM: FILE pointer Is Not Closed After Operations in acrn_load_elf

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3817]
In below function, FILE pointer “fp” will not be closed if condition @line 236

 (elf_ehdr->e_ident[EI_CLASS] == ELFCLASS32) is true:

./acrn-hypervisor/devicemodel/core/sw_load_elf.c | acrn_load_elf()

**Comment by lirui34** [comment]
[External_System_ID] ACRN-5330

**Comment by Mingyuan18** [comment]
Verify pass, close this ticket.
