### ISSUE TITLE
DM: 'request_mutex' is potentially not unlocked in tpm_crb.c

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3825]
pthread_mutex_lock/unlock pair are not well maintained in below usage case:  

./acrn-hypervisor/devicemodel/hw/platform/tpm/tpm_crb.c | crb_reg_write()

Variable 'tpm_vdev->request_mutex' locked on line 319 was not unlocked if

pthread_cond_signal(&tpm_vdev->request_cond) is true.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-5332

**Comment by Mingyuan18** [comment]
Verify pass, close this ticket.
