### ISSUE TITLE
Service VM power off need at least one minute when passthru NVMe to RTVM

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3827]
**Environment**
- KBL I7 NUC
- Installed version: 31230

**Reproduce step**
  1. Boot Service VM.
  2. ``acrnctl add launch_hard_rt_vm.sh`` in Service VM.
  3. under Service VM, type ``systemctl unmask acrnd``
  4. poweroff in Service VM.

**Current result**
Service VM power off need at least one minute when passthru NVMe to RTVM

**Expected result**
Service VM power off quickly.

**repetition rate :** 100%

**Comment by lirui34** [comment]
[External_System_ID] ACRN-5364

**Comment by Mingyuan18** [comment]
The bug cannot reproduced in below build:
Tag:acrn-2019w41.4-140000p
CL: 31290
