### ISSUE TITLE
[KBLNUC][WaaG] bring back non-context register save/restore

### ISSUE THREAD

**Issue by xinyunliu** [projectacrn/acrn-hypervisor#3830]
The non-context registers value might be changed, some of them impact the engine status when switch the gpu contexts between different VMs.

If uos is Windows and sos is Linux, must save/restore these registers.

Add an option `enable_context_protection` to enable/disable this feature.

Meanwhile, the non-conformance test and per-ring scheduler need to be dropped

**Comment by xinyunliu** [comment]
[External_System_ID] ACRN-5427

**Comment by Mingyuan18** [comment]
The patch was merged and verify pass.
