### ISSUE TITLE
User VM has no display with uefi boot mode

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#3840]
**Environment**: UP2
**Steps**:
1. set up Hybrid hypervisor in UP2
2. boot up User VM
3. start weston in User VM
   ``weston --tty=1 -i 0 &``

**Expected result**:
User VM has display in screen

**Actual result**:
User VM has no display

**Reproduce rate**:
100%

**Comment by lirui34** [comment]
[External_System_ID] ACRN-5432

**Comment by Mingyuan18** [comment]
Very pass.
