### ISSUE TITLE
Local variable 'info' maybe referenced before initializing in 'vmsi_remap()'

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3903]
@file vmsi.c /static int32_t vmsi_remap(const struct pci_vdev *vdev, bool enable)

fields of  local variable 'info' maybe accessed before initializing:

1) input 'enable' is false

2) call 'ptirq_msix_remap()'

3)  info.pmsi_addr will be used but it was not initialized or set by 'ptirq_msix_remap()'

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5361

**Comment by Mingyuan18** [comment]
Close this issue due to no regression issue.
