### ISSUE TITLE
dm: update ACPI with latest ASL standard

### ISSUE THREAD

**Issue by gaojunhao0504** [projectacrn/acrn-hypervisor#3933]
The device model generating ACPI table use the old ASL
standard(version:20190816), then the iasl in clearlinux(version:31360)
is 20191018, it can't disassemble the ACPI table compiled by old
standard.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5513

**Comment by Mingyuan18** [comment]
Verify pass. So close it.
