### ISSUE TITLE
linux-iot-lts2018-sos-4.19.78-95.x86_64

### ISSUE THREAD

**Issue by paspndevops** [projectacrn/acrn-hypervisor#3958]
Login Prompt appeared successfully but keyboard not responding for input entry 

![VirtualBox_ClearLinux_29_10_2019_16_22_45](https://user-images.githubusercontent.com/53786011/67761054-8b2c7480-fa68-11e9-962b-5bbf6026643c.png)

**Comment by paspndevops** [comment]
@fuzhongl 

![VirtualBox_ClearLinux_29_10_2019_16_27_42](https://user-images.githubusercontent.com/53786011/67761353-21f93100-fa69-11e9-809e-4dd00163882a.png)

**Comment by fuzhongl** [comment]
@paspndevops USB ports are assigned to UOS in your script? Could you please share the launch script? 
Thanks!

**Comment by fuzhongl** [comment]
@paspndevops  Which Clear Linux build are you using?
Ant steps to reproduce this issue?
Thanks!

**Comment by paspndevops** [comment]
@fuzhongl 

clr-os **31380** i tried and Kernel " **linux-iot-lts2018-sos-4.19.78-95.x86_64**"

**Comment by fuzhongl** [comment]
@paspndevops  clr-os 31380 isn't the workable CL build, please try the latest build or 31310(verified on our side).
Thanks!

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5558

**Comment by paspndevops** [comment]
@fuzhongl @Mingyuan18 

Could you please confirm on which NUC(Model) 31310 verified now I am using ( NUC7i7DNK(BOARD-NUC7i7DNB)

**Comment by fuzhongl** [comment]
@paspndevops We verified this build  on KBLNUC7i7DNHE. 
Thanks.

**Comment by paspndevops** [comment]
@fuzhongl 

Is there any specific reason to use above HW why i am not able work with NUC7i7DNK and intel laptop.

Thanks !

**Comment by fuzhongl** [comment]
@paspndevops 
We don't have KBLNUC7i7DNK; KBLNUC7i7DNHE is our QA verified platform.
Thanks!

**Comment by paspndevops** [comment]
@fuzhongl 
Thanks for your quick reply could you please tell me is there any hardware dependency in acrn.efi or sos kernel.

**Comment by fuzhongl** [comment]
@paspndevops 
Following is verified platform:
https://projectacrn.github.io/latest/reference/hardware.html
Thanks!

**Comment by fuzhongl** [comment]
@paspndevops Do you copy the lib/modules to your board for this issue?
