### ISSUE TITLE
The boot uos script will display the sos information on the uos screen for about 2s

### ISSUE THREAD

**Issue by xinyunliu** [projectacrn/acrn-hypervisor#3979]
Environment
KBLNUC
Steps
1.boot sos
2.boot uos
3.Expected result
uos boot successfully
Actual result
Short-lived sos information will appear on the windows startup interface.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5312

**Comment by Mingyuan18** [comment]
Can't reproduced on below build:
ACRN tag: acrn-2019w46.2-140000p
CL: 31630
