### ISSUE TITLE
Fedora 30 as User OS 

### ISSUE THREAD

**Issue by paspndevops** [projectacrn/acrn-hypervisor#3984]
Hi
Please help me how to start working Fedora 30 as UserOS :

**NUC and SOS Details:**

$ sudo sh acrn_quick_setup.sh -s 31440 -d

root@clrdev/usr/share/acrn/samples/nuc # dmesg |grep ACRN
[    0.000000] Hypervisor detected: ACRN
[    1.029518] ACRNTrace: Initialized acrn trace module with 8 cpu
[    1.031944] ACRN HVLog: Failed to init last hvlog devs, errno -19
[    1.032105] ACRN HVLog: Initialized hvlog module with 8 cpu

**root@clrdev/usr/share/acrn/samples/nuc # uname -r**
4.19.78-95.iot-lts2018-sos
**root@clrdev/usr/share/acrn/samples/nuc # ls /dev/acrn***
/dev/acrn_hvlog_cur_0  /dev/acrn_hvlog_cur_2  /dev/acrn_hvlog_cur_4  /dev/acrn_hvlog_cur_6  /dev/acrn_trace_0  /dev/acrn_trace_2  /dev/acrn_trace_4  /dev/acrn_trace_6  /dev/acrn_vhm
/dev/acrn_hvlog_cur_1  /dev/acrn_hvlog_cur_3  /dev/acrn_hvlog_cur_5  /dev/acrn_hvlog_cur_7  /dev/acrn_trace_1  /dev/acrn_trace_3  /dev/acrn_trace_5  /dev/acrn_trace_7

**Comment by paspndevops** [comment]
@ttzeng 

Could you please help me how to launch Fedora30 as a UOS on **NUC7i7BNH** Now i am able to launch CL41370 as UOS .

Thanks in Advance

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5612

**Comment by fuzhongl** [comment]
@paspndevops Please use CL build newer than 31470.
Thanks!

**Comment by paspndevops** [comment]
@fuzhongl 

Please provide the solution to install **Fedora UOS on NVM storage**  or how to create fedora image to burn on NVM storage

dd if=preempt-rt-31670.img of=/dev/nvme0n1 bs=4M oflag=sync status=progress

Thanks!

**Comment by paspndevops** [comment]
@fuzhongl 

Please provide the solution to install **Fedora UOS on NVM storage**  or how to create fedora image to burn on NVM storage

dd if=preempt-rt-31670.img of=/dev/nvme0n1 bs=4M oflag=sync status=progress

Thanks!

**Comment by gvancuts** [comment]
Can you also share your launch script and error when attempting this?

**Comment by paspndevops** [comment]
@gvancuts 

here i attached launcher script for Fedora Server 30

[Laun_UOS.txt](https://github.com/projectacrn/acrn-hypervisor/files/4020005/Laun_UOS.txt)

Thanks in Advance !

**Comment by gvancuts** [comment]
Thanks @paspndevops . You are not attempting to use the NVMe drive in that script, instead you are using a local `uosFC.img` file. You'll want something like this in your script:
`-s 2,passthru,3c/0/0 \` instead of `-s 3,virtio-blk,./uosFC.img`.

Have you already verified that the BDF info in your script matches your platform (send us the output of `lspci -nn` in doubt).

How was the `preempt-rt-31670.img` image created?

**Comment by paspndevops** [comment]
@gvancuts 

### **How to know which scenario is running on ACRN NUC(sdc,sdc2,industry)**

### **How Burn the Fedora-UOS VM image onto the NVMe**

sda                     8:0    0 256.2G  0 disk 
├─sda1                  8:1    0   512M  0 part /boot/efi
└─sda2                  8:2    0 255.7G  0 part 
  ├─ubuntu--vg-root   253:0    0 254.7G  0 lvm  /
  └─ubuntu--vg-swap_1 253:1    0   976M  0 lvm  [SWAP]
nvme0n1               259:0    0  13.4G  0 disk 
├─nvme0n1p1           259:1    0   510M  0 part 
├─nvme0n1p2           259:2    0    33M  0 part 
└─nvme0n1p3           259:3    0     8G  0 part 

### How to configure Industry scenario on NUC7i7BNB  Board ( RTVM )

### lspci -nn
00:00.0 Host bridge [0600]: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Host Bridge [8086:5af0] (rev 0b)
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:5927] (rev 06)
00:08.0 System peripheral [0880]: Intel Corporation Skylake Gaussian Mixture Model [8086:1911]
00:14.0 USB controller [0c03]: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller [8086:9d2f] (rev 21)
00:14.2 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Thermal subsystem [8086:9d31] (rev 21)
00:16.0 Communication controller [0780]: Intel Corporation Sunrise Point-LP CSME HECI #1 [8086:9d3a] (rev 21)
00:17.0 SATA controller [0106]: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] [8086:9d03] (rev 21)
00:1c.0 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port [8086:9d10] (rev f1)
00:1c.5 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 [8086:9d15] (rev f1)
00:1c.7 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #8 [8086:9d17] (rev f1)
00:1d.0 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 [8086:9d18] (rev f1)
00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:9d4e] (rev 21)
00:1f.2 Memory controller [0580]: Intel Corporation Sunrise Point-LP PMC [8086:9d21] (rev 21)
00:1f.3 Audio device [0403]: Intel Corporation Sunrise Point-LP HD Audio [8086:9d71] (rev 21)
00:1f.4 SMBus [0c05]: Intel Corporation Sunrise Point-LP SMBus [8086:9d23] (rev 21)
00:1f.6 Ethernet controller [0200]: Intel Corporation Ethernet Connection (4) I219-V [8086:15d8] (rev 21)
3a:00.0 Network controller [0280]: Intel Corporation Wireless 8265 / 8275 [8086:24fd] (rev 78)
3b:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5229 PCI Express Card Reader [10ec:5229] (rev 01)
3c:00.0 Non-Volatile memory controller [0108]: Intel Corporation Device [8086:2522]


Thanks!

**Comment by paspndevops** [comment]
@gvancuts 

![nvm](https://user-images.githubusercontent.com/53786011/71952509-f03cdd00-3204-11ea-8e73-049716b8a3bb.png)


Thanks!

**Comment by fuzhongl** [comment]
> @gvancuts
> 
> ### **How to know which scenario is running on ACRN NUC(sdc,sdc2,industry)**
sudo sh acrn_quick_setup.sh -s 31440 -d is for SDC

> ### **How Burn the Fedora-UOS VM image onto the NVMe**
> sda 8:0 0 256.2G 0 disk
> ├─sda1 8:1 0 512M 0 part /boot/efi
> └─sda2 8:2 0 255.7G 0 part
> ├─ubuntu--vg-root 253:0 0 254.7G 0 lvm /
> └─ubuntu--vg-swap_1 253:1 0 976M 0 lvm [SWAP]
> nvme0n1 259:0 0 13.4G 0 disk
> ├─nvme0n1p1 259:1 0 510M 0 part
> ├─nvme0n1p2 259:2 0 33M 0 part
> └─nvme0n1p3 259:3 0 8G 0 part
> 
You need  Fedora iso file to make install U disk
> ### How to configure Industry scenario on NUC7i7BNB Board ( RTVM )
sudo sh acrn_quick_setup.sh -s 31440 -d -i is for industry
> ### lspci -nn
> 00:00.0 Host bridge [0600]: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Host Bridge [8086:5af0] (rev 0b)
> 00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:5927] (rev 06)
> 00:08.0 System peripheral [0880]: Intel Corporation Skylake Gaussian Mixture Model [8086:1911]
> 00:14.0 USB controller [0c03]: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller [8086:9d2f] (rev 21)
> 00:14.2 Signal processing controller [1180]: Intel Corporation Sunrise Point-LP Thermal subsystem [8086:9d31] (rev 21)
> 00:16.0 Communication controller [0780]: Intel Corporation Sunrise Point-LP CSME HECI #1 [8086:9d3a] (rev 21)
> 00:17.0 SATA controller [0106]: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] [8086:9d03] (rev 21)
> 00:1c.0 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port [8086:9d10] (rev f1)
> 00:1c.5 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 [8086:9d15] (rev f1)
> 00:1c.7 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #8 [8086:9d17] (rev f1)
> 00:1d.0 PCI bridge [0604]: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 [8086:9d18] (rev f1)
> 00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:9d4e] (rev 21)
> 00:1f.2 Memory controller [0580]: Intel Corporation Sunrise Point-LP PMC [8086:9d21] (rev 21)
> 00:1f.3 Audio device [0403]: Intel Corporation Sunrise Point-LP HD Audio [8086:9d71] (rev 21)
> 00:1f.4 SMBus [0c05]: Intel Corporation Sunrise Point-LP SMBus [8086:9d23] (rev 21)
> 00:1f.6 Ethernet controller [0200]: Intel Corporation Ethernet Connection (4) I219-V [8086:15d8] (rev 21)
> 3a:00.0 Network controller [0280]: Intel Corporation Wireless 8265 / 8275 [8086:24fd] (rev 78)
> 3b:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5229 PCI Express Card Reader [10ec:5229] (rev 01)
> 3c:00.0 Non-Volatile memory controller [0108]: Intel Corporation Device [8086:2522]
> 
> ### How was the preempt-rt-31670.img image created?
> I am getting good latency in similar way i am looking solution for Fedora/ubuntu
> 
> Thanks!

**Comment by gvancuts** [comment]
> lspci -nn

That does not look like the output from a NUC7i7BNB board, did you get it mixed up with another system?

**Comment by fuzhongl** [comment]
@paspndevops  Seeing Fedora as User OS is working on your side.[here](https://github.com/projectacrn/acrn-hypervisor/issues/4369)
Could you help to close this ticket?
Thanks!
