### ISSUE TITLE
Assert statement is used to validate input parameters in pci_emul_mem_handler(apl_sdc_stable).

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3991]
Assert statement is used to validate input parameters in below ACRN Device Model API function, this application will crash if Fuzz tool inject specific invalid parameters to this function.

acrn-dm: hw/pci/core.c (in function (pci_emul_mem_handler())in the Device Model module does not properly validate the arguments when handling  emulated MMIO access request from guest OS, which allows guest OS users to cause a denial of service via a crafted application.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5593

**Comment by NanlinXie** [comment]
Patch merged and no regression, close it.
