### ISSUE TITLE
Trampoline code in hypervisor potentially be accessible to service VM

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#3992]
Trampoline code exists in LOW_RAM region in hypervisor,  it should not be accessible to service VM, but now current codebase, it is mapped in Service VM's EPT, so it is potentially accessible to service VM.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5296

**Comment by Mingyuan18** [comment]
The Patch was merge and no regression issue found.
