### ISSUE TITLE
dm: remove cfc/cf8 pio handler

### ISSUE THREAD

**Issue by gaojunhao0504** [projectacrn/acrn-hypervisor#3999]
The acrn vhm driver will convert all PCI configure space access to
PCI_CFG type, so the pci_emul_cfgaddr and pci_emul_cfgdata will nerver
be invoked. Remove these useless functions.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5601

**Comment by Mingyuan18** [comment]
No regression issue found, so close this issue.
ACRN tag: acrn-2019w46.2-140000p
CL: 31630
