### ISSUE TITLE
Refine print string format for 'uint64_t' type value in hypervisor

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#4020]
in string format functions such as 'printf()',  "%ll*" and "%l*" are used for 'uint64_t' type value, it is confusing.

 
expected:

use "0x%l*" string to format 'uint64_t' type value, instead of "0x%ll*" for some cases.

**Comment by yonghuah** [comment]
[External_System_ID] ACRN-5618

**Comment by Mingyuan18** [comment]
No regression issue found, so close this issue.
ACRN tag: acrn-2019w46.2-140000p
CL: 31630
