### ISSUE TITLE
ACRN fails to load the Service VM on a second attempt

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#4023]
The ACRN hypervisor will fail to load the Service VM *if* a previous attempt to load the bootloader was unsuccessful. I do not know exactly at this point where it fails, my best suspicion is that it fails to correctly load and run the EFI bootloader (`bootloaderx64.efi).

This is reproducible with the latest as of today, i.e. https://github.com/projectacrn/acrn-hypervisor/commit/20c1ad1b3a1dcb1db6fd4c3bed4eb2a679465df2 on a NUC7i7BNH.

This is reproducible as follows:
1. Make sure ACRN and the Service VM are correctly installed
2. Boot to the EFI prompt
3. Run `acrn.efi bootloader=\EFI\org.clearlinux\grubx64.efi`
4. It will fail and invite you to press any key to continue, taking you back to the EFI shell prompt
5. Run `acrn.efi` this time (which will use `bootloaderx64.efi`)
6. It will start, display a couple of messages on the console (no error/warning) but then gets stuck there and the EFI bootloader menu never shows up

**Comment by fuzhongl** [comment]
@gvancuts This issue was fixed by add the additional "space" at the end of efibootmgr command;
 The GSG were also updated.
Could you please close this git issue?
Thanks!
