### ISSUE TITLE
Only slot-2 can work in "-s n,passthru,02/00/0 \" for RTVM, other slots are not functional

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#4049]
Steps to reproduce:
set launch_hart_rt_vm.sh acrn-dm passthru nvme disk part as "-s 2,passthru,3c/00/0 \"
Then launch RTVM.

**Comment by lirui34** [comment]
[External_System_ID] ACRN-5055

**Comment by Mingyuan18** [comment]
The bug cannot reproduced in kbl nuc in v1.4 release build
ACRN tag: acrn-2019w45.4-140000p
