### ISSUE TITLE
hv: instr_emul: use cs segment when fetching instructions

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#4064]
In non-64-bit mode, CS segment base address should be considered when determining the linear address of the vcpu's instruction pointer.

**Comment by peterfang** [comment]
[External_System_ID] ACRN-5592

**Comment by Mingyuan18** [comment]
No regression issue found, so close this issue.
ACRN tag: acrn-2019w46.2-140000p
CL: 31630
