### ISSUE TITLE
Support auto make build for new broad from XML file.

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#4067]
Currently we only can build hypervisor from XML file for existed board because there is a limitation in Makefile that the make will be depend on $(BOARD).config file. But for a new board, the $(BOARD).config never existed, so the make will be failed.

This issue blocks the integration for WHL platform.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5629

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.
