### ISSUE TITLE
hv: add printf "not support the value of vuart index parameter" in function vuart_register_io_handler

### ISSUE THREAD

**Issue by xiajidong** [projectacrn/acrn-hypervisor#4072]
Call vuart_register_io_handler function, when the  parameter vuart_idx is greater than or equal to 2，print the vuart index value which will not register the vuart.

**Comment by Mingyuan18** [comment]
@xiajidong , Please add your email information to your git account. Thank you

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5669

**Comment by xiajidong** [comment]
> @xiajidong , Please add your email information to your git account. Thank you

**Comment by xiajidong** [comment]
> @xiajidong , Please add your email information to your git account. Thank you

@Mingyuan18 ,I have already add my email information to my git account in Settings,in Setting options have email information，and I add it in there，is anyother place which I should to add？
Thanks
Best Regards

**Comment by Mingyuan18** [comment]
@xiajidong ，Do you plan to submit this patch?

**Comment by xiajidong** [comment]
Yes，I plan to submit this patch.
Thanks,
Best Regards

**Comment by xiajidong** [comment]
> @xiajidong ，Do you plan to submit this patch?

@Mingyuan18 ，Yes,I plan to submit this patch.and any other things I can do ?
Thanks，
Best Regards

**Comment by fuzhongl** [comment]
@xiajidong Can this git issue be closed now?
Thanks!

**Comment by xiajidong** [comment]
ok,I will close it now,ths.
