### ISSUE TITLE
Machine Check Error on Page Size Change

### ISSUE THREAD

**Issue by binbinwu1** [projectacrn/acrn-hypervisor#4101]
Machine Check Error on Page Size Change
Instruction fetch may cause machine check error if page size
and memory type was changed without invalidation on some
processors. Malicious guest kernel could trigger this issue.

**Comment by binbinwu1** [comment]
[External_System_ID] ACRN-5676

**Comment by Mingyuan18** [comment]
The patch was merged and no regression issue found.
