### ISSUE TITLE
Creating Ubuntu SOS not working - black screen

### ISSUE THREAD

**Issue by ErinRJ** [projectacrn/acrn-hypervisor#4123]
Following the instructions found at [Using Ubuntu as the Service OS](https://projectacrn.github.io/latest/tutorials/using_ubuntu_as_sos.html), we were unable to create an SOS with Ubuntu.

Board used: UP2

After following the instructions and booting to the SOS, it just shows a black screen. When rebooting the board, and trying to access the original Ubuntu installed on the board, it can no longer load and just shows a purple screen.

Since we're using a UP2 board instead of a NUC, we tried the installation with two different configurations:  Using "/mnt", and using "/boot", since the [UP2 Instructions](https://projectacrn.github.io/1.2/getting-started/up2.html) specified using mnt instead of boot. Regardless, both had the black screen SOS problem.

Please let me know if you need any more information and thank you for your time,

Erin

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5701

**Comment by fuzhongl** [comment]
@ErinRJ Does the native Ubuntu work well on your board?
If yes, could you please share the acrn-dm version info?
Thanks!

**Comment by ErinRJ** [comment]
HI Fuzhongl! 
Thank you for your prompt support.
Before configuring the ACRN SOS, Ubuntu worked well and as expected on the board.

Unfortunately, we've actually switched over to a different part of our project for now so we won't be using this operating system configuration at the moment.
If we end up using Ubuntu in the future, I'll create a new issue thread if need be, but for now I'll close it.

Thanks again,
Erin
