### ISSUE TITLE
CI commit message check missed an error

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#4138]
I noticed an odd line in the 1.4 release notes.  A blank line is needed after the commit description and before the Tracked-on or Signed-off-by lines, but the CI check didn't catch this for https://github.com/projectacrn/acrn-hypervisor/commit/5ca26d3b

As a result, the commit summary in the release notes isn't right:

* 5ca26d3b - Modify KBL-NUC/SDC for default build remove acrn.efi and modify KBL-NUC/SDC for default build Tracked-On: #3953 Signed-off-by: wenlingz <wenling.zhang@intel.com>

**Comment by wenlingz** [comment]
I will be careful  next time, thanks for your remind
