### ISSUE TITLE
Extend ACRN support for multiple physical IOAPICs

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#4151]
Server platforms tend to have more than one physical IOAPIC on the platform.
With multiple physical IOAPICs, pass-through devices for SOS and post-launched VMs, depending on IO-APIC for interrupts, could be impacted.

**Comment by sainath14** [comment]
[External_System_ID] ACRN-3975

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.
