### ISSUE TITLE
Hv: support xsave in context switch

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#4166]
content:   xsave area:
        legacy region: 512 bytes
        xsave header: 64 bytes
        extended region: < 3k bytes
    So, pre-allocate 4k area for xsave. Use certain instruction to save or
   restore the area according to hardware xsave feature set.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5774

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.
