### ISSUE TITLE
acrntrace fixes and improvement

### ISSUE THREAD

**Issue by KaigeFu** [projectacrn/acrn-hypervisor#4175]
Bugs in acrntrace:
    - Total vmexit number may be wrong in some cases.
    - Total run time may be output as 0 sec if it is less 1 sec.

BTW, there are some functions should be improved:
   - Add opt to specify the cpus where we should capture the trace data
  - set the FLAG_CLEAR_BUF by default

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5787
