### ISSUE TITLE
CPU Sharing: IO-Sensitive Round-Robin CPU Scheduler

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#4178]
The hypervisor shall support improved round-robin algorithm CPU scheduler for Service VM & post-launched VM under sharing configuration.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-3813

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.
