### ISSUE TITLE
acrnboot: the end address of _DYNAME region is not calculated correct

### ISSUE THREAD

**Issue by bigdata-memory** [projectacrn/acrn-hypervisor#4191]
In the file hypervisor/boot/reloc.c, the function relocate(...) does incorrectly calculate the end address of _DYNAMIC region, it may causes the relocation info associated with the entry of R_X86_64_RELATIVE to be set incorrectly.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5800
