### ISSUE TITLE
acrn-config: Fix target xml generation issue when no P-state scaling driver is present

### ISSUE THREAD

**Issue by vijaydhanraj** [projectacrn/acrn-hypervisor#4199]
There seems to be a corner case where target xml file fails to get generated if there was no P-state scaling driver present. This patch addresses it by handling the file not present exception and setting a warning as well a "not available" string to successfully generate target xml file.

**Comment by vijaydhanraj** [comment]
[External_System_ID] ACRN-5797

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.
