### ISSUE TITLE
Extend non-contiguous HPA for pre-launched VMs in Hybrid mode

### ISSUE THREAD

**Issue by vijaydhanraj** [projectacrn/acrn-hypervisor#4217]
This patch extends the non-contiguous HPA allocations for pre-launched VMs in hybrid mode. This also takes care of the needed acrn-config tool changes.

**Comment by vijaydhanraj** [comment]
[External_System_ID] ACRN-5792

**Comment by NanlinXie** [comment]
Closed with no regression issue.
