### ISSUE TITLE
acrn-config: Fix ve820 table generation when guest memory size is >512MB

### ISSUE THREAD

**Issue by vijaydhanraj** [projectacrn/acrn-hypervisor#4219]
This change fixes an issue with the generation of guest ve820 when the size of the memory is >512MB. The issue is primarily with respect to converting between hex and int.

**Comment by vijaydhanraj** [comment]
[External_System_ID] ACRN-5814

**Comment by NanlinXie** [comment]
Closed with no regression issue.
