### ISSUE TITLE
Disable debug features in default build/compile configuration

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#4222]
Disable debug features in your default build/compile configuration
1.These should require action, either at configuration or at runtime, to enable,
 e.g. editing a configuration file or running with specific arguments.
2. This should be well documented

**Comment by wenlingz** [comment]
Please add the JIRA

**Comment by yonghuah** [comment]
[External_System_ID] ACRN-5812

**Comment by yonghuah** [comment]
@wenlingz added the JIRA ID,thanks.

**Comment by Mingyuan18** [comment]
fix patch is integrated and verified.so close this issue.
