### ISSUE TITLE
ClearLinux desktop GUI of SOS fails to launch

### ISSUE THREAD

**Issue by kiendinh** [projectacrn/acrn-hypervisor#424]
I set up the ACRN environment on the APL NUC and UP2 board with ClearLinux 22950. SOS was confirmed to boot up on ACRN. After installing the desktop GUI on ClearLinux following [this guide](https://clearlinux.org/documentation/clear-linux/guides/maintenance/enable-user-space#enable-user-space), the GUI failed to launch on the SOS in both HW. It could be launched after booting to the native kernel in both HW though. And it was alright on old ClearLinux v21260.

**Comment by gvancuts** [comment]
I think it may have to do with the introduction of GVT-g and plane ownership. I think @ttzeng may have looked at this already.

**Comment by kiendinh** [comment]
It looks like the fb console has been disabled with parameter i915.enable_initial_modeset=1 in the acrn.conf. This is by design. The GUI can be set up to launch on boot-up. For gdm, please follow this [guide](https://clearlinux.org/documentation/clear-linux/guides/maintenance/enable-user-space) to enable graphic UI on boot-up.
