### ISSUE TITLE
Check the validity of GPA is required in hc_write_protect_page()

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#4240]
Potential hypervisor crash may be triggered when  calling hcall_write_protect_page() with a crafted
 GPA in 'struct wp_data' instance, e.g. an invalid  GPA that is not in the scope of the target VM's
 EPT address space.

**Comment by yonghuah** [comment]
[External_System_ID] ACRN-5672

**Comment by Mingyuan18** [comment]
Verify  Pass, Run this test 48h, there's no crash
