### ISSUE TITLE
acrnboot: parse hv cmdline incorrectly when containing any trailing white-spaces

### ISSUE THREAD

**Issue by bigdata-memory** [projectacrn/acrn-hypervisor#4250]
In hypervisor/boot/cmdline.c source file. the function parse_hv_cmdline() is used to parse hv cmdline to tokens, the parsing logic doesn't consider the corner case of containing trailing white-spaces, that will cause de-referencing pointer variable 'end' at the the wrong address out of cmdline string.
this issue may result in the wrong parsing since it will ignore the whitespace character following NULL and continue to parse until encountering a non-white-space character immediately following NULL.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5858
