### ISSUE TITLE
acrnctl stop VM1 and mouse pointer not visible

### ISSUE THREAD

**Issue by paspndevops** [projectacrn/acrn-hypervisor#4280]
Hi ,

When iam trying to stop /reset/suspend with acrnctl UOS not responded also let know how to resolve mouse pointer visibility on UOS.

Thanks !

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5887

**Comment by fuzhongl** [comment]
@paspndevops For UOS normal case acrnctl works well:
https://projectacrn.github.io/latest/misc/acrn-manager/README.html
You can add -f option if UOS is in abnormal status.
About UOS mouse cursor issue, please using acrn-kernel for SOS.
https://github.com/projectacrn/acrn-kernel

Thanks!

**Comment by paspndevops** [comment]
@fuzhongl 

I tried to stop vm with -f but no response Please guide me how to compile acrn-kernel for NUC7i7BNB.(Which configuration file .config)

Thanks!

**Comment by fuzhongl** [comment]
@paspndevops  Please refer following link; and  build acrn.efi for NUC7i7BNB with config-tool:
https://projectacrn.github.io/latest/tutorials/acrn_configuration_tool.html
Thanks!

**Comment by paspndevops** [comment]
@fuzhongl 

UOS not **shutdown and reboot error** after adding RTVM parameters please provide the solution for UOS launcher script added here for acrn-dm:

acrn-dm -A -m $mem_size -s 0:0,hostbridge \
   --lapic_pt \
   --rtvm \
   -U 495ae2e5-2603-4d64-af76-d4bc5a8ec0e5 \
   -s 3,virtio-blk,./uosFC.img \
   -s 4,virtio-console,@stdio:stdio_port \
   $pm_channel $pm_by_vuart \
   --ovmf /usr/share/acrn/bios/OVMF.fd \
   hard_rtvm



Thanks !

**Comment by fuzhongl** [comment]
@paspndevops  Could you please share RT kernel version?
Thanks!

**Comment by fuzhongl** [comment]
Closed since it can't be reproduced with latest code and no feedback long time.
