### ISSUE TITLE
devicemodel: refactor CMD_OPT_LAPIC_PT case branch

### ISSUE THREAD

**Issue by bigdata-memory** [projectacrn/acrn-hypervisor#4283]
There is no "break" to prevent the CMD_OPT_LAPIC_PT case branch to the next case, that is intended but it is better to refactor this case branch to add "break" and explicitly enable its dependent option RTVM at the same place. I also think, the user should be aware of that dependency when they use option LAPIC but not specify the option RTVM.
if this dependency is not documented, I think the best way is to exit when user do not use both of these options at same time.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5884
