### ISSUE TITLE
PCID virtualization support

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#4296]
Guest OS kernels, like Linux kernel, enabled Kernal Page Table Isolation (KPTI) as the mitigation of Meltdown.Enabling KPTI without the support of PCID will cause significant performance loss when user/kernel space switch is frequent.This patch series passes-through PCID capabilities to guest VM.

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5952

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.
