### ISSUE TITLE
Where is project version maintained?

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#430]
The project version seems to be stored in at least two places: the Makefiles for hypervisor and devicemodel both define a MAJOR_VERSION, MINOR_VERSION, and RC_VERSION and the top-level Makefile does not.

The project version should be maintained in one place (maybe an include file called ``version.mk`` at the top level that each of the lower-level Makefiles include with ``include ../version.mk``).

**Comment by zhujun74** [comment]
It is good ides.for reason of hyperviser cpncerned lots OS&Hardware.Specfic Plarform should be included.

**Comment by jren1** [comment]
Thanks, good proposal. I will follow up.

**Comment by mwang106** [comment]
Now project version maintained in acrn-hypervisor/VERSION
