### ISSUE TITLE
Failed to ping when VxWorks passthru network.

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#4313]
HW/Board
WHL
Steps
Hypervisor_Passthrough_Ethernet_to_VxWorks

Expected result
Can ping ok
Actual result
Failed to ping

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5958

**Comment by fuzhongl** [comment]
Fixed in v2.3.
