### ISSUE TITLE
[WHL][Function][WaaG] Run case "OpenCL2.0 Basic GPU" fail on WHL

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#4318]
Environment:
Hardware Board:  WLK
Clear Linux version:31470
GFX driver version: 7323
Waag Link: 
 Reproduce steps:
1. Boot up SOS 
2. Launch Waag
3. Copy opencl2.0  packages into WaaG C:
4. Open opencl2.0 folder,and open "cmd.exe"
5.  Execute the command "basic\test_basic64.exe gpu"
Current result:
Run case "OpenCL2.0 Basic GPU"  fail on WHL
Expected result:
This test case can run passed, display "passed 116 of 116 tests"

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5623

**Comment by fuzhongl** [comment]
No this issue for GVT-d.
