### ISSUE TITLE
[Document] Build cmd error in "Build the ACRN User VM PREEMPT_RT Kernel in Docker" document

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#4322]
Build the ACRN User VM PREEMPT_RT Kernel in Docker

For the Docker image built from Dockerfile, use this command to build ACRN:
$ cp x86-64_defconfig .config $ docker run -u`id -u`:`id -g` --rm -v $PWD:/workspace \ acrn/clearlinux-acrn-builder:latest \ bash -c "make clean && make olddefconfig && make && make modules_install INSTALL_MOD_PATH=out/" 
this cmd is incorrect, should be deleted acrn/ in "acrn/clearlinux-acrn-builder:latest "

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-5995

**Comment by gvancuts** [comment]
Good catch! See #4331
