### ISSUE TITLE
The "Using SDC mode on the NUC" tutorial is broken

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#4359]
The [Using SDC Mode on the NUC](https://projectacrn.github.io/latest/tutorials/kbl-nuc-sdc.html) tutorial is broken, in at least a couple of places:
- Link to Clear Linux OS installer is no longer valid: https://download.clearlinux.org/releases/31470/clear/clear-31470-live-server.iso.xz
- Link to Clear Linux OS installation guide is no longer valid: https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install-server

**Comment by fuzhongl** [comment]
@gvancuts  this issue is fixed.
