### ISSUE TITLE
doc build dependencies missing in CI environment

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#438]
Building documentation was recently included into the CI tests, but the dependencies for document building aren't set up in the CI environment.

```
make -C /workspace/acrn-hypervisor-premerge-build-nuc/acrn-hypervisor/doc html BUILDDIR=/workspace/acrn-hypervisor-premerge-build-nuc/acrn-hypervisor/build/doc
make[1]: Entering directory '/workspace/acrn-hypervisor-premerge-build-nuc/acrn-hypervisor/doc'
make[1]: [Makefile:52: html] Error 2 (ignored)

New errors/warnings found, please fix them:
==============================================

Warning: sphinx_rtd_theme missing. Use pip to install it.

Extension error:
Could not import extension breathe (exception: No module named 'breathe')
make[1]: Leaving directory '/workspace/acrn-hypervisor-premerge-build-nuc/acrn-hypervisor/doc'
```

Doc build dependencies are documented in https://projectacrn.github.io/latest/howtos/process/docbuild.html#installing-the-documentation-tools

Are the CI environment configuration files checked into GitHub somewhere? (They should)  How do we update the CI environment?

**Comment by NanlinXie** [comment]
This issue is fixed now and CI could check document build.

**Comment by NanlinXie** [comment]
@dbkinder , Could you help to close this issue?

**Comment by dbkinder** [comment]
doc build is now part of PR checking by the CI, so we can close this issue.
