### ISSUE TITLE
Introduce SR-IOV feature for ACRN

### ISSUE THREAD

**Issue by liuyuan-GitHub** [projectacrn/acrn-hypervisor#4433]
SR-IOV(single root input/output virtualization) can isolate PCIe devices and
make the devices to have good performance, close to bare-metal. The SR-IOV
consists of two basic units, one is called PF(Physical Function) that supports
SRIOV PCIe extended capability and manages entire physical device, another is
called VF (Virtual Function) and is a "lightweight" PCIe function which is meant
to be given to a VM as a pass-through device. For more details, please refer to
PCI Express Base Specification Revision 4.0 Chapter 9.

[External_System_ID] ACRN-5933

**Comment by ClaudZhang1995** [comment]
[External_System_ID] ACRN-5933

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-5933
