### ISSUE TITLE
need to support 64bit BAR pt device for pre-launched VM

### ISSUE THREAD

**Issue by jsun26intel** [projectacrn/acrn-hypervisor#4458]
currently vbar addr of pci_devices.h is 1:1 map to pbar addr, this would cause pass through failed for a device which has big 64bit BAR addr (i.e > 4GB) in pre-launched VM.

**Comment by jsun26intel** [comment]
[External_System_ID] ACRN-6075

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.
