### ISSUE TITLE
doc: broken link to AGL release image

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#4504]
Our AGL-VMS tutorial (https://projectacrn.github.io/latest/tutorials/agl-vms.html) references an old AGL release image version 6.0.2 that's no longer available to download. 

Perhaps this 6.05 version will still work, but we need verification from ACRN engineering/QA: https://mirrors.edge.kernel.org/AGL/release/flounder/6.0.5/intel-corei7-64/deploy/images/intel-corei7-64/agl-demo-platform-crosssdk-intel-corei7-64-20200304031825.rootfs.wic.xz

**Comment by fuzhongl** [comment]
@NanlinXie With Limited resource; Do we still need to maintain this kinds of Doc?
Thanks!

**Comment by dbkinder** [comment]
@NanlinXie Should we drop this Automotive Grade Linux (AGL) documentation for ACRN?

**Comment by gvancuts** [comment]
Let's drop it for now. If someone gets around to validating this again with a newer version, we can always resurrect it at that point.

**Comment by kiendinh** [comment]
Somehow the AGL folks has replaced the old 6.0.2 release image with the newer one created on March 2020. The new link for the "hopefully the same" image is:

https://mirrors.edge.kernel.org/AGL/release/flounder/6.0.2/intel-corei7-64/deploy/images/intel-corei7-64/agl-demo-platform-crosssdk-intel-corei7-64-20200318141526.rootfs.wic.xz

**Comment by dbkinder** [comment]
Fixed in #4973
