### ISSUE TITLE
doc: UP2 kit listed in an SBL tutorial is no longer available (broken link)

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#4505]
The UP2 Kit N3350 link (https://up-shop.org/up-boards/94-up-squared-celeron-duo-core-4gb-memory32gb-emmc.html) in the SBL tutorial (https://projectacrn.github.io/latest/tutorials/using_sbl_on_up2.html) is broken because that kit is no longer available.  What's the appropriate replacement?

Note also that the N3350 Kit is listed as supported hardware in https://projectacrn.github.io/latest/reference/hardware.html and also referenced in another tutorial (but without a link): https://projectacrn.github.io/latest/tutorials/using_partition_mode_on_up2.html

**Comment by fuzhongl** [comment]
fixed with new link.
