### ISSUE TITLE
HV: add support for VT-d Posted Interrupts

### ISSUE THREAD

**Issue by donsheng** [projectacrn/acrn-hypervisor#4506]
If VT-d Posted interrupts are supported by the platform , hypervisor shall be able to use it to deliver interrupts directly to partitions

Enable VT-d posted interrupts for eligible platforms such as ANL, if vt-d posted interrupt is detected and vm-config is set to use vt-d posted interrupt, pt devices for that vm will use vt-d posted interrupt to deliver interrupts to guest without vm-exits, which can improve performance for the pt devices.

[External_System_ID] ACRN-6085

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-6085

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.
