### ISSUE TITLE
acrn-config: fails to import scenario xml files

### ISSUE THREAD

**Issue by ttzeng** [projectacrn/acrn-hypervisor#4522]
ACRN configuration offline tool fails to import the scenario xml files, and throws "Internal Server Error" as the following screenshot:

![server-error](https://user-images.githubusercontent.com/1763431/77313934-b1b4ba00-6d3f-11ea-9176-bbf3d267df41.png)

**Comment by ClaudZhang1995** [comment]
[External_System_ID] ACRN-6164
