### ISSUE TITLE
HV: clean-up some codes 

### ISSUE THREAD

**Issue by qianwang-intel** [projectacrn/acrn-hypervisor#4535]
Clean-up some codes of HV
hypervisor/acpi_parser/dmar_parse.c:
1.removed multiple returns

hypervisor/arch/x86/vtd.c:
1.corrected the return type of some functions,
2.simplified the logic of dmar_wait_completion() and iommu_read64(),
3.renamed some static functions
4.remove some code branches about iommu_domain.is_host and iommu_domain.is_tt_ept
since their values are determined

/hypervisor/include/arch/x86/vtd.h
1.removed the "is_host" and "is_tt_ept" members of struct iommu_domain
since their values are always determined

hypervisor/hw/pci.c
1.renamed some data structures to make them more understandable

**Comment by qianwang-intel** [comment]
[External_System_ID] ACRN-6173

**Comment by NanlinXie** [comment]
Closed with no regression issue.
