### ISSUE TITLE
Reserve space for VMs'  EPT 4k pages after boot

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#4563]
As ACRN prepares to support servers with large amounts of memory
current logic to allocate space for 4K pages of EPT at compile time
will increase the size of .bss section of ACRN binary.

Bootloaders could run into a situation where they cannot
find enough contiguous space to load ACRN binary under 4GB,
which is typically heavily fragmented with E820 types Reserved,
ACPI data, 32-bit PCI hole etc.

**Comment by sainath14** [comment]
[External_System_ID] ACRN-6084

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.
