### ISSUE TITLE
Handle PCI devices with 64-bit MMIO BARs and BAR Base addresses > 4G

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#4586]
Platforms with devices using larger MMIO address spaces typically have MMIO BAR Base address assigned to physical addresses around TBs (Terabyte).
Size of such devices' BAR can go beyond GB (Giga Byte).
This issue tracks changes to hypervisor and acrn-config tool to handle such platforms.

**Comment by sainath14** [comment]
[External_System_ID] ACRN-6084

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.
