### ISSUE TITLE
ACRN needs to support dynamic CPU affinity configuration

### ISSUE THREAD

**Issue by ZideChen0** [projectacrn/acrn-hypervisor#4616]
The statically configured vCPU affinity for post-launched VM in vm_configs[] could be used in different ways:

1. legacy approach: acrn-dm launch post-launched VM without specifying vCPU affinity and hypervisor launches the VM on all the pCPUs that are defined in vm_configs[].
2. the new dynamic configuration: acrn-dm can choose to specify vCPU affinity in the CREATE_VM hypercall, but the new vCPU affinity should be the entire or a subset of the pre-defined pcpu_affinity_bitmap.

**Comment by ZideChen0** [comment]
[External_System_ID] ACRN-6203

**Comment by NanlinXie** [comment]
Patch merged and no regression. Close it.
