### ISSUE TITLE
The `board_parser.py` tool contains a few grammatical mistakes and typos

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#4630]
There are a few grammatical mistakes and typos in the text potentially printed out by the `board_parser.py` [1] tool (as part of the `acrn-config` tool).

[1] https://github.com/projectacrn/acrn-hypervisor/blob/master/misc/acrn-config/target/board_parser.py

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-6257

**Comment by gvancuts** [comment]
The patch has been merged, not sure why it's not clearly displayed in this thread... but closing this bug anyway.
