### ISSUE TITLE
The `acrn-dm` parameters documentation is outdated

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#4732]
The document [1] listing and describing all parameters available to `acrn-dm` has gone out of sync with the actual implementation [2].

There is also an extra parameter still listed in [2] but with no actual implementation.

[1] `doc/user-guides/acrn-dm-parameters.rst`
[2] `devicemodel/core/main.c`

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-6309

**Comment by gvancuts** [comment]
Patch was merged, closing,
