### ISSUE TITLE
improve boot stack usage in CPU booting

### ISSUE THREAD

**Issue by mgcao** [projectacrn/acrn-hypervisor#4738]
The original stack used in CPU booting is: ld_bss_end + 4KB;
    which could be out of the RAM size limit defined in link_ram file.

    So add a specific stack space in link_ram file, and used in
    CPU booting.

**Comment by mgcao** [comment]
[External_System_ID] ACRN-6287

**Comment by NanlinXie** [comment]
Closed with no regression issue.
