### ISSUE TITLE
Need to initialize the PCI_CLASS type of igd_lpc bridge to make Linux GVT-d work

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#4745]
Currently the PCI_CLASS field of igd_lpc bridge is not initialized. In such case the Linux GVT-d fails to detect the hw-platform and it can't work.

**Comment by yakuizhao** [comment]
[External_System_ID] ACRN-6297

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-6297
