### ISSUE TITLE
Config Splitlock Detection to be disable

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#4765]
#AC should be normally enabled for slpitlock detection, however,
    community developers may want to run ACRN on buggy system.
    In this case, CONFIG_ENFORCE_TURNOFF_AC can be used to turn off the
     #AC, to let the guest run without #AC.

**Comment by taoyuhong** [comment]
[External_System_ID] ACRN-6310

**Comment by NanlinXie** [comment]
Closed with no regression issue.
