### ISSUE TITLE
'reboot' dbg cmd in HV shell cannot work

### ISSUE THREAD

**Issue by shuox** [projectacrn/acrn-hypervisor#4817]
Now, the 'reboot' cmd in HV console triggers a 'divide by 0' error. It could work on the platform which enabled watchdog, but cannot reboot the platform without watchdog enabled. 

Use 'reset_host' directly to reboot the platform.

**Comment by wenlingz** [comment]
Please add JIRA

**Comment by shuox** [comment]
[External_System_ID] ACRN-6370
