### ISSUE TITLE
dm: bzimage: dynamically adapt to ramdisk size

### ISSUE THREAD

**Issue by tttech-industrial-buchsbaum** [projectacrn/acrn-hypervisor#4840]
Using images with ramdisks > 4MB with `acrn-dm -r <ramdisk_file> ...` is not possible. This is required e.g. when using ramdisk based systems, as I used for RT-VM tests to avoid using virtio-blk device thus ruling out any influence on RT behavior. These ramdisks contain an entire Linux system and tend to be rather large, up to 128MB and above.
Other than making the size configurable, which still does not avoid the need to rebuild the devicemodel when ramdisks change, we can solve this by adapting to the ramdisk size dynamically. Thus the supported ramdisk size only depends on the memory available.
This is also one of the patches used in #4833.

**Comment by fuzhongl** [comment]
[External_System_ID] ACRN-6381
