### ISSUE TITLE
dm: acpi: validate minimal length of PSDS

### ISSUE THREAD

**Issue by tttech-industrial-buchsbaum** [projectacrn/acrn-hypervisor#4846]
My Kontron COMe-mAL10 E2 base industrial PC provides the following PSDS table:

```
root@kontron:~# hd /sys/firmware/acpi/tables/PSDS
00000000  50 53 44 53 4d 00 00 00  01 0d 49 4e 54 45 4c 20  |PSDSM.....INTEL |
00000010  45 44 4b 32 20 20 20 20  05 00 00 00 49 4e 54 4c  |EDK2    ....INTL|
00000020  0d 00 00 01 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  49 4e 54 45 4c 20 20 20  |........INTEL   |
00000040  20 20 20 20 20 20 20 20  00 00 03 00 20           |        .... |
0000004d

```
The length of this table of 77 byte contradicts the needs of acrn-dm's ACPI code, which accesses a PSDS table up to offset 79. Since I could not find any information about a PSDS ACPI table in ACPI Specification v6.3 (Jan 2019) or anywhere else on the internet, I cannot judge if Kontron's table is still meaningful. I simply rely on the ACPI code given in acpi.c, so this optional table is too short and has to be rendered invalid. Adding a simply table length check can achieve this. Probably we should also add a link to where the PSDS table is defined.

This is also one of the patches used in #4833.

**Comment by fuzhongl** [comment]
[External_System_ID] ACRN-6381
