### ISSUE TITLE
Inter-VM communication for post-launched VMs

### ISSUE THREAD

**Issue by liuyuan-GitHub-zz** [projectacrn/acrn-hypervisor#4853]
The hypervisor and device model shall provide inter-VM communication method for specific post-launched VMs, which shall expose to guest as a PCI-based device, and the communication shall be based on shared memory.

The device model should help to organize the PCI device resource which include its share memory allocation.

[External_System_ID]ACRN-6392

**Comment by wenlingz** [comment]
[External_System_ID]ACRN-6392

**Comment by NanlinXie** [comment]
Closed with no regression issue.
