### ISSUE TITLE
ARINC 653 support

### ISSUE THREAD

**Issue by amirkazemi94** [projectacrn/acrn-hypervisor#4871]
support acrn arinc 653 standard?

**Comment by fuzhongl** [comment]
@amirkazemi94 Could you please say more info about arinc 653 standard?
@terryzouhao  Could you please answer this question?

**Comment by lygstate** [comment]
He is talking about VxWorks 653

**Comment by fuzhongl** [comment]
@lygstate Thanks for your information.
Yes, ACRN supports VxWorks 653 as User VM, Please check with engineer of VxWorks since VxWorks isn't open source project.
