### ISSUE TITLE
Need support Kernel cmdline configured in Grub in direct mode

### ISSUE THREAD

**Issue by jsun26intel** [projectacrn/acrn-hypervisor#4885]
The VM kernel bootargs for pre-launched VMs and direct boot mode of SOS VM are built-in hypervisor binary so end users have no way to change it. Need a option that support Kernel cmdline configured in Grub. This would bring convenience to end users.

**Comment by jsun26intel** [comment]
[External_System_ID] ACRN-6351

**Comment by NanlinXie** [comment]
Close with test passed.
