### ISSUE TITLE
ACRN Config tool: launch_generic_linux() function call is missing in the generated launch script for VM3

### ISSUE THREAD

**Issue by vmurthy-intel** [projectacrn/acrn-hypervisor#4901]
Issue: 
In master branch; after running the “launch_cfg_gen.py” to generate launch scripts for 3 or more VMs, in the generated launch script for VM3 and above there is **NO** “launch_generic_linux()” call with appropriate parameters at the end of the script.
Please check the attached [launch_uos_id3.txt](https://github.com/projectacrn/acrn-hypervisor/files/4738527/launch_uos_id3.txt) launch script file, at the end of the script there is **NO** function call “launch_generic_linux()” with appropriate parameters.
This is needed since in our current setup the third user VM is Generic linux.

**Comment by liuwei987** [comment]
[External_System_ID] ACRN-6421
