### ISSUE TITLE
acrn Config Tool: Issue with & character in <BASE_BOARD_INFO> section

### ISSUE THREAD

**Issue by maschweik** [projectacrn/acrn-hypervisor#4916]
Expected Behavior:
Output of the board_parser.py script could be imported in to ACRN config app, like described in https://projectacrn.github.io/latest/tutorials/acrn_configuration_tool.html

Actual Behavior:
ACRN config app reports an error “ Error on parsing Board info check the xml syntax …”

Problem:
The issue is related to the “&” character in the Manufacturer Name  attribute of the BASE BOARD Info section. 

     <BASE_BOARD_INFO>
     Base Board Information
     Manufacturer: xyz  GmbH & Co. KG
     Product Name: xyz
     Version: v1
     </BASE_BOARD_INFO>

Wouldn’t it improve the user experience if we either fix this directly in the board_parser by adding  escape string &amp; or better point to the line which causes the problem?

**Comment by fuzhongl** [comment]
Fixed in v3.0
