### ISSUE TITLE
1.61 industry images 404 error

### ISSUE THREAD

**Issue by TSYS-RTOS** [projectacrn/acrn-hypervisor#4918]
All images for industry 1.61 are not found. 
Example: # wget https://github.com/projectacrn/acrn-hypervisor/releases/download/acrn-2020w18.4-140000p/sos-industry-33050.img.xz responds with 404 file not found.

**Comment by gvancuts** [comment]
Thanks for the report @TSYS-RTOS !

I have submitted #4922 to fix this.

@NanlinXie @dbkinder , should this be backported to the v1.6.1 tag/release?

**Comment by dbkinder** [comment]
Updates the 1.6.1 documentation with the same fix: https://github.com/projectacrn/acrn-hypervisor/pull/4923

**Comment by gvancuts** [comment]
Both patches were merged. Closing this issue.
