### ISSUE TITLE
SOS Kernel crash NULL pointer dereference with HV 1.6.1 

### ISSUE THREAD

**Issue by cheeyanglee** [projectacrn/acrn-hypervisor#5021]
observed  kernel crash while running glmark2 on NUC7i7DNH1E

**ACRN Hpervisor  v1.6.1** [commit id: 3c64d59a18240637153942df5f647fed85ea69ac]
**Linux-intel v5.4.46** [Commit id: 3c038f1968310a1d08245b5f1a550e4e0e06d25d ]

**Cmdline :** 
LABEL=Boot root=PARTUUID=27b590ac-08ca-4ae6-b0d8-cd9487cba2ff  rootfstype=ext4  rootwait console=ttyS0,115200 console=tty0 hvlog=2M@0x1FE00000  i915.enable_gvt=1 i915.nuclear_pageflip=1 i915.avail_planes_per_pipe=0x01010F i915.domain_plane_owners=0x011111110000 i915.domain_scaler_owner=0x011100

**Hypervisor version :**
HV version 1.6-2020-07-02 16:23:44-3c64d59a1-dirty DBG (daily tag:acrn-2020w18.4-140000p)

**Crash log:**
BUG: kernel NULL pointer dereference, address: 0000000000000848
#PF: supervisor write access in kernel mode
#PF: error_code(0x0002) - not-present page
PGD 0 P4D 0 
Oops: 0002 [#1] PREEMPT SMP PTI
CPU: 1 PID: 579 Comm: glmark2-es2 Tainted: G     U  W         5.4.46-linux-intel-acrn-sos #1
Hardware name: Intel(R) Client Systems NUC7i7DNHE/NUC7i7DNB, BIOS DNKBLi7v.86A.0056.2018.1003.1622 10/03/2018
RIP: 0010:gen8_emit_flush_render+0x16c/0x190
Code: 79 00 00 48 3d 00 f0 ff ff 0f 86 78 ff ff ff e9 29 ff ff ff be 0c 00 00 00 e8 30 79 00 00 48 3d 00 f0 ff ff 0f 87 13 ff ff ff <48> c7 40 08 00 00 00 00 48 83 c0 18 48 c7 40 f8 00 00 00 00 48 c7
RSP: 0018:ffffb6f4418aba00 EFLAGS: 00010203
RAX: 0000000000000840 RBX: 0000000000344c1c RCX: 0000000000003f90
RDX: 0000000000000870 RSI: 00000000000000e0 RDI: ffff9b4d8ca24000
RBP: ffffb6f4418aba08 R08: 0000000000000110 R09: ffff9b4d97d33590
R10: 0000000000000000 R11: 000000000000a000 R12: ffff9b4d8ca24000
R13: ffff9b4d8e93c400 R14: ffff9b4d9d566f00 R15: 0000000000000cc0
FS:  00007f82481c3740(0000) GS:ffff9b4da5c80000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 0000000000000848 CR3: 00000002576bc005 CR4: 00000000003606e0
DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Call Trace:
 execlists_request_alloc+0x29/0x40
 __i915_request_create+0x205/0x270
 i915_request_create+0x7b/0xd0
 i915_gem_do_execbuffer+0x919/0x16b0
 ? _raw_spin_unlock+0x16/0x30
 ? unix_stream_read_generic+0x22f/0x8a0
 i915_gem_execbuffer2_ioctl+0xeb/0x3b0
 ? i915_gem_execbuffer_ioctl+0x2c0/0x2c0
 drm_ioctl_kernel+0xae/0xf0
 drm_ioctl+0x228/0x3c0
 ? i915_gem_execbuffer_ioctl+0x2c0/0x2c0
 ? __fget+0x7a/0xa0
 do_vfs_ioctl+0x3f4/0x650
 ? __fget+0x7a/0xa0
 ksys_ioctl+0x67/0x90
 __x64_sys_ioctl+0x1a/0x20
 do_syscall_64+0x4d/0x120
 entry_SYSCALL_64_after_hwframe+0x44/0xa9

**Comment by fuzhongl** [comment]
[External_System_ID] ACRN-6538
