### ISSUE TITLE
life_mngr build error

### ISSUE THREAD

**Issue by ynahum** [projectacrn/acrn-hypervisor#5043]
**Describe the bug**
Trying to build and run the HV according to the github getting started info:
https://projectacrn.github.io/latest/getting-started/building-from-source.html

I’ve built the HV on APL with JunperHill board using the commands as described with BOARD=generic:

make all BOARD=generic SCENARIO=sdc

Used the default configuration as it is created. Managed to open the menuconfig utility but I didn’t change anything in it.
When running 
user@user-Broxton-P:~/yair_wa/acrn-hypervisor$ make FIRMWARE=uefi

it builds but an error is shown:

make[2]: Leaving directory '/home/user/yair_wa/acrn-hypervisor/misc/acrnbridge'
make -C /home/user/yair_wa/acrn-hypervisor/misc/life_mngr OUT_DIR=/home/user/yair_wa/acrn-hypervisor/build/misc/tools
make[2]: Entering directory '/home/user/yair_wa/acrn-hypervisor/misc/life_mngr'
cc -g life_mngr.c -o /home/user/yair_wa/acrn-hypervisor/build/misc/tools/life_mngr -lpthread -g -std=gnu11 -D_GNU_SOURCE -DNO_OPENSSL -m64 -Wall -ffunction-sections -Werror -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fno-strict-aliasing -fno-delete-null-pointer-checks -fwrapv -fpie -fpic  -fstack-protector-strong -Wl,-z,noexecstack -Wl,-z,relro,-z,now -pie 
cp life_mngr.service /home/user/yair_wa/acrn-hypervisor/build/misc/tools/life_mngr.service
x86_64-w64-mingw32-gcc -g life_mngr_win.c -o /home/user/yair_wa/acrn-hypervisor/build/misc/tools/life_mngr_win.exe -Wall -O2 
_**make[2]: x86_64-w64-mingw32-gcc: Command not found
make[2]: [Makefile:43: all] Error 127 (ignored)**_
cp COPYING.MinGW-w64-runtime.txt /home/user/yair_wa/acrn-hypervisor/build/misc/tools/COPYING.MinGW-w64-runtime.txt
make[2]: Leaving directory '/home/user/yair_wa/acrn-hypervisor/misc/life_mngr'
make[1]: Leaving directory '/home/user/yair_wa/acrn-hypervisor/misc'
make -C /home/user/yair_wa/acrn-hypervisor/devicemodel DM_OBJDIR=/home/user/yair_wa/acrn-hypervisor/build/devicemodel DM_BUILD_VERSION= DM_BUILD_TAG= DM_ASL_COMPILER= RELEASE=1
make[1]: Entering directory '/home/user/yair_wa/acrn-hypervisor/devicemodel'
make[1]: Leaving directory '/home/user/yair_wa/acrn-hypervisor/devicemodel'
-e 
ACRN Configuration Summary: 
BOARD = generic              SCENARIO = sdc
-e BUILD type = -e RELEASE
-e Hypervisor configuration is based on:
               Kconfig file:        /home/user/yair_wa/acrn-hypervisor/hypervisor/build/.config;
-e           Others are set by default in:        /home/user/yair_wa/acrn-hypervisor/hypervisor/arch/x86/Kconfig;
VM configuration is based on current code base;

**To Reproduce**
make clean
make all BOARD=generic SCENARIO=sdc
make FIRMWARE=uefi

**Expected behavior**
no error

**Additional context**

**Comment by fuzhongl** [comment]
@ynahum same issue with [4812](https://github.com/projectacrn/acrn-hypervisor/issues/4812)
Will fix in 2.1 release.
Please build with xml for 2.0.
