### ISSUE TITLE
Juniper Hill board build and run

### ISSUE THREAD

**Issue by ynahum** [projectacrn/acrn-hypervisor#5044]
**Describe the bug**
Using APL with Juniper Hill board. 
Tried to build w/ BOARD=generic but I'm not sure it will work.
What configuration should I use for this kind of board. didn't find any info on it.
Also, how to run it exactly once it is built? I saw instructions for Ubuntu w/ industry scenario

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by fuzhongl** [comment]
@ynahum VT-D can't be enabled on Juniper Hill board.

**Comment by ynahum** [comment]
Doesn't it depend on the BIOS version? would it not support VT-D on JuniperHill w/o relation to the BIOS/UEFI?

Thanks.
Yair

**Comment by fuzhongl** [comment]
please update BIOS with VT-D enable option.
