### ISSUE TITLE
The ACRN SOS dmesg log is flooded with DRM error messages

### ISSUE THREAD

**Issue by na3em** [projectacrn/acrn-hypervisor#5047]
**Describe the bug**

- After booting the ACRN SOS, the dmesg console is flooded with error message.
- Error logs are coming from gfx/display pipes.
- We can see these error messages also if there is no eDP display connected
- The issue does not occur if we use the ACRN kernel (based on 4.19).
- The issue occurs with linux-intel-acrn kernel (Linux intel-corei7-64 5.4.46-linux-intel-acrn-sos).
- Issue resolved when SOS is not assigned to pipe A or B (i915.avail_planes_per_pipe=0x010000 and i915.domain_plane_owners=0x000022221111)
- The issue is also observed when changing the SOS display configuration on the fly.
- The issue is observed only for certain monitors (Ex: 12'' automotive display at the HDMI output or with two big displays HP EliteDisplay E232, using two HDMI cables, with one DP-to-HDMI adapter).

**To Reproduce**
1. Build using meta-acrn industrial scenario.
2. Use Yocto based SOS with Linux Intel-corei7-64 5.4.46-linux-intel-acrn-sos
3. Change i915 configurations on the fly or use one of the mentioned monitor types.

**Expected behavior**
In a normal scenario, the dmesg shouldn't be flooded with this error.

**Additional context**
dmesg errors: 

[  278.508985] [drm:gen8_de_irq_handler] ERROR Fault errors on pipe B: 0x00000080
[  278.524843] [drm:gen8_de_irq_handler] ERROR Fault errors on pipe B: 0x00000080
[  278.525649] [drm:gen8_de_irq_handler] ERROR Fault errors on pipe B: 0x00000080

**Comment by na3em** [comment]
[External_System_ID] ACRN-6554

**Comment by fuzhongl** [comment]
@na3em  Do you still have issue with v2.2?

**Comment by fuzhongl** [comment]
Closed since no feedback for long time.
