### ISSUE TITLE
Refine status transition of thread object

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#5057]
Thread object's status is changed without context switch done. This is
not accurate. Move the status transition after context switch to make it
more accurate.

Also move kick_thread() logic from schedule framework to vcpu layer,
because it's more about vcpu notification which has less relevant with
scheduling.

**Comment by wenlingz** [comment]
@conghuic23  please add JIRA

**Comment by conghuic23** [comment]
[External_System_ID]ACRN-6561
