### ISSUE TITLE
Build and install from source failed.

### ISSUE THREAD

**Issue by bem-nrl** [projectacrn/acrn-hypervisor#510]
Hardware: NUC Kit NUC6CAYH with 8G Memory and 128G SSD

Installed Clearlinux successfully using clear-23270-installer.img

EFI state with a working Clearlinux install looks like this:
![screen shot 2018-06-27 at 9 14 41 am](https://user-images.githubusercontent.com/40635569/41979879-1bfb6f0e-79f3-11e8-940b-a9feb563dd0b.png)

Followed instructions for building ACRN from Source within
https://projectacrn.github.io/latest/getting_started/index.html

After successfully building ACRN I did a **make install**

Followed instructions to Add ACRN hypervisor to EFI partition.

EFI state after doing this looks like this:
![screen shot 2018-06-27 at 9 36 28 am](https://user-images.githubusercontent.com/40635569/41980255-05d2d50e-79f4-11e8-931b-0c68c5134807.png)

Reboot and select **The ACRN Service OS**

System does not boot, and won't come up regardless of which selection from EFI boot menu.

Please advise.

Many thanks.

**Comment by gvancuts** [comment]
Hi @bem-nrl , can you check the following for us please?
* Bios version (I believe we tested version 0047 mostly)
* What does it say if you drop to a shell and run the `acrn.efi` manually?
* Do you have VT enabled in the bios?

**Comment by bem-nrl** [comment]
Hi @gvancuts , thanks for the rapid response.

My Bios version is 0050 and VT is enabled in BIOS.

When running **acrn.efi** manually from a shell the EFI boot menu appears, just as in a normal boot.
However, just like before no matter what I select the machine does not boot.

**Comment by bem-nrl** [comment]
Hi @gvancuts , thanks for the rapid response.

My Bios version is 0050 and VT is enabled in BIOS.

When running acrn.efi manually from a shell the EFI boot menu appears, just as in a normal boot.
However, just like before no matter what I select the machine does not boot.

--

Respectfully,

**Comment by gvancuts** [comment]
Thanks for the feedback @bem-nrl , we'll need to test this on our side. It looks to me like you're doing all the right stuff so there may be something specific with that Bios version or that version of Clear Linux. If you want to try a couple of more things, I would try a different version of Clear Linux or the latest bios.

@ttzeng , would you be able to test this?

**Comment by ttzeng** [comment]
@bem-nrl I am also using NUC6CAYH but with BIOS 0047, Clear 23100, I can boot to the Service OS. Before I setting up Clear 23100 in my side, would you clarify what did you mean by "However, just like before no matter what I select the machine does not boot."? You should have two systemd.boot entries, what if you select `fs0:\EFI\org.clearlinux\loaderx64.efi` in the UEFI shell, and select the `native` kernel to boot from, would you be able to boot into the Clear rootfs? If yes, then at least the SOS rootfs part is OK, perhaps you can boot the `acrn.efi` included in the original image, instead of using the binary built by yourself, and see any difference? I'll get back to you whether Clear 23270 kernel work in my side.

**Comment by ttzeng** [comment]
@bem-nrl Clear 23270 also works for me, so the discrepancies left are (1) BIOS version, (2) `acrn.efi` executable.

**Comment by bem-nrl** [comment]
@ttzeng my machine is no longer in the state that it was in at time of query.  I think that my EFI partition is all messed up now.  Assuming all the files are where they should be what would be the commands needed to rebuild my EFI partition manually?

Does anyone there have a development disk image with the ACRN source and booting up ACRN which was installed from that source directly for the NUC hardware that they can share?

Many thanks for help.

**Comment by ttzeng** [comment]
@bem-nrl one kernel setting in `acrn.conf` you might need to check: I changed `i915.enable_initial_modeset` to 0, though the default setting is 1.

**Comment by bem-nrl** [comment]
Great!  Thanks @ttzeng.  I'll give that a try when I can.

**Comment by gvancuts** [comment]
Hi @bem-nrl , can you close this issue (assuming the problem has been resolved)? Thanks!

**Comment by bem-nrl** [comment]
This issue was not resolved.  However, it was overtaken by events. I have not had time to continue working on this, nor will I have time in the near future.  Closing it would be fine with me.
