### ISSUE TITLE
- [question] it's possible to run ACRN with VirtualBox Ubuntu/Debian SOS? - 

### ISSUE THREAD

**Issue by ionutnechita** [projectacrn/acrn-hypervisor#5109]
**Describe the feature**
Hi ACRN Team,

My idea is to start an SOS in the VirtualBox.
How can i do this?
Is this possible?

Thanks.

**Comment by fuzhongl** [comment]
@ionutnechita 
It's possible, but we did not try it.
We support run ACRN on qemu:
https://projectacrn.github.io/latest/tutorials/acrn_on_qemu.html
