### ISSUE TITLE
 dm: support to provide ACPI SSDT for UOS

### ISSUE THREAD

**Issue by lonzoc** [projectacrn/acrn-hypervisor#5148]
SSDT is a continuation of the DSDT, those device belonging to sepcific board should better been add to SSDT.
    
We can describe devices in a SSDT ASL file, compile the SSDT asl file using ACPI compiler(e.g. iasl) before passing it to acrn-dm by --acpi_ssdt parameter, then dm will combine it with other ACPI tables.

**Comment by fuzhongl** [comment]
[External_System_ID] ACRN-5149
