### ISSUE TITLE
Boot UOS failed with USB3.0 mediator Enabled

### ISSUE THREAD

**Issue by Ragnarliu** [projectacrn/acrn-hypervisor#5172]
Bug detailed description:
-------------
Boot UOS failed with USB3.0 mediator

Reproduce steps:

Boot to HV and SOS
insert USB3.0 disk on USB3.0 port
boot UOS with USB mediator:  "-s 7,xhci,3-4,3-8,4-2:log=D \"
check USB3.0 disk can work in UOS

[External_System_ID] ACRN-6598

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-6598

**Comment by wenlingz** [comment]
@Ragnarliu  please add [External_System_ID] ACRN-6598 separately next time
