### ISSUE TITLE
Remove the de-privileged boot mode support

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#5197]
De-privileged boot mode was used with Clear Linux SOS, it de-privilege UEFI execution environment from native to Service VM non-root mode, but must ensure any hardware resource touched by UEFI FW before de-privilege must keep the same configuration after boot to service VM. It brings lots of scalability issues when porting ACRN to new platforms. 

Another reason is for hybrid mode support - as de-privileged UEFI environment in service VM still keep the whole HW resource's view, so it's not applicable for hybrid mode support as there is pre-launched VM which will pre-allocate some HW resources from service VM.

Thus ACRN plans to remove the de-privileged mode support and turn to direct boot mode.

**Comment by ZideChen0** [comment]
[External_System_ID] ACRN-6487

**Comment by gvancuts** [comment]
@NanlinXie , how do we know when this is done (both from a code and documentation perspective)?

Just for the record, here is one paragraph that should update: https://projectacrn.github.io/latest/developer-guides/hld/hld-security.html#verified-boot-sequence-with-uefi
