### ISSUE TITLE
[UPsquared N3350 board] Solution to Bootloader issue

### ISSUE THREAD

**Issue by starmachine24** [projectacrn/acrn-hypervisor#5215]
Hi

We managed to figure out a solution to a problem related to the UEFI not saving the bootorder on the UPsquared board. We found this solution in the BIOS setting for our board which is a N3350, so we don't know if this works on the other UPsquared boards. 

Anyway, the solution was to go into the BIOS for the system and then go over to the Boot section. Then go into the **UEFI harddisk drive BBS priorities** and switch the top most alternative with the Hypervisor boot option. This has worked for us on version acrn-2019w35.1-140000p and 2.0.

**Comment by gvancuts** [comment]
I will try this on my board soon as it has affected me too for a while, thanks for sharing the tip!! :+1:

**Comment by starmachine24** [comment]
no problem
