### ISSUE TITLE
Hypervisor P2SB Bridge Passthrough

### ISSUE THREAD

**Issue by donsheng** [projectacrn/acrn-hypervisor#5221]
For ACRN partitioning or hybrid configurations, there shall be support of direct assignment of P2SB bridge to one pre-launched safety VM. Access to the P2SB bridge from the Service VM shall be blocked.
Also perform some cosmetic fix

[External_System_ID]ACRN-6450

**Comment by wenlingz** [comment]
[External_System_ID]ACRN-6450

**Comment by NanlinXie** [comment]
Closed with no regression issue.
