### ISSUE TITLE
acrn-config: refinement for CAT/MBA and upload configuration source

### ISSUE THREAD

**Issue by donsheng** [projectacrn/acrn-hypervisor#5229]
Fix the following issue:
SBL boot HV fail with error: "Unhandled exception: 13 (General Protection)"

And:
Keep XML <-> source code aligned
Upload configuration source code for:
    Board               scenarios
    whl-ipc-i5          industry, hybrid, hybrid_rt, logical_partiton
    whl-ipc-i7          industry, hybrid, hybrid_rt, logical_partiton
    ehl-crb-b           industry, hybrid, hybrid_rt, logical_partition
    nuc7i7dnb           industry, hybrid, logical_partition

[External_System_ID]ACRN-6643

**Comment by wenlingz** [comment]
[External_System_ID]ACRN-6643
