### ISSUE TITLE
add vmexit data sampling in HV for branch v2.0

### ISSUE THREAD

**Issue by mgcao** [projectacrn/acrn-hypervisor#5232]
in HV, to sample vmexit data as per-pCPU and per-vCPU

    this feature is used to sample vmexit data as per physical CPU
    and per virutal CPU of VM, command used in HV console as following:
      1. vmexit clear --> to clear current vmexit buffer
      2. vmexit -->output current vmexit info

**Comment by wenlingz** [comment]
@mgcao please add JIRA ID, thanks

**Comment by mgcao** [comment]
[External_System_ID] ACRN-7353
