### ISSUE TITLE
hv: support PIO access to platform hidden devices

### ISSUE THREAD

**Issue by stanleyintel** [projectacrn/acrn-hypervisor#5257]
Some kernel drivers (e.g., Intel ICH LPC) will access platform hidden device thru PIO. Because the platform hidden device is not an available vdev, it will result in HV reports the PCI device is not found.

[External_System_ID] ACRN-6670

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-6670

**Comment by NanlinXie** [comment]
Patch merged and verified.
