### ISSUE TITLE
Doc: Need update FAQ document for some tips.

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#5265]
Need update FAQ document including:
1.  Trouble shooting for issues
2.  Some Tips from customer support.

**Comment by dbkinder** [comment]
@NanlinXie @fuzhongl @gvancuts Where can we get material to update this FAQ?  Alternatively, we should delete it (or just empty out what's there) since it's not very useful or even wrong (e.g, no more ``make menuconfig``).

**Comment by gvancuts** [comment]
I would remove this section entirely for now. Half of it is plain outdated and the other half is of limited value in my opinion, the most relevant entry in there in for me is the explanation as to why many things are static in ACRN. So if we want to keep the FAQ, let's use that entry and say a little more than that. It's not just memory size, but also the fact many things are hard-coded such as number of VMs that can be run, etc.

Other good candidates to be put in there would be questions about governance, membership once these things are established.

**Comment by dbkinder** [comment]
@NanlinXie @gvancuts If we're not going to keep an FAQ doc updated, I propose we should delete it, right?
