### ISSUE TITLE
Doc: Improvement for GSG

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#5378]
Address @gvancuts  comment in PR
https://github.com/projectacrn/acrn-hypervisor/pull/5365

**Comment by gvancuts** [comment]
To summarize the key points of my comments:
- Let's not rename remote branches when we provide instructions to check them out, i.e. let's simply use `git checkout release_2.2` (without the `-b v2.2` option that we currently use)
- We need to fix the checkout and kernel versions. We instruct the use to check out `release_2.2` from the `acrn-kernel` repo but the kernel version we mention in the doc does not match what's in that branch. We need to make sure these match, and that the instructions match what we tested.
