### ISSUE TITLE
Doc: debian-10.1.0-amd64-netinst.iso is not available in document "Run Debian as the Service VM"

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#5408]
Currently below decription for "Run Debian as the Service VM" is invalid now since there's only 10.6 version in the Debian 10 iso link.  Either change to general description for Debian 10.x version or verify it and update to latest version.

"Navigate to Debian 10 iso. Select and download debian-10.1.0-amd64-netinst.iso (scroll down to the bottom of the page)."

**Comment by gvancuts** [comment]
How about we add a note that indicates which version we tested, adding that the URL may contain newer versions?

**Comment by dbkinder** [comment]
done as Geoffroy suggested.
