### ISSUE TITLE
[TGL] Add pseudo-SRAM support for RTVM (phase-2)

### ISSUE THREAD

**Issue by qianwang-intel** [projectacrn/acrn-hypervisor#5418]
Phase2 of pSRAM support on TGL-U.

1. Added support for single pre-launched RTVM
2. Fixed some problems of phase-1
3. Merge target is now mainline.

**Comment by qianwang-intel** [comment]
[External_System_ID] ACRN-6695

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-6695
