### ISSUE TITLE
Correctly handle EAGAIN in pm_vuart when listening

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#5429]
pm_vuart stops listening and relays the message right away if it encounters EAGAIN during read(). This causes the messages relayed to be fragmented.

Only relay the message when it encounters a null character or a newline character, or when the buffer is full.

**Comment by peterfang** [comment]
[External_System_ID] ACRN-6776

**Comment by NanlinXie** [comment]
Closed with no regression issue.
