### ISSUE TITLE
acrn-dm built-in help needs a light clean-up

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#5445]
A light clean-up is in order in the built-in help for `acrn-dm`. Some options are missing in the top part (where the list is given with no explanation). A couple of options need to be put inside an `#ifdef` statement and a couple of typos were spotted.

**Comment by gvancuts** [comment]
Updated my PR as the typos and `#ifdef` statements are for options that are in fact obsolete, this latest version removes them.

**Comment by wenlingz** [comment]
@gvancuts please add JIRA info, thanks

**Comment by gvancuts** [comment]
[External_System_ID]ACRN-6799

**Comment by gvancuts** [comment]
Patch was merged, closing.
