### ISSUE TITLE
vmei_proc_tx()  the function using data that coming from user buffer without checking the user buffer length

### ISSUE THREAD

**Issue by tomasbw** [projectacrn/acrn-hypervisor#5451]
**Describe the bug**
In  vmei_proc_tx()  the function using data that coming from user buffer without checking the user buffer length, that can cause to read out of bound. 

**Platform**
APL-I, Any apply 

**Codebase**
master 
Need backport to apl_sdc_stable

**Scenario**
Describe the scenario: Hybrid, Industry or logical_partition

**To Reproduce**
In case of misbehaving UOS. The issue discovered after code review. 

**Expected behavior**
Detect memory boundaries crossing 

**Additional context**
Attach the following logs if available:

- native Linux boot kernel message log
- ACRN serial port log (when issues happens)
- Service VM kernel message when issue happens
- acrn-dm log: all files in /var/log/acrn-tm
- console log when running script to launch guest VM

**Comment by wenlingz** [comment]
please add JIRA info, thanks

**Comment by fuzhongl** [comment]
[External_System_ID]ACRN-6829
