### ISSUE TITLE
dm: virtio: paddr_guest2host but the function can return NULL but checks are missing

### ISSUE THREAD

**Issue by tomasbw** [projectacrn/acrn-hypervisor#5452]
**Describe the bug**
`paddr_guest2host()`  may return `NULL`,  and this might be govern by UOS setting. 
T

**Platform**
Any

**Codebase**
maseter

**Scenario**
Describe the scenario: Hybrid, Industry or logical_partition

**To Reproduce**
he major issue is in 
`_vq_record()` helper function which sets `iov_base` 
It will return w/o error even when `paddr_guest2host()` fails. 
This can cause NULL dereferencing in consequent flow.

**Expected behavior**
Fail gracefully when paddr_guest2host returns NULL.

**Additional context**
Attach the following logs if available: N/A

**Comment by fuzhongl** [comment]
[External_System_ID]ACRN-6810

**Comment by NanlinXie** [comment]
Closed with no regression issue.
