### ISSUE TITLE
SBL-compile error

### ISSUE THREAD

**Issue by tomwei666** [projectacrn/acrn-hypervisor#5473]
**Describe the bug**
I want to compile SBL for up2, I compile like this: python3.6 BuildLoader.py build apl

The error log is:

tom@tom-linuxer:~/work/slimbootloader$ python3.6 BuildLoader.py build apl
Using "/usr/bin/python3.6", Version 3.6.9
Using GCC5, Version 7
Using /usr/bin/openssl, Version OpenSSL 1.1.1  11 Sep 2018
Using /usr/bin/nasm, Version NASM version 2.13.02
Using /usr/bin/git, Version git version 2.17.1
Build [apl] ...
SBL_KEY_DIR is set to /home/tom/work/slimbootloader !!
Create FSP component file '/home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/FSP_S.bin'
Create FSP component file '/home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/FSP_M.bin'
Create FSP component file '/home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/FSP_T.bin'
Warning: No 'SlimBootloader.bin' component in image list !
Key used for Singing /home/tom/work/slimbootloader/MasterTestKey_Priv_RSA2048.pem !!
Container 'KEYH' was created successfully at:  
  /home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/KEYHASH.bin
Rebase FSP-T from 0xFFFFF000 to 0xFFFF8000:
  Patched 37 entries in 1 TE/PE32 images.
  Patched 1 entries using FSP patch table.
Rebase FSP-M from 0xFEF71000 to 0xFEF94000:
  Patched 2583 entries in 6 TE/PE32 images.
  Patched 1 entries using FSP patch table.
Rebase FSP-S from 0x00200000 to 0x01055000:
  Patched 34 entries in 2 TE/PE32 images.
  Patched 1 entries using FSP patch table.
Create FSP component file '/home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/FSP_S.bin'
Create FSP component file '/home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/FSP_M.bin'
Create FSP component file '/home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/FSP_T.bin'
2 config binary files were merged successfully!
6 config binary files were merged successfully!
Key used for Singing /home/tom/work/slimbootloader/ConfigTestKey_Priv_RSA2048.pem !!
Config file was signed successfully!
	ASM	Bin/ResetVector.ia32.raw
	FIXUP	Bin/ResetVector.ia32.raw
Build environment: Linux-5.4.0-48-generic-x86_64-with-Ubuntu-18.04-bionic
Build start time: 14:11:18, Nov.05 2020

WORKSPACE        = /home/tom/work/slimbootloader
PACKAGES_PATH    = /home/tom/work/slimbootloader
EDK_TOOLS_PATH   = /home/tom/work/slimbootloader/BaseTools
CONF_PATH        = /home/tom/work/slimbootloader/Conf
PYTHON_COMMAND   = "/usr/bin/python3.6"

Architecture(s)  = IA32
Build target     = DEBUG
Toolchain        = GCC5

Active Platform          = /home/tom/work/slimbootloader/BootloaderCorePkg/BootloaderCorePkg.dsc

Processing meta-data ..## done!
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/StageLib/StageLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/ContainerLib/ContainerLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/CpuExceptionLib/CpuExceptionLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/DebugDataLib/DebugDataLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/LitePeCoffLib/LitePeCoffLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/FspApiLib/FspmApiLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/LoaderPerformanceLib/LoaderPerformanceLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/FspSupportLib/FspSupportLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Platform/ApollolakeBoardPkg/Library/LoaderLib/LoaderLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Platform/ApollolakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/Stage1BSocInitLib/Stage1BSocInitLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/ModuleEntryLib/ModuleEntryLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/DecompressLib/DecompressLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/SecureBootLib/SecureBootLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/BaseXApicLib/BaseXApicLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/DebugAgentLib/DebugAgentLibNull.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/ResetSystemLib/ResetSystemLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/ThunkLib/ThunkLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/TimeStampLib/TimeStampLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/ExtraBaseLib/ExtraBaseLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/ConfigDataLib/ConfigDataLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/SocInfoLib/SocInfoLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/CommonSocPkg/Library/SpiFlashLib/SpiFlashLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/MmcAccessLib/MmcAccessLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Platform/ApollolakeBoardPkg/Library/IocIpcLib/IocIpcLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/RleCompressLib/RleCompressLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/BootGuardLib20/BootGuardLib20.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/CommonSocPkg/Library/HeciLib/HeciLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Platform/CommonBoardPkg/Library/BoardSupportLib/BoardSupportLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/BaseIpcLib/BaseIpcLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/Lz4DecompressLib/Lz4DecompressLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/LzmaCustomDecompressLib/LzmaCustomDecompressLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/MdePkg/Library/BaseRngLib/BaseRngLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/PagingLib/PagingLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/CommonSocPkg/Library/PchSpiLib/PchSpiLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/IoMmuLib/IoMmuLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/Crc32Lib/Crc32Lib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/TpmLib/TpmLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/AcpiTimerLib/AcpiTimerLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/MeChipsetLib/MeChipsetLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/IppCryptoLib/IppCryptoLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/BootloaderCommonLib/BootloaderCommonLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/MdePkg/Library/BasePciLibPciExpress/BasePciLibPciExpress.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/MdePkg/Library/BasePciExpressLib/BasePciExpressLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/MdePkg/Library/BaseLib/BaseLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsic.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/BootloaderCoreLib/BootloaderCoreLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/MemoryAllocationLib/MemoryAllocationLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/BootloaderDebugLib/BootloaderDebugLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/SerialPortLib/SerialPortLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/DebugLogBufferLib/DebugLogBufferLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/ConsoleOutLib/ConsoleOutLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/MdePkg/Library/BaseMemoryLibRepStr/BaseMemoryLibRepStr.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/PcdLib/PcdLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/MdePkg/Library/BasePrintLib/BasePrintLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/DebugPrintErrorLevelLib/DebugPrintErrorLevelLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/GraphicsLib/GraphicsLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/BootloaderLib/BootloaderLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/PlatformHookLib/PlatformHookLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/GpioLib/GpioLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/ScSbiAccessLib/ScSbiAccessLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/HobLib/HobLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/SmbiosInitLib/SmbiosInitLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/FspApiLib/FspsApiLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/HobBuildLib/HobBuildLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/AcpiInitLib/AcpiInitLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/PciEnumerationLib/PciEnumerationLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Platform/ApollolakeBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/Stage2SocInitLib/Stage2SocInitLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/MpInitLib/MpInitLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/IgdOpRegionLib/IgdOpRegionLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/VtdLib/VtdLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/PsdLib/PsdLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Platform/ApollolakeBoardPkg/Library/HdaLib/HdaLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/CommonSocPkg/Library/VtdPmrLib/VtdPmrLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/S3SaveRestoreLib/S3SaveRestoreLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/MdePkg/Library/BaseSynchronizationLib/BaseSynchronizationLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/FirmwareUpdateLib/FirmwareUpdateLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/PcdData/PcdData.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Library/FspApiLib/FsptApiLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Platform/ApollolakeBoardPkg/Library/Stage1ABoardInitLib/Stage1ABoardInitLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Silicon/ApollolakePkg/Library/Stage1ASocInitLib/Stage1ASocInitLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/StringSupportLib/StringSupportLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/LinuxLib/LinuxLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/LiteFvLib/LiteFvLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/PayloadPkg/Library/TrustyBootLib/TrustyBootLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/PayloadPkg/Library/SblParameterLib/SblParameterLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/PayloadPkg/Library/AbSupportLib/AbSupportLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/RpmbLib/RpmbLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/SeedListInfoLib/SeedListInfoLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/MultibootLib/MultibootLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/IasImageLib/IasImageLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/ShellLib/ShellLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/PayloadPkg/Library/PayloadEntryLib/PayloadEntryLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/ElfLib/ElfLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/FileSystemLib/FileSystemLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/PartitionLib/PartitionLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/BootOptionLib/BootOptionLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Platform/ApollolakeBoardPkg/Library/ShellExtensionLib/ShellExtensionLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/ConsoleInLib/ConsoleInLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/SortLib/SortLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/MtrrLib/MtrrLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/PayloadPkg/Library/PayloadSupportLib/PayloadSupportLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/FatLib/FatLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/Ext23Lib/Ext23Lib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/UsbKbLib/UsbKbLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/MediaAccessLib/MediaAccessLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/NvmExpressLib/NvmExpressLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/MemoryDeviceBlockIoLib/MemoryDeviceBlockIoLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/SpiBlockIoLib/SpiBlockIoLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/UfsBlockIoLib/UfsBlockIoLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/UsbBlockIoLib/UsbBlockIoLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/AhciLib/AhciLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/MmcTuningLib/MmcTuningLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/UsbInitLib/UsbInitLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/LiteVariableLib/LiteVariableLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/XhciLib/XhciLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/UsbBusLib/UsbBusLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/PayloadPkg/Library/PlatformHookLib/PlatformHookLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCommonPkg/Library/FullMemoryAllocationLib/FullMemoryAllocationLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/MdePkg/Library/BaseMemoryLibSse2/BaseMemoryLibSse2.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/PayloadPkg/Library/PayloadLib/PayloadLib.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/Platform/ApollolakeBoardPkg/AcpiTables/AcpiTables.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Stage1B/Stage1B.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Stage2/Stage2.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/PayloadPkg/FirmwareUpdate/FirmwareUpdate.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/BootloaderCorePkg/Stage1A/Stage1A.inf [IA32]
make: 对“tbuild”无需做任何事。
Building ... /home/tom/work/slimbootloader/PayloadPkg/OsLoader/OsLoader.inf [IA32]
make: 对“tbuild”无需做任何事。

Fd File Name:STAGE1B (/home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/STAGE1B.fd)

Generate Region at Offset 0x0
   Region Size = 0x14000
   Region Name = FV
#
Generating STAGE1B FV
##
Generate Region at Offset 0x14000
   Region Size = 0x59000
   Region File Name = /home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/FSP_M.bin

Fd File Name:STAGE2 (/home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/STAGE2.fd)

Generate Region at Offset 0x0
   Region Size = 0x55000
   Region Name = FV

Generating STAGE2 FV
###
Generate Region at Offset 0x55000
   Region Size = 0x2B000
   Region File Name = /home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/FSP_S.bin

Fd File Name:STAGE1A (/home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/STAGE1A.fd)

Generate Region at Offset 0x0
   Region Size = 0x2000
   Region File Name = /home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/FSP_T.bin

Generate Region at Offset 0x2000
   Region Size = 0x6000
   Region Name = FV

Generating STAGE1A FV
#######
Fd File Name:OSLOADER (/home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/OSLOADER.fd)

Generate Region at Offset 0x0
   Region Size = 0x4E000
   Region Name = FV

Generating OSLOADER FV

Generating FWUPDATE FV

GUID cross reference file can be found at /home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV/Guid.xref

FV Space Information
STAGE1B [83%Full] 81920 total, 68208 used, 13712 free
STAGE2 [55%Full] 348160 total, 193920 used, 154240 free
STAGE1A [62%Full] 24576 total, 15328 used, 9248 free
FWUPDATE [97%Full] 176128 total, 172128 used, 4000 free
OSLOADER [78%Full] 319488 total, 249760 used, 69728 free
Build report can be found at /home/tom/work/slimbootloader/Report.log

- Done -
Build end time: 14:11:23, Nov.05 2020
Build total time: 00:00:04

Patching STAGE1A
Patched offset 0x00007FFC:[90909090] with value 0xFFFFA000  # Patch BFV
ERROR: Unknown symbol Stage1A:__ModuleEntryPoint !
Error in running process:
  /usr/bin/python3.6 BootloaderCorePkg/Tools/PatchFv.py /home/tom/work/slimbootloader/Build/BootloaderCorePkg/DEBUG_GCC5/FV STAGE1A:STAGE1A 0xFFFFFFFC,            _BASE_STAGE1A_,                    @Patch BFV _OFFS_STAGE1A_,        Stage1A:__ModuleEntryPoint,        @Patch Stage1A Entry _OFFS_STAGE1A_+4,      Stage1A:BASE,                      @Patch Module Base <Stage1A:__gPcd_BinaryPatch_PcdVerInfoBase>,  {3473A022-C3C2-4964-B309-22B3DFB0B6CA:0x1C}, @Patch VerInfo <Stage1A:__gPcd_BinaryPatch_PcdFileDataBase>, {EFAC3859-B680-4232-A159-F886F2AE0B83:0x1C}, @Patch PcdBase 0xFFFFFFF8, {3CEA8EF3-95FC-476F-ABA5-7EC5DFA1D77B:0x1C}, @Patch FlashMap <Stage1A:__gPcd_BinaryPatch_PcdHashStoreBase>, {18EDB1DF-1DBE-4EC5-8E26-C44808B546E1:0x1C}, @Patch HashStore

**Comment by gvancuts** [comment]
hi @tomwei666 , this should be reported to the [SBL project](https://slimbootloader.github.io/). The have mailing list you can use to get help, you can also search through the archives or open a [Github issue](https://github.com/slimbootloader/slimbootloader/issues/new/choose).

I took a very quick look at  your environment and the first thing I spotted is that you may need to you update your GCC to 7.3 min (see https://slimbootloader.github.io/getting-started/build-host-setup.html#running-on-linux).
