### ISSUE TITLE
SBL firmware update error

### ISSUE THREAD

**Issue by tomwei666** [projectacrn/acrn-hypervisor#5478]
**Desccribe the bug**
There is an old sbl in my up2 board!
I compile the sbl and update throug the USB.

Compiling the sbl steps:
1. export SBL_KEY_DIR=/tmp/sbl_key_dir/
2. python3.6 BootloaderCorePkg/Tools/GenerateKeys.py -k $SBL_KEY_DIR
3. python3.6 BuildLoader.py build apl
4. python3.6 Platform/ApollolakeBoardPkg/Script/StitchLoader.py -b sbl.bios.bin -i UPA1AM52.bin -s Outputs/apl/Stitch_Components.zip -o up2_sbl.bin -p 0xAA00000E
ps: My board : up2-N3350, so I download the UPA1AM52.zip BIOS firmware.

Update the sbl firmware steps:
1. Copy up2_sbl.bin to the usb root dir, and rename up2_sbl.bin to FwuImage.bin
2. Enter SBL shell
3. input fwupdate command

The attach update-error.log: update sbl log.
The attach before-update.log: Before updating ,the sbl log.
The sbl in my board version is sbl_up2_ifwi.bin(2019-03-19 20:59) is from acrn daily server.

**Platform**
Product/Kit Name:   UP2-N3350
Memory:  4G
Storage: 32G

**Comment by tomwei666** [comment]
[before-upgrade.txt](https://github.com/projectacrn/acrn-hypervisor/files/5498446/before-upgrade.txt)
[update-error.log](https://github.com/projectacrn/acrn-hypervisor/files/5498447/update-error.log)

**Comment by tomwei666** [comment]
[before-upgrade.txt](https://github.com/projectacrn/acrn-hypervisor/files/5498713/before-upgrade.txt)
[update-error.log](https://github.com/projectacrn/acrn-hypervisor/files/5498714/update-error.log)

**Comment by tomwei666** [comment]
This shoud report to the SBL issue, So I closed this bug!

**Comment by terryzouhao** [comment]
@tomwei666 , actually from slimboot guide: https://slimbootloader.github.io/supported-hardware/up2.html#prerequisites
the 'up2_sbl.bin to FwuImage.bin'  you built from Slimboot source and stitched with APL BIOS (UPA1AM52.bin)  in step4, was full binary/bin and recommended to flash on UP2 board with SPI programmer. 
Step4: python3.6 Platform/ApollolakeBoardPkg/Script/StitchLoader.py -b **sbl.bios.bin** -i UPA1AM52.bin -s Outputs/apl/Stitch_Components.zip -o up2_sbl.bin -p 0xAA00000E

If you want to update slime boot with USB disc (already had workable sbl), you need generate CapsuleFirmware with below command:  python BootloaderCorePkg/Tools/GenCapsuleFirmware.py -k $SBL_KEY_DIR/FirmwareUpdateTestKey_Priv_RSA2048.pem -o FwuImage.bin -b bios.bin
Remember to generate IAS image for fastboot support also, Step 3: Generate IAS image containing fastboot.elf

You can find the detailed GUIDE of "Boot ACRN with SBL here ": https://slimbootloader.github.io/how-tos/boot-acrn.html

sbl_up2_ifwi.bin:  The binary file to be flashed by BIOS flash tool or SPI programmer
FwuImage.bin:    The binary file to be copied to USB flash drive to upgrade SBL from shell command

**Comment by tomwei666** [comment]
./iasimage create -o Platform/ApollolakeBoardPkg/SpiIasBin/iasimage1.bin -d ./BootloaderCorePkg/Tools/Keys/TestSigningPrivateKey.pem -i 0x40000 cmdline.txt fastboot.elf

How to generate the file of TestSigningPrivateKey.pem!

**Comment by tomwei666** [comment]
./iasimage create -o Platform/ApollolakeBoardPkg/SpiIasBin/iasimage1.bin -d ./BootloaderCorePkg/Tools/Keys/TestSigningPrivateKey.pem -i 0x40000 cmdline.txt fastboot.elf

How to generate the file of TestSigningPrivateKey.pem?

**Comment by tomwei666** [comment]
Hi,
 If want to BIOS flash tool to update the SBL firmware, it need to use uefi shell. But my scenario is sbl in up2 already, so cannot use this method!
Brs,
Tom

**Comment by terryzouhao** [comment]
> ./iasimage create -o Platform/ApollolakeBoardPkg/SpiIasBin/iasimage1.bin -d ./BootloaderCorePkg/Tools/Keys/TestSigningPrivateKey.pem -i 0x40000 cmdline.txt fastboot.elf
> 
> How to generate the file of TestSigningPrivateKey.pem?

Yes, There is one commit https://github.com/slimbootloader/slimbootloader/pull/757 that removed 'Keys' folder under Tools. but you can get such keys from older version (before Jun-20) in 'master' or switch to 'Testing' branch.

**Comment by terryzouhao** [comment]
> Hi,
> If want to BIOS flash tool to update the SBL firmware, it need to use uefi shell. But my scenario is sbl in up2 already, so cannot use this method!
> Brs,
> Tom

If first time to update SBL, you can do it from UEFI BIOS shell interface.
If you want to update SBL firmware with newer versions on UP2:
Step 1: Copy '**FwuImage.bin**' onto USB flash drive formatted in FAT32
Step 2: Reset UP2 and press any key to enter shell
Run:
Shell>
Shell> fwupdate
HECI SecMode 0
Group    =00000020
Command  =00000007
IsRespone=00000001
Result   =00000000

BUT,  It is highly recommended to have an SPI programmer in case UP2 is bricked after firmware update.

**Comment by tomwei666** [comment]
Hi,

I want to generate IAS image for fastboot support , I followed the link: https://slimbootloader.github.io/how-tos/boot-acrn.html

The steps I do:
1）mkdir -p Platform/ApollolakeBoardPkg/SpiIasBin
2）touch cmdline.txt
3）chmod 755 ./iasimage
4）sudo pip3 install cryptography==2.2.2 --target=/home/tom/work/slimbootloader
5） ./iasimage create -o Platform/ApollolakeBoardPkg/SpiIasBin/iasimage1.bin -d ./BootloaderCorePkg/Tools/Keys/TestSigningPrivateKey.pem -i 0x40000 cmdline.txt fastboot.elf
note: In SBL master branch ,there is no dir: BootloaderCorePkg/Tools/Keys/. I copy this dir from Testing branch. I compile the code in master branch.

python3.6 BuildLoader.py build apl
python3.6 Platform/ApollolakeBoardPkg/Script/StitchLoader.py -i UPA1AM40.bin -s Outputs/apl/Stitch_Components.zip -o sbl_up2_ifwi.bin -p 0xAA00000E -b bios.bin
python3.6 BootloaderCorePkg/Tools/GenCapsuleFirmware.py -k $SBL_KEY_DIR/FirmwareUpdateTestKey_Priv_RSA2048.pem -o FwuImage.bin -p BIOS bios.bin
When I update FwuImage using USB, I got these error log in attach file of update-error-20201110.txt





[update-error-20201110.txt](https://github.com/projectacrn/acrn-hypervisor/files/5514517/update-error-20201110.txt)

**Comment by terryzouhao** [comment]
@tomwei666 eventually we found a APL UP2 board, and tried your upgrade scenario.
1. yes, current SlimBoot 'Master' and 'Testing' had updated the source code, e.g., deleted 'Keys' folder in Master, and cannot just copy such folder from 'Testing' branch. we even tried build 'Testing' branch, same flash failure/error found. 

2. APL UP2 mainly supported ACRN1.0 acrh, and new features had switched to KBL/WHL/TGL. We didn't try SlimBoot 20' upgrades/versions. So you can try legacy 19' version of slimboot, actually we just verified below version and successfully flashed SBL. Please find detailed steps and let us know if you have any further questions:
**Connect serial adapter between UP2 and the host, enter Shell from host to 'Shell> fwupdate' with 'FwuImage.bin' in USB disck.**
**commit f4f16878abf1162fe22d22ad08c22bb1633a86e1 (HEAD)**
Author: Aiden Park <aiden.park@intel.com>
Date:   Mon Sep 9 14:58:04 2019 -0700

CMD history:
2027  cd $workspace/slimbootloader/
2114  git clean -dfx && git reset --hard && git checkout f4f16878abf1162fe22d22ad08c22bb1633a86e1
2117  cp -r ../iasimage.py ./
2118  cp -r ../fastboot.elf ./
2119  cp -r ../UPA1AM40.zip ./
2120  unzip UPA1AM40.zip
2121  chmod 755 ./iasimage.py
2122  mkdir -p Platform/ApollolakeBoardPkg/SpiIasBin
2123  touch cmdline.txt
2124  chmod 755 ./iasimage.py
2125  ./iasimage.py create -o Platform/ApollolakeBoardPkg/SpiIasBin/iasimage1.bin -d ./BootloaderCorePkg/Tools/Keys/TestSigningPrivateKey.pem -i 0x40000 cmdline.txt fastboot.elf
2126  python BuildLoader.py build apl
2127  python Platform/ApollolakeBoardPkg/Script/StitchLoader.py -i UPA1AM40.bin -s Outputs/apl/Stitch_Components.zip -o sbl_up2_ifwi.bin -p 0xAA00000E -b bios.bin
2129  python BootloaderCorePkg/Tools/GenCapsuleFirmware.py -k ./BootloaderCorePkg/Tools/Keys/TestSigningPrivateKey.pem -o FwuImage.bin -p BIOS bios.bin
2132  cp -r ./FwuImage.bin /media/ssg-hv/CB62-18DB/FwuImage.bin
2133  sync
2134  umount /dev/sdc1

**Comment by tomwei666** [comment]
Shell> fwupdate
HECI SecMode 0
Group    =00000020
Command  =00000007
IsRespone=00000001
Result   =00000000
BtGuard: VB : 0, MB : 0 

============= Intel Slim Bootloader STAGE1A =============
SBID: SB_APLI 
ISVN: 001
IVER: 000.005.001.000.06157
SVER: EDC112328CF3E414
FDBG: BLD(D) FSP(R)
FSPV: ID($APLFSP$) REV(01040301)
Loader global data @ 0xFEF01D54
Run  STAGE1A @ 0xFEF80000
Load STAGE1B @ 0xFEF88000
No BtGuard verification !

============= Intel Slim Bootloader STAGE1B =============
CPU : APL-B1 [2C @ 1100MHz: premium SKU], uCode rev.32
Early GpioInit for EMMC
MMC global data init
Use SDMA instead of ADMA2
MMC Phase 1 init
SpiInstance = FEF034A0
Load EXT CFG Data @ 0xFEF03FC4:0x0C30 ... Success
HASH Verification Success! Component Type (4)
RSA Verification Success!
BOOT: BP0 
MODE: 0
BoardID: 0x0E
PlatformName: UP2
BootPolicy : 0x00000010
Memory Init
Looking for MRC saving data
Read MRC ParamData at 0xFF232000
Decompress ParamData
Read MRC VarData at 0xFF231000
Use slot 57
MRC data was found @ 0xFEF40400(Param) and 0xFEF40000(Var)
Load memory parameters from CfgData.
Load general parameter from CfgData.
Call FspMemoryInit ... Success
Loader global data @ 0x7ABBFD80
Enable Paging ...
Switch to memory stack @ 0x7ABFFF00
Stage1 stack: 0x2000 (0x1684 used)
Stage1 heap: 0x6000 (0x4B70 used)
Call FspTempRamExit ... Success
CSE: FW 3.1.50.2222, VB: 0, MB: 0
CSE: boot dev #2: SPI
  00000000: 43 46 47 44 10 00 00 00-34 00 00 00 80 00 00 00  *CFGD....4.......*
  00000010: 25 00 01 08 FF FF FF FF-05 00 00 00 00 00 00 02  *%...............*
  00000020: 46 77 75 49 6D 61 67 65-2E 62 69 6E 00 00 00 00  *FwuImage.bin....*
  00000030: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  *................*
  00000040: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  *................*
  00000050: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  *................*
  00000060: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  *................*
  00000070: 00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  *................*
MRC: [v0.56.89.20]
Memory FSP @ 0x7AC00000
Memory TOP @ 0x7A074000
HASH Verification Success! Component Type (1)
Loaded STAGE2 @ 0x7AB32000

============= Intel Slim Bootloader STAGE2 =============
Disable Paging ...
245 GPIO entries are populated from Base platform
Programming 245 GPIO entries
Variable region: 0xFF22F000:0x2000
Save MRC Training Data (0x7AC210A0 0x00B2C0) ... 
Save MRC NVS Data
MRC VarData matches data in flash, skip update!
Writing MRC ParamData: Success
MRC VarData matches data in flash, skip update!
Write MRC VarData: Success
0
Call FspSiliconInit ... 
Success
MEM: 0000000000000000 00000000000A0000 00 1
MEM: 00000000000A0000 0000000000060000 00 2
MEM: 0000000000100000 000000000FF00000 00 1
MEM: 0000000010000000 0000000002151000 00 2
MEM: 0000000012151000 00000000675B3000 00 1
MEM: 0000000079704000 0000000000900000 01 2
MEM: 000000007A004000 0000000000068000 00 3
MEM: 000000007A06C000 0000000000008000 00 4
MEM: 000000007A074000 0000000000B8C000 00 2
MEM: 000000007AC00000 0000000000400000 00 2
MEM: 000000007B000000 0000000000800000 00 2
MEM: 000000007B800000 0000000004800000 00 2
MEM: 00000000FF800000 0000000000800000 00 2
MP Init (Wakeup)
MP Init (Run)
Detected 2 CPU threads
 CPU  0 APIC ID: 0
 CPU  1 APIC ID: 4
PCI Enum
System BIOS ID is Intel
VbtAddress =0x7AB4B304 
VBT data found
VbtFileBuffer->HeaderVbtSize = 0x180A 
extended VBT supported
IgdOpRegion ended
  IPCBar0Address Address = 0xFE042000, Len = 0x00002000
  SSRAMBar0Address Address = 0xFE900000, Len = 0x00002000
  P2SBBaseAddress Old = 0xFFFFFFFF, New = 0xD0000000
  BIOS MAIL-BOX Data= 0xFED17080 
  BIOS MAIL-BOX Interface= 0xFED17084 
  GPIO0Addr Address = 0xD0C50000, Len = 0x0000076C
  GPIO1Addr Address = 0xD0C40000, Len = 0x00000764
  GPIO2Addr Address = 0xD0C70000, Len = 0x00000674
  GPIO3Addr Address = 0xD0C00000, Len = 0x00000654
  RpAddress Port[0] Address = 0x00140000
  RpAddress Port[1] Address = 0x00140001
  RpAddress Port[2] Address = 0x00130000
  RpAddress Port[3] Address = 0x00130001
  RpAddress Port[4] Address = 0x00130002
  RpAddress Port[5] Address = 0x00130003
ACPI Init
DMAR table update.
DmarTableUpdate() - start
McD0BaseAddress 0xE0000000, MchBar 0xFED10000, IgdMode 0x0002
GttMode 0x0003, GttMemSize 0x00800000
RMRR Base  address IGD 000000007B800000
RMRR Limit address IGD 000000007FFFFFFF
RMRR Base  address HECI 000000007AB11000
RMRR Limit address HECI 000000007AB30FFF
VTD base address1 0x00000000FED64000
VTD base address2 0x00000000FED65000
 VtdLib: P2sbMmbase = 0xE0068000, IBDF = 0xFAF8
 VtdLib: IoApicId 0x1
DmarTableUpdate()  - end
Updated Hpet BaseAddressLower32Bit = 0xFED00000, EventTimerBlockId = 0x8086A701
Number of P States: 17 (Ratio 8 ~ 24)
ACPI Ret: Success
HASH Verification Success! Component Type (3)
Load Payload ID 0x00000000 @ 0x7AAD0000
PE32 Format Payload
MP Init (Done)
HOB @ 0x7ABC0000
SerialPortInfo Type=2 BaseAddr=0x81532000 RegWidth=4
Boot Target: 0, Action: 0
Stage2 stack: 0x40000 (stack used 0x700, HOB used 0xDF0, 0x3EB10 free)
Stage2 heap: 0xB4C000 (0xF0000 used, 0xA5C000 free)
Payload entry: 0x7AAE9CB0
Jump to payload

Payload startup
ACPI PmTimer Base: 0x408
PCI Express  Base: 0xE0000000
Starting Firmware Update

=================Read Capsule Image==============
BootMediumPciBase(0xE00A8000)
Init USB XHCI - Success
XhcPeiControlTransfer: error - Device Error, transfer - 100
XhcPeiControlTransfer: error - Device Error, transfer - 100
XhcPeiControlTransfer: error - Device Error, transfer - 100
PeiUsbGet Device Descriptor fail: 3 Device Error
Enumerate Bus - Success
Found 1 USB devices on bus
Found mass storage on device 0
find boot partition
Partition type: MBR  (1 logical partitions)
Find partion success
Find partition
Detected FAT on HwDev 0 Part 0
Capsule Image found, ImageSize=0xEFE280
First 256Bytes of capsule image
  00000000: 58 AE 3E 1A 80 B5 EF 4F-AC A3 A1 6D 9E 00 DF 5F  *X.>....O...m..._*
  00000010: 40 00 00 00 01 00 00 00-00 00 00 00 78 E1 EF 00  *@...........x...*
  00000020: 08 01 00 00 40 00 00 00-38 E0 EF 00 78 E0 EF 00  *....@...8...x...*
  00000030: 00 01 00 00 00 00 00 00-00 00 00 00 00 00 00 00  *................*
  00000040: 01 00 00 00 00 00 01 00-10 00 00 00 00 00 00 00  *................*
  00000050: 02 00 00 00 13 68 5C 60-C7 C2 42 42 9C 27 50 A4  *.....h\`..BB.'P.*
  00000060: C3 63 DB A4 01 00 00 00-00 E0 EF 00 00 00 00 00  *.c..............*
  00000070: 00 00 00 00 00 00 00 00-AA 55 00 00 0D 00 01 00  *.........U......*
  00000080: 00 00 00 00 00 00 00 00-03 00 01 00 32 00 AE 08  *............2...*
  00000090: 09 00 00 00 00 00 00 00-00 00 00 00 0A 00 00 00  *................*
  000000A0: 00 02 00 00 10 00 00 00-05 00 00 00 00 80 14 00  *................*
  000000B0: 00 10 14 00 01 00 00 00-00 50 00 00 00 A0 00 00  *.........P......*
  000000C0: 0C 00 00 00 00 00 00 00-00 00 00 00 0D 00 00 00  *................*
  000000D0: 00 00 00 00 00 00 00 00-02 00 00 00 00 F0 01 00  *................*
  000000E0: 00 10 06 00 11 00 00 00-10 02 00 00 08 01 00 00  *................*
  000000F0: 00 00 00 00 00 10 00 00-00 40 00 00 0E 00 00 00  *.........@......*
CapsuleImage: 0x787AF000, CapsuleSize: 0xEFE280
HASH Verification Success! Component Type (5)
RSA Verification Success!
The new BOOTLOADER image passed verification
BPDT header Signature or partition number verification failed.
SetBootPartitionInvalid failed! Status = 0x80000003
GetFirmwareUpdateInfo, Status = 0x80000003
Firmware update failed with Status = Unsupported
Firmware update Done! clear CSE flag to normal boot mode.
HECI SecMode 0
Group    =00000020
Command  =00000007
IsRespone=00000001
Result   =00000000
Rebooting ...
BtGuard: VB : 0, MB : 0 


yet another error!

**Comment by terryzouhao** [comment]
@tomwei666 , we were also using the same N3350 APL-UP2 board (Intel® Celeron™ N3350 (up to 2.4 GHz) ). 
Just re-tried another commit #4803d94 (Sep 10, 2019 ), one day earlier than the previous one, all passed and flashed to N3350 again with enclosed log.  
Actually just guess your failure "BPDT header Signature or partition number verification failed" was still because of the different "Priv key":
./iasimage.py create -o Platform/ApollolakeBoardPkg/SpiIasBin/iasimage1.bin -d ./BootloaderCorePkg/Tools/Keys/TestSigningPrivateKey.pem -i 0x40000 cmdline.txt fastboot.elf
python BootloaderCorePkg/Tools/GenCapsuleFirmware.py -k ./BootloaderCorePkg/Tools/Keys/TestSigningPrivateKey.pem  -o FwuImage.bin -p BIOS bios.bin

Please try with # git checkout 4803d940b1e9e2eff9a9bac28e936b03d02fb246 commit, and refer to our successful log: [N3350_UP2_sbl_upgrade_sucess_log.txt] (https://github.com/projectacrn/acrn-hypervisor/files/5528388/N3350_UP2_sbl_upgrade_sucess_log.txt)

Detailed steps for your reference again:
cd slimbootloader/
git clean -dfx
git reset --hard
git checkout 4803d940b1e9e2eff9a9bac28e936b03d02fb246
cp -r ../UPA1AM40.zip .
cp -r ../iasimage.py .
cp -r ../fastboot.elf .
unzip UPA1AM40.zip
chmod +x ./iasimage.py
mkdir -p Platform/ApollolakeBoardPkg/SpiIasBin
touch cmdline.txt
./iasimage.py create -o Platform/ApollolakeBoardPkg/SpiIasBin/iasimage1.bin -d ./BootloaderCorePkg/Tools/Keys/TestSigningPrivateKey.pem -i 0x40000 cmdline.txt fastboot.elf
python BuildLoader.py build apl
python Platform/ApollolakeBoardPkg/Script/StitchLoader.py -i UPA1AM40.bin -s Outputs/apl/Stitch_Components.zip -o sbl_up2_ifwi.bin -p 0xAA00000E -b bios.bin
python BootloaderCorePkg/Tools/GenCapsuleFirmware.py -k ./BootloaderCorePkg/Tools/Keys/TestSigningPrivateKey.pem  -o FwuImage.bin -p BIOS bios.bin
cp -r FwuImage.bin /media/ssg-hv/CB62-18DB/
sync
umount /dev/sdc1
Then insert the Udisk into UP2 board and start upgrading SBL via “fwupdate” cmd.  You will see the sbl update log as the given attachment.
