### ISSUE TITLE
acrn-config: insert vbdf in hex format and vuart vbdf logic

### ISSUE THREAD

**Issue by yuchuyang** [projectacrn/acrn-hypervisor#5482]
Bug fix:
1. The bdf were inserted in decimal. Fix it with hexadecimal
format.
2. The vuart vbdf will only take the dev which no used bdf has
the same dev. For example: If 00:01.1 is in used but not 00:01.0,
vuart vbdf will skip 00:01.0 and look for 00:02.0, 00:03.0 and so on.

Signed-off-by: Yang,Yu-chu <yu-chu.yang@intel.com>

**Comment by yuchuyang** [comment]
[External_System_ID]ACRN-6802

**Comment by yuchuyang** [comment]
[External_System_ID]ACRN-6804

**Comment by wenlingz** [comment]
[External_System_ID]ACRN-6802
