### ISSUE TITLE
[Documentation] Incorrect order and definition of GVT_args

### ISSUE THREAD

**Issue by stanleyintel** [projectacrn/acrn-hypervisor#5528]
**Describe the bug**

Documentation error: The description of GVT_args in user-guides/acrn-dm-parameters.html wrongly places gvt_high_gm_sz before gvt_low_gm_sz. Also gvt_low_gm_sz should be for GVT-g aperture size and gvt_high_gm_sz should be for GVT-g hidden gfx memory size.

Doc URL: https://projectacrn.github.io/latest/user-guides/acrn-dm-parameters.html

**Comment by gvancuts** [comment]
Nice catch - thanks! Please take a look at PR #5529 to see if it correctly addresses the problem. Thanks!

**Comment by gvancuts** [comment]
hi @stanleyintel , the patch was merged so let me close this issue. Feel free to re-open it if something is still missing to address it. Thanks
