### ISSUE TITLE
can't boot  RTVM in industry scenario

### ISSUE THREAD

**Issue by rome-xi** [projectacrn/acrn-hypervisor#5558]
Ubuntu version: 20.04
GCC version: 9.3
ACRN-hypervisor branch: release_2.2 (acrn-2020w40.1-180000p)
ACRN-Kernel (Service VM kernel): release_2.2 (5.4.43-PKT-200203T060100Z)
RT kernel for Ubuntu User OS: 4.19/preempt-rt (4.19.72-rt25)
HW: Maxtang Intel WHL-U i7-8565U 
toturial:https://projectacrn.github.io/latest/getting-started/rt_industry_ubuntu.html
I refer to the website tutorial,sos is booted,but the rtvm can't.
I guess the problem is my launch script.
****************************************************************************************************************************************
 #!/bin/bash
 #Copyright (C) 2019 Intel Corporation.
 #SPDX-License-Identifier: BSD-3-Clause
 #This is an example of launch script for KBL NUC7i7DNH, may need to revise for other platform.

#pci devices for passthru
declare -A passthru_vpid
declare -A passthru_bdf

passthru_vpid=(
["eth"]="8086 156f"
["sata"]="8086 9dd3"
["nvme"]="8086 f1a6"
)
passthru_bdf=(
["eth"]="0000:00:1f.6"
["sata"]="0000:00:17.0"
["nvme"]="0000:02:00.0"
)

function launch_hard_rt_vm()
{
#for memsize setting
mem_size=1024M

modprobe pci_stub
#Ethernet pass-through
#echo ${passthru_vpid["eth"]} > /sys/bus/pci/drivers/pci-stub/new_id
#echo ${passthru_bdf["eth"]} > /sys/bus/pci/devices/${passthru_bdf["eth"]}/driver/unbind
#echo ${passthru_bdf["eth"]} > /sys/bus/pci/drivers/pci-stub/bind

#SATA pass-through
echo ${passthru_vpid["sata"]} > /sys/bus/pci/drivers/pci-stub/new_id
echo ${passthru_bdf["sata"]} > /sys/bus/pci/devices/${passthru_bdf["sata"]}/driver/unbind
echo ${passthru_bdf["sata"]} > /sys/bus/pci/drivers/pci-stub/bind

#NVME pass-through
#echo ${passthru_vpid["nvme"]} > /sys/bus/pci/drivers/pci-stub/new_id
#echo ${passthru_bdf["nvme"]} > /sys/bus/pci/devices/${passthru_bdf["nvme"]}/driver/unbind
#echo ${passthru_bdf["nvme"]} > /sys/bus/pci/drivers/pci-stub/bind

#or pm setting
pm_channel="--pm_notify_channel uart "
pm_by_vuart="--pm_by_vuart tty,/dev/ttyS1"

/usr/bin/acrn-dm -A -m $mem_size -s 0:0,hostbridge \
   --lapic_pt \
   --rtvm \
   --virtio_poll 1000000 \
   -U 495ae2e5-2603-4d64-af76-d4bc5a8ec0e5 \
   -s 2,passthru,00/17/0 \
   -s 3,virtio-console,@stdio:stdio_port \
   -s 8,virtio-net,tap0 \
   $pm_channel $pm_by_vuart \
/usr/bin/acrn-dm -A -m $mem_size -s 0:0,hostbridge \
   --lapic_pt \
   --rtvm \
   --virtio_poll 1000000 \
   -U 495ae2e5-2603-4d64-af76-d4bc5a8ec0e5 \
   -s 2,passthru,00/17/0 \
   -s 3,virtio-console,@stdio:stdio_port \
   -s 8,virtio-net,tap0 \
   $pm_channel $pm_by_vuart \
   --ovmf /usr/share/acrn/bios/OVMF.fd \
   -B"root=/dev/sda2 rw rootwait nohpet console=hvc0 console=ttyS0 \
   no_timer_check ignore_loglevel log_buf_len=16M consoleblank=0 \
   clocksource=tsc tsc=reliable x2apic_phys processor.max_cstate=0 \
   intel_idle.max_cstate=0 intel_pstate=disable mce=ignore_ce audit=0 \
   isolcpus=nohz,domain,1 nohz_full=1 rcu_nocbs=1 nosoftlockup idle=poll \
   irqaffinity=0" \
   hard_rtvm

}

#-s 2,passthru,0/17/0 \ #please using "lspci -nn" check the bdf info

#Depends on which partation RT_LaaG is installed in;maybe need to change
#/dev/nvme0n1p3 to /dev/sda3 on NUC and uncomment SATA pass-through
#Add following RT_LaaG kernel cmdline into loader/entries/xxx.conf of EFI partation
#root=/dev/nvme0n1p3 rw rootwait nohpet console=hvc0 console=ttyS0 \
#no_timer_check ignore_loglevel log_buf_len=16M consoleblank=0 \
#clocksource=tsc tsc=reliable x2apic_phys processor.max_cstate=0 \
#intel_idle.max_cstate=0 intel_pstate=disable mce=ignore_ce audit=0 \
#isolcpus=nohz,domain,1 nohz_full=1 rcu_nocbs=1 nosoftlockup idle=poll \
#irqaffinity=0

#offline SOS CPUs except BSP before launch UOS
for i in `ls -d /sys/devices/system/cpu/cpu[1-99]`; do
        online=`cat $i/online`
        idx=`echo $i | tr -cd "[1-99]"`
        echo cpu$idx online=$online
        if [ "$online" = "1" ]; then
                echo 0 > $i/online
                echo $idx > /sys/class/vhm/acrn_vhm/offline_cpu
        fi
done
launch_hard_rt_vm
****************************************************************************************************************************************
How should I modify it so that I can launch rtvm?
It‘s launch log.
****************************************************************************************************************************************
acrn@acrn-WL10:~$ sudo /usr/share/acrn/samples/nuc/launch_hard_rt_vm.sh
cpu1 online=1
cpu2 online=1
cpu3 online=1
pm by vuart node-index = 1
SW_LOAD: get ovmf path /usr/share/acrn/bios/OVMF.fd, size 0x200000
SW_LOAD: get bootargs root=/dev/sda2 rw rootwait nohpet console=hvc0 console=ttyS0    no_timer_check ignore_loglevel log_buf_len=16M consoleblank=0    clocksource=tsc tsc=reliable x2apic_phys processor.max_cstate=0    intel_idle.max_cstate=0 intel_pstate=disable mce=ignore_ce audit=0    isolcpus=nohz,domain,1 nohz_full=1 rcu_nocbs=1 nosoftlockup idle=poll    irqaffinity=0
vm_create: hard_rtvm
VHM api version 1.0
vm_setup_memory: size=0x40000000
open hugetlbfs file /run/hugepage/acrn/huge_lv1/hard_rtvm/495AE2E526034D64AF76D4BC5A8EC0E5
open hugetlbfs file /run/hugepage/acrn/huge_lv2/hard_rtvm/495AE2E526034D64AF76D4BC5A8EC0E5
level 0 free/need pages:0/1 page size:0x200000
level 1 free/need pages:12/1 page size:0x40000000
to reserve more free pages:
to reserve pages (+orig 0): echo 1 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
now enough free pages are reserved!

try to setup hugepage with:
	level 0 - lowmem 0x0, biosmem 0x200000, highmem 0x0
	level 1 - lowmem 0x40000000, biosmem 0x0, highmem 0x0
total_size 0x180000000

mmap ptr 0x0x7f6b15401000 -> baseaddr 0x0x7f6b40000000
mmap 0x40000000@0x7f6b40000000
touch 1 pages with pagesz 0x40000000
mmap 0x200000@0x7f6c3fe00000
touch 1 pages with pagesz 0x200000

really setup hugepage with:
	level 0 - lowmem 0x0, biosmem 0x200000, highmem 0x0
	level 1 - lowmem 0x40000000, biosmem 0x0, highmem 0x0
vm_init_vdevs
pm_by_vuart_init idx: 1, path: /dev/ttyS1
polling 35...
Listening 35...
initiate a connection on a socket error
create socket to connect life-cycle manager failed
pci init hostbridge
pci init passthru
modify_bar_registration: bypass for pci-passthru 0:2.0
acrn-dm: passthru device 0/17/0 BAR 1: size[100] is expanded to page aligned [1000]

modify_bar_registration: bypass for pci-passthru 0:2.0
modify_bar_registration: bypass for pci-passthru 0:2.0
modify_bar_registration: bypass for pci-passthru 0:2.0
modify_bar_registration: bypass for pci-passthru 0:2.0
acrn-dm: passthru device 0/17/0 BAR 5: size[800] is expanded to page aligned [1000]

modify_bar_registration: bypass for pci-passthru 0:2.0
pci init virtio-console
pci init virtio-net
tpm: init_vtpm2:Invalid socket path!
                                    /tmp/dm.XlezcoZ     24:     Device (PCI0)
                                                                             Warning  3073 -        Multiple types ^  (Device object requires either a _HID or _ADR, but not both)

                  /tmp/dm.XlezcoZ    110:     Processor (CPU0, 0x00, 0x00000000, 0x00) {}
         Warning  3168 -                          ^ Legacy Processor() keyword detected. Use Device() keyword instead.

                                      /tmp/dm.XlezcoZ    111:     Processor (CPU1, 0x01, 0x00000000, 0x00) {}
                             Warning  3168 -                          ^ Legacy Processor() keyword detected. Use Device() keyword instead.

                                                          acrn_sw_load
                                                                      SW_LOAD: partition blob /usr/share/acrn/bios/OVMF.fd size 2097152 copy to guest 0xffe00000
                                                                               SW_LOAD: build e820 10 entries to addr: 0x7f6b400ef008
SW_LOAD: entry[0]: addr 0x0000000000000000, size 0x00000000000a0000,  type 0x1
SW_LOAD: entry[1]: addr 0x00000000000a0000, size 0x0000000000060000,  type 0x2
SW_LOAD: entry[2]: addr 0x0000000000100000, size 0x000000003ff00000,  type 0x1
SW_LOAD: entry[3]: addr 0x0000000040000000, size 0x0000000040000000,  type 0x2
SW_LOAD: entry[4]: addr 0x0000000049000000, size 0x0000000037000000,  type 0x2
SW_LOAD: entry[5]: addr 0x0000000080000000, size 0x0000000008000000,  type 0x2
SW_LOAD: entry[6]: addr 0x00000000db000000, size 0x0000000004000000,  type 0x2
SW_LOAD: entry[7]: addr 0x00000000df000000, size 0x0000000001000000,  type 0x2
SW_LOAD: entry[8]: addr 0x00000000e0000000, size 0x0000000020000000,  type 0x2
SW_LOAD: entry[9]: addr 0x0000000100000000, size 0x0000000040000000,  type 0x2
SW_LOAD: ovmf_entry 0xfffffff0
                              add_cpu
                                     out instr on NMI port (0x61) not supported
                                                                               out instr on NMI port (0x61) not supported
                                         out instr on NMI port (0x61) not supported
*************************************************************************************************************************************************

**Comment by fuzhongl** [comment]
@rome-xi Please remove **-s 8,virtio-net,tap0** in your launch script.
Thanks!

**Comment by rome-xi** [comment]
> @rome-xi Please remove **-s 8,virtio-net,tap0** in your launch script.
> Thanks!
The result has not changed.

**Comment by rome-xi** [comment]
linux /boot/bzImage root=PARTUUID="fe3100fa-5742-421f-8381-c63a4977e9c4" rw rootwait nohpet console=hvc0 console=ttyS0 no_timer_check ignore_loglevel log_buf_len=16M consoleblank=0 clocksource=tsc tsc=reliable x2apic_phys processor.max_cstate=0 intel_idle.max_cstate=0 intel_pstate=disable mce=ignore_ce audit=0 isolcpus=nohz,domain,1 nohz_full=1 rcu_nocbs=1 nosoftlockup idle=poll irqaffinity=0

**Comment by fuzhongl** [comment]
zcat /proc/config.gz

check if following is in:

CONFIG_SERIAL_8250_EXTENDED=y
CONFIG_SERIAL_8250_DETECT_IRQ=y

**Comment by fuzhongl** [comment]
@rome-xi Please apply following patch in 4.19 rt kernel: Then, you can login without uart cable.

```
From f27141bd61bf4dad80300a18d10c4a170caedac7 Mon Sep 17 00:00:00 2001
From: "wei.tan@intel.com" <wei.tan@intel.com>
Date: Thu, 6 Jun 2019 02:18:23 +0000
Subject: [PATCH] virtio: add virtio polling support for ACRN

add virtio polling mode for ACRN.

Signed-off-by: Tw <wei.tan@intel.com>
---
 drivers/block/virtio_blk.c    |   3 +
 drivers/char/virtio_console.c |   3 +
 drivers/net/virtio_net.c      |   3 +
 drivers/virtio/Kconfig        |  10 ++++
 drivers/virtio/virtio.c       | 101 ++++++++++++++++++++++++++++++++++
 drivers/virtio/virtio_input.c |   3 +
 drivers/virtio/virtio_ring.c  |  35 +++++++++++-
 include/linux/virtio.h        |  21 +++++++
 include/linux/virtio_config.h |  17 ------
 x86-64_defconfig              |   4 ++
 10 files changed, 181 insertions(+), 19 deletions(-)

diff --git a/drivers/block/virtio_blk.c b/drivers/block/virtio_blk.c
index f88d39ca53fb..3c1fcbe9c958 100644
--- a/drivers/block/virtio_blk.c
+++ b/drivers/block/virtio_blk.c
@@ -984,6 +984,9 @@ static struct virtio_driver virtio_blk = {
 	.driver.name			= KBUILD_MODNAME,
 	.driver.owner			= THIS_MODULE,
 	.id_table			= id_table,
+#ifdef CONFIG_VIRTIO_PMD
+	.polling_mode        = true,
+#endif
 	.probe				= virtblk_probe,
 	.remove				= virtblk_remove,
 	.config_changed			= virtblk_config_changed,
diff --git a/drivers/char/virtio_console.c b/drivers/char/virtio_console.c
index c55f6aeb4227..d0970d334df0 100644
--- a/drivers/char/virtio_console.c
+++ b/drivers/char/virtio_console.c
@@ -2239,6 +2239,9 @@ static struct virtio_driver virtio_console = {
 	.driver.name =	KBUILD_MODNAME,
 	.driver.owner =	THIS_MODULE,
 	.id_table =	id_table,
+#ifdef CONFIG_VIRTIO_PMD
+	.polling_mode        = true,
+#endif
 	.probe =	virtcons_probe,
 	.remove =	virtcons_remove,
 	.config_changed = config_intr,
diff --git a/drivers/net/virtio_net.c b/drivers/net/virtio_net.c
index c88ee376a2eb..b7ab99b46be3 100644
--- a/drivers/net/virtio_net.c
+++ b/drivers/net/virtio_net.c
@@ -3226,6 +3226,9 @@ static struct virtio_driver virtio_net_driver = {
 	.driver.owner =	THIS_MODULE,
 	.id_table =	id_table,
 	.validate =	virtnet_validate,
+#ifdef CONFIG_VIRTIO_PMD
+	.polling_mode        = true,
+#endif
 	.probe =	virtnet_probe,
 	.remove =	virtnet_remove,
 	.config_changed = virtnet_config_changed,
diff --git a/drivers/virtio/Kconfig b/drivers/virtio/Kconfig
index 51d43fd4bd2b..3e8f13a08a16 100644
--- a/drivers/virtio/Kconfig
+++ b/drivers/virtio/Kconfig
@@ -100,4 +100,14 @@ config ACRN_VIRTIO_DEVICES
 
 	  If unsure, say 'N'.
 
+config VIRTIO_PMD
+	bool "Enable polling mode for virtio devices"
+	default n
+	depends on VIRTIO
+	---help---
+	  This option enables polling mode for virtio devices including
+	  virtio-net, virtio-blk, virtio-console and virtio-input devices.
+
+	  If sure, say 'Y'.
+
 endif # VIRTIO_MENU
diff --git a/drivers/virtio/virtio.c b/drivers/virtio/virtio.c
index 59e36ef4920f..6a32e7bf4237 100644
--- a/drivers/virtio/virtio.c
+++ b/drivers/virtio/virtio.c
@@ -68,6 +68,13 @@ static struct attribute *virtio_dev_attrs[] = {
 };
 ATTRIBUTE_GROUPS(virtio_dev);
 
+#ifdef CONFIG_VIRTIO_PMD
+static unsigned long virtio_polling_interval = 10000000UL;
+module_param(virtio_polling_interval, ulong, 0644);
+MODULE_PARM_DESC(virtio_polling_interval,
+        "virtio polling interval in ns. (default: 10000000)");
+#endif
+
 static inline int virtio_id_match(const struct virtio_device *dev,
 				  const struct virtio_device_id *id)
 {
@@ -187,6 +194,71 @@ int virtio_finalize_features(struct virtio_device *dev)
 }
 EXPORT_SYMBOL_GPL(virtio_finalize_features);
 
+#ifdef CONFIG_VIRTIO_PMD
+static enum hrtimer_restart virtio_handle_polling_timer(struct hrtimer *t)
+{
+        struct virtio_device *dev = container_of(t, struct virtio_device, hr_timer);
+
+        virtio_poll_virtqueues(dev);
+        /* virtio_config_changed(dev); */
+        hrtimer_start(&dev->hr_timer, ns_to_ktime(virtio_polling_interval), HRTIMER_MODE_REL);
+        return HRTIMER_NORESTART;
+}
+
+static inline void virtio_init_polling_timer(struct virtio_device *dev)
+{
+        if (virtio_polling_mode_enabled(dev)) {
+                hrtimer_init(&dev->hr_timer, CLOCK_MONOTONIC, HRTIMER_MODE_REL);
+                (dev->hr_timer).function = virtio_handle_polling_timer;
+        }
+}
+
+static void virtio_start_polling_timer(struct virtio_device *dev)
+{
+        if (virtio_polling_mode_enabled(dev)) {
+                hrtimer_start(&dev->hr_timer, ns_to_ktime(virtio_polling_interval), HRTIMER_MODE_REL);
+                dev_notice(&dev->dev, "start polling timer: %lu\n",
+                        virtio_polling_interval);
+        }
+}
+
+static void virtio_stop_polling_timer(struct virtio_device *dev)
+{
+        if (virtio_polling_mode_enabled(dev)) {
+                hrtimer_cancel(&dev->hr_timer);
+                dev_notice(&dev->dev, "stop polling timer\n");
+        }
+}
+#endif
+
+/**
+ * virtio_device_ready - enable vq use in probe function
+ * @vdev: the device
+ *
+ * Driver must call this to use vqs in the probe function.
+ *
+ * Note: vqs are enabled automatically after probe returns.
+ */
+void virtio_device_ready(struct virtio_device *dev)
+{
+	unsigned status = dev->config->get_status(dev);
+
+	BUG_ON(status & VIRTIO_CONFIG_S_DRIVER_OK);
+	dev->config->set_status(dev, status | VIRTIO_CONFIG_S_DRIVER_OK);
+
+#ifdef CONFIG_VIRTIO_PMD
+	/*
+	 * In polling mode, virtqueue interrupts are disabled from the
+	 * beginning. we must make sure the polling timer is started
+	 * just after the virtqueue is ready. When vring_create_virtqueue
+	 * is called the virtqueues are not ready. Start polling timer
+	 * when status is changed to DRIVER_OK is a good chance then.
+	 */
+	virtio_start_polling_timer(dev);
+#endif
+}
+EXPORT_SYMBOL_GPL(virtio_device_ready);
+
 static int virtio_dev_probe(struct device *_d)
 {
 	int err, i;
@@ -202,6 +274,13 @@ static int virtio_dev_probe(struct device *_d)
 	/* Figure out what features the device supports. */
 	device_features = dev->config->get_features(dev);
 
+#ifdef CONFIG_VIRTIO_PMD
+	if (virtio_polling_mode_enabled(dev)) {
+		device_features &= ~VIRTIO_F_NOTIFY_ON_EMPTY;
+		device_features &= ~VIRTIO_RING_F_EVENT_IDX;
+	}
+#endif
+
 	/* Figure out what features the driver supports. */
 	driver_features = 0;
 	for (i = 0; i < drv->feature_table_size; i++) {
@@ -242,6 +321,10 @@ static int virtio_dev_probe(struct device *_d)
 	if (err)
 		goto err;
 
+#ifdef CONFIG_VIRTIO_PMD
+	virtio_init_polling_timer(dev);
+#endif
+
 	err = drv->probe(dev);
 	if (err)
 		goto err;
@@ -257,6 +340,9 @@ static int virtio_dev_probe(struct device *_d)
 
 	return 0;
 err:
+#ifdef CONFIG_VIRTIO_PMD
+	virtio_stop_polling_timer(dev);
+#endif
 	virtio_add_status(dev, VIRTIO_CONFIG_S_FAILED);
 	return err;
 
@@ -269,6 +355,9 @@ static int virtio_dev_remove(struct device *_d)
 
 	virtio_config_disable(dev);
 
+#ifdef CONFIG_VIRTIO_PMD
+	virtio_stop_polling_timer(dev);
+#endif
 	drv->remove(dev);
 
 	/* Driver should have reset device. */
@@ -340,6 +429,10 @@ int register_virtio_device(struct virtio_device *dev)
 
 	INIT_LIST_HEAD(&dev->vqs);
 
+#ifdef CONFIG_VIRTIO_PMD
+	spin_lock_init(&dev->vq_lock);
+#endif
+
 	/*
 	 * device_add() causes the bus infrastructure to look for a matching
 	 * driver.
@@ -370,6 +463,10 @@ int virtio_device_freeze(struct virtio_device *dev)
 
 	virtio_config_disable(dev);
 
+#ifdef CONFIG_VIRTIO_PMD
+	virtio_stop_polling_timer(dev);
+#endif
+
 	dev->failed = dev->config->get_status(dev) & VIRTIO_CONFIG_S_FAILED;
 
 	if (drv && drv->freeze)
@@ -415,6 +512,10 @@ int virtio_device_restore(struct virtio_device *dev)
 	/* Finally, tell the device we're all set */
 	virtio_add_status(dev, VIRTIO_CONFIG_S_DRIVER_OK);
 
+#ifdef CONFIG_VIRTIO_PMD
+	virtio_start_polling_timer(dev);
+#endif
+
 	virtio_config_enable(dev);
 
 	return 0;
diff --git a/drivers/virtio/virtio_input.c b/drivers/virtio/virtio_input.c
index 3a0468f2ceb0..dc5fd9c96477 100644
--- a/drivers/virtio/virtio_input.c
+++ b/drivers/virtio/virtio_input.c
@@ -372,6 +372,9 @@ static struct virtio_driver virtio_input_driver = {
 	.feature_table       = features,
 	.feature_table_size  = ARRAY_SIZE(features),
 	.id_table            = id_table,
+#ifdef CONFIG_VIRTIO_PMD
+	.polling_mode        = true,
+#endif
 	.probe               = virtinput_probe,
 	.remove              = virtinput_remove,
 #ifdef CONFIG_PM_SLEEP
diff --git a/drivers/virtio/virtio_ring.c b/drivers/virtio/virtio_ring.c
index 9529e28e1822..22023f447e9c 100644
--- a/drivers/virtio/virtio_ring.c
+++ b/drivers/virtio/virtio_ring.c
@@ -798,7 +798,9 @@ unsigned virtqueue_enable_cb_prepare(struct virtqueue *_vq)
 	u16 last_used_idx;
 
 	START_USE(vq);
-
+#ifdef CONFIG_VIRTIO_PMD
+	if (!virtio_polling_mode_enabled(_vq->vdev)) {
+#endif
 	/* We optimistically turn back on interrupts, then check if there was
 	 * more to do. */
 	/* Depending on the VIRTIO_RING_F_EVENT_IDX feature, we need to
@@ -809,6 +811,9 @@ unsigned virtqueue_enable_cb_prepare(struct virtqueue *_vq)
 		if (!vq->event)
 			vq->vring.avail->flags = cpu_to_virtio16(_vq->vdev, vq->avail_flags_shadow);
 	}
+#ifdef CONFIG_VIRTIO_PMD
+	}
+#endif
 	vring_used_event(&vq->vring) = cpu_to_virtio16(_vq->vdev, last_used_idx = vq->last_used_idx);
 	END_USE(vq);
 	return last_used_idx;
@@ -876,11 +881,17 @@ bool virtqueue_enable_cb_delayed(struct virtqueue *_vq)
 	/* Depending on the VIRTIO_RING_F_USED_EVENT_IDX feature, we need to
 	 * either clear the flags bit or point the event index at the next
 	 * entry. Always update the event index to keep code simple. */
+#ifdef CONFIG_VIRTIO_PMD
+	if (!virtio_polling_mode_enabled(_vq->vdev)) {
+#endif
 	if (vq->avail_flags_shadow & VRING_AVAIL_F_NO_INTERRUPT) {
 		vq->avail_flags_shadow &= ~VRING_AVAIL_F_NO_INTERRUPT;
 		if (!vq->event)
 			vq->vring.avail->flags = cpu_to_virtio16(_vq->vdev, vq->avail_flags_shadow);
 	}
+#ifdef CONFIG_VIRTIO_PMD
+	}
+#endif
 	/* TODO: tune this threshold */
 	bufs = (u16)(vq->avail_idx_shadow - vq->last_used_idx) * 3 / 4;
 
@@ -964,6 +975,7 @@ struct virtqueue *__vring_new_virtqueue(unsigned int index,
 {
 	unsigned int i;
 	struct vring_virtqueue *vq;
+	bool disable_cb = (callback == NULL);
 
 	vq = kmalloc(sizeof(*vq) + vring.num * sizeof(struct vring_desc_state),
 		     GFP_KERNEL);
@@ -996,8 +1008,13 @@ struct virtqueue *__vring_new_virtqueue(unsigned int index,
 		!context;
 	vq->event = virtio_has_feature(vdev, VIRTIO_RING_F_EVENT_IDX);
 
+#ifdef CONFIG_VIRTIO_PMD
+	if (!disable_cb && virtio_polling_mode_enabled(vdev))
+		disable_cb = true;
+#endif
+
 	/* No callback?  Tell other side not to bother us. */
-	if (!callback) {
+	if (disable_cb) {
 		vq->avail_flags_shadow |= VRING_AVAIL_F_NO_INTERRUPT;
 		if (!vq->event)
 			vq->vring.avail->flags = cpu_to_virtio16(vdev, vq->avail_flags_shadow);
@@ -1251,4 +1268,18 @@ const struct vring *virtqueue_get_vring(struct virtqueue *vq)
 }
 EXPORT_SYMBOL_GPL(virtqueue_get_vring);
 
+#ifdef CONFIG_VIRTIO_PMD
+void virtio_poll_virtqueues(struct virtio_device *dev)
+{
+	struct virtqueue *_vq;
+	unsigned long flags;
+
+	spin_lock_irqsave(&dev->vq_lock, flags);
+	list_for_each_entry(_vq, &dev->vqs, list)
+		vring_interrupt(0, _vq);  /* parameter irq is not used */
+	spin_unlock_irqrestore(&dev->vq_lock, flags);
+}
+EXPORT_SYMBOL_GPL(virtio_poll_virtqueues);
+#endif
+
 MODULE_LICENSE("GPL");
diff --git a/include/linux/virtio.h b/include/linux/virtio.h
index fa1b5da2804e..972d63b5675a 100644
--- a/include/linux/virtio.h
+++ b/include/linux/virtio.h
@@ -90,6 +90,10 @@ dma_addr_t virtqueue_get_desc_addr(struct virtqueue *vq);
 dma_addr_t virtqueue_get_avail_addr(struct virtqueue *vq);
 dma_addr_t virtqueue_get_used_addr(struct virtqueue *vq);
 
+#ifdef CONFIG_VIRTIO_PMD
+void virtio_poll_virtqueues(struct virtio_device *dev);
+#endif
+
 /*
  * Legacy accessors -- in almost all cases, these are the wrong functions
  * to use.
@@ -135,6 +139,10 @@ struct virtio_device {
 	struct list_head vqs;
 	u64 features;
 	void *priv;
+#ifdef CONFIG_VIRTIO_PMD
+	spinlock_t vq_lock;
+	struct hrtimer hr_timer;
+#endif
 };
 
 static inline struct virtio_device *dev_to_virtio(struct device *_dev)
@@ -152,6 +160,7 @@ void virtio_config_changed(struct virtio_device *dev);
 void virtio_config_disable(struct virtio_device *dev);
 void virtio_config_enable(struct virtio_device *dev);
 int virtio_finalize_features(struct virtio_device *dev);
+void virtio_device_ready(struct virtio_device *dev);
 #ifdef CONFIG_PM_SLEEP
 int virtio_device_freeze(struct virtio_device *dev);
 int virtio_device_restore(struct virtio_device *dev);
@@ -184,6 +193,9 @@ struct virtio_driver {
 	unsigned int feature_table_size;
 	const unsigned int *feature_table_legacy;
 	unsigned int feature_table_size_legacy;
+#ifdef CONFIG_VIRTIO_PMD
+	bool polling_mode;
+#endif
 	int (*validate)(struct virtio_device *dev);
 	int (*probe)(struct virtio_device *dev);
 	void (*scan)(struct virtio_device *dev);
@@ -200,6 +212,15 @@ static inline struct virtio_driver *drv_to_virtio(struct device_driver *drv)
 	return container_of(drv, struct virtio_driver, driver);
 }
 
+#ifdef CONFIG_VIRTIO_PMD
+static inline bool virtio_polling_mode_enabled(struct virtio_device *dev)
+{
+	struct virtio_driver *drv = drv_to_virtio(dev->dev.driver);
+
+	return drv->polling_mode;
+}
+#endif
+
 int register_virtio_driver(struct virtio_driver *drv);
 void unregister_virtio_driver(struct virtio_driver *drv);
 
diff --git a/include/linux/virtio_config.h b/include/linux/virtio_config.h
index 32baf8e26735..c85a4ae611c9 100644
--- a/include/linux/virtio_config.h
+++ b/include/linux/virtio_config.h
@@ -202,23 +202,6 @@ int virtio_find_vqs_ctx(struct virtio_device *vdev, unsigned nvqs,
 				      desc);
 }
 
-/**
- * virtio_device_ready - enable vq use in probe function
- * @vdev: the device
- *
- * Driver must call this to use vqs in the probe function.
- *
- * Note: vqs are enabled automatically after probe returns.
- */
-static inline
-void virtio_device_ready(struct virtio_device *dev)
-{
-	unsigned status = dev->config->get_status(dev);
-
-	BUG_ON(status & VIRTIO_CONFIG_S_DRIVER_OK);
-	dev->config->set_status(dev, status | VIRTIO_CONFIG_S_DRIVER_OK);
-}
-
 static inline
 const char *virtio_bus_name(struct virtio_device *vdev)
 {
diff --git a/x86-64_defconfig b/x86-64_defconfig
index c1f8175925fc..4de1162c13d2 100644
--- a/x86-64_defconfig
+++ b/x86-64_defconfig
@@ -127,6 +127,8 @@ CONFIG_RCU_FANOUT_LEAF=16
 # CONFIG_RCU_BOOST is not set
 CONFIG_RCU_NOCB_CPU=y
 # CONFIG_IKCONFIG is not set
+CONFIG_IKCONFIG=y
+CONFIG_IKCONFIG_PROC=y
 CONFIG_LOG_BUF_SHIFT=17
 CONFIG_LOG_CPU_MAX_BUF_SHIFT=12
 CONFIG_PRINTK_SAFE_LOG_BUF_SHIFT=13
@@ -5707,6 +5709,8 @@ CONFIG_VIRTIO_BALLOON=m
 CONFIG_VIRTIO_INPUT=m
 CONFIG_VIRTIO_MMIO=m
 # CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES is not set
+CONFIG_ACRN_VIRTIO_DEVICES=y
+CONFIG_VIRTIO_PMD=y
 # CONFIG_ACRN_VIRTIO_DEVICES is not set
 
 #
-- 
2.17.1

```

**Comment by zhangshuai75** [comment]
> @rome-xi Please apply following patch in 4.19 rt kernel: Then, you can login without uart cable. We will switch rt kernel to 5.4 later; so 4.19 kernel isn't maintained any more.

Hi @fuzhongl 
Can you update the patch file?
When copy the above patch content to a file, it will cause the use of “spaces” to replace the “Tab”, which will lead to patching failure

**Comment by fuzhongl** [comment]
Hi ZhangShai
The patch is generated by git.
The format maybe changed when copied to github.
This patch is NOT MUST if your board has serial port or you use 5.4 rt kernel.

BR.
Fuzhong

**Comment by iaGuoZhi** [comment]
Hi @fuzhongl 
Can ACRN hypervisor v2.0 support rt kernel 5.4? I encountered the same problem when boot rt kernel 4.19 on ACRN hypervisor v2.0.

**Comment by iaGuoZhi** [comment]
Is ACRN document out of date? Documents whether v2.0 or latest version both tell me to build rt kernel with version 4.19. which will cause above problem.

**Comment by fuzhongl** [comment]
@iaGuoZhi It is fine for v2.0.
Which board are you using? with serial port or not? If without serial please adding virtio-console in launch script?

**Comment by iaGuoZhi** [comment]
Hi @fuzhongl , I'm working on ACRN v2.0 on MAXTANG WHL Board.(WHL-IPC-I5). However I came across such error when launch RTVM with kernel version 4.19. 

https://github.com/projectacrn/acrn-hypervisor/issues/5970#issuecomment-826776579

Would you mind having a look at this issue? Thanks a lot.
