### ISSUE TITLE
doc: replace an Ubuntu cloud guest image into openstack doc.

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#5564]
Track below issue as future task.
[doc: update the doc to setup openstack with ACRN](https://github.com/projectacrn/acrn-hypervisor/pull/5560)
We use a Clear Linux cloud guest image, can we replace this by an Ubuntu cloud guest image? I'd suggest we pick the latest one as of today, i.e. https://cloud-images.ubuntu.com/focal/20201126/

**Comment by dbkinder** [comment]
@gvancuts May we assign this to you?

**Comment by gvancuts** [comment]
> @gvancuts May we assign this to you?

OK (just did it)

**Comment by dbkinder** [comment]
doc is updated now (though new instructions are not independently tested)
