### ISSUE TITLE
CODEOWNERS has outdated information

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#5581]
The `CODEOWNERS` file has outdated and missing information. Specifically:
* `/misc/efi-stub/` no longer exists
* `packaging`, `life_mngr`, `hv_prebuild` and `vm_configs` are missing an owner

**Comment by gvancuts** [comment]
@NanlinXie @terryzouhao if you can help me identify the right owners for these, I can send a PR.

**Comment by gvancuts** [comment]
Part of this is being addressed in #5657

**Comment by NanlinXie** [comment]
[External_System_ID] ACRN-4759

**Comment by gvancuts** [comment]
A couple of patches have been merged that take care of this. Closing.
