### ISSUE TITLE
ACRN Configuration Summary Message is not well formed on the screen

### ISSUE THREAD

**Issue by ionutnechita** [projectacrn/acrn-hypervisor#5588]
Hi ACRN team,

I tried to make a new compilation, but the result summary is a bit changed as well.
Error is this:
**_make[1]: Leaving directory '/acrn-hypervisor/devicemodel'
\n\033[47;30mACRN Configuration Summary:\033[0m \nBOARD = nuc7i7dnb\t SCENARIO = industry
BUILD type = \c
RELEASE
Hypervisor configuration is based on:
\tdefconfig file:\t\t\t/acrn-hypervisor/misc/vm_configs/scenarios/industry/nuc7i7dnb/nuc7i7dnb.config;
\tOthers are set by default in:\t/acrn-hypervisor/hypervisor/arch/x86/Kconfig;
VM configuration is based on:
\tSource code at:\t\t\t/acrn-hypervisor/misc/vm_configs_**

cat build/hypervisor/cfg.log
\n\033[47;30mACRN Configuration Summary:\033[0m \nBOARD = nuc7i7dnb\t SCENARIO = industry
BUILD type = \c
RELEASE
Hypervisor configuration is based on:
\tdefconfig file:\t\t\t/acrn-hypervisor/misc/vm_configs/scenarios/industry/nuc7i7dnb/nuc7i7dnb.config;
\tOthers are set by default in:\t/acrn-hypervisor/hypervisor/arch/x86/Kconfig;
VM configuration is based on:
\tSource code at:\t\t\t/acrn-hypervisor/misc/vm_configs

From what I see the echo command that makes the on-screen display and the file, no longer works properly.

Development machine:
NAME="openSUSE Tumbleweed"
VERSION="20201201"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20201201"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20201201"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"

ldd --version
ldd (GNU libc) 2.32
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

gcc --version
gcc (SUSE Linux) 10.2.1 20201117 [revision 98ba03ffe0b9f37b4916ce6238fad754e00d720b]
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

iasl -v
Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20200717
Copyright (c) 2000 - 2020 Intel Corporation

bash --version
GNU bash, version 5.0.18(1)-release (x86_64-suse-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[log_compile1.txt](https://github.com/projectacrn/acrn-hypervisor/files/5647695/log_compile1.txt)

**Comment by ionutnechita** [comment]
With git revert from this commit:
git revert e2590d88aa3e1c72dc6473eadc83312412a604b3


    Revert "hv: fix formatting for cfg.log output"

    This reverts commit e2590d88aa3e1c72dc6473eadc83312412a604b3.

Summary is fine.

**Comment by fuzhongl** [comment]
@gvancuts Could you please help to check it?
Thanks!

**Comment by gvancuts** [comment]
Hmmm... OK, the behaviour is different based on different systems. Tumbleweed and Clear Linux need this `-e` option to format things properly, but Ubuntu does not (and actually prints out this `-e` inside the file which also messes up (differently) the format.

**Comment by gvancuts** [comment]
OK, I think I found what's causing this. On Clear Linux and Tumbleweed, `/bin/sh` is a symlink to `/bin/bash`. `/bin/sh` is the shell used by default by `make` unless otherwise stated. The built-in `echo` command in bash understands the `-e` argument.

On Ubuntu, `/bin/sh` points at `/bin/dash` and the built-in `echo` command in dash does not understand the `-e` option, so it simply prints it out on the screen.

`-e` is not a POSIX compliant argument, so it is considered not very portable to use it.

Having said that, the simplest option I came up with in this case is to explicitly set the shell to be used by `make` to `/bin/bash`

**Comment by gvancuts** [comment]
@ionutnechita , can you do a sanity check on your side with this fix? I tried it on my Docker image based on Tumbleweed and it solved the problem... so hopefully this works for your native env too!

**Comment by ionutnechita** [comment]
Hi @gvancuts,

I tested now with this modification is fine now.
Using OpenSUSE Tumbleweed, native OS.
It's fine to merge this modification.

Thanks.

**Comment by fuzhongl** [comment]
[External_System_ID] ACRN-6882

**Comment by gvancuts** [comment]
patch has been merged, closing this issue.
