### ISSUE TITLE
[Feature] Uptime command not exist in ACRN Shell Commands

### ISSUE THREAD

**Issue by ionutnechita** [projectacrn/acrn-hypervisor#5598]
Hi ACRN team,

I observe this page:
https://projectacrn.github.io/latest/user-guides/acrn-shell.html
But not observe "uptime" command in this table.

You can implement this command in ACRN Shell Commands to see uptime while ACRN Hypervisor is running?
ACRN:/> uptime
ACRN Hypervisor Uptime: 40 minutes

Thanks.

**Comment by gvancuts** [comment]
hi @ionutnechita , out of curiosity, what use-case do you have in mind for this new command?

**Comment by ionutnechita** [comment]
Hi @gvancuts,

Is for testing and debug hypervisor; I would like to know how long this hypervisor has been running.

**Comment by fuzhongl** [comment]
Not support this feature.
