### ISSUE TITLE
Unable to launch UOS

### ISSUE THREAD

**Issue by bem-nrl** [projectacrn/acrn-hypervisor#560]
Following instructions on https://projectacrn.github.io/latest/getting-started/apl-nuc.html I was able to boot up ACRN using a static IP address without loosing my connectivity in the SOS thanks to your help.

However, I am unable to launch a UOS now.

Here is the output when attempting to launch a UOS:

![screen shot 2018-06-29 at 9 53 35 am](https://user-images.githubusercontent.com/40635569/42160123-11682b0c-7dc4-11e8-99c6-e59f3a515675.png)

The launch script that was used is as follows:

![screen shot 2018-06-29 at 9 54 18 am](https://user-images.githubusercontent.com/40635569/42160164-36a050c0-7dc4-11e8-9ee3-de53142ca965.png)

Attempting to determine if any VM was launched I then did the following:

![screen shot 2018-06-29 at 9 54 31 am](https://user-images.githubusercontent.com/40635569/42160194-5244ab6e-7dc4-11e8-861f-fec61fb4b68c.png)

Not sure if the missing file error above is an indication of some other problem.

Please advise.

Thanks.

**Comment by gvancuts** [comment]
@ttzeng @ailun258 , could you take a look at this issue please?

**Comment by bem-nrl** [comment]
This problem persists. Is there no resolution?

Perhaps someone could  provide a launch_uos.sh script that is working with the latest version of ACRN?

Would using static IP addressing instead of DHCP cause any trouble with this?

Ideally, a working /dev/sda image for the latest ClearLinux/ACRN for the NUC would be awesome provided it either did NOT require network access, or used a static IP address.

**Comment by ttzeng** [comment]
@bem-nrl, I used to use `mem_size=1G` in my launch script, you may give it a try. I don't think the static IP address matter, I can launch the UOS even the device does not connect to the network. Besides, what's your acrn.conf settings? I also have `hugepagesz=1G hugepages=4` in my acrn.conf. FYI.

**Comment by Mingyuan18** [comment]
Can't reproduce this issue.
