### ISSUE TITLE
[doc] Fix typo in document

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#5647]
https://projectacrn.github.io/latest/developer-guides/hld/hv-dev-passthrough.html 

"Remapping of (virtual) PIC interrupts are set up in a similar sequence" should be 
"Remapping of (virtual) MSI interrupts are set up in a similar sequence"

**Comment by dbkinder** [comment]
fixed.

**Comment by NanlinXie** [comment]
[External_System_ID] ACRN-7612
