### ISSUE TITLE
[GuestOS] FreeBSD is it supported to be booted with acrn-dm?

### ISSUE THREAD

**Issue by ionutnechita** [projectacrn/acrn-hypervisor#5681]
Hi ACRN Team,

I would plan in the future to try to start a virtual machine with FreeBSD.

FreeBSD is a free and open-source Unix-like operating system descended from the Berkeley Software Distribution (BSD), which was based on Research Unix. The first version of FreeBSD was released in 1993. In 2005, FreeBSD was the most popular open-source BSD operating system, accounting for more than three-quarters of all installed simply, permissively licensed BSD systems.

Is this possible?
Should i do some workaround?

Thanks.

**Comment by fuzhongl** [comment]
@ionutnechita 
We don't try it yet, please have a try, Any problem please raise git issue.
Thanks!
