### ISSUE TITLE
Keep Open: Used when updating config option documentation in .xsd files

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#5692]
Documentation for ACRN configuration options is now maintained in ``misc/config_tools/schema/*.xsd`` files.  This Jira issue (ACRN-6954) and GitHub issue (5692) are open for reference in GitHub for making edits to the documentation within these files so they're not caught by CI checks as an undocumented code change.

Use ``Tagged-On: #5692`` in PRs that are doc-only changes but also touch one of the ``.xsd`` files to satisfy the CI check.

**Comment by dbkinder** [comment]
[External_System_ID] ACRN-6954

**Comment by NanlinXie** [comment]
Closed with no regression issue.
