### ISSUE TITLE
Unused kernel config (`kernel_config_sos`) in the `acrn-kernel` repo

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#5699]
The reference kernel configuration for the Service VM OS (`sos`) is stored in the `acrn-kernel` repo. We use `kernel_config_uefi_sos` these days, and have been for quite some time. Previously, that reference config was kept in `kernel_config_sos` but that is obsolete by now and completely unused. We should remove this file.

**Comment by NanlinXie** [comment]
[External_System_ID] ACRN-6973

**Comment by gvancuts** [comment]
Patch was merged, closing.
