### ISSUE TITLE
windows ivshmem driver does not work with hv land ivshmem

### ISSUE THREAD

**Issue by chejianj** [projectacrn/acrn-hypervisor#5717]
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/upstream-virtio/virtio-win10-prewhql-0.1-161.zip

Install above driver in WaaG.

It is working with dm land ivshmem, but not working with hv land ivshmem

**Comment by chejianj** [comment]
[External_System_ID] ACRN-6873

**Comment by zhangshuai75** [comment]
Hi @chejianj how did you test the ivshmem? Is there any open source demo or programming information?
