### ISSUE TITLE
[config_tools]  "Create a new scenario" from the "Scenario Setting" menu Fail

### ISSUE THREAD

**Issue by szhen11** [projectacrn/acrn-hypervisor#5723]
Environment

repo: https://github.com/projectacrn/acrn-hypervisor.git
branch: release_2.4
config-tool wiki: https://projectacrn.github.io/latest/tutorials/acrn_configuration_tool.html#instructions
step 4: Load or create the scenario setting
host: ubuntu 18.04

Steps

git clone https://github.com/projectacrn/acrn-hypervisor.git
cd acrn-hypervisor/misc/acrn-config/config_app;python3 app.py
Open Config_app UI by following guide, Click "Scenario Setting" "create a new scenario"
Expected result
can create new scenario successfully

Actual result
error out "500 internal server error" during generate new scenario in browser

Reproduce rate
5/5

**Comment by szhen11** [comment]
during "generate launch script" can also get this error, but can get new launch script.

**Comment by szhen11** [comment]
[External_System_ID] ACRN-6966

**Comment by NanlinXie** [comment]
Closed with no regression issue.
