### ISSUE TITLE
Allow only one active SOS life_mngr socket

### ISSUE THREAD

**Issue by peterfang** [projectacrn/acrn-hypervisor#5736]
At most one VM is allowed to use "--pm_notify_channel uart" at a time, since only one socket connection to SOS life_mngr is allowed.

Monitor the listening socket in SOS life_mngr and close any additional connections after a socket connection is established. Identify a closed socket connection to SOS life_mngr as a failure in dm and fail gracefully.

**Comment by peterfang** [comment]
[External_System_ID] ACRN-6824

**Comment by yuchuyang** [comment]
[External_System_ID] ACRN-6990

**Comment by gvancuts** [comment]
This issue can be closed since the patch got merged.

This is not the right way forward however, but we will follow up in subsequent patches.
