### ISSUE TITLE
The `RELEASE` variable is not correctly handled

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#5772]
The preference nowadays is to use `RELEASE=[y|n]` instead of `[0|1]`. This is also always encoded in the scenario XML file which sets it to `y` or `n`. The value is not correctly handled when building components other than the hypervisor itself. This problem is manifesting itself in a couple of ways:
1. The `build/hypervisor/cfg.log` file does not pick it up correctly and always indicates a `RELEASE` BUILD type unless `RELEASE=0` was used at the command-line
2. Some tools are only built when building a debug version of ACRN, specifically `acrn-crashlog acrnlog acrntrace`. You can see that these are **not** built if the `RELEASE` version is retrieved from the scernario XML or if `RELEASE=n` is used. They are only built when `RELEASE=0` is used at the command-line.

This seems to be a value propagation problem from the `hypervisor/Makefile` up to the top-level Makefile.

**Comment by junjiemao1** [comment]
[External_System_ID] ACRN-6991
