### ISSUE TITLE
Fix incorrect struct definition for ir_bits

### ISSUE THREAD

**Issue by sainath14** [projectacrn/acrn-hypervisor#5773]
Incorrect struct definition for ir_bits in ioapic_rte. Since the bits after the delivery status in the lower 32 bits are not touched by code, this has never showed up as an issue. (And the higher 32 bits in the RTE are aligned by the compiler)

**Comment by sainath14** [comment]
[External_System_ID] ACRN-6989

**Comment by NanlinXie** [comment]
Closed with no regression issue.
