### ISSUE TITLE
ACRN Device Model arguments and parameters out-of-sync

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#5781]
The ACRN Device Model (`acrn-dm`) parameter descriptions in our documentation has gone (once more :-() a bit out of sync with what's in the actual code. These three pages need to be back in sync:
* (Source code) https://github.com/projectacrn/acrn-hypervisor/blob/master/devicemodel/core/main.c (check consistency between `usage()` function and actual implementation
* https://projectacrn.github.io/latest/user-guides/acrn-dm-parameters.html
* https://projectacrn.github.io/latest/developer-guides/hld/hld-devicemodel.html#configuration (the examples throughout the doc also needs updating, inc. https://projectacrn.github.io/latest/developer-guides/hld/hld-devicemodel.html#pci-host-bridge-and-hierarchy)

**Comment by wenlingz** [comment]
@gvancuts Please add JIRA ID, thanks

**Comment by gvancuts** [comment]
[External_System_ID] ACRN-6997

**Comment by gvancuts** [comment]
> 
> 
> @gvancuts Please add JIRA ID, thanks

Done - thanks

**Comment by amyreye** [comment]
@gvancuts What's the status?

**Comment by NanlinXie** [comment]
@gvancuts , could we close this issue now?
