### ISSUE TITLE
The PL2303 USB-to-Serial Devices will function lost after hot-plug

### ISSUE THREAD

**Issue by liudlong** [projectacrn/acrn-hypervisor#5795]
Description
Environment

USB mediator

HW/Board

ALL platform

Build link

Image info

Steps

Expected result

Actual result

Reproduce rate
percentage is not acceptable, please use the actually records like 1/20, 2/20 ,etc.

Debugging info

**Comment by Ragnarliu** [comment]
[External_System_ID] ACRN-6896
