### ISSUE TITLE
[EHL][v2.4_rc1] Failed to boot up WAAG randomly

### ISSUE THREAD

**Issue by szhen11** [projectacrn/acrn-hypervisor#5818]
Environment
BOARD: EHL SBL
SOS Kernel: 5.4.90-linux-intel-ese-lts-acrn-sos-lts
Build Info: YOCTO-2021ww05.3 rc1
 
Steps
1. Boot to SOS
2. Boot up waag with script
 
acrn-dm -A -m $mem_size -s 0:0,hostbridge -U d2795438-25d6-11e8-864e-cb7a18b34643 \
--windows \
$logger_setting \
-s 6,virtio-blk,/root/waag/win10-ltsc.img \
-s 7,virtio-blk,/root/waag/newdisk.img \
-s 5,virtio-net,tap_WaaG,mac=00:16:3E:12:23:34 \
-s 2,passthru,0/2/0,gpu \
--ovmf /usr/share/acrn/bios/OVMF.fd \
$intr_storm_monitor \
-s 1:0,lpc \
-l com1,stdio \
-s 0:20:0,passthru,00/14/0,d3hot_reset \
$vm_name
 
 Expected result
boot up waag successfully
Actual result
sometimes failed to boot up waag , hang on the "welcom" screen , and cannot ping ip 
fail rate:2/10

**Comment by szhen11** [comment]
[External_System_ID] ACRN-6984

**Comment by ionutnechita** [comment]
Hi @gvancuts,

I also saw this issue today.
But with this change made:

-        <ENFORCE_TURNOFF_AC>n</ENFORCE_TURNOFF_AC>
+        <ENFORCE_TURNOFF_AC>y</ENFORCE_TURNOFF_AC>

This issue is not solved.
At startup/booting, virtual machine with Windows does not display an image on the screen.

**Comment by szhen11** [comment]
@ionutnechita Could you describe the configs(board, scenario, launch script, WaaG version and graphics driver version) and steps and  when you see "At startup/booting, virtual machine with Windows does not display an image on the screen."?
