### ISSUE TITLE
Tiger Lake support

### ISSUE THREAD

**Issue by caschulz88** [projectacrn/acrn-hypervisor#5822]
Hi, seems like we are still lacking support for Tiger Lake architecture by Intel. I am using GVT-d based setup but I am not able to make it work with latest ACRN. Can someone please tell me what the status is for the new arch with Intel Xe iGPU? Thanks!

**Comment by fuzhongl** [comment]
@caschulz88 
Please try V2.3 since it is the PV version for Tiger Lake platform.
Thanks!

**Comment by caschulz88** [comment]
Awesome! Thanks a lot!
