### ISSUE TITLE
HV:disable MSI interrupt under some cases in VT-d scenario

### ISSUE THREAD

**Issue by liujunming** [projectacrn/acrn-hypervisor#5847]
In VT-d scenario, if MSI interrupt has been enabled, vCPU writes the content in MSI registers, and all bits of the content are read-only.
In this case, hypervisor code will call enable_disable_msi(vdev, false), which will disable MSI. This is wrong behavior, which will result in the disable of MSI.

**Comment by liujunming** [comment]
[External_System_ID] ACRN-7020

**Comment by NanlinXie** [comment]
Closed with no regression issue.
