### ISSUE TITLE
hybrid_rt scenario does not work with large initrd in pre-launched VM

### ISSUE THREAD

**Issue by fuzhongl** [projectacrn/acrn-hypervisor#5879]
**Describe the bug**
For Hybrid_rt scenario, even the grub related `out of memory` issue fixed by adding `--nounzip` parameter after module2;
pre_launched VM still can't boot up with initrd image if the image is larger than 128M.

**Platform**
KBLNUC WHL TGL

**Codebase**
V2.*

**Scenario**
Hybrid_rt

**Comment by gvancuts** [comment]
Hi @fuzhongl , can you also add a description of the bug/problem in the text above?

**Comment by fuzhongl** [comment]
@gvancuts Just updated the description of the bug.

**Comment by fuzhongl** [comment]
[External_System_ID] ACRN-7049
