### ISSUE TITLE
Nested virtualization in ACRN Hypervisor

### ISSUE THREAD

**Issue by ionutnechita** [projectacrn/acrn-hypervisor#5882]
Hi ACRN Team,

How could i activate Nested Virtualization in ACRN Hypervisor?
I have a Windows VM / WaaG machine and I would like to work with Hyper-V Manager and Docker containers.

![image](https://user-images.githubusercontent.com/9405900/112613079-5c1a5e00-8e28-11eb-89b4-97153ac29a80.png)

In Turn Windown features on and off, Hyper-V Platform option cannot be enabled on.

How can i activate this?
Is this possible?

Scenario used:
Industrial / Industry

ACRN: 2.4

**Comment by gvancuts** [comment]
Hi @ionutnechita , it is not possible to enable this, nested virtualization is not supported on ACRN.

**Comment by ionutnechita** [comment]
Hi @gvancuts,

Do you know any possibilities how I can work with Docker containers in Windows?

**Comment by gvancuts** [comment]
> Do you know any possibilities how I can work with Docker containers in Windows?

I don't I'm afraid.... I'm not an expert on Docker in Windows but my understanding was also that it required virtualization (Hyper-V) to be available... I don't know any way around that :-(

**Comment by ionutnechita** [comment]
Hi @gvancuts,

I observed this ticket:
https://github.com/projectacrn/acrn-hypervisor/issues/5923

Maybe is possible in future. Maybe with ACRN 2.5.

Thanks.

**Comment by gvancuts** [comment]
Hi @ionutnechita , yes, there is some form of nested virtualization that the team is looking into. I have not seen much details yet but my understanding is that the primary use-case is to allow this from within the Service VM. In your case, you would like to do this from a standard post-launched VM, and I'm not sure if that's within the scope of what they're looking at at the moment.

Having said that, @NanlinXie how can we capture this as a feature request to make sure the architects/engineers take it into consideration as part of #5923 ?

**Comment by gvancuts** [comment]
@ionutnechita , FYI, the first set of patches to support nested virtualization have been sent on the mailing list for review: https://lists.projectacrn.org/g/acrn-dev/message/31213
