### ISSUE TITLE
Unable to launch vm at the second time with `pty,/run/acrn/life_mngr_$vm_name` parameter added in the launch script

### ISSUE THREAD

**Issue by lirui34** [projectacrn/acrn-hypervisor#5888]
**Describe the bug**
After adding parameter `pty,/run/acrn/life_mngr_$vm_name` into the launch script, the vm is able to launch at the first try but fail  at the second time once perform the poweroff operation in the vm...

**Platform**
EHL

**Codebase**
`HV release_2.4 branch`

**Scenario**
Hybrid_rt

**To Reproduce**
1. Setting below parameter into the launch script:
     `--pm_by_vuart pty,/run/acrn/life_mngr_$vm_name \`
2. Try the first launch.
3. Poweroff the vm and then try the second launch.
4. VM launch fails and you will see the error prompt that fail to init life_mngr socket:
```
mmap ptr 0x0x7f6494bf6000 -> baseaddr 0x0x7f6494c00000
mmap 0x20000000@0x7f6494c00000
touch 256 pages with pagesz 0x200000
mmap 0x200000@0x7f6594a00000
touch 1 pages with pagesz 0x200000

really setup hugepage with:
        level 0 - lowmem 0x20000000, biosmem 0x200000, highmem 0x0
vm_init_vdevs
pm_by_vuart_init idx: 0, path: /run/acrn/life_mngr_post_vm_id2
initiate a connection on a socket error
create socket to connect life-cycle manager failed
Unable to init vdev (111) 
```

**Comment by fuzhongl** [comment]
fixed in v2.5
