### ISSUE TITLE
Hybrid cores support in hypervisor

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#5918]
For platform with hybrid cores (eg. ADL), the hypervisor shall be able to do enumeration and boot all big and small cores in its context.

**Comment by NanlinXie** [comment]
[External_System_ID] ACRN-6632

**Comment by NanlinXie** [comment]
Doc Impact Analysis: 

- [x] New feature -> new HLD and usage guide
- [ ] [HLDs](https://projectacrn.github.io/2.3/developer-guides/hld/index.html)
- [ ] [Configuration data](https://projectacrn.github.io/2.3/tutorials/acrn_configuration_tool.html)
- [ ] [Kernel module parameters](https://projectacrn.github.io/2.3/user-guides/kernel-parameters.html)
- [ ] [Device Model (acrn-dm) parameters](https://projectacrn.github.io/2.3/user-guides/acrn-dm-parameters.html)
- [ ] [Hypervisor shell commands](https://projectacrn.github.io/2.3/user-guides/acrn-shell.html)
- [ ] [ACRN tools (debug and/or service)](https://projectacrn.github.io/2.3/develop.html#configuration-and-tools)
- [ ] [Build system](https://projectacrn.github.io/latest/getting-started/building-from-source.html)
- [ ] [Other documents (e.g. tutorials)](https://projectacrn.github.io/2.3/develop.html#enable-acrn-features)

**Comment by NanlinXie** [comment]
There's one limitation for configuration: only support assign same cores to a VM.

**Comment by gvancuts** [comment]
> There's one limitation for configuration: only support assign same cores to a VM.

Where should this be mentionned?

Should this HLD be updated as a result of this new feature? https://projectacrn.github.io/latest/developer-guides/hld/hv-cpu-virt.html

**Comment by NanlinXie** [comment]
@lifeix , Any comments?

**Comment by lifeix** [comment]
> > There's one limitation for configuration: only support assign same cores to a VM.
> 
> Where should this be mentionned?
> 
> Should this HLD be updated as a result of this new feature? https://projectacrn.github.io/latest/developer-guides/hld/hv-cpu-virt.html

Actually, we could not claim we have supported hybrid core yet. We still need to assign the same cores to a VM. In theory, this only includes the configuration tool's change. So I think there's no need to update the HLD now. Thanks.

**Comment by NanlinXie** [comment]
The error descirption already updated in config tool xsd file, please check whether document is proper generated. @dbkinder

**Comment by dbkinder** [comment]
@NanlinXie @junjiemao1 We have no processing that turns ``<xs:assert . . . >`` annotations into documentation.  Let's talk about how and where such assert documentation should be processed and generated.

**Comment by dbkinder** [comment]
@NanlinXie I don't think we can close this issue since the the implementation (and documentation) for supporting hybrid cores is not done.

**Comment by NanlinXie** [comment]
@dbkinder , I would like to put the topic "how and where such assert documentation should be processed and generated" into DX future debug discussion. This is a general topic not just this issue. For now, we don't provide the document that described such assert information.  For this issue, there's only change to the assert , thus there's no document change needed, could we close this issue?

**Comment by dbkinder** [comment]
@NanlinXie Is there an update for this?
