### ISSUE TITLE
[acrn-configuration-tool] Audio device should be removed from launch script xml files

### ISSUE THREAD

**Issue by szhen11** [projectacrn/acrn-hypervisor#5925]
Audio pt event should be removed from these launch script xml as below since audio device is no more exist in "ehl-crb-b.xml":

misc/config_tools/data/ehl-crb-b/industry_launch_1uos_waag.xml:         <audio desc="vm audio device">00:1f.3 Multimedia audio controller: Intel Corporation Device 4b58</audio>
misc/config_tools/data/ehl-crb-b/hybrid_rt_launch_1uos_waag.xml:                <audio desc="vm audio device">00:1f.3 Multimedia audio controller: Intel Corporation Device 4b58</audio>
misc/config_tools/data/ehl-crb-b/industry_launch_2uos.xml:              <audio desc="vm audio device">00:1f.3 Multimedia audio controller: Intel Corporation Device 4b58</audio>
Or not it will fail to generate launch script for EHL board:

(venv) root@dailyio:~/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor# ../../generate_script.sh                                                ++ board=ehl-crb-b
++ xml_path=misc/config_tools/data/ehl-crb-b
++ scenario=industry
++ export board_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
++ board_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
++ export scenario_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/industry.xml
++ scenario_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/industry.xml
++ export launch_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml
++ launch_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml
++ python /root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/launch_config/launch_cfg_gen.py --board /root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml --scenario /root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/industry.xml --launch /root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml --uosid 0
Traceback (most recent call last):
  File "/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/launch_config/launch_cfg_gen.py", line 246, in <module>
    err_dic = main(ARGS)
  File "/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/launch_config/launch_cfg_gen.py", line 231, in main
    err_dic = generate_script_file(names, pt_sel, virt_io.dev, dm.args, post_vm_i, config)
  File "/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/launch_config/launch_cfg_gen.py", line 144, in generate_script_file
    com.gen(names, pt_sel, virt_io, dm, vmid, config)
  File "/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/launch_config/com.py", line 666, in gen
    pt.gen_pt_head(names, dm, pt_sel, vmid, config)
  File "/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/config_tools/launch_config/pt.py", line 242, in gen_pt_head
    if not sel.vpid[pt_dev] or not sel.vpid[pt_dev][vmid]:
KeyError: 1

**Comment by szhen11** [comment]
[External_System_ID] ACRN-7029

**Comment by NanlinXie** [comment]
Closed with no regression issue.
