### ISSUE TITLE
How to write an application to test Inter-VM Communication

### ISSUE THREAD

**Issue by zhangshuai75** [projectacrn/acrn-hypervisor#5939]
![ivshmem](https://user-images.githubusercontent.com/41183477/114996320-4c46e480-9ed1-11eb-920b-7863ae71db0d.png)

As shown in the picture, Is there an application demo under linux and windows？
Or where can I find the relevant information? like the ivshmem user-space driver and the API

**Comment by gvancuts** [comment]
Hi @zhangshuai75 , this is a gap, we do not have such tutorial or example code. It would be good to have one. @NanlinXie , who can we assign this to?

**Comment by yonghuah** [comment]
@zhangshuai75 @gvancuts ,  ACRN implements IVHSHMEM device following below device specification defined by KVM/QEMU community: 
https://git.qemu.org/?p=qemu.git;a=blob_plain;f=docs/specs/ivshmem-spec.txt;hb=HEAD

For usage information, please refer to "Enable Inter-VM Communication Based on Ivshmem“
https://projectacrn.github.io/latest/tutorials/enable_ivshmem.html

-Yonghua

**Comment by gvancuts** [comment]
Thanks @yonghuah , I am aware of these documents (and I guess @zhangshuai75 is too), but it would be good to have a small sample app that demonstrates this and can also help users validate that the shared memory segments they set up are working correctly. `man shm_open` (https://man7.org/linux/man-pages/man3/shm_open.3.html) gives a simple example and something similar, but for ACRN would be good to have.

**Comment by zhangshuai75** [comment]
@gvancuts @yonghuah , Thanks, our main purpose now is to test the functionality and performance of ACRN, the application development will be put after the verification. From our point of view, it’s better to have a demo, otherwise we may take a lot of time to write and the test results are not comprehensive

**Comment by gvancuts** [comment]
We need a tutorial on how to use `ivshmem`, let's track this in this request, re-opening. Please assign someone to this task and @dbkinder @fitchbe and I will help review this.

**Comment by NanlinXie** [comment]
@gvancuts, do you agree that we provice some sample code in the document for this requirement?

**Comment by gvancuts** [comment]
> @gvancuts, do you agree that we provice some sample code in the document for this requirement?

That works for me as long as it's clear and accurate enough so that there is no ambiguity.

**Comment by NanlinXie** [comment]
https://github.com/projectacrn/acrn-hypervisor/pull/6973
