### ISSUE TITLE
When reboot RTVM, the SOS reboot

### ISSUE THREAD

**Issue by zhangshuai75** [projectacrn/acrn-hypervisor#5965]
**Describe the bug**
When I reboot the RTVM, the SOS will reboot.

**Platform**
WHL Intel(R) Core(TM) i7-8665U

**Codebase**
$ acrn-dm -v
DM version is: 2.3-cfc3017a6-dirty (daily tag:acrn-2020w48.5-180000p)

**Scenario**
industry

**To Reproduce**

 sudo ./launch_xenomai.sh -b /dev/sda2 -k ../linux-4.19.59-xenomai-3.1-acrn+-x86.tar.gz
or
sudo ./launch_hard_rt_vm.sh

In RTVM, poweroff function is normal, but when running reboot，the SOS will restart after RTVM shuts down.
In other UOS, like Windows,Debian, reboot function is normal.

[launch_hard_rt_vm.sh.txt](https://github.com/projectacrn/acrn-hypervisor/files/6362117/launch_hard_rt_vm.sh.txt)
[launch_xenomai.sh.txt](https://github.com/projectacrn/acrn-hypervisor/files/6362118/launch_xenomai.sh.txt)

**Comment by fuzhongl** [comment]
@zhangshuai75 It works as design since RTVM has high priority than SOS.
Maybe, the policy will be changed later: separate the severity flag and RTVM.
