### ISSUE TITLE
Modularization: hide arch names in include directives

### ISSUE THREAD

**Issue by ylian16** [projectacrn/acrn-hypervisor#5975]
Instead of use explicit arch names, e.g., "include <x86/foo.h>", it is now mandatory to use "include <asm/foo.h>".

The makefile will setup the correct include path based on config.

**Comment by wenlingz** [comment]
@ylian16 please add the JIRA

**Comment by NanlinXie** [comment]
@ylian16 , please use https://github.com/projectacrn/acrn-hypervisor/issues/5920 as tracked on
