### ISSUE TITLE
Add Tiger Lake (TGL) NUC support

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#5988]
* Add TGL support to list of Supported Hardware
* Add TGL NUC board and scenario XML files so simple build instructions can be used

**Comment by gvancuts** [comment]
@NanlinXie , is this something we'd want in 2.5?

**Comment by NanlinXie** [comment]
Yes, we plan to do it in v2.5.

**Comment by gvancuts** [comment]
These tasks have been performed, closing.
