### ISSUE TITLE
Compilation failure with gcc-11

### ISSUE THREAD

**Issue by saininav** [projectacrn/acrn-hypervisor#5993]
Compilation is failing with gcc-11. Throwing [-Werror=array-parameter=] errors

OS: Yocto
GCC:11
ACRN: Release 2.4, Branch: release_2.4
Scenario: Industry
Board:  nuc7i7dnb

Ref: [GCC-11 release notes](https://gcc.gnu.org/gcc-11/changes.html).

Reproducible steps:
(1) Build latest master of all layers by following [guide](https://github.com/intel/meta-acrn/blob/master/docs/getting-started.md)
(2) execute $ bitbake acrn-tools

Error log:
| probeutils.c:61:29: error: argument 1 of type 'char *' declared as a pointer [-Werror=array-parameter=]
|    61 | int get_uptime_string(char *newuptime, int *hours)
|       |                       ~~~~~~^~~~~~~~~
| In file included from /home/saininav/work/development/acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.4-r0/git/misc/debug_tools/acrn_crashlog/acrnprobe/include/load_conf.h:13,
|                  from /home/saininav/work/development/acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.4-r0/git/misc/debug_tools/acrn_crashlog/acrnprobe/include/property.h:24,
|                  from probeutils.c:30:
| /home/saininav/work/development/acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.4-r0/git/misc/debug_tools/acrn_crashlog/acrnprobe/include/probeutils.h:41:28: note: previously declared as an array 'char[24]'
|    41 | int get_uptime_string(char newuptime[24], int *hours);
|       |                       ~~~~~^~~~~~~~~~~~~
| probeutils.c:89:33: error: argument 1 of type 'char *' declared as a pointer [-Werror=array-parameter=]
|    89 | int get_current_time_long(char *buf)
|       |                           ~~~~~~^~~
| In file included from /home/saininav/work/development/acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.4-r0/git/misc/debug_tools/acrn_crashlog/acrnprobe/include/load_conf.h:13,
|                  from /home/saininav/work/development/acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.4-r0/git/misc/debug_tools/acrn_crashlog/acrnprobe/include/property.h:24,
|                  from probeutils.c:30:
| /home/saininav/work/development/acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.4-r0/git/misc/debug_tools/acrn_crashlog/acrnprobe/include/probeutils.h:42:32: note: previously declared as an array 'char[32]'
|    42 | int get_current_time_long(char buf[32]);
|       |                           ~~~~~^~~~~~~
| cc1: all warnings being treated as errors

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-7149
