### ISSUE TITLE
Cannot boot to 5.10 sos on ADL

### ISSUE THREAD

**Issue by shuox** [projectacrn/acrn-hypervisor#6006]
TPAUSE, UMONITOR or UMWAIT instructions execution in guest VM cause
    a #UD if "enable user wait and pause" (bit 26) of VMX_PROCBASED_CTLS2
    is not set. To fix this issue, set the bit 26 of VMX_PROCBASED_CTLS2.

**Comment by shuox** [comment]
[External_System_ID] ACRN-7066

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
