### ISSUE TITLE
Refine the vPCI code for virtual bar emulation

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#6011]
vPCI Code Refine

Boot HV, lots of HV warnings print as below:
pci_vdev_update_vbar_base reprogram PCI:00:15.0 BAR0 to addr:0x607d4e8000, which is out of mmio window[0x0 - 0x0]0
pci_vdev_update_vbar_base reprogram PCI:00:15.1 BAR0 to addr:0x607d4e7000, which is out of mmio window[0x0 - 0x0]0

**Comment by taoyuhong** [comment]
[External_System_ID] ACRN-6924

**Comment by gvancuts** [comment]
Can you also put in this issue the logs showing the problem. I _think_ this is what I saw running ACRN v2.5 on QEMU but it would be good to confirm this by comparing the log output.

**Comment by taoyuhong** [comment]
> Can you also put in this issue the logs showing the problem. I _think_ this is what I saw running ACRN v2.5 on QEMU but it would be good to confirm this by comparing the log output.

Updated

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
