### ISSUE TITLE
config-tools: Obsolete terms cleanup for SSRAM

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#6012]
Update as below:

PSRAM -> SSRAM
PTCT -> RTCT

CONFIG_PSRAM_ENABLED ===> CONFIG_SSRAM_ENABLED

**Comment by yonghuah** [comment]
[External_System_ID] ACRN-7137

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
