### ISSUE TITLE
Make ACRN builds reproducible

### ISSUE THREAD

**Issue by tttech-industrial-buchsbaum** [projectacrn/acrn-hypervisor#6035]
Due to using 'date' command during build and not supporting SOURCE_DATE_EPOCH as recommended at https://reproducible-builds.org/ ACRN builds are not reproducible. Most build and packaging systems require a build to be reproducible. So a first step will be supporting SOURCE_DATE_EPOCH and the possibility to set all items that are part of generated files.

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-6381

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
