### ISSUE TITLE
RDT Configuration tutorial needs to be updated

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#6081]
The current `doc/tutorials/rdt_configuration.rst` is outdated:
* https://projectacrn.github.io/latest/tutorials/rdt_configuration.html#configure-rdt-for-vm-using-vm-configuration (esp. the extract of config files)
* Add `sudo apt install hwloc-nox` as a note so the user has the `lstopo-no-graphics` installed
* Remove the need to be root for `lstopo-no-graphics` (`#` shell prompt)
* Update step 6 that give simplified build instructions (`make` command is no longer valid and it talks about `acrn.efi`)

_Originally posted by @gvancuts in https://github.com/projectacrn/acrn-hypervisor/issues/5917#issuecomment-834307830_

**Comment by dbkinder** [comment]
@amyreye for tutorial update planning, but we know many of these feature enabling tutorials are out of date now.
