### ISSUE TITLE
[acrn-configuration-tool] Need update tgl-rvp.xml to the latest BIOS info

### ISSUE THREAD

**Issue by Kunhui-Li** [projectacrn/acrn-hypervisor#6104]
HV branch: release_2.5
Issue description:
TGL RVP bios now is BIOS TGLIFUI1.R00.4163.A01.2104221540 04/22/2021
But the tgl-rvp.xml board info is: TGLIFUI1.R00.3333.A04.2009091208

**Comment by Kunhui-Li** [comment]
[External_System_ID] ACRN-7169

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-7169
