### ISSUE TITLE
Add the `CONFIG_VIRTIO_BLK` driver to the Service VM kernel configuration

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#6125]
Running ACRN in QEMU requires to slightly tweak the Service VM configuration by adding the `CONFIG_VIRTIO_BLK` driver to it. We should enable this by default in our reference configuration to make the process easier for the user.

**Comment by gvancuts** [comment]
@fuzhongl , FYI

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-6711

**Comment by gvancuts** [comment]
Patch was merged, closing.
