### ISSUE TITLE
Has the migration to the ARM platform been delayed?

### ISSUE THREAD

**Issue by iaGuoZhi** [projectacrn/acrn-hypervisor#6153]
**Describe the feature**

![image](https://user-images.githubusercontent.com/41318515/120752494-677eb980-c53c-11eb-9067-75c6d5261cbe.png)

I found a ACRN proposal where shows ARM platform will been supported in 2019. However there is no arm device in supported hardware now. Has the migration to the ARM platform been delayed?

**Comment by terryzouhao** [comment]
@iaGuoZhi Yes x86 is still main platform in ACRN supported Hardware [list,](urlhttps://projectacrn.github.io/latest/reference/hardware.html).  But ACRN is designed for multi-arch, so really open and welcome other Arch e.g., ARM support and contribution to ACRN community. thanks.
