### ISSUE TITLE
`IGC` driver not in the Service VM kernel config

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#6221]
The latest NUCs based on Intel Tiger Lake (TGL) (e.g. [1]) also come with the Intel Ethernet I225-LM Ethernet adpater. The driver for this is called IGC, this patch enables it (as a module) in the kernel configuration.

[1] https://ark.intel.com/content/www/us/en/ark/products/205594/intel-nuc-11-pro-kit-nuc11tnhi5.html

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-7227
