### ISSUE TITLE
PSE port not working in SOS

### ISSUE THREAD

**Issue by clefrks** [projectacrn/acrn-hypervisor#6237]
**Describe the bug**
PSE TSN GbEs is not working 
([ 19.756677] stmmaceth 0000:00:1d.1 enp0s29f1: stmmac_request_irq: alloc mac MSI -22 (error: -22)

**Platform**
EHL-CRB

**Codebase**
ACRN version 2.3

**Scenario**
Industry

**To Reproduce**
1. Go to https://projectacrn.github.io/2.3/getting-started/rt_industry_ubuntu.html
2. Completed ACRN installation
3. BOOT to acrn
4. dmesg | grep eth
5. ([ 19.756677] stmmaceth 0000:00:1d.1 enp0s29f1: stmmac_request_irq: alloc mac MSI -22 (error: -22)

**Expected behavior**
ethernet has IP and can work

**Additional context**
Attach the following logs if available:

- native Linux boot kernel message log
- ACRN serial port log (when issues happens)
- Service VM kernel message when issue happens
- acrn-dm log: all files in /var/log/acrn-tm
- console log when running script to launch guest VM

**Comment by gvancuts** [comment]
Hi @clefrks , can you attach the logs you mention?

@NanlinXie , I don't have such platform available to me. Can we get someone from the engineering team to look at this once we have the logs?

**Comment by clefrks** [comment]
Attaching the dmesg log
[dmesg-ehl.txt](https://github.com/projectacrn/acrn-hypervisor/files/6706033/dmesg-ehl.txt)

**Comment by fuzhongl** [comment]
@clefrks EHL-CRB isn't  ACRN open source platform; please contact with INTEL FAE who supports your project.

**Comment by clefrks** [comment]
@fuzhongl EHL-CRB and ehl-crb-b is a different platform ? 
`acrn-hypervisor/misc/config_tools/data/ehl-crb-b/`

**Comment by fuzhongl** [comment]
You can generate the board.xml with your EHL platform and compare with the one in acrn-hypervisor/misc/config_tools/data/ehl-crb-b/

BTW: ehl-crb-b is also not ACRN open source platform. please check following link for open source platform:
https://projectacrn.github.io/latest/reference/hardware.html#tested-platforms-by-acrn-release

**Comment by clefrks** [comment]
Closing since ehl crb is not open source platform.
