### ISSUE TITLE
HV: enable #GP for guest uc-lock 

### ISSUE THREAD

**Issue by taoyuhong** [projectacrn/acrn-hypervisor#6299]
The hypervisor shall present a virtual UC lock capability to the guest, and directly deliver #GP to guest. Virtual UC lock capability helps the guest to isolate violations from user land. Guest write of MSR_TEST_CTL is ignored, guest read gets the written value.

**Comment by taoyuhong** [comment]
[External_System_ID] ACRN-6637

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
