### ISSUE TITLE
hv: debug: enable hv console when lapic-pt is enabled on BSP

### ISSUE THREAD

**Issue by yfliuuu** [projectacrn/acrn-hypervisor#6312]
In some scenarios (e.g., nested) where lapic-pt is enabled for a vcpu running on a pcpu hosting console timer, the hv console will be inaccessible. The console can be re-enabled by hooking the callback into every VM-exit event.

**Comment by yfliuuu** [comment]
[External_System_ID] ACRN-7305

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
