### ISSUE TITLE
[config_tools]: "Launch Name" is not work on UI

### ISSUE THREAD

**Issue by Kunhui-Li** [projectacrn/acrn-hypervisor#6316]
**Branch**

master

**Steps**

1. git clone https://github.com/projectacrn/acrn-hypervisor.git
2. python3 misc/acrn-config/config_app/app.py
3. click "Import Board Info " choose  "tgl-rvp"
4. click "Load a default scenario" choose "hybrid_rt"
5. click "Load a default launch setting" choose "hybrid_rt_launch_1uos_waag"
6. click "Generate Launch Script" then fill customized name (xxx) in the "Launch Name" field, and fill ./misc/ path in "Source Path" field, finally click "Submit" button.

**Expected result**

Find xxx.sh under the ./misc/tgl-rvp/output/ directory.

**Actual result**

Find launch_uos_id1.sh under ./misc/tgl-rvp/output/ directory.

**Reproduce rate**

100%

**Comment by Kunhui-Li** [comment]
[External_System_ID] ACRN-7308

**Comment by NanlinXie** [comment]
Closed with no regression issue.
