### ISSUE TITLE
keyboard setting affects the user interface

### ISSUE THREAD

**Issue by liujunming** [projectacrn/acrn-hypervisor#6326]
Tested on TGL with ACRN from master  branch(HV 2.6-unstable-2021-07-23 14:32:34-e3a52d5fa-dirty DBG (daily tag: acrn-2021w30.3-180000p) industry@tgl-rvp build by 1000):

When setting the keyboard to English (United Status) US Keyboard, press “Ctl+Alt+Space” can switch from vm console to acrn shell; press “Ctl+Space” can switch from vm console to acrn shell.

When setting keyboard to **Chinese (Simplified China) Microsoft Pinyin Keyboard**, press “Ctl+Alt+Space” can switch from vm console to acrn shell; **press “Ctl+Space” can NOT switch from vm console to acrn shell**.

**Comment by dbkinder** [comment]
@liujunming @NanlinXie Is this still an issue?  Is there a code fix or do we need to document the issue as a problem with a Pinyin keyboard?  What's the workaround?
