### ISSUE TITLE
[doc] need guideline/constrains doc for guest passthru device enabling

### ISSUE THREAD

**Issue by jsun26intel** [projectacrn/acrn-hypervisor#6337]
Need a guideline/constrain doc to educate user how to enable passthru device for guest VM or what kind of device can't be pass-throughed to guest VM.

**Comment by dbkinder** [comment]
@jsun26intel @NanlinXie Any update on when this is needed and who can help?

**Comment by dbkinder** [comment]
duplicated by (newer) #7031,, so let's close this one.
