### ISSUE TITLE
hv: SMBIOS passthrough: UEFI environment checks should be added before probing

### ISSUE THREAD

**Issue by yfliuuu** [projectacrn/acrn-hypervisor#6345]
Previously SMBIOS passthrough assumes UEFI environment but this may cause problems on non-UEFI environment. Checks should be added before probing SMBIOS table.

**Comment by yfliuuu** [comment]
[External_System_ID] ACRN-6527

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
