### ISSUE TITLE
ACPI NVS region might not be mapped on prelaunched-VM

### ISSUE THREAD

**Issue by yfliuuu** [projectacrn/acrn-hypervisor#6423]
In hypervisor codebase there is an assumption that ACPI NVS/Data region for pre-launched VM is at most 1M. This assumption is no longer true since recent patches to enlarge the ACPI NVS region. As a result the ACPI NVS region might not be mapped because the remaining_hpa_size (arch/x86/guest/vm.c, prepare_prelaunched_vm_memmap) is not large enough.

**Comment by yfliuuu** [comment]
[External_System_ID] ACRN-7346

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
