### ISSUE TITLE
pci_xhci_insert_event SEGV on read from NULL

### ISSUE THREAD

**Issue by liudlong** [projectacrn/acrn-hypervisor#6476]
Test target:  mainline (commit id: c4cb95f3b4023a58b6ceeaa59b8677a2c5c54c24) + 2 hypercube patches with unchanged 2.5 kernel on TGL
mainline (commit id: fdc4da5f72184cb8731c27008fbd43d226de62b5) + 2 hypercube patches with 5.10 kernel on ADL
Test tool: 5 latest Hypercube iso:  hypercube_APIC.iso/ hypercube_PCI_HPET.iso/ hypercube_PCI_USB.iso/ hypercube_PCI_ecam.iso/ hypercube_PIO.iso, built with new scrip- build-all.sh.
Test method: 1: try industry scenario . 2: only boot 1 guest with 1 vcpu. 3: use same launch parameters temporarily
root@intel-corei7-64:~/hypercube# ./launch_pci_hpet.sh

 __________________________

 

Failed to emhw/pci/xhci.c:1822:25: runtime error: member access within null pointer of type 'struct xhci_erst'
ASAN:DEADLYSIGNAL
=================================================================
==348==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55a4ba21c024 bp 0x7fbbe991f910 sp 0x7fbbe991f8b0 T16)
==348==The signal is caused by a READ memory access.
==348==Hint: address points to the zero page.
#0 0x55a4ba21c023 in pci_xhci_insert_event hw/pci/xhci.c:1822
#1 0x55a4ba221ed5 in pci_xhci_reset_port hw/pci/xhci.c:3957
#2 0x55a4ba223a39 in pci_xhci_portregs_write hw/pci/xhci.c:1312
#3 0x55a4ba22e162 in pci_xhci_hostop_write hw/pci/xhci.c:3614
#4 0x55a4ba2408d4 in pci_xhci_write hw/pci/xhci.c:3637
#5 0x55a4ba24750a in pci_emul_mem_handler hw/pci/core.c:532
#6 0x55a4ba30debb in mem_write core/mem.c:148
#7 0x55a4ba315212 in emulate_mem core/mem.c:187
#8 0x55a4ba320156 in vmexit_mmio_emul core/main.c:336
#9 0x55a4ba31f5b8 in handle_vmexit core/main.c:407
#10 0x55a4ba31fa22 in vm_loop core/main.c:707
#11 0x55a4ba320812 in start_thread core/main.c:251
#12 0x7fbd34f6dea3 (/lib/libpthread.so.0+0x8ea3)
#13 0x7fbd33d2ddfe in clone (/lib/libc.so.6+0xf8dfe)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV hw/pci/xhci.c:1822 in pci_xhci_insert_event
Thread T16 (vcpu 0) created by T0 (mevent) here:
#0 0x55a4ba09120f in __interceptor_pthread_create (/usr/bin/acrn-dm+0x18920f)
#1 0x55a4ba31e1a8 in add_cpu core/main.c:277
#2 0x55a4ba322762 in main core/main.c:1092
#3 0x7fbd33c5bcda in __libc_start_main (/lib/libc.so.6+0x26cda)

==348==ABORTING

**Comment by Ragnarliu** [comment]
[External_System_ID] ACRN-7288
