### ISSUE TITLE
PCIE_PTM is not set on sos 5.10 kernel

### ISSUE THREAD

**Issue by GGGZZZRRR** [projectacrn/acrn-hypervisor#6544]
**Describe the bug**
PCIE_PTM is not set on sos 5.10 kernel

**Platform**
ADL-S-CRB

**Scenario**
industry

**To Reproduce**
1.boot to sos with 5.10.56 kernel
2.check kernel config of PTM:
$ zcat /proc/config.gz |grep -i ptm

**Expected behavior**
CONFIG_PCIE_PTM=y

**Additional context**
CONFIG_PCIE_PTM is not set

**Comment by wenlingz** [comment]
@GGGZZZRRR please add JIRA ID, thanks

**Comment by GGGZZZRRR** [comment]
[External_System_ID] ACRN-7374
