### ISSUE TITLE
enable CAT feature on tgl-rvp on v2.5

### ISSUE THREAD

**Issue by mgcao** [projectacrn/acrn-hypervisor#6547]
for TGL-U CAT feature is released now, enable it on release-2.5, so customer can use it easily.

**Comment by wenlingz** [comment]
@mgcao please add JIRA ID, thanks

**Comment by mgcao** [comment]
[External_System_ID] ACRN-7393

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
