### ISSUE TITLE
don't force http.sslVerify to be false in ClearLinux docker

### ISSUE THREAD

**Issue by jren1** [projectacrn/acrn-hypervisor#659]
In https://github.com/projectacrn/acrn-hypervisor/blob/master/.travis-dockerfiles/Dockerfile.clearlinux:
http.sslVerify is forced to be false.
That could introduce the security concern.
Please remove it and try different workaround:
Solution#1: (that will use the Clearelinux auto-proxy)
$ unset https_proxy

Solution#1:
 $ export https_proxy=http://<proxy>:913/

Solution#3:
$ git clone https://.... 
==>
$ git clone http://

**Comment by jren1** [comment]
@gvancuts Please review the fix: https://github.com/projectacrn/acrn-hypervisor/pull/665

**Comment by gvancuts** [comment]
This is a duplicate of #654 , I have submitted a PR (#656) to address this.

**Comment by NanlinXie** [comment]
PR merged, close this issue.
