### ISSUE TITLE
[Doc] Adapt to the new kernel HSM driver

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#6623]
We need go through all the document to check the “HSM “has been updated correctly, especially for the pictures.

**Comment by dbkinder** [comment]
PR #6645 updates doxygen comments that still had VHM references, and PR #6642 updates 19 images with VHM references.

**Comment by amyreye** [comment]
@dbkinder Can we close this issue?

**Comment by dbkinder** [comment]
Done.
