### ISSUE TITLE
Black Screen when booting NUC with Hypervisor

### ISSUE THREAD

**Issue by nwang-intel** [projectacrn/acrn-hypervisor#663]
We found a black screen issue when boot up APL NUC with Hypervisor, After debugging we found it's ClearLinux issue. Here is the work around.

In order to successfully boot up SOS/UOS with their displays (otherwise there is NO display after boot up SOS), the following steps are needed before rebooting native Clear Linux to SOS, 

1. After launching native Clear Linux, you MUST install the ``desktop`` bundle:
        ``$ swupd bundle-add desktop``
2. Get the IP for clearlinux, record IP for ssh login to the SOS in case SOS display fails after the SOS is booted:
        ``$ ip addr``
3. Create the file ``/lib/systemd/system/weston.service`` with the following content:

   ```
   [Unit]
   Description=Weston
   Before=slices.target

   [Service]
   User=root
   Environment=HOME=/root
   WorkingDirectory=/tmp
   Environment=XDG_RUNTIME_DIR=/run/wayland
   ExecStartPre=-/bin/mkdir -p /run/wayland
   ExecStart=/usr/bin/weston --idle-time=0 --log=/var/log/weston.log
   ExecStop=/usr/bin/killall -s TERM weston
   StandardInput=tty
   StandardOutput=journal
   StandardError=journal
   TTYPath=/dev/tty2
   SupplementaryGroups=input

   [Install]
   WantedBy=multi-user.target
   ```
4. Run this command to start the weston service:
        ``$ systemctl enable Weston``

When booting up SOS:

5.	press F7
6.	choose “ACRN Hypervisor"   (hypervisor name set by efibootmgr )
7.	select “The ACRN Service OS”
8.	then enter SOS

After booting up the UOS, step 1)~4) are needed for the UOS display too.

**Comment by dbkinder** [comment]
@nwang-intel  The instructions say a ``weston.service`` file is attached, but there is no such file here.

**Comment by puneetse** [comment]
Thanks for the workaround. It worked for me. 
 
One comment on this step:
> 3. Create the file /lib/systemd/system/weston.service with the following content:

I think  `/etc/systemd/system/weston.service` is a better place to put the custom unit file, because Clear Linux is stateless and /usr is assumed to be owned by the Clear OS. More information on this here: https://clearlinux.org/features/stateless

**Comment by rustylynch** [comment]
I don't understand why you need to install the desktop bundle just to run a command line argument to find the IP address.  /usr/bin/ip is installed with os-core, so you already have that with the most basic native install and you just have to run it in the virtual terminal

**Comment by ttzeng** [comment]
@rustylynch , install the desktop bundle is to use the graphics tools, as the console is not visible when the system boots with the hypervisor and `enable_initial_modeset=1`, so what @nwang-intel is proposing is to get the IP address from a **native** session, then reboot the system and SSH into the SOS to setup the weston.
