### ISSUE TITLE
Current HV_RAM_SIZE calculation algrithom sometimes cause build failure

### ISSUE THREAD

**Issue by lifeix** [projectacrn/acrn-hypervisor#6663]
[External_System_ID] ACRN-7390

**Comment by wenlingz** [comment]
[External_System_ID] ACRN-7390

**Comment by gvancuts** [comment]
This seems to have served as well to remove the `hvlog` parameter from the code. This implies some documentation needs to be updated, at least the `kernel-parameters.rst` and `hld-trace-log.rst` documents.

**Comment by NanlinXie** [comment]
We didn't remove this function, we just remove default configuration in XML file, thus there's no need to update document.

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
