### ISSUE TITLE
Remove the `d3hot_reset` parameter (`acrn-dm`)

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#6665]
We can use the `is_winvm` flag in the `acrn-dm` code to know if the User VM is running Windows (`--windows` parameter). When that's the case, our pass-through code could automatically add the logic behind `d3hot_reset` for the pass-through devices.

_Originally posted by @liuhang-bit in https://github.com/projectacrn/acrn-hypervisor/issues/6445#issuecomment-941963311_

**Comment by dbkinder** [comment]
@liuhang-bit @NanlinXie Is this something that's getting implemented (v2.8)?

**Comment by gvancuts** [comment]
I believe this (#7076) should do it. I have not actually tested it myself though... :-)

**Comment by gvancuts** [comment]
[External_System_ID] ACRN-7609

**Comment by gvancuts** [comment]
Closing as per https://github.com/projectacrn/acrn-hypervisor/pull/7076#issuecomment-1024181337
