### ISSUE TITLE
NUC No serial port, USB to DB9 problem

### ISSUE THREAD

**Issue by LQ-lq** [projectacrn/acrn-hypervisor#6713]
Hi ACRN Team,

NUC11TNHC5 does not have a serial port. I used a USB to DB9 adapter cable. I can log in to Linux but cannot enter the ACRN console.
Is it supported to access the ACRN console using a serial port conversion cable?

**Comment by fuzhongl** [comment]
@LQ-lq Please refer following link to enable serial port over PCIe:
https://projectacrn.github.io/latest/tutorials/using_serial_port.html#option-2-enabling-pcie-serial-port-on-tgl-intel-nuc
