### ISSUE TITLE
Update the `virtio-net` option to explicitly specify the type

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#6727]
The `virtio-net` option uses TAP devices today (either TAP or MacVTap), this distinction between TAP and MacVTap is done at runtime. There may be new types introduced in the future, and currently, the code determines the type of device based on its name, specifically, it treats it as a TAP device if the device name contains the `tap` string in its name.

The objective is to introduce a new parameter that explicitly specify the type of device, instead of deriving it from its name. There shall not be any restriction in the naming of the device once that mechanism is in place. The proposal is to use something akin to this:
```
-s virtio-net,<device-type>=<interface name>[,mac=XX.XX.XX.XX.XX]
```
Where the `<device-type>` indicates the type, i.e. `tap` for TAP/MacVTap devices and `netmap`, as an example as it is not implemented, for a `netmap` type device.

**Comment by dbkinder** [comment]
@gvancuts @NanlinXie What's the status on this?  Do we need to document the rules for naming devices?

**Comment by gvancuts** [comment]
> @gvancuts @NanlinXie What's the status on this? Do we need to document the rules for naming devices?

We have #7059 in flight... but we need to fix the implementation :-(
