### ISSUE TITLE
Documentation is inaccurate for the description of the LOGLEVELs (MEM_, NPK_ and CONSOLE_)

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#6734]
The documentation relative to the three `LOGLEVEL` available (namely `MEM_`, `NPK_` and `CONSOLE_`) is incorrect in that it talks about a number between 0 and 7, but only values from 1 to 6 are described - see 
![image](https://user-images.githubusercontent.com/2192801/139231802-2a62fd2c-6363-4d07-977c-10eae9945934.png)

**Comment by dbkinder** [comment]
Option documentation updated
