### ISSUE TITLE
doc: Update VBSK docs

### ISSUE THREAD

**Issue by amyreye** [projectacrn/acrn-hypervisor#6738]
**Describe the bug**
@liuhang-bit mentioned that VBSK is no longer supported. Please update documentation accordingly. Here are 2 docs that mention VBSK (there may be more, please check): 

- Virtio Devices High-Level Design: https://projectacrn.github.io/latest/developer-guides/hld/hld-virtio-devices.html
- VBS-K Framework Virtualization Overhead Analysis: https://projectacrn.github.io/latest/developer-guides/VBSK-analysis.html

**Comment by liuhang-bit** [comment]
https://github.com/projectacrn/acrn-hypervisor/pull/6824

**Comment by amyreye** [comment]
@NanlinXie @dbkinder I think we can close this issue. Should I do it?

**Comment by NanlinXie** [comment]
Thanks @amyreye , close it.
