### ISSUE TITLE
acrn-crashlog/acrnprobe compilation failure with OpenSSL 3.0

### ISSUE THREAD

**Issue by saininav** [projectacrn/acrn-hypervisor#6743]
With openssl 3.0,  SHA256_Init,  SHA256_Update,  SHA256_Final APIs are deprecated, which causing acrnprobe  compilation failure.

Error log:
| probeutils.c: In function 'compute_key':
| probeutils.c:118:9: error: 'SHA256_Init' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|   118 |         SHA256_Init(&sha);
|       |         ^~~~~~~~~~~
| In file included from probeutils.c:28:
| /acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.7-r0/recipe-sysroot/usr/include/openssl/sha.h:73:27: note: declared here
|    73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
|       |                           ^~~~~~~~~~~
| probeutils.c:125:9: error: 'SHA256_Update' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|   125 |         SHA256_Update(&sha, (unsigned char *)buf, strnlen(buf, VERSION_SIZE));
|       |         ^~~~~~~~~~~~~
| In file included from probeutils.c:28:
| /acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.7-r0/recipe-sysroot/usr/include/openssl/sha.h:74:27: note: declared here
|    74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
|       |                           ^~~~~~~~~~~~~
| probeutils.c:126:9: error: 'SHA256_Update' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|   126 |         SHA256_Update(&sha, (unsigned char *)seed, strnlen(seed, slen));
|       |         ^~~~~~~~~~~~~
| In file included from probeutils.c:28:
| /acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.7-r0/recipe-sysroot/usr/include/openssl/sha.h:74:27: note: declared here
|    74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
|       |                           ^~~~~~~~~~~~~
| probeutils.c:128:9: error: 'SHA256_Final' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|   128 |         SHA256_Final(results, &sha);
|       |         ^~~~~~~~~~~~
| In file included from probeutils.c:28:
| /acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.7-r0/recipe-sysroot/usr/include/openssl/sha.h:76:27: note: declared here
|    76 | OSSL_DEPRECATEDIN_3_0 int SHA256_Final(unsigned char *md, SHA256_CTX *c);
|       |                           ^~~~~~~~~~~~
| cc1: all warnings being treated as errors
| cp ./acrnd.service /acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.7-r0/build/misc/services/acrnd.service
| make[2]: Leaving directory '/acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.7-r0/git/misc/services/acrn_manager'
| Makefile:23: recipe for target '/acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.7-r0/build/misc/debug_tools/acrn-crashlog/acrnprobe/obj/probeutils.o' failed
| make[3]: *** [/acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.7-r0/build/misc/debug_tools/acrn-crashlog/acrnprobe/obj/probeutils.o] Error 1
| make[3]: *** Waiting for unfinished jobs....
| make[3]: Leaving directory '/acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.7-r0/git/misc/debug_tools/acrn_crashlog/acrnprobe'
| Makefile:92: recipe for target 'all' failed
| make[2]: *** [all] Error 2
| make[2]: Leaving directory '/acrn-workspace/poky/build-master/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.7-r0/git/misc/debug_tools/acrn_crashlog'
| Makefile:39: recipe for target 'acrn-crashlog' failed
| make[1]: *** [acrn-crashlog] Error 2

Yocto build:
Poky, branch=master
meta-acrn, branch=master-next or master
BOARD = "nuc11tnbi5"
SCENARIO  = "shared"

**Comment by tw4452852** [comment]
[External_System_ID] ACRN-7510
