### ISSUE TITLE
[v2.7] Vulnerable coding style in hypervisor and applications 

### ISSUE THREAD

**Issue by yfliuuu** [projectacrn/acrn-hypervisor#6769]
Vulnerable coding style in device model
1. Array 'ops->modalias' of size 32 may use index value(s) 32..63

int get_more_acpi_dev_info(char *hid, uint32_t instance, struct acpi_dev_pt_ops *ops)

167 {
168 char pathbuf[128], line[64];
//.....

182 memcpy(ops->hid, hid, 8);
183 memcpy(ops->modalias, line, ch_read);
184 ret = 0;

**Comment by yfliuuu** [comment]
[External_System_ID] ACRN-7474

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
