### ISSUE TITLE
SOS force reboot while launching vxworks

### ISSUE THREAD

**Issue by fuzhongl** [projectacrn/acrn-hypervisor#6799]
Steps:
1. Launch shared scenario.
2. Generate rt script, in virtio-blk event using vxwork img directory instead.
3. launch vxworks.

Expected result:
Launch vxworks successfully.

Actual result:
Platform force rebooted:

 init virtio-blk\x0d
12,1041,17164969807,-;acrn_dm: pci init virtio-net\x0d
6,1042,17164969877,-;acrn-br0: port 3(tap_rt) entered blocking state
6,1043,17164969878,-;acrn-br0: port 3(tap_rt) entered forwarding state
12,1044,17164969921,-;acrn_dm: tpm: init_vtpm2:Invalid socket path!
12,1045,17165034012,-;acrn_dm: acrn_sw_load
12,1046,17165034365,-;acrn_dm: add_cpu
12,1047,17165189367,-;acrn_dm: out instr on NMI port (0x61) not supported
12,1048,17165189454,-;acrn_dm: out instr on NMI port (0x61) not supported
12,1049,17165244391,-;acrn_dm: out instr on NMI port (0x61) not supported
12,1050,17170973722,-;acrn_dm: out instr on NMI port (0x61) not supported
12,1051,17171023753,-;acrn_dm: out instr on NMI port (0x61) not supported
[17194017884us][cpu=8][vm2:vcpu0][sev=3][seq=362]:vlapic: Start Secondary VCPU1 for VM[2]...

**Comment by shiqingg** [comment]
[External_System_ID] ACRN-7463
