### ISSUE TITLE
hv: trampoline size

### ISSUE THREAD

**Issue by YuanyuanZhao609** [projectacrn/acrn-hypervisor#6805]
This is one task of ACRN-7413 which is `Remove some configuration items from user perspecitve`.
More info refer to  https://jira.devtools.intel.com/browse/ACRN-7413 

Add dynamical calculation of `trampoline size` in hv, and remove dependence on CONFIG_LOW_RAM_SIZE.

**Comment by YuanyuanZhao609** [comment]
[External_System_ID] ACRN-7413

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
