### ISSUE TITLE
I'm fallowing 

### ISSUE THREAD

**Issue by Waiting-For-Wind** [projectacrn/acrn-hypervisor#6839]
**Describe the bug**

**Platform**
Describe the platform information, 

**Codebase**
Describe which codebase is used.

**Scenario**
Describe the scenario: Hybrid, Industry or logical_partition

**To Reproduce**

**Expected behavior**

**Additional context**
Attach the following logs if available:

- native Linux boot kernel message log
- ACRN serial port log (when issues happens)
- Service VM kernel message when issue happens
- acrn-dm log: all files in /var/log/acrn-tm
- console log when running script to launch guest VM

**Comment by gvancuts** [comment]
This one seems like a mistake, closing it but feel free to re-open if we need something else than #6840 to track your issues.
