### ISSUE TITLE
I'm fallowing Getting Started Guide install a Service VM But it can't work -- stuck at "loading ACRN..."

### ISSUE THREAD

**Issue by Waiting-For-Wind** [projectacrn/acrn-hypervisor#6840]
Hi everyone ,I'm a Rookie about ACRN and Linux , Hope you can help me , thanks !

**Describe the bug**
I'm fallowing Getting Started Guide install a Service VM But it can't work -- stuck at "loading ACRN..." 
Before this, I find some different from the guide :

0.When I was runing `board_inspector.py`. the terminal print :
```
Resource Allocation is not supported!
WARNING:root:Cannot read the configuration space of 00:14.1 from /sys/devices/pci0000:00/0000:00:14.1/config. Assume the PCI device does not exist.
```
I ignore that.

1. When I `Generate the scenario configuration file:` I can't `Load adefault scenario`  I select a default scenario in `scenario setting list` that scenario is called `industry`.
2. After I build ACRN , I copy the `linux-5.10.52-acrn-sos-x86.tar.gz` to USBdisk , I find the guide is not indicate it path , just `cp linux-5.10.52-acrn-sos-x86.tar.gz $disk/`, so I find `inux-5.10.52-acrn-sos-x86.tar.gz` file in the acrn-work folder , but I'm not found , instead I found a `linux-5.10.52-acrn-sos-gbf7f88634a83-x86.tar.gz` in /acrn-work/acrn-kernel folder, so I copy this file to my USB disk . In addition , the `acrn-2.6-unstable.tar.gz` in my folder is named `acrn-2.6.tar.gz` , but I think this is irrelevant.
3. When I an first see `loading ACRN...` it is like this:
```
loading ACRN...
WARNING: no console will be available to OS
error: file `/boot/vmlinuz-5.10.52-acrn-sos' not found

Press any key to continue...
```
But when I press "any key" there is not a little bit corresponding.

In my computer at `/boot` it is named `vmlinuz-5.10.52-acrn-sos-gbf7f88634a83-x86.tar.gz`

So I correct the `/etc/grub.d/40_custom` file , change ` module2 /boot/vmlinuz-5.10.52-acrn-sos Linux_bzImage` to ` module2 /boot/vmlinuz-5.10.52-acrn-sos-gbf7f88634a83 Linux_bzImage`

It is work , when I reboot , there is none of WARNING or error ,but except `loading ACRN...` there is none of every thing. I press "every key " there is not a little bit corresponding.

In addition to the above operations, the other operations are almost completely in accordance with the guide.

*So I think may be I copy the incorrect  linux-5.10.52-acrn-sos-x86.tar.gz file , or I build a incorrect file.*

Thanks!
Best wish.

**Comment by gvancuts** [comment]
hi @Waiting-For-Wind , we need more details on your set-up. Can you start by describing it?
- HW environment
- ACRN version

Thanks!

**Comment by gvancuts** [comment]
> Your response speed is amazing，and I'm sorry , when I first Edit this my browser crashed. I'm so sorry.

No worries at all! ;-)

**Comment by gvancuts** [comment]
Hi @Waiting-For-Wind , is this still an issue?
