### ISSUE TITLE
[DM] segfault on virtio_console_control_tx()

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#6851]
==440==ERROR: AddressSanitizer: SEGV on unknown address 0x000041b58ab7 (pc 0x55ab324a17ae bp 0x7f7c07e738f0 sp 0x7f7c07e73850 T16)
==440==The signal is caused by a READ memory access.
    #0 0x55ab324a17ad in virtio_console_control_tx /home/pepe/acrn/acrn-fuzzing/acrn-hypervisor/devicemodel/hw/pci/virtio/virtio_console.c:286
    #1 0x55ab324a17ad in ?? ??:0
    #2 0x55ab32497705 in virtio_console_notify_tx /home/pepe/acrn/acrn-fuzzing/acrn-hypervisor/devicemodel/hw/pci/virtio/virtio_console.c:394

**Comment by yonghuah** [comment]
[External_System_ID] ACRN-7468

**Comment by NanlinXie** [comment]
Closed since patch merged without regression.
