### ISSUE TITLE
Release document verification

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#6873]
In each release, we need ensure below documents are verified:
1. Supported Hardware: https://projectacrn.github.io/latest/reference/hardware.html
2. Configuration and Development Overview: https://projectacrn.github.io/latest/getting-started/overview_dev.html
3. Getting Started Guide: https://projectacrn.github.io/latest/getting-started/getting-started.html
4. Getting Started Guide for ACRN Hybrid Mode: https://projectacrn.github.io/latest/tutorials/using_hybrid_mode_on_nuc.html
5. Getting Started Guide for ACRN Partitioned Mode: https://projectacrn.github.io/latest/tutorials/using_partition_mode_on_nuc.html
6. Configtool:
https://projectacrn.github.io/latest/tutorials/acrn_configuration_tool.html
https://projectacrn.github.io/latest/tutorials/board_inspector_tool.html
https://projectacrn.github.io/latest/tutorials/acrn_configurator_tool.html

**Comment by fuzhongl** [comment]
All doc were verified and PRed for v2.7.
