### ISSUE TITLE
Remove CONFIG_LOG_DESTINATION

### ISSUE THREAD

**Issue by weichenli-intel** [projectacrn/acrn-hypervisor#6934]
Remove CONFIG_LOG_DESTINATION from hv and config tool, check the loglevel of each channel, close the
output when the loglevel is ZERO.

[External_System_ID] ACRN-7432

**Comment by NanlinXie** [comment]
[External_System_ID] ACRN-7432

**Comment by NanlinXie** [comment]
Patch merged and close with no regression.
