### ISSUE TITLE
No "--cpu_affinity" under acrn-dm cmdline when launch script generated with cpu "SCHED_NOOP"

### ISSUE THREAD

**Issue by Weiyi-Feng** [projectacrn/acrn-hypervisor#6961]
**Describe the bug**
No "--cpu_affinity" under acrn-dm cmdline when launch script generated with cpu "SCHED_NOOP"

**Codebase**
master

**Scenario**
shared

**To Reproduce**
1.use config tool to change scenario xml with "SCHED_NOOP"
2.load  a default launch script "shared_launch_2user_vm.xml" 
3.generate launch script

**Expected behavior**
can find "--cpu_affinity" under acrn-dm cmdline in the launch script

**Comment by wenlingz** [comment]
please add JIRA ID

**Comment by Weiyi-Feng** [comment]
[External_System_ID] ACRN-7530

**Comment by NanlinXie** [comment]
patch merged and close with no regression
