### ISSUE TITLE
Possible race conditions in method virtio_blk_abort?

### ISSUE THREAD

**Issue by ycaibb** [projectacrn/acrn-hypervisor#6964]
Hi, developers, the  `vq_relchain(vq, idx, 1);`  and `vq_endchains(vq, 0);` should be guarded by lock `blk->mtx` in the method  `virtio_blk_abort` just as in the method `virtio_blk_done`.
https://github.com/projectacrn/acrn-hypervisor/blob/a65e01ae9547be78ccad26333a907743c8c8c5d7/devicemodel/hw/pci/virtio/virtio_block.c#L215-L228

**Comment by NanlinXie** [comment]
@liuhang-bit , any comments?

**Comment by ycaibb** [comment]
@liuhang-bit  @NanlinXie  Hi, could you take a look?
