### ISSUE TITLE
Update severity of Safety VM and post-launched RTVM

### ISSUE THREAD

**Issue by wuxyintel** [projectacrn/acrn-hypervisor#6993]
Update severity of pre-launched Safety VM to SEVERITY_STANDARD_VM since there is no customer requirement for it.
Update severity of post-launched RTVM to SEVERITY_STANDARD_VM since isolation from Service VM has not been fully implemented. Service VM can shut down post-launched RTVM forcefully.

**Comment by gvancuts** [comment]
```
doc/user-guides/acrn-dm-parameters.rst
doc/developer-guides/hld/hld-power-management.rst --> (6) S3 is only available on configurations that have no DM launched RTVM. ?)

```

**Comment by NanlinXie** [comment]
This change didn't get approval yet, let's close it for now and reopen if we have clear plan for that.
