### ISSUE TITLE
Failed to start acrnd service in Service VM

### ISSUE THREAD

**Issue by wuxyintel** [projectacrn/acrn-hypervisor#6994]
Currently, if user starts acrnd service, acrnd service will fail to find the folder "/sys/kernel/gvt" in Service VM.
Root cause is GVT-g is not supported in current ACRN, the folder "/sys/kernel/gvt" will not be created in Service VM.

**Comment by gvancuts** [comment]
Out of curiosity, is the `After=weston.service` line not a problem?

What is the OS running in the Service VM here?

**Comment by wuxyintel** [comment]
Hi Geoffory, weston is the reference implementation of a Wayland server. A Wayland server is a display server, a window manager, and a compositor all in one. Weston service is optional for ACRN, so I will remove this configuration in acrnd service. I verified it on Ubuntu Service VM.

**Comment by gvancuts** [comment]
> Hi Geoffory, weston is the reference implementation of a Wayland server. A Wayland server is a display server, a window manager, and a compositor all in one. Weston service is optional for ACRN, so I will remove this configuration in acrnd service. I verified it on Ubuntu Service VM. Thanks!

Thanks!

**Comment by wuxyintel** [comment]
[External_System_ID] ACRN-7575
