### ISSUE TITLE
RTCT table virtualization

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#7010]
Support  virtualization of Software SRAM for user MV on ACRN.

Doc Impact Analysis: 

- [x] New feature -> new HLD and usage guide
- [x] [HLDs](https://projectacrn.github.io/2.3/developer-guides/hld/index.html)
- [ ] [Configuration data](https://projectacrn.github.io/2.3/tutorials/acrn_configuration_tool.html)
- [ ] [Kernel module parameters](https://projectacrn.github.io/2.3/user-guides/kernel-parameters.html)
- [ ] [Device Model (acrn-dm) parameters](https://projectacrn.github.io/2.3/user-guides/acrn-dm-parameters.html)
- [ ] [Hypervisor shell commands](https://projectacrn.github.io/2.3/user-guides/acrn-shell.html)
- [ ] [ACRN tools (debug and/or service)](https://projectacrn.github.io/2.3/develop.html#configuration-and-tools)
- [ ] [Build system](https://projectacrn.github.io/latest/getting-started/building-from-source.html)
- [ ] [Other documents (e.g. tutorials)](https://projectacrn.github.io/2.3/develop.html#enable-acrn-features)

**Comment by yonghuah** [comment]
[External_System_ID] ACRN-7497

**Comment by dbkinder** [comment]
Format of dm ``--ssram`` option is changing with v3.0 so doc update is still needed
