### ISSUE TITLE
Add TGL Vecow configuration files

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#7019]
We need enable the commercially available TGL IPC (Vecow) as our OpenSource recommended platform.

**Comment by NanlinXie** [comment]
[External_System_ID] ACRN-7514

**Comment by dbkinder** [comment]
We need to document (supported hardware doc perhaps) what the BIOS settings (e.g., Hyperthreading enabled, Turbo mode enabled?) and Hardware settings (e.g., memory size) are assumed by this Vecow configuration (xml) file.

**Comment by dbkinder** [comment]
We've got the configuration files in the repo, but need to update the supported hardware page
