### ISSUE TITLE
Release Note update for v3.0

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#7028]
Use this issue to record the future v2.8 Release Note change:
1. "–cpu_affinity": Original vcpu_affinity means the vcpus' pcpu affinity, We changed the interface to Service VM's point of view. @YuanyuanZhao609 
2. PMU/PEBS supported in RTVM, vtune/perf can run in RTVM.
3. Need additional library in both build/target machine:  sudo apt-get install libcjson-dev 
Refer to https://github.com/projectacrn/acrn-hypervisor/pull/7101
Note: for ubuntu 18.04, if you want to install libcjson-dev, you need follow below steps:
sudo add-apt-repository ppa:jrtc27/cjson
sudo apt-get update
sudo apt install libcjson1 libcjson-dev
4. Virtio-GPU VF creation and offline CPU guide and script
5. scenario XML data modification
6. New configuration upgrade document added : https://github.com/projectacrn/acrn-hypervisor/pull/7312
Rather than installing the Python dependencies by hand, those libraries shall now be installed by referring to the requirements.txt in the repo:
sudo pip3 install -r acrn-hypervisor/misc/config_tools/requirements.txt

**Comment by dbkinder** [comment]
@NanlinXie Good idea.

**Comment by junjiemao1** [comment]
Rather than installing the Python dependencies by hand, those libraries shall now be installed by referring to the `requirements.txt` in the repo:

`sudo pip3 install -r acrn-hypervisor/misc/config_tools/requirements.txt`
