### ISSUE TITLE
Handling of undefined hypercall/ioctl

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#7029]
1 ACRN hypervisor shall handle undefined or obsoleted hypercalls as follows.

When the hypercall invokes a function that is undefined for the requester VM, the hypervisor shall return -ENOSYS (which indicates that the function is not implemented).
When the hypercall invokes a function that has been obsoleted and dropped for the requester VM, the hypervisor shall return -ENOSUP (which indicates the operation is not supported).
Note:

A function of a hypercall is identified by the hypercall ID.
A function is "undefined" with regard to a specific version X of the hypervisor if the hypercall ID is not defined in any version up to version X.
A function is "obsoleted" with regard to a specific version X of the hypervisor if the hypercall ID is defined in any version prior to X but not in X itself.

2. ACRN HSM shall handle undefined or obsoleted ioctl requests as follows.

When the ioctl issues a request that is undefined, the HSM shall return -ENOSYS (which indicates that the function is not implemented).
When the ioctl issues a request that has been obsoleted and dropped, the HSM shall return -ENOSUP (which indicates the operation is not supported).
Note:

An ioctl request is identified by the second parameter request.
A request is "undefined" with regard to a specific version X of the HSM if the request is not defined in any version up to version X.
A request is "obsoleted" with regard to a specific version X of the HSM if the request is defined in any version prior to X but not in X itself.

**Comment by dbkinder** [comment]
Should there be a logging requirement as well?
