### ISSUE TITLE
config_tools: update board_inspector to fetch missing pci device names

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#7086]
As described in the discussion of PR #7061, the board_inspector should show PCI vendor and device IDs as a human-readable string. If the target systems ``pci.ids`` file is outdated when we run the board_inspector, only the PCI vendor and device code numbers are shown.  For example, instead of showing this:
```
00:00.0 Host bridge: Intel Corporation Device 3e30 (rev 0d)
```
we should show this, with updated PCI ID information if it's missing:
```
00:00.0 Host bridge: Intel Corporation 8th/9th Gen Core 8-core Desktop Processor Host Bridge/DRAM Registers [Coffee Lake S] (rev 0d)
```

As a DX improvement, in the board_inspector tool, update the calls to ``lspci`` to include the ``-q`` option.

In the man page for lspci it says:
```
      -q     Use DNS to query the central PCI ID database if a device is not found in the local pci.ids file. If the
              DNS  query  succeeds,  the  result is cached in ~/.pciids-cache and it is recognized in subsequent runs
              even if -q is not given any more.
```

**Comment by yuchuyang** [comment]
Out of curious, since we may retire the <PCI_DEVICE> section which calls lspci to list the available pci devices. Instead, UI may query the list of available pci devices based on the vendor, identifier, subsystem_vendor, subsystem_identifier, class...with pci.ids
Shall we still try to fix the lspci option or always force the pci.ids to be up-to-date?

**Comment by dbkinder** [comment]
If you remove the <PCI_DEVICE> section of the board.xml file, where will you get a list of available PCI devices found on the target when you run the configurator UI on the development machine?  I haven't heard any plans run the configurator UI on the target? @gvancuts Your thoughts?

**Comment by gvancuts** [comment]
> Just to clarify: even when we remove the PCI_DEVICE section in board XML, we still use pci.ids to fetch a proper description of the device, though this is done directly by the board inspector, not via `lspci` any more. So it still makes sense to update pci.ids.

OK, if I understand you correctly @junjiemao1 , we cannot rely on this automatic fetching of the latest data that is built into the `lspci -q` mechanism. Or is the plan for the tool to be able to do this (similar to what's done [here](https://github.com/pciutils/pciutils/blob/master/lib/names-net.c)?
