### ISSUE TITLE
Do we or plan to support virtio mmio bus?

### ISSUE THREAD

**Issue by archersmind** [projectacrn/acrn-hypervisor#7087]
It seems that `acrn` only supports `PCI` bus for `virtio`, my question is do we have any plan to support `mmio` bus in the future? Any roadmap planned?

Many thanks to the acrn team.

**Comment by gvancuts** [comment]
@anthonyzxu @terryzouhao can you take a look at this question please?

**Comment by ywan170** [comment]
Hi Alan,

We have no plan to support mmio based virtio devices as we only support X86 so far.
Once the ACRN supports the ARM platform then this is a must-have feature.
BTW, may I know what is your usage for this requirement?

Thanks
Yu

**Comment by archersmind** [comment]
Thank you Yu for the reply,

Actually we're conducting some research to bring up acrn on top of ARM platform, so the the question would be ARM support is in your roadmap yet?

**Comment by terryzouhao** [comment]
@archersmind, Glad to see you are interested and researching enabling ACRN on ARM platform. Basically, ACRN is designed to support multi-architectures, including ARM, but only enabled and verified on IA platform yet. As open source project, ACRN is open and welcome everybody in community to contribute ARM enabling, we can discuss more for any idea/proposal in mailing list for detailed technical discussing first, then come to TSC for design/arch approval next.

**Comment by archersmind** [comment]
Thank you guys, totally understood!
