### ISSUE TITLE
Python traceback if the 'dpkg' tool is not available

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#7109]
Our `Makefile` will, by default, try to build a Debian package of ACRN. This is very useful to users and is the right thing to do since we only officially support Ubuntu. It does, however, generate an error if we attempt to build ACRN on a non-Debian system (which wouldn't have the `dpkg` utility).

It would be preferable from a user point of view to catch this ahead of running the script and simply ignore this last step (i.e. ACRN and all artefacts would still be built, just that a Debian package with all of these would not be created).

**Comment by NanlinXie** [comment]
[External_System_ID] ACRN-7612

**Comment by dbkinder** [comment]
dpkg check is merged now.
