### ISSUE TITLE
Predefined tgl-vecow-spc-7100-Corei7 scenario and launch XML disagree

### ISSUE THREAD

**Issue by dbkinder** [projectacrn/acrn-hypervisor#7156]
The predefined XML files found in ``/misc/config_tools/data/tgl-vecow-spc-7100-Corei7`` disagree about the system configuration.
The ``shared.xml`` defines  a SERVICE_VM (ID 0) where the root for booting is ``root=/dev/sda3`` and the image name is ``Linux_bzImage``, and defines one POST_LAUNCHED_VM (ID 1).  

The ``shared_launch_2user_vm.xml`` defines VM ID 1 as a WINDOWS VM where the image can be found at ``./win10-ltsc.img``
and also defines a HARD_RT VM with VM ID 2 with it's image at ``./core-image-weston-intel-corei7-64.wic``

**VM ID 2 is not defined in the scenario.xml** and the launch xml can't define more VMs than what's in the scenario.xml, right?

**Comment by dbkinder** [comment]
@junjiemao1 should the configurator catch a launch XML with more VMs than defined in the scenario XML?

**Comment by junjiemao1** [comment]
Having duplicated information in scenario and launch XMLs leads to potential inconsistency here and there, and this disagreement of the number of VMs is one of them.

In v3.0 we'll get rid of these by merging data in launch XMLs into the scenario XML.
