### ISSUE TITLE
Copying kernel file in GSG for Partitioned Mode

### ISSUE THREAD

**Issue by xsltzx** [projectacrn/acrn-hypervisor#7168]
Hello，I have some doubts about this step in GSG for partitioned mode

![9153084c1f82a45d58376e1ac24acc1](https://user-images.githubusercontent.com/57651262/156164607-ed16db6d-f522-467f-ad30-91e53339dc50.png)

The kernel release info means the original kernel of the target computer itself(for example 5.4.0-89-generic), or it means the Service VM kernel(for example vmlinuz-5.10.65-acrn-service-vm) as well as initrd.img's version. I want to know which version should I choose for partitioned mode, 

I am using version 2.7.

thanks.

**Comment by gvancuts** [comment]
It's the original kernel you want to use in the pre-launched VM, not the Service VM one.

**Comment by xsltzx** [comment]
> It's the original kernel you want to use in the pre-launched VM, not the Service VM one.

Oh, thanks for your reply and now I know that.
