### ISSUE TITLE
Exception"not enough space in guest VE820 SSRAM area" showed when built ACRN with RTCT table

### ISSUE THREAD

**Issue by izhouwu** [projectacrn/acrn-hypervisor#7212]

**Comment by izhouwu** [comment]
[External_System_ID] ACRN-7629

**Comment by izhouwu** [comment]
SSRAM area in GPA has been hard-coded to 8MB. Changing it to actual area size could fix the issue.

**Comment by NanlinXie** [comment]
Closed with no regression.
