### ISSUE TITLE
Remove SCHED_IORR and KERNEL_RAWIMAGE

### ISSUE THREAD

**Issue by amyreye** [projectacrn/acrn-hypervisor#7256]
Issues:
1. Remove SCHED_IORR and KERNEL_RAWIMAGE in the XSD.
2. Update documentation that mentions IORR:
    - https://projectacrn.github.io/latest/developer-guides/hld/hv-cpu-virt.html
    - https://projectacrn.github.io/latest/tutorials/cpu_sharing.html

**Comment by fuzhongl** [comment]
[External_System_ID] ACRN-8734
