### ISSUE TITLE
boot time issue for acrn-dm

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#7298]
When Post-launched VM's memory is setup to 9G, the boot time from launching acrn-dm to the Guest VM initiate done  more then 2s. The time is too long, and it is because the Guest memory is erased twice during initiate, need to remove one erasing.

**Comment by conghuic23** [comment]
[External_System_ID] ACRN-8800

**Comment by conghuic23** [comment]
[External_System_ID] ACRN-8735

**Comment by NanlinXie** [comment]
Closed with no regression issue.
