### ISSUE TITLE
[Virtio-GPU]Not enough free memory reserved in SOS

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#7301]
Test step:

1: BOOT to ACRN and SOS 

2.check memory in SOS found the free memory is only more than 900M, and when log in local UI , system will crash;

Expect result: enough free memory for used in SOS and no crash happened 

Actual Result: No enough free memory in SOS and that sometimes cause crash when login SOS local UI

Fail Rate: 100%

**Comment by NanlinXie** [comment]
[External_System_ID] ACRN-8696

**Comment by dbkinder** [comment]
Please use "Service VM" instead of "SOS" :)

**Comment by NanlinXie** [comment]
Closed with no regression
