### ISSUE TITLE
The Debian packaging incorrectly indicates a runtime dependency on a development package (for SDL2).

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#7311]
This is incorrect, we need the `libsdl2-2.0-0` package and not the development package. Can you please submit a new PR to correct this?

_Originally posted by @gvancuts in https://github.com/projectacrn/acrn-hypervisor/pull/7293#discussion_r852767280_

**Comment by fuzhongl** [comment]
Fixed in PR 7319:
https://github.com/projectacrn/acrn-hypervisor/pull/7319/commits/44ef41e8cf51854fa96e9a53c5711573302f23dc
