### ISSUE TITLE
ACRN debug version build fail for board which doesn't have serial port

### ISSUE THREAD

**Issue by fuzhongl** [projectacrn/acrn-hypervisor#7313]
**Describe the bug**

**Platform**
TGLNUC without serial port

**Codebase**
V2.7 or master

**Scenario**
Shared

**To Reproduce**
Build debug version fail for board which doesn't have serial port.
That error was: “lib.error.ResourceError: ttyS0 is not in the native environment! The ttyS available are: dict_keys([])”

**Comment by gvancuts** [comment]
Duplicate of #7069
