### ISSUE TITLE
Build will fail when using absolute path

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#7345]
Build error log:

scripts/makefile/config.mk:185: The command line sets SCENARIO to be '', but an existing build is configured with 'scenario'
scripts/makefile/config.mk:185: Try cleaning up the existing build with 'make clean' or setting HV_OBJDIR to a newly-created directory
scripts/makefile/config.mk:185: *** Configuration conflict identified.  Stop.
make[1]: Leaving directory '/root/acrn-configurator/acrn-hypervisor/hypervisor'
make: *** [Makefile:133: hvdefconfig] Error 2

**Comment by conghuic23** [comment]
[External_System_ID] ACRN-8735

**Comment by NanlinXie** [comment]
Closed with no regression
