### ISSUE TITLE
[UI]Not delete all VMs while delete Service_VM on UI

### ISSUE THREAD

**Issue by conghuic23** [projectacrn/acrn-hypervisor#7349]
In UI, no any warning when delete Service VM , and can delete Service_VM and keep other VMs saved successfully.
The design behavior is: warning will pop up and all Posted-launched VMs will be deleted when Service VM is deleted.

**Comment by conghuic23** [comment]
[External_System_ID] ACRN-8736

**Comment by NanlinXie** [comment]
Closed with no regression
