### ISSUE TITLE
[UI]  Board info not updated when user changed the board XML

### ISSUE THREAD

**Issue by Weiyi-Feng** [projectacrn/acrn-hypervisor#7356]
**Describe the bug**
 Board info not updated when user changed the board XML

**Platform**
ACRN Configurator on all Platform which it supported

**Codebase**
master

**To Reproduce**
1. Start configurator
2. import board file
3. change board file
4. Board Info still is step2's.

**Expected behavior**
Board Info updated.

**Comment by NanlinXie** [comment]
[External_System_ID] ACRN-8729

**Comment by NanlinXie** [comment]
Closed with no regression
