### ISSUE TITLE
Virtio-GPU in guest_vm fails to get the EDID

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#7376]
After the virtio-gpu is loaded in guest_vm, it will read the EDID to check the supported resolution. This is based on
VIRTIO_GPU_CMD_GET_EDID request and the VIRTIO_GPU_RESP_OK_EDID response.
But now the virtio-gpu fails to get the EDID.

**Comment by yakuizhao** [comment]
[External_System_ID] ACRN-8788

**Comment by NanlinXie** [comment]
Closed with no regression.
