### ISSUE TITLE
[acrn-configuration-tool][acrn-deb] grub is not update correctly after install the acrn-deb

### ISSUE THREAD

**Issue by zhangqiang4** [projectacrn/acrn-hypervisor#7400]
Steps:
1. install partitioned acrn deb
2. reinstall shared acrn deb on sos:

apt install ./acrn-adl-s-crb-shared.deb --reinstall

3. check the grub.cfg.

Expected result:
3. Should not see ACPI module entry from the grub.cfg.

Actual result:
3. Though we reinstalled the shared acrn deb, we can still see the ACPI bin for partitioned ACRN is written to the grub.cfg.

Reproduce rate:
100%

**Comment by zhangqiang4** [comment]
[External_System_ID] ACRN-8850

**Comment by NanlinXie** [comment]
Close with no regression.
