### ISSUE TITLE
[config_tool] Virtual USB HCI should be a dropdown menu

### ISSUE THREAD

**Issue by zhangqiang4** [projectacrn/acrn-hypervisor#7424]
To help generate launch script about USB mediator devices,
Virtual USB HCI should be a dropdown menu in Configurator:

droplist: 
<bus number-port number>

data format:xhci,1-2,2-2

**Comment by zhangqiang4** [comment]
[External_System_ID] ACRN-8822

**Comment by NanlinXie** [comment]
Close with no regression.
