### ISSUE TITLE
[config_tool] No validation for required fields in widgets

### ISSUE THREAD

**Issue by izhouwu** [projectacrn/acrn-hypervisor#7481]
How Found: DX review

In widgets like IVSHMEM and vUART, there are several fields marked "required". However, when you leave the fields blank and then save the configuration, there is no error message that tells the user that the field is required. Fields outside of widgets have the error message, but fields inside the widgets do not.

**Comment by izhouwu** [comment]
[External_System_ID] ACRN-8866

**Comment by NanlinXie** [comment]
Close with no regression.
