### ISSUE TITLE
[config_tool] Starting new configuration deletes all files in existing working folder

### ISSUE THREAD

**Issue by zhangqiang4** [projectacrn/acrn-hypervisor#7495]
How Found: DX review
Found in 2022/05/12 daily build

Steps:

Under "Start a new configuration," select an existing folder that has a non-ACRN file in it, such as a PNG image file.
Warning message appears that says all files will be deleted.
Configurator deletes all files, including PNG image file.

**Comment by zhangqiang4** [comment]
[External_System_ID] ACRN-9006

**Comment by NanlinXie** [comment]
Close with no regression.
