### ISSUE TITLE
board_inspector.py fails to run on target with clean Ubuntu installation

### ISSUE THREAD

**Issue by zihengL1** [projectacrn/acrn-hypervisor#7498]
After installing board_inspector debian package (built from master) on a clean Ubuntu 20.04 installation on my Vecow target system, running the board inspector fails with:

    david@Vecow:~$ sudo board_inspector.py vecow-3.0
    Traceback (most recent call last):
      File "/usr/bin/board_inspector.py", line 22, in <module>
       from inspectorlib import validator
      File "/usr/bin/inspectorlib/validator.py", line 12, in <module>
       import xmlschema
    ModuleNotFoundError: No module named 'xmlschema'

**Comment by zihengL1** [comment]
[External_System_ID] ACRN-8922

**Comment by NanlinXie** [comment]
Close with no regression.
