### ISSUE TITLE
[config_tool] Failed to delete post-launched VM due to IVSHMEM

### ISSUE THREAD

**Issue by izhouwu** [projectacrn/acrn-hypervisor#7500]
step:
Sprint:ACRN bugs Sprint 21 (ww20-21)
How Found:by-dev
Platform/Program:
ADL
Found in build:daily-build/2022ww14.5-2

Open UI
Use new working folder.
Import board, and create new scenario (shared).
 remove 'VM1'

VM1 can not be removed.

Error:

Config.vue:289 
        
    Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'IVSHMEM_REGION')
    at Proxy.vmNameChange (Config.vue:289:47)
    at Config.vue:258:16

**Comment by izhouwu** [comment]
[External_System_ID] ACRN-9017

**Comment by NanlinXie** [comment]
Close with no regression.
