### ISSUE TITLE
[configurator] Assigning one cpu to multiple Pre-launched VMs is not reported as error

### ISSUE THREAD

**Issue by zhangqiang4** [projectacrn/acrn-hypervisor#7526]
steps to reproduce:

1. launch configurator
2. import a board xml
3. create a hybrid scenario with 2 Pre-launched VMs
4. assign cpu1 to both Pre-launched VMs
5. click save button

Expected Result:

Prompt that cpu assigned to Pre-launched VM could not be assigned to other VM

Actual Result:

Validation passed and scenario.xml saved.

**Comment by zhangqiang4** [comment]
[External_System_ID] ACRN-9032

**Comment by NanlinXie** [comment]
Close with no regression.
