### ISSUE TITLE
config-tools: add vhost vsock in v3.0

### ISSUE THREAD

**Issue by izhouwu** [projectacrn/acrn-hypervisor#7535]
add a new parameter for vsock.
• The parameter format is like “-s 7 vhost-vsock cid=19”
• The cid value should in 2 ~ 0xffffffff.
• One VM only can have on vsock and it is only for post VM.
What is Vsock ?
New socket address family for host/guest communication.

 expect to have this parameter set in UI for v3.0 and generate the parameter in launch script

**Comment by izhouwu** [comment]
[External_System_ID] ACRN-9020

**Comment by NanlinXie** [comment]
Close with no regression.
