### ISSUE TITLE
[config_tool]: rename virtio console as virtio serial port(as console)

### ISSUE THREAD

**Issue by Kunhui-Li** [projectacrn/acrn-hypervisor#7540]
virtio serial port and virtio console are all based on virito serial port .
but virtio serial port functionally can not be used as console, which may lead to user confusion, so explicitly specify the point by changing the item name as follows:
virtio console -> virtio serial port (as console)

**Comment by Kunhui-Li** [comment]
[External_System_ID] ACRN-9043

**Comment by NanlinXie** [comment]
Close with no regression.
