### ISSUE TITLE
[config_tool] VUART is configured to PCI and generate launch script without relevant parameters

### ISSUE THREAD

**Issue by Kunhui-Li** [projectacrn/acrn-hypervisor#7556]
**Describe the bug**
After VUART is configured to PCI, the generated launch script without related dm parameters.

**Step**
1. build configurator (Win)
2. install configurator and launch
3. Set work directory and load the board XML file
4. Import/Load default scenario XML file
5. Modify HV basic InterVM Virtual UART Connection from "legacy" to "PCI"
6. Click the "Save" button
7. Check scenario XML and launch scripts.

**Expected result**
The parameters of DM in the script should be generated correctly, for example:
`add_virtual_device                       3 uart vuart_idx:1`

**Actual result**
The generated launch script without related dm parameters.

**Comment by Kunhui-Li** [comment]
[External_System_ID] ACRN-9044

**Comment by NanlinXie** [comment]
Close with no regression.
