### ISSUE TITLE
[ADL-S][SSRAM]RTCM Unit run failed with 2G memory size

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#7563]
Enable TCC and SRAM in Bios

HV : mainliine-e09968e5e

Step:

  1. enable sram and disable cdp in shared.xml, then build acrn

  2. replace acrn build on target board and reboot

  3. boot acrn and SOS 

  4. Run PMC(acrn-unit) as post-rt in SOS with 2G memory size
  5. Check if pmc L2 miss/hit is reasonable comparing with no RTCM

 

Expected result:

RTCM unit test run passed with 2G memory 

Actual result:

RTVM unit run failed with 2G memory

**Comment by yonghuah** [comment]
[External_System_ID] ACRN-7624

**Comment by NanlinXie** [comment]
Close with no regression.
