### ISSUE TITLE
uninitialized variables are used in hpet.c

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#7606]
hw/platform/hpet.c: In function ‘vhpet_mmio_read’: hw/platform/hpet.c:914:9: warning: ‘data’ may be used uninitialized in this function [-Wmaybe-uninitialized] 914 | data >>= 32; | ~~~~^~~~~

**Comment by yonghuah** [comment]
[External_System_ID] ACRN-9084

**Comment by NanlinXie** [comment]
Close with no regression.
