### ISSUE TITLE
[config_tool] igd-vf para is no longer needed in launch script

### ISSUE THREAD

**Issue by zhangqiang4** [projectacrn/acrn-hypervisor#7623]
igb-vf was a temporary flag for virtio-gpu + sriov-vf development. It's no longer needed now.

Other passthrough options: "d3hot_reset" and "enable_ptm" are failed to pass to acrn-dm because of shell s;yntax error.

**Comment by zhangqiang4** [comment]
[External_System_ID] ACRN-9011

**Comment by NanlinXie** [comment]
Close with no regression.
