### ISSUE TITLE
Update TSC members and delete maintainers

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#7706]
The list of TSC members needs to be updated and a couple of `maintainers` files should be deleted.

**Comment by gvancuts** [comment]
[External_System_ID] ACRN-9162

**Comment by gvancuts** [comment]
Hi @fuzhongl , couldn't this one be closed?

**Comment by fuzhongl** [comment]
@gvancuts The linked JIRA isn't in closed status: [External_System_ID] ACRN-9162
If no more action needed, will close JIRA also.
Thanks!
