### ISSUE TITLE
[acrn-configuration-tool] ACRN-Configurator does not consider L3 CAT config when opening an exiting configuration

### ISSUE THREAD

**Issue by chuangxke** [projectacrn/acrn-hypervisor#7927]
**To Reproduce**
Check the attached scenario xml file. It has RDT enabled and provides a CAT way masks for the L3 cache. All non-rt VMs have way mask 0x0ff. vCPU1 of RT_VM1 uses way mask 0x300. vCPU of RT_VM2 uses way mask 0xc00.
Load this configuration into the ACRN configurator. 
When you check the Hypervisor / Advances Parameters, you can see that the bars of the GUI correspond to a way mask of 0xfff for all vCPUs / all VMs.

**Comment by chuangxke** [comment]
[External_System_ID] ACRN-9255

**Comment by NanlinXie** [comment]
Closed with no regression
