### ISSUE TITLE
Improve HV console as a bash-like one

### ISSUE THREAD

**Issue by NanlinXie** [projectacrn/acrn-hypervisor#7931]
Support keys with left/right/home/end/delete/backspace keys, and up/down to select buffered former commands.

**Comment by NanlinXie** [comment]
[External_System_ID] ACRN-9284

**Comment by dbkinder** [comment]
This PR adds functionality to the console that we need to document.  New key behavior and command history (8 previous commands).  See https://projectacrn.github.io/latest/user-guides/acrn-shell.html
