### ISSUE TITLE
Create a requirements.txt for python packages needed for ACRN developers

### ISSUE THREAD

**Issue by zihengL1** [projectacrn/acrn-hypervisor#7974]
Today, the list of required python packages a developer needs to install is maintained in the Getting Started Guide document.  This should really be in a requirements.txt file and we update the documentation to tell users to use that file to install python packages:

   pip3 install -r requirements.txt

This will require a clone of the acrn-hypervisor repo earlier in the instructions so that requirements.txt file is available.

**Comment by zihengL1** [comment]
[External_System_ID] ACRN-9258

**Comment by NanlinXie** [comment]
Closed with no regression
