### ISSUE TITLE
[life_mngr] Sync between SOS and RTVM failed when startup hence life_mngr cannot work

### ISSUE THREAD

**Issue by chejianj** [projectacrn/acrn-hypervisor#8111]
1) deploy life_mngr on Service VM and RTVM
2) Sync between Service VM and RTVM failed

The reason is that RTVM will write 1 to fifo and the string received by Service VM is preceded by -1

**Comment by chejianj** [comment]
[External_System_ID] ACRN-9352

**Comment by gvancuts** [comment]
Updated `SOS` to `Service VM`
