### ISSUE TITLE
Add the support of PCI_ROM for virtual PCI device based on Passthru device

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#8175]
PCI ROM is the firmware specific to PCI device and it is provided by
the device vendor. The PCI rom resides in 0x30 offset of PCI config space.
This can be used to check whether the PCI rom exists. And when it exists,
it can load the firmware from the addr that is obtained from ROM bar addr.
     Based on the PCI rom, it is convenient to add the GPU GOP for OVMF firmward 
instead of integrating the GPU Gop into the OVMF.

**Comment by yakuizhao** [comment]
[External_System_ID] ACRN-9341

**Comment by NanlinXie** [comment]
Closed with no regression.
