### ISSUE TITLE
ACRN boot failure

### ISSUE THREAD

**Issue by kiendinh** [projectacrn/acrn-hypervisor#843]
Setting up ACRN on a NUC with Clear Linux v24120, it failed to boot up. Building the latest acrn-hypervisor in master branch @1f32abc and replacing the acrn.efi with the newly built one resulted in the same failure. By replacing the acrn.efi from an old Clear Linux version (v24010) it booted successfully. Maybe some recent changes may cause the regression.

**Comment by zhujun74** [comment]
could paste the difference of clear Linux (v24120) and Linux(v24010)  on board?

**Comment by kiendinh** [comment]
I've confirmed commit @fb667d0 on acrn-kernel helped to fix the issue. I also confirmed that Clear Linux 24180 could boot successfully with ACRN. So this issue has been solved.
