### ISSUE TITLE
Options of ACRN hypervisor may miss in grub menu after first installation and reboot.

### ISSUE THREAD

**Issue by jiayuan-intel** [projectacrn/acrn-hypervisor#8667]
**Describe the bug**
When firstly installed ACRN and boot up a VM, the options related to ACRN may miss after rebooting SOS. The acrn.bin and something else is existed in /boot, and run update-grub will fix. But why the options in the menu will miss once? It's not 100% appeared but both showed on Vecow and Asus mini PC once.

**Platform**
Both showed once on Vecow and Asus mini PC

**Codebase**
release_3.3

**Scenario**
Shared scenario described in Getting Started Guide.

**To Reproduce**
1.Follow GSG, finish all the steps and poweroff the VM.
2.Reboot SOS, check grub menu.

![image](https://github.com/user-attachments/assets/4a39abbb-276a-42de-ae0c-8ade3fe6b90f)

**Comment by jiaqingz-intel** [comment]
```
update-initramfs: deferring update (trigger activated)
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/acrn.cfg'
WARNING: GRUB_DEFAULT changed to boot into ACRN by default!
         Edit /etc/default/grub.d/acrn.cfg to avoid this warning.
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-6.8.0-31-generic
Found initrd image: /boot/initrd.img-6.8.0-31-generic
Found linux image: /boot/vmlinuz-6.1.80-acrn-service-vm-375511-g2355d104a177
Found initrd image: /boot/initrd.img-6.1.80-acrn-service-vm-375511-g2355d104a177
Found linux image: /boot/vmlinuz-6.8.0-31-generic
Found initrd image: /boot/initrd.img-6.8.0-31-generic
Found linux image: /boot/vmlinuz-6.1.80-acrn-service-vm-375511-g2355d104a177
Found initrd image: /boot/initrd.img-6.1.80-acrn-service-vm-375511-g2355d104a177
Found memtest86+ 64bit EFI image: /boot/memtest86+x64.efi
debconf: DbDriver "config": /var/cache/debconf/config.dat is locked by another process: Resource temporarily unavailable
ACRN: Cannot access debconf acrn-hypervisor/board:
```

Failed to read parameters when configuring package

**Comment by jiayuan-intel** [comment]
Fixed. Thanks @jiaqingz-intel. 

Close this issue.
