### ISSUE TITLE
Virtual Boot Loader

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#879]
Virtual Boot loader is responsible for perfoming following actions during startup of the guest OS: '- VMM HW initialization (according to Hypervisor capabilities and guest boot loader configuration), '- loading of guest boot image, '- transfer of control to the loaded boot image. Virtual Boot loader shall start execution from guest reset vector and terminate operation when the control flow is passed with the guest OS kernel.

**Comment by hwang37** [comment]
[External_System_ID]212409

**Comment by Mingyuan18** [comment]
AMvSBL binary has been released to 1L team, and vSBL can boot both Linux & Android UOS.
