### ISSUE TITLE
TCU Sharing

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#881]
The Virtual Machine infrastructure shall provide software access to the TCU unit, connected via ethernet, to enable Service OS and guest access to TCU services like connectivity, signal strength, GNSS information, and vehicle WAN access.
Note: This feature is invalid in Apollo Lake project.

**Comment by hwang37** [comment]
[External_System_ID]212406

**Comment by Mingyuan18** [comment]
No regression issue found in test.
