### ISSUE TITLE
System Configuration

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#882]
Virtual device configurations shall be loaded statically at build or initialization time without any runtime discoverability overhead (e.g. don't probe/parse for EDID display information, pre'-parse ACPI tables to avoid interpreter overhead)

**Comment by hwang37** [comment]
[External_System_ID]212404

**Comment by Mingyuan18** [comment]
The current boot time has met the requirements, so close this issue.
