### ISSUE TITLE
Storage: physical disk

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#883]
The hypervisor shall provide the Service OS access to the primary physical storage device/EMMC/UFS. Additional storage devices can be configured as pass'-through to guess, which would be visible to that guest only.

**Comment by hwang37** [comment]
[External_System_ID]212400

**Comment by Mingyuan18** [comment]
PMPhysical EMMC exposed to Service OS is already done.USB stick could be passthrough to guest.I think we can mark this task as done.
