### ISSUE TITLE
Security: Service OS Support for Platform Security Discovery

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#888]
The platform shall mediate access to the Platform Security Discovery (PSD) data structure between all guest operating systems, including the Service OS.

**Comment by hwang37** [comment]
[External_System_ID]212392

**Comment by binbinwu1** [comment]
[External_System_ID]ACRN-2268

**Comment by Mingyuan18** [comment]
Verify this issue pass when use below build: 
ACRN-Hypervisor | 2019w03.5.150000p_148
SOS : 27215
