### ISSUE TITLE
Power Management: VMM control

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#892]
For CPU dynamic sharing, the hypervisor and VM's shall support VMM'-controlled CPU Cx/Px states

**Comment by hwang37** [comment]
[External_System_ID]212381

**Comment by NanlinXie** [comment]
Feature is ready for platform with IOC (I/O Controller) onboard chip. For NUC platform, will have new design for UOS lifecycle management. Close it for IOC platform here
