### ISSUE TITLE
Power Management: Guest control

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#896]
For CPU static CPU partitioning, the hypervisor and VM's shall support guest'-controlled CPU Cx/Px states. For CPU dynamic sharing, the hypervisor shall implement Cx/Px state management.

**Comment by hwang37** [comment]
[External_System_ID]212378

**Comment by Mingyuan18** [comment]
PMCx patches of HV/DM have been merged.
