### ISSUE TITLE
Platform Configuration Tool

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#897]
The distribution for the hypervisor shall provide a platform configuration tool, enabling the customer to enable a new platform configuration and its configuration including (but not exclusive): 1. Machine configuration (such as VBT and EDID blogs) 2. ACPI settings 3. Guest OS configuration parameters (such as kernel configuration and required command line launch parameters, and userspace compositor configurations 4. Developer vs. production mode 5. Security settings and keys

**Comment by hwang37** [comment]
[External_System_ID]212377

**Comment by Mingyuan18** [comment]
No regression issue found in test.
