### ISSUE TITLE
Graphics Virtualization on RTOS HLD

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#910]
Need Engineering HLD input and architectural feedback. This is the deep dive doc for Graphics Mediator. Would also need to have information on porting the mediator to a different service OS.

**Comment by hwang37** [comment]
[External_System_ID]212351

**Comment by Mingyuan18** [comment]
AMthis will be delivered as a training/workshop to PAEs in shanghai in April'18, the PPTs would serve as HLDs

**Comment by gvancuts** [comment]
Did you mean April 2018 (in the past) or April 2019 (early next year)?

Can we make those presentations public and available somewhere on the website/wiki?

**Comment by hwang37** [comment]
It's about GVT-g for ACRN (a.k.a AcrnGT) design doc and porting guide.  Published in ACRN document website.
https://projectacrn.github.io/latest/developer-guides/hld/hld-APL_GVT-g.html
https://projectacrn.github.io/latest/developer-guides/GVT-g-porting.html

**Comment by gvancuts** [comment]
> It's about GVT-g for ACRN (a.k.a AcrnGT) design doc and porting guide. Published in ACRN document website.
> https://projectacrn.github.io/latest/developer-guides/hld/hld-APL_GVT-g.html
> https://projectacrn.github.io/latest/developer-guides/GVT-g-porting.html

Perfect, thanks for the confirmation!
