### ISSUE TITLE
GPU Sharing

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#913]
Mediation of the GPU to be shared by up to 2 Linux, Android, or Service OS guests Render/Compute and Media functionality shared with all domains, with at least 1 domain of safety critical priority wrt/ workload scheduling for QoS '- Displays assignable at the pipe and or plane granularity

**Comment by hwang37** [comment]
[External_System_ID]212347

**Comment by Mingyuan18** [comment]
No regression issue found in test.
