### ISSUE TITLE
GPU Passthrough

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#914]
At boot assignment of the GPU device to be shared by 1'-2 Linux, Android, and Service OS guests, through a mediator hosted in the Service OS, for support of the render, compute, and media engines.
Note: For this Apollo Lake SOC project, we use GVT-g for GPU sharing, not support GPU passthrough. This feature is invalid.

**Comment by hwang37** [comment]
[External_System_ID]212346

**Comment by NanlinXie** [comment]
Skylake NUC has been verified this feature with additional patch, please refer to a GSG guide to be published in ACRN document website
