### ISSUE TITLE
GPU Mediator will support native MMIO device model for guest domains.

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#915]
GPU Mediator will support native MMIO device model for guest domains. Each guest domain will be presented with a device model consistent with the native MMIO of the Gen11 GPU in the KSL'-I platform. Linux/Android Guest graphics drivers will require the basic 'gvt' patch set support for the KMD (upstreamed already) to function over this interface.

**Comment by hwang37** [comment]
[External_System_ID]212345

**Comment by Mingyuan18** [comment]
No regression issue found in test.
