### ISSUE TITLE
GPU Mediator support for up to 3 guest domains.

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#916]
GPU Mediator support for up to 3 guest domains. The GPU Mediator will reside in the service OS and will support graphics/media/compute workloads from the Service OS and up to 3 additional guest domains. 
Note: This feature is invalid for Apollo Lake SOC platform, OK for Kaby Lake platform.

**Comment by hwang37** [comment]
[External_System_ID]212344

**Comment by Mingyuan18** [comment]
No regression issue found in test.
