### ISSUE TITLE
GPU Mediator shall support virtual displays for guest domains

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#917]
GPU Mediator shall support virtual displays for guest domains Some domains on the platform may have no assigned display pipes or planes and yet may be producing output that will be directed to some display (local through indirect display or remote) With that in mind the domain will require some means of determining the parameters of the physical display target (i.e. virtual VBT or cached EDID information) and GPU mediator will need to in some way provide MMIO state the driver requires to determine a display device is present (when it is not physically) and that the graphics stack should produce a display output buffer.

**Comment by hwang37** [comment]
[External_System_ID]212343

**Comment by Mingyuan18** [comment]
No regression issue found in test.
