### ISSUE TITLE
GPU Mediator shall provide for guest control of display plane rotation

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#919]
GPU Mediator shall provide for guest control of display plane rotation Where a guest domain has been assigned control over a display plane on a given pipe the GPU Mediator shall permit that guest control over the rotation state of that plane on a frame'-by'-frame basis. This control may be direct through MMIO emulation and mediation or it may be through para'-virtualization and a specific request of the GPU mediator in the service domain.

**Comment by hwang37** [comment]
[External_System_ID]212336

**Comment by Mingyuan18** [comment]
No regression issue found in build.
