### ISSUE TITLE
GPU Mediator shall provide for allocation of display scalers to specific guest domains for control of content on assigned planes

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#921]
GPU Mediator shall provide for allocation of display scalers to specific guest domains for control of content on assigned planes GPU resources such as scalers for plane content are more limited in number than the planes themselves. Therefore allocation of a scaler resource to a domain shall be made separate and explicit in addition to the allocation of a plane to a guest domain. It is expected that scalers, like planes, be allocated at initialization time and will not require dynamic re'-allocation during the life'-cycle of the system. Attempts by a guest domain to program a scaler not assigned to it will be discarded.

**Comment by hwang37** [comment]
[External_System_ID]212335

**Comment by Mingyuan18** [comment]
No regression issue found in test.
