### ISSUE TITLE
GPU Mediator shall provide assignment of particular Display Pipes to individual guest domains.

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#922]
GPU Mediator shall provide assignment of particular Display Pipes to individual guest domains. GPU mediator will provide a mechanism by which the system can be configured such that the available display pipes and ports can be assigned to individual guest domains. (i.e. pipe a to domain 1 and pipe b to domain2 etc.) rather than assuming all pipes are mapped concurrently to only 1 domain. Pipe assignment is expected to be a static mapping of displays to domains in production (no dynamic re'-assignment) but the assignment must support hot unplug/plug events of display devices in order to deal with the potential for momentary disconnects of the connectors due to shock/vibration etc. Access to assigned pipes is still mediated. Pipe updates by a guest OS to which the pipe has been assigned will be accepted; attempts by a guest OS to update pipe registers for a pipe that has not been assigned to it will be discarded.

**Comment by hwang37** [comment]
[External_System_ID]212334

**Comment by Mingyuan18** [comment]
No regression issue found in test.
