### ISSUE TITLE
GPU Mediator shall be compatible with operation of graphics safety watchdog

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#923]
GPU Mediator shall be compatible with operation of a graphics safety watchdog This safety watchdog process will run only in the service domain. This watchdog service will monitor the configuration of display HW to ensure that the output configuration is as expected and that critical content is being delivered to the desired display device in a system where there is a functional safety requirement (ie output of telltales to the IC display). The host i915 driver shall permit access to physical register contents such that the graphics safety service has direct, un'-mediated, visibility to the necessary content; this direct access must not impact the regular behavior of the graphics mediator. 
Note: This feature is invalid for Apollo Lake SoC project.

**Comment by Mingyuan18** [comment]
This feature depends on the i915 safety watchdog. As I know, so far i915 doesn't commit to support this on APL platform. So reject it.
