### ISSUE TITLE
General: VMM Watchdog

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#925]
The hypervisor shall enable detection of Guest OS hang or kernel fault, and reboot Guest OS with notification to Service OS. The hypervisor and SOS shall enable a platform watchdog to detect the hang of hypervisor and SOS itself, to trigger a platform reboot. Each Guest shall provide support to renew the watchdog timer periodically to prevent reset.

**Comment by mwang106** [comment]
this feature has been verified on MRB/APL NUC/KBL NUC/UP2
