### ISSUE TITLE
DAL Session Isolation

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#942]
'- A DAL session created using JHI in one Guest OS shall not be accessible/usable by another Guest OS. '- A DAL session created using KDI in one Guest OS shall not be accessible/usable by another Guest OS. '- A Guest OS shall be restricted to create sessions to only those applets it had installed.

**Comment by hwang37** [comment]
[External_System_ID]212302

**Comment by NanlinXie** [comment]
The HECI firmware and driver have been updated to support those features
