### ISSUE TITLE
CPU: Native HALT support

### ISSUE THREAD

**Issue by hwang37** [projectacrn/acrn-hypervisor#960]
For virtual machines which use a static physical core CPU partitioning, the hypervisor shall pass HALT/MWAIT instructions natively, except for the following exception: in some cases hypervisor may dynamically switch from native execution to trap'-emulation, upon demand of directly enforcing some PM policy, e.g.: 1) turbo mode on one core requires other cores in same package in deep C'-state. It's possible that low'-priority VM doesn't enter deep'-enough C'-state then high'-priority VM cannot acquire desired frequency when requesting turbo. 2) due to some over'-heat condition, hypervisor want to enforce deeper C'-state or lower frequency regardless of guest decision. Above is true even for static partitioning scenario

**Comment by hwang37** [comment]
[External_System_ID]211416

**Comment by Mingyuan18** [comment]
No regression found in test.
