### ISSUE TITLE
Guest graphics driver updating ggtt and ppgtt causes a lot of vm exits.

### ISSUE THREAD

**Issue by zhipenggong** [projectacrn/acrn-hypervisor#994]
ggtt update causes mmio vm exits
ppgtt update causes write protection vm exits. 
They should be optimized.

**Comment by mwang106** [comment]
[External_System_ID] 251250

**Comment by dandanyx** [comment]
No performance degradation in SOS or UOS on WW38 LaaG E2E build.

**Comment by dandanyx** [comment]
In recent one month, update:
reflash ioc => reflash ifwi => reflash build => executed test cases
Performance has no degradation in SOS or UOS.
Suggest to close this issue.

**Comment by Mingyuan18** [comment]
Performance has no degradation in SOS or UOS.
